name: Restore full heptools cache
description: Restores heptools from cache and sets MG5 accordingly

runs:
  using: composite
  steps:
    - name: get os 
      run: echo "CACHE_KEY=heptools-$ImageOS" >> $GITHUB_ENV
      shell: bash

    - name: restore full cache
      id: heptools-cache
      uses: actions/cache/restore@v5
      with:
        path: ~/.cache/HEPtools
        key: ${{ env.CACHE_KEY }}

    # setup other environment of previous level of cache 
    # try to use their cache if previous cache failed
    - uses: ./.github/actions/restore_heptools_lhapdf
      with: 
        setup_only: ${{ steps.heptools-cache.outputs.cache-hit }} 
    - uses: ./.github/actions/restore_heptools_pythia8
      with: 
        setup_only: ${{ steps.heptools-cache.outputs.cache-hit }}
    - uses: ./.github/actions/restore_heptools_emela
      with: 
        setup_only: ${{ steps.heptools-cache.outputs.cache-hit }}
    - uses: ./.github/actions/restore_heptools_contur
      with: 
        setup_only: ${{ steps.heptools-cache.outputs.cache-hit }}
    - uses: ./.github/actions/restore_heptools_looptools
      with: 
        setup_only: ${{ steps.heptools-cache.outputs.cache-hit }}

