name: Restore lhapdf cache
description: Restores lhapdf from cache and sets MG5 accordingly

runs:
  using: composite
  steps:
    - uses: ./.github/actions/restore_heptools_lhapdf
    - name: Set cache key
      run: echo "CACHE_KEY=emela-$ImageOS" >> $GITHUB_ENV
      shell: bash

    - uses: actions/cache/restore@v5
      with:
        path: ~/.cache/HEPtools
        key: ${{ env.CACHE_KEY }}

    - run: |
        cd $GITHUB_WORKSPACE
        echo "eMELA = /home/runner/.cache/HEPtools/bin/eMELA-config" >>       input/mg5_configuration.txt
      shell: bash
