      SUBROUTINE SMATRIX9(P, RHEL, RCOL, channel, IVEC, ANS, IHEL,
     $  ICOL)
C     
C     Generated by MadGraph5_aMC@NLO v. 3.7.1, 2026-04-10
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     MadGraph5_aMC@NLO for Madevent Version
C     
C     Returns amplitude squared summed/avg over colors
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL)
C     potentially times multi-channel weight
C     
C     Process: g u~ > e+ e- c u~ c~ WEIGHTED<=7 @1
C     Process: g u~ > mu+ mu- c u~ c~ WEIGHTED<=7 @1
C     Process: g c~ > e+ e- u c~ u~ WEIGHTED<=7 @1
C     Process: g c~ > mu+ mu- u c~ u~ WEIGHTED<=7 @1
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      Include 'genps.inc'
      Include 'maxconfigs.inc'
      Include 'nexternal.inc'
      Include 'maxamps.inc'
      INTEGER                 NCOMB         
      PARAMETER (             NCOMB=16)
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=48) 
      INTEGER    NDIAGS
      PARAMETER (NDIAGS=48) 
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      double precision RHEL    !  random number for selecting helicity
      double precision RCOL    !  random number for selecting helicity
      integer channel    !  channel to keep for the multi-channel
      integer ivec    !  for using the correct coupling
C     
C     output argument
C     
      integer ihel, icol    !  selected helicity/color
      double precision ans 
C     
C     LOCAL VARIABLES 
C     
      INTEGER CONFSUB(MAXSPROC,LMAXCONFIGS)
      INCLUDE 'config_subproc_map.inc'
      INTEGER NHEL(0:NEXTERNAL,NCOMB)
      REAL*8 T
      REAL*8 R,SUMHEL,TS(NCOMB)
      INTEGER I,IDEN
      INTEGER JC(NEXTERNAL),II
      REAL*8 XTOT
      INTEGER  J, JJ
      double precision get_channel_cut
      external get_channel_cut

C     
C     GLOBAL VARIABLES
C     
      include '../../Source/vector.inc'    !  defines VECSIZE_MEMMAX
      DOUBLE PRECISION AMP2(MAXAMPS), JAMP2(0:MAXFLOW)


C     
C     INFORMATION TO WRITE THE HELICITY IN THE EVENT --not memory
C      efficient--
C     
      INTEGER NB_SPIN_STATE_in(2)
      common /nb_hel_state/ nb_spin_state_in

      REAL*8 POL(2)

      COMMON/TO_POLARIZATION/ POL
      double precision tmin_for_channel
      integer sde_strat    !  1 means standard single diagram enhancement strategy,
C     2 means approximation by the	denominator of the propagator
      common/TO_CHANNEL_STRAT/tmin_for_channel,	sde_strat

      INTEGER          ISUM_HEL
      LOGICAL                    MULTI_CHANNEL
      COMMON/TO_MATRIX/ISUM_HEL, MULTI_CHANNEL
      INTEGER MAPCONFIG(0:LMAXCONFIGS), ICONFIG
      COMMON/TO_MCONFIGS/MAPCONFIG, ICONFIG
      
      DATA (NHEL(I,1),I=0,7) /3,-1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,2),I=0,7) /8,-1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,3),I=0,7) /27,-1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,4),I=0,7) /32,-1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,5),I=0,7) /33,-1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,6),I=0,7) /38,-1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,7),I=0,7) /57,-1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,8),I=0,7) /62,-1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,9),I=0,7) /67, 1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,10),I=0,7) /72, 1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,11),I=0,7) /91, 1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,12),I=0,7) /96, 1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,13),I=0,7) /97, 1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,14),I=0,7) /102, 1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,15),I=0,7) /121, 1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,16),I=0,7) /126, 1, 1,-1, 1, 1, 1,-1/
      DATA IDEN/96/

C     ----------
C     BEGIN CODE
C     ----------

      DO I=1,NEXTERNAL
        JC(I) = +1
      ENDDO

      IF (multi_channel) THEN
        DO I=1,NDIAGS
          AMP2(I)=0D0
        ENDDO
      ENDIF
      JAMP2(0)=4
      DO I=1,INT(JAMP2(0))
        JAMP2(I)=0D0
      ENDDO


      ANS = 0D0

      TS(:) = 0d0

      call MATRIX9(P ,JC(1), TS, AMP2, JAMP2, IVEC)
      DO I=1,NCOMB     
        T=TS(I)  
        DO JJ=1,nincoming
          IF(POL(JJ).NE.1d0.AND.NHEL(JJ,I).EQ.INT(SIGN(1d0,POL(JJ))))
     $      THEN
            T=T*ABS(POL(JJ))*NB_SPIN_STATE_IN(JJ)/2d0    !  NB_SPIN_STATE(JJ)/2d0 is added for polarised beam
          ELSE IF(POL(JJ).NE.1d0)THEN
            T=T*(2d0-ABS(POL(JJ)))*NB_SPIN_STATE_IN(JJ)/2d0
          ENDIF
        ENDDO
        ANS=ANS+DABS(T)
        TS(I)=T
      ENDDO

      IF (ANS.ne.0d0) THEN
        SUMHEL=0d0
        DO I=1,NCOMB
          SUMHEL=SUMHEL+DABS(TS(I))/ANS
          IF(RHEL.LT.SUMHEL)THEN
            IHEL = NHEL(0,I)    !  this returns the id of the helicity before helicity recycling
C           WRITE(HEL_BUFF,'(20i5)')(NHEL(II,I),II=1,NEXTERNAL)
C           Set right sign for ANS, based on sign of chosen helicity
            ANS=DSIGN(ANS,TS(I))
            GOTO 10
          ENDIF
        ENDDO
 10     CONTINUE   
      ENDIF
      IF (MULTI_CHANNEL) THEN
        XTOT=0D0
        DO I=1,LMAXCONFIGS
          J = CONFSUB(9, I)
          if (J.ne.0)then
            if (sde_strat.eq.1)then
              AMP2(J) = AMP2(J) * GET_CHANNEL_CUT(P, I)
            else
              AMP2(J) = GET_CHANNEL_CUT(P, I)
            endif
            XTOT=XTOT+AMP2(J)

          endif
        ENDDO
        IF (XTOT.NE.0D0) THEN
          ANS=ANS*AMP2(channel)/XTOT
        ELSE IF(ANS.ne.0d0) THEN
          write(*,*) 'Problem in the multi-channeling. All amp2 are'
     $     //' zero but not the total matrix-element'
          stop 1
        ENDIF
      ENDIF
      ANS=ANS/DBLE(IDEN)

      call select_color(rcol, jamp2, iconfig,9,  icol, ivec)

      END


      Subroutine  MATRIX9(P,IC, TS, AMP2, JAMP2, IVEC)
C     
C     Generated by MadGraph5_aMC@NLO v. 3.7.1, 2026-04-10
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared summed/avg over colors
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: g u~ > e+ e- c u~ c~ WEIGHTED<=7 @1
C     Process: g u~ > mu+ mu- c u~ c~ WEIGHTED<=7 @1
C     Process: g c~ > e+ e- u c~ u~ WEIGHTED<=7 @1
C     Process: g c~ > mu+ mu- u c~ u~ WEIGHTED<=7 @1
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=48) 
      include 'genps.inc'
      include 'nexternal.inc'
      include 'maxamps.inc'
      INTEGER    NWAVEFUNCS,     NCOLOR
      PARAMETER (NWAVEFUNCS=206, NCOLOR=4) 
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=1, NSQAMPSO=1)
      LOGICAL CHOSEN_SO_CONFIGS(NSQAMPSO)
      DATA CHOSEN_SO_CONFIGS/.TRUE./
      SAVE CHOSEN_SO_CONFIGS
      INTEGER                 NCOMB         
      PARAMETER (             NCOMB=16)
      double precision bwcutoff
      common/to_bwcutoff/ bwcutoff
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
      REAL*8 TS(NCOMB)
      INTEGER IVEC
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J,M,N,K
      COMPLEX*16 ZTEMP,TMP_JAMP(43)
      COMPLEX*16 TMP(6)
      INTEGER CF(NCOLOR*(NCOLOR+1))
      INTEGER DENOM, CF_INDEX
      COMPLEX*16 AMP(NCOMB,NGRAPHS), JAMP(NCOLOR,NAMPSO)
      COMPLEX*16 W(6,NWAVEFUNCS)
C     Needed for v4 models
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0d0, 0d0), (1d0, 0d0)/

      double precision fk_ZERO 
      double precision fk_mdl_WZ 
      save fk_ZERO 
      save fk_mdl_WZ 

      logical first
      data first /.true./
      save first
C     
C     FUNCTION
C     
      INTEGER SQSOINDEX9

C     
C     GLOBAL VARIABLES
C     
      include '../../Source/vector.inc'    !  defines VECSIZE_MEMMAX
      Double Precision amp2(maxamps), jamp2(0:maxflow)
      include 'coupl.inc'    !  needs VECSIZE_MEMMAX (defined in vector.inc)

      double precision tmin_for_channel
      integer sde_strat    !  1 means standard single diagram enhancement strategy,
C     2 means approximation by the	denominator of the propagator
      common/TO_CHANNEL_STRAT/tmin_for_channel,	sde_strat

      double precision small_width_treatment
      common/narrow_width/small_width_treatment
C     
C     COLOR DATA
C     
      DATA Denom/1/
      DATA (CF(i),i=  1,  4) /12,8,8,0/
C     1 T(1,2,6) T(5,7)
      DATA (CF(i),i=  5,  7) /12,0,8/
C     1 T(1,2,7) T(5,6)
      DATA (CF(i),i=  8,  9) /12,8/
C     1 T(1,5,6) T(2,7)
      DATA (CF(i),i= 10, 10) /12/
C     1 T(1,5,7) T(2,6)
C     ----------
C     BEGIN CODE
C     ----------
      if (first) then
        first=.false.
        fk_zero = 0d0
        IF(mdl_WZ.ne.0d0) then 
          fk_mdl_WZ = SIGN(MAX(ABS(mdl_WZ), ABS(mdl_MZ
     $     *small_width_treatment)), mdl_WZ) 
        else 
          fk_mdl_WZ = 0d0
        endif

      endif
      AMP(:,:) = (0d0,0d0)
            CALL VXXXXX(P(0,1),ZERO,+1,-1*IC(1),W(1,1))  !  count 76
      CALL VXXXXX(P(0,1),ZERO,-1,-1*IC(1),W(1,2))  !  count 76
      CALL OXXXXX(P(0,2),ZERO,+1,-1*IC(2),W(1,3))  !  count 91
      CALL OXXXXX(P(0,2),ZERO,-1,-1*IC(2),W(1,4))  !  count 91
      CALL IXXXXX(P(0,3),ZERO,+1,-1*IC(3),W(1,5))  !  count 2
      CALL IXXXXX(P(0,3),ZERO,-1,-1*IC(3),W(1,6))  !  count 2
      CALL OXXXXX(P(0,4),ZERO,+1,+1*IC(4),W(1,7))  !  count 2
      CALL OXXXXX(P(0,4),ZERO,-1,+1*IC(4),W(1,8))  !  count 2
      CALL OXXXXX(P(0,5),ZERO,+1,+1*IC(5),W(1,9))  !  count 91
      CALL OXXXXX(P(0,5),ZERO,-1,+1*IC(5),W(1,10))  !  count 91
      CALL IXXXXX(P(0,6),ZERO,+1,-1*IC(6),W(1,11))  !  count 91
      CALL IXXXXX(P(0,6),ZERO,-1,-1*IC(6),W(1,12))  !  count 91
      CALL IXXXXX(P(0,7),ZERO,+1,-1*IC(7),W(1,13))  !  count 91
      CALL IXXXXX(P(0,7),ZERO,-1,-1*IC(7),W(1,14))  !  count 91
      CALL FFV1_2(W(1,11),W(1,1),GC_11(IVEC),ZERO,FK_ZERO,W(1,15))  !  count 7
      CALL FFV1_2(W(1,11),W(1,2),GC_11(IVEC),ZERO,FK_ZERO,W(1,16))  !  count 7
      CALL FFV1_2(W(1,12),W(1,1),GC_11(IVEC),ZERO,FK_ZERO,W(1,17))  !  count 7
      CALL FFV1_2(W(1,12),W(1,2),GC_11(IVEC),ZERO,FK_ZERO,W(1,18))  !  count 7
      CALL FFV1P0_3(W(1,5),W(1,8),GC_3,ZERO,FK_ZERO,W(1,19))  !  count 56
      CALL FFV1P0_3(W(1,6),W(1,7),GC_3,ZERO,FK_ZERO,W(1,20))  !  count 56
      CALL FFV1P0_3(W(1,15),W(1,3),GC_11(IVEC),ZERO,FK_ZERO,W(1,21))  !  count 16
      CALL FFV1P0_3(W(1,16),W(1,3),GC_11(IVEC),ZERO,FK_ZERO,W(1,22))  !  count 16
      CALL FFV1P0_3(W(1,17),W(1,4),GC_11(IVEC),ZERO,FK_ZERO,W(1,23))  !  count 16
      CALL FFV1P0_3(W(1,18),W(1,4),GC_11(IVEC),ZERO,FK_ZERO,W(1,24))  !  count 16
      CALL FFV1_1(W(1,9),W(1,19),GC_2,ZERO,FK_ZERO,W(1,25))  !  count 16
      CALL FFV1_1(W(1,9),W(1,20),GC_2,ZERO,FK_ZERO,W(1,26))  !  count 16
      CALL FFV1_1(W(1,10),W(1,19),GC_2,ZERO,FK_ZERO,W(1,27))  !  count 16
      CALL FFV1_1(W(1,10),W(1,20),GC_2,ZERO,FK_ZERO,W(1,28))  !  count 16
      CALL FFV1P1N_2(W(1,13), W(1,21), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/13,15/), 
     & (/27,28/),
     & TMP, W, AMP(1,1))
      CALL FFV1P1N_2(W(1,13), W(1,22), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/5,7/), 
     & (/27,28/),
     & TMP, W, AMP(1,1))
      CALL FFV1P1N_2(W(1,13), W(1,23), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/9,11/), 
     & (/27,28/),
     & TMP, W, AMP(1,1))
      CALL FFV1P1N_2(W(1,13), W(1,24), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/1,3/), 
     & (/27,28/),
     & TMP, W, AMP(1,1))
      CALL FFV1P1N_2(W(1,14), W(1,21), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/14,16/), 
     & (/25,26/),
     & TMP, W, AMP(1,1))
      CALL FFV1P1N_2(W(1,14), W(1,22), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/6,8/), 
     & (/25,26/),
     & TMP, W, AMP(1,1))
      CALL FFV1P1N_2(W(1,14), W(1,23), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/10,12/), 
     & (/25,26/),
     & TMP, W, AMP(1,1))
      CALL FFV1P1N_2(W(1,14), W(1,24), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/2,4/), 
     & (/25,26/),
     & TMP, W, AMP(1,1))  !  count 1
      CALL FFV1_2(W(1,13),W(1,19),GC_2,ZERO,FK_ZERO,W(1,29))  !  count 16
      CALL FFV1_2(W(1,13),W(1,20),GC_2,ZERO,FK_ZERO,W(1,30))  !  count 16
      CALL FFV1_2(W(1,14),W(1,19),GC_2,ZERO,FK_ZERO,W(1,31))  !  count 16
      CALL FFV1_2(W(1,14),W(1,20),GC_2,ZERO,FK_ZERO,W(1,32))  !  count 16
      CALL FFV1P1N_1(W(1,10), W(1,21), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/13,15/), 
     & (/29,30/),
     & TMP, W, AMP(1,2))
      CALL FFV1P1N_1(W(1,10), W(1,22), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/5,7/), 
     & (/29,30/),
     & TMP, W, AMP(1,2))
      CALL FFV1P1N_1(W(1,10), W(1,23), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/9,11/), 
     & (/29,30/),
     & TMP, W, AMP(1,2))
      CALL FFV1P1N_1(W(1,10), W(1,24), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/1,3/), 
     & (/29,30/),
     & TMP, W, AMP(1,2))
      CALL FFV1P1N_1(W(1,9), W(1,21), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/14,16/), 
     & (/31,32/),
     & TMP, W, AMP(1,2))
      CALL FFV1P1N_1(W(1,9), W(1,22), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/6,8/), 
     & (/31,32/),
     & TMP, W, AMP(1,2))
      CALL FFV1P1N_1(W(1,9), W(1,23), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/10,12/), 
     & (/31,32/),
     & TMP, W, AMP(1,2))
      CALL FFV1P1N_1(W(1,9), W(1,24), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/2,4/), 
     & (/31,32/),
     & TMP, W, AMP(1,2))  !  count 1
      CALL FFV2_4_3(W(1,5),W(1,8),GC_50,GC_59,MDL_MZ,FK_MDL_WZ,W(1,33))  !  count 56
      CALL FFV2_4_3(W(1,6),W(1,7),GC_50,GC_59,MDL_MZ,FK_MDL_WZ,W(1,34))  !  count 56
      CALL FFV2_5_1(W(1,9),W(1,33),-GC_50,GC_58,ZERO,FK_ZERO,W(1,35))  !  count 16
      CALL FFV2_5_1(W(1,9),W(1,34),-GC_50,GC_58,ZERO,FK_ZERO,W(1,36))  !  count 16
      CALL FFV2_5_1(W(1,10),W(1,33),-GC_50,GC_58,ZERO,FK_ZERO,W(1,37))  !  count 16
      CALL FFV2_5_1(W(1,10),W(1,34),-GC_50,GC_58,ZERO,FK_ZERO,W(1,38))  !  count 16
      CALL FFV1P1N_2(W(1,13), W(1,21), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/13,15/), 
     & (/37,38/),
     & TMP, W, AMP(1,3))
      CALL FFV1P1N_2(W(1,13), W(1,22), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/5,7/), 
     & (/37,38/),
     & TMP, W, AMP(1,3))
      CALL FFV1P1N_2(W(1,13), W(1,23), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/9,11/), 
     & (/37,38/),
     & TMP, W, AMP(1,3))
      CALL FFV1P1N_2(W(1,13), W(1,24), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/1,3/), 
     & (/37,38/),
     & TMP, W, AMP(1,3))
      CALL FFV1P1N_2(W(1,14), W(1,21), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/14,16/), 
     & (/35,36/),
     & TMP, W, AMP(1,3))
      CALL FFV1P1N_2(W(1,14), W(1,22), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/6,8/), 
     & (/35,36/),
     & TMP, W, AMP(1,3))
      CALL FFV1P1N_2(W(1,14), W(1,23), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/10,12/), 
     & (/35,36/),
     & TMP, W, AMP(1,3))
      CALL FFV1P1N_2(W(1,14), W(1,24), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/2,4/), 
     & (/35,36/),
     & TMP, W, AMP(1,3))  !  count 1
      CALL FFV2_5_2(W(1,13),W(1,33),-GC_50,GC_58,ZERO,FK_ZERO,W(1,39))  !  count 16
      CALL FFV2_5_2(W(1,13),W(1,34),-GC_50,GC_58,ZERO,FK_ZERO,W(1,40))  !  count 16
      CALL FFV2_5_2(W(1,14),W(1,33),-GC_50,GC_58,ZERO,FK_ZERO,W(1,41))  !  count 16
      CALL FFV2_5_2(W(1,14),W(1,34),-GC_50,GC_58,ZERO,FK_ZERO,W(1,42))  !  count 16
      CALL FFV1P1N_1(W(1,10), W(1,21), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/13,15/), 
     & (/39,40/),
     & TMP, W, AMP(1,4))
      CALL FFV1P1N_1(W(1,10), W(1,22), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/5,7/), 
     & (/39,40/),
     & TMP, W, AMP(1,4))
      CALL FFV1P1N_1(W(1,10), W(1,23), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/9,11/), 
     & (/39,40/),
     & TMP, W, AMP(1,4))
      CALL FFV1P1N_1(W(1,10), W(1,24), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/1,3/), 
     & (/39,40/),
     & TMP, W, AMP(1,4))
      CALL FFV1P1N_1(W(1,9), W(1,21), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/14,16/), 
     & (/41,42/),
     & TMP, W, AMP(1,4))
      CALL FFV1P1N_1(W(1,9), W(1,22), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/6,8/), 
     & (/41,42/),
     & TMP, W, AMP(1,4))
      CALL FFV1P1N_1(W(1,9), W(1,23), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/10,12/), 
     & (/41,42/),
     & TMP, W, AMP(1,4))
      CALL FFV1P1N_1(W(1,9), W(1,24), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/2,4/), 
     & (/41,42/),
     & TMP, W, AMP(1,4))  !  count 1
      CALL FFV1P0_3(W(1,13),W(1,10),GC_11(IVEC),ZERO,FK_ZERO,W(1,43))  !  count 46
      CALL FFV1P0_3(W(1,14),W(1,9),GC_11(IVEC),ZERO,FK_ZERO,W(1,44))  !  count 46
      CALL FFV1_2(W(1,15),W(1,19),GC_2,ZERO,FK_ZERO,W(1,45))  !  count 2
      CALL FFV1_2(W(1,15),W(1,20),GC_2,ZERO,FK_ZERO,W(1,46))  !  count 2
      CALL FFV1_2(W(1,16),W(1,19),GC_2,ZERO,FK_ZERO,W(1,47))  !  count 2
      CALL FFV1_2(W(1,16),W(1,20),GC_2,ZERO,FK_ZERO,W(1,48))  !  count 2
      CALL FFV1_2(W(1,17),W(1,19),GC_2,ZERO,FK_ZERO,W(1,49))  !  count 2
      CALL FFV1_2(W(1,17),W(1,20),GC_2,ZERO,FK_ZERO,W(1,50))  !  count 2
      CALL FFV1_2(W(1,18),W(1,19),GC_2,ZERO,FK_ZERO,W(1,51))  !  count 2
      CALL FFV1_2(W(1,18),W(1,20),GC_2,ZERO,FK_ZERO,W(1,52))  !  count 2
      CALL FFV1P1N_1(W(1,3), W(1,43), GC_11(IVEC), TMP(1))
      call CombineAmp(4,
     & (/13,15,5,7/), 
     & (/45,46,47,48/),
     & TMP, W, AMP(1,5))
      CALL FFV1P1N_1(W(1,3), W(1,44), GC_11(IVEC), TMP(1))
      call CombineAmp(4,
     & (/14,16,6,8/), 
     & (/45,46,47,48/),
     & TMP, W, AMP(1,5))
      CALL FFV1P1N_1(W(1,4), W(1,43), GC_11(IVEC), TMP(1))
      call CombineAmp(4,
     & (/9,11,1,3/), 
     & (/49,50,51,52/),
     & TMP, W, AMP(1,5))
      CALL FFV1P1N_1(W(1,4), W(1,44), GC_11(IVEC), TMP(1))
      call CombineAmp(4,
     & (/10,12,2,4/), 
     & (/49,50,51,52/),
     & TMP, W, AMP(1,5))  !  count 1
      CALL FFV1_2(W(1,15),W(1,43),GC_11(IVEC),ZERO,FK_ZERO,W(1,53))  !  count 4
      CALL FFV1_2(W(1,15),W(1,44),GC_11(IVEC),ZERO,FK_ZERO,W(1,54))  !  count 4
      CALL FFV1_2(W(1,16),W(1,43),GC_11(IVEC),ZERO,FK_ZERO,W(1,55))  !  count 4
      CALL FFV1_2(W(1,16),W(1,44),GC_11(IVEC),ZERO,FK_ZERO,W(1,56))  !  count 4
      CALL FFV1_2(W(1,17),W(1,43),GC_11(IVEC),ZERO,FK_ZERO,W(1,57))  !  count 4
      CALL FFV1_2(W(1,17),W(1,44),GC_11(IVEC),ZERO,FK_ZERO,W(1,58))  !  count 4
      CALL FFV1_2(W(1,18),W(1,43),GC_11(IVEC),ZERO,FK_ZERO,W(1,59))  !  count 4
      CALL FFV1_2(W(1,18),W(1,44),GC_11(IVEC),ZERO,FK_ZERO,W(1,60))  !  count 4
      CALL FFV1P1N_1(W(1,3), W(1,19), GC_2, TMP(1))
      call CombineAmp(4,
     & (/13,14,5,6/), 
     & (/53,54,55,56/),
     & TMP, W, AMP(1,6))
      CALL FFV1P1N_1(W(1,3), W(1,20), GC_2, TMP(1))
      call CombineAmp(4,
     & (/15,16,7,8/), 
     & (/53,54,55,56/),
     & TMP, W, AMP(1,6))
      CALL FFV1P1N_1(W(1,4), W(1,19), GC_2, TMP(1))
      call CombineAmp(4,
     & (/9,10,1,2/), 
     & (/57,58,59,60/),
     & TMP, W, AMP(1,6))
      CALL FFV1P1N_1(W(1,4), W(1,20), GC_2, TMP(1))
      call CombineAmp(4,
     & (/11,12,3,4/), 
     & (/57,58,59,60/),
     & TMP, W, AMP(1,6))  !  count 1
      CALL FFV2_5_2(W(1,15),W(1,33),-GC_50,GC_58,ZERO,FK_ZERO,W(1,61))  !  count 2
      CALL FFV2_5_2(W(1,15),W(1,34),-GC_50,GC_58,ZERO,FK_ZERO,W(1,62))  !  count 2
      CALL FFV2_5_2(W(1,16),W(1,33),-GC_50,GC_58,ZERO,FK_ZERO,W(1,63))  !  count 2
      CALL FFV2_5_2(W(1,16),W(1,34),-GC_50,GC_58,ZERO,FK_ZERO,W(1,64))  !  count 2
      CALL FFV2_5_2(W(1,17),W(1,33),-GC_50,GC_58,ZERO,FK_ZERO,W(1,65))  !  count 2
      CALL FFV2_5_2(W(1,17),W(1,34),-GC_50,GC_58,ZERO,FK_ZERO,W(1,66))  !  count 2
      CALL FFV2_5_2(W(1,18),W(1,33),-GC_50,GC_58,ZERO,FK_ZERO,W(1,67))  !  count 2
      CALL FFV2_5_2(W(1,18),W(1,34),-GC_50,GC_58,ZERO,FK_ZERO,W(1,68))  !  count 2
      CALL FFV1P1N_1(W(1,3), W(1,43), GC_11(IVEC), TMP(1))
      call CombineAmp(4,
     & (/13,15,5,7/), 
     & (/61,62,63,64/),
     & TMP, W, AMP(1,7))
      CALL FFV1P1N_1(W(1,3), W(1,44), GC_11(IVEC), TMP(1))
      call CombineAmp(4,
     & (/14,16,6,8/), 
     & (/61,62,63,64/),
     & TMP, W, AMP(1,7))
      CALL FFV1P1N_1(W(1,4), W(1,43), GC_11(IVEC), TMP(1))
      call CombineAmp(4,
     & (/9,11,1,3/), 
     & (/65,66,67,68/),
     & TMP, W, AMP(1,7))
      CALL FFV1P1N_1(W(1,4), W(1,44), GC_11(IVEC), TMP(1))
      call CombineAmp(4,
     & (/10,12,2,4/), 
     & (/65,66,67,68/),
     & TMP, W, AMP(1,7))  !  count 1
      CALL FFV2_5P1N_1(W(1,3), W(1,33), -GC_50, GC_58, TMP(1))
      call CombineAmp(4,
     & (/13,14,5,6/), 
     & (/53,54,55,56/),
     & TMP, W, AMP(1,8))
      CALL FFV2_5P1N_1(W(1,3), W(1,34), -GC_50, GC_58, TMP(1))
      call CombineAmp(4,
     & (/15,16,7,8/), 
     & (/53,54,55,56/),
     & TMP, W, AMP(1,8))
      CALL FFV2_5P1N_1(W(1,4), W(1,33), -GC_50, GC_58, TMP(1))
      call CombineAmp(4,
     & (/9,10,1,2/), 
     & (/57,58,59,60/),
     & TMP, W, AMP(1,8))
      CALL FFV2_5P1N_1(W(1,4), W(1,34), -GC_50, GC_58, TMP(1))
      call CombineAmp(4,
     & (/11,12,3,4/), 
     & (/57,58,59,60/),
     & TMP, W, AMP(1,8))  !  count 1
      CALL FFV1_1(W(1,3),W(1,1),GC_11(IVEC),ZERO,FK_ZERO,W(1,69))  !  count 7
      CALL FFV1_1(W(1,3),W(1,2),GC_11(IVEC),ZERO,FK_ZERO,W(1,70))  !  count 7
      CALL FFV1_1(W(1,4),W(1,1),GC_11(IVEC),ZERO,FK_ZERO,W(1,71))  !  count 7
      CALL FFV1_1(W(1,4),W(1,2),GC_11(IVEC),ZERO,FK_ZERO,W(1,72))  !  count 7
      CALL FFV1P0_3(W(1,11),W(1,69),GC_11(IVEC),ZERO,FK_ZERO,W(1,73))  !  count 16
      CALL FFV1P0_3(W(1,11),W(1,70),GC_11(IVEC),ZERO,FK_ZERO,W(1,74))  !  count 16
      CALL FFV1P0_3(W(1,12),W(1,71),GC_11(IVEC),ZERO,FK_ZERO,W(1,75))  !  count 16
      CALL FFV1P0_3(W(1,12),W(1,72),GC_11(IVEC),ZERO,FK_ZERO,W(1,76))  !  count 16
      CALL FFV1P1N_2(W(1,13), W(1,73), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/13,15/), 
     & (/27,28/),
     & TMP, W, AMP(1,9))
      CALL FFV1P1N_2(W(1,13), W(1,74), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/5,7/), 
     & (/27,28/),
     & TMP, W, AMP(1,9))
      CALL FFV1P1N_2(W(1,13), W(1,75), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/9,11/), 
     & (/27,28/),
     & TMP, W, AMP(1,9))
      CALL FFV1P1N_2(W(1,13), W(1,76), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/1,3/), 
     & (/27,28/),
     & TMP, W, AMP(1,9))
      CALL FFV1P1N_2(W(1,14), W(1,73), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/14,16/), 
     & (/25,26/),
     & TMP, W, AMP(1,9))
      CALL FFV1P1N_2(W(1,14), W(1,74), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/6,8/), 
     & (/25,26/),
     & TMP, W, AMP(1,9))
      CALL FFV1P1N_2(W(1,14), W(1,75), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/10,12/), 
     & (/25,26/),
     & TMP, W, AMP(1,9))
      CALL FFV1P1N_2(W(1,14), W(1,76), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/2,4/), 
     & (/25,26/),
     & TMP, W, AMP(1,9))  !  count 1
      CALL FFV1P1N_1(W(1,10), W(1,73), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/13,15/), 
     & (/29,30/),
     & TMP, W, AMP(1,10))
      CALL FFV1P1N_1(W(1,10), W(1,74), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/5,7/), 
     & (/29,30/),
     & TMP, W, AMP(1,10))
      CALL FFV1P1N_1(W(1,10), W(1,75), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/9,11/), 
     & (/29,30/),
     & TMP, W, AMP(1,10))
      CALL FFV1P1N_1(W(1,10), W(1,76), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/1,3/), 
     & (/29,30/),
     & TMP, W, AMP(1,10))
      CALL FFV1P1N_1(W(1,9), W(1,73), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/14,16/), 
     & (/31,32/),
     & TMP, W, AMP(1,10))
      CALL FFV1P1N_1(W(1,9), W(1,74), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/6,8/), 
     & (/31,32/),
     & TMP, W, AMP(1,10))
      CALL FFV1P1N_1(W(1,9), W(1,75), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/10,12/), 
     & (/31,32/),
     & TMP, W, AMP(1,10))
      CALL FFV1P1N_1(W(1,9), W(1,76), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/2,4/), 
     & (/31,32/),
     & TMP, W, AMP(1,10))  !  count 1
      CALL FFV1P1N_2(W(1,13), W(1,73), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/13,15/), 
     & (/37,38/),
     & TMP, W, AMP(1,11))
      CALL FFV1P1N_2(W(1,13), W(1,74), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/5,7/), 
     & (/37,38/),
     & TMP, W, AMP(1,11))
      CALL FFV1P1N_2(W(1,13), W(1,75), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/9,11/), 
     & (/37,38/),
     & TMP, W, AMP(1,11))
      CALL FFV1P1N_2(W(1,13), W(1,76), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/1,3/), 
     & (/37,38/),
     & TMP, W, AMP(1,11))
      CALL FFV1P1N_2(W(1,14), W(1,73), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/14,16/), 
     & (/35,36/),
     & TMP, W, AMP(1,11))
      CALL FFV1P1N_2(W(1,14), W(1,74), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/6,8/), 
     & (/35,36/),
     & TMP, W, AMP(1,11))
      CALL FFV1P1N_2(W(1,14), W(1,75), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/10,12/), 
     & (/35,36/),
     & TMP, W, AMP(1,11))
      CALL FFV1P1N_2(W(1,14), W(1,76), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/2,4/), 
     & (/35,36/),
     & TMP, W, AMP(1,11))  !  count 1
      CALL FFV1P1N_1(W(1,10), W(1,73), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/13,15/), 
     & (/39,40/),
     & TMP, W, AMP(1,12))
      CALL FFV1P1N_1(W(1,10), W(1,74), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/5,7/), 
     & (/39,40/),
     & TMP, W, AMP(1,12))
      CALL FFV1P1N_1(W(1,10), W(1,75), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/9,11/), 
     & (/39,40/),
     & TMP, W, AMP(1,12))
      CALL FFV1P1N_1(W(1,10), W(1,76), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/1,3/), 
     & (/39,40/),
     & TMP, W, AMP(1,12))
      CALL FFV1P1N_1(W(1,9), W(1,73), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/14,16/), 
     & (/41,42/),
     & TMP, W, AMP(1,12))
      CALL FFV1P1N_1(W(1,9), W(1,74), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/6,8/), 
     & (/41,42/),
     & TMP, W, AMP(1,12))
      CALL FFV1P1N_1(W(1,9), W(1,75), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/10,12/), 
     & (/41,42/),
     & TMP, W, AMP(1,12))
      CALL FFV1P1N_1(W(1,9), W(1,76), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/2,4/), 
     & (/41,42/),
     & TMP, W, AMP(1,12))  !  count 1
      CALL FFV1_1(W(1,69),W(1,19),GC_2,ZERO,FK_ZERO,W(1,77))  !  count 2
      CALL FFV1_1(W(1,69),W(1,20),GC_2,ZERO,FK_ZERO,W(1,78))  !  count 2
      CALL FFV1_1(W(1,70),W(1,19),GC_2,ZERO,FK_ZERO,W(1,79))  !  count 2
      CALL FFV1_1(W(1,70),W(1,20),GC_2,ZERO,FK_ZERO,W(1,80))  !  count 2
      CALL FFV1_1(W(1,71),W(1,19),GC_2,ZERO,FK_ZERO,W(1,81))  !  count 2
      CALL FFV1_1(W(1,71),W(1,20),GC_2,ZERO,FK_ZERO,W(1,82))  !  count 2
      CALL FFV1_1(W(1,72),W(1,19),GC_2,ZERO,FK_ZERO,W(1,83))  !  count 2
      CALL FFV1_1(W(1,72),W(1,20),GC_2,ZERO,FK_ZERO,W(1,84))  !  count 2
      CALL FFV1P1N_2(W(1,11), W(1,43), GC_11(IVEC), TMP(1))
      call CombineAmp(4,
     & (/13,15,5,7/), 
     & (/77,78,79,80/),
     & TMP, W, AMP(1,13))
      CALL FFV1P1N_2(W(1,11), W(1,44), GC_11(IVEC), TMP(1))
      call CombineAmp(4,
     & (/14,16,6,8/), 
     & (/77,78,79,80/),
     & TMP, W, AMP(1,13))
      CALL FFV1P1N_2(W(1,12), W(1,43), GC_11(IVEC), TMP(1))
      call CombineAmp(4,
     & (/9,11,1,3/), 
     & (/81,82,83,84/),
     & TMP, W, AMP(1,13))
      CALL FFV1P1N_2(W(1,12), W(1,44), GC_11(IVEC), TMP(1))
      call CombineAmp(4,
     & (/10,12,2,4/), 
     & (/81,82,83,84/),
     & TMP, W, AMP(1,13))  !  count 1
      CALL FFV1_1(W(1,69),W(1,43),GC_11(IVEC),ZERO,FK_ZERO,W(1,85))  !  count 4
      CALL FFV1_1(W(1,69),W(1,44),GC_11(IVEC),ZERO,FK_ZERO,W(1,86))  !  count 4
      CALL FFV1_1(W(1,70),W(1,43),GC_11(IVEC),ZERO,FK_ZERO,W(1,87))  !  count 4
      CALL FFV1_1(W(1,70),W(1,44),GC_11(IVEC),ZERO,FK_ZERO,W(1,88))  !  count 4
      CALL FFV1_1(W(1,71),W(1,43),GC_11(IVEC),ZERO,FK_ZERO,W(1,89))  !  count 4
      CALL FFV1_1(W(1,71),W(1,44),GC_11(IVEC),ZERO,FK_ZERO,W(1,90))  !  count 4
      CALL FFV1_1(W(1,72),W(1,43),GC_11(IVEC),ZERO,FK_ZERO,W(1,91))  !  count 4
      CALL FFV1_1(W(1,72),W(1,44),GC_11(IVEC),ZERO,FK_ZERO,W(1,92))  !  count 4
      CALL FFV1P1N_2(W(1,11), W(1,19), GC_2, TMP(1))
      call CombineAmp(4,
     & (/13,14,5,6/), 
     & (/85,86,87,88/),
     & TMP, W, AMP(1,14))
      CALL FFV1P1N_2(W(1,11), W(1,20), GC_2, TMP(1))
      call CombineAmp(4,
     & (/15,16,7,8/), 
     & (/85,86,87,88/),
     & TMP, W, AMP(1,14))
      CALL FFV1P1N_2(W(1,12), W(1,19), GC_2, TMP(1))
      call CombineAmp(4,
     & (/9,10,1,2/), 
     & (/89,90,91,92/),
     & TMP, W, AMP(1,14))
      CALL FFV1P1N_2(W(1,12), W(1,20), GC_2, TMP(1))
      call CombineAmp(4,
     & (/11,12,3,4/), 
     & (/89,90,91,92/),
     & TMP, W, AMP(1,14))  !  count 1
      CALL FFV2_5_1(W(1,69),W(1,33),-GC_50,GC_58,ZERO,FK_ZERO,W(1,93))  !  count 2
      CALL FFV2_5_1(W(1,69),W(1,34),-GC_50,GC_58,ZERO,FK_ZERO,W(1,94))  !  count 2
      CALL FFV2_5_1(W(1,70),W(1,33),-GC_50,GC_58,ZERO,FK_ZERO,W(1,95))  !  count 2
      CALL FFV2_5_1(W(1,70),W(1,34),-GC_50,GC_58,ZERO,FK_ZERO,W(1,96))  !  count 2
      CALL FFV2_5_1(W(1,71),W(1,33),-GC_50,GC_58,ZERO,FK_ZERO,W(1,97))  !  count 2
      CALL FFV2_5_1(W(1,71),W(1,34),-GC_50,GC_58,ZERO,FK_ZERO,W(1,98))  !  count 2
      CALL FFV2_5_1(W(1,72),W(1,33),-GC_50,GC_58,ZERO,FK_ZERO,W(1,99))  !  count 2
      CALL FFV2_5_1(W(1,72),W(1,34),-GC_50,GC_58,ZERO,FK_ZERO,W(1,100))  !  count 2
      CALL FFV1P1N_2(W(1,11), W(1,43), GC_11(IVEC), TMP(1))
      call CombineAmp(4,
     & (/13,15,5,7/), 
     & (/93,94,95,96/),
     & TMP, W, AMP(1,15))
      CALL FFV1P1N_2(W(1,11), W(1,44), GC_11(IVEC), TMP(1))
      call CombineAmp(4,
     & (/14,16,6,8/), 
     & (/93,94,95,96/),
     & TMP, W, AMP(1,15))
      CALL FFV1P1N_2(W(1,12), W(1,43), GC_11(IVEC), TMP(1))
      call CombineAmp(4,
     & (/9,11,1,3/), 
     & (/97,98,99,100/),
     & TMP, W, AMP(1,15))
      CALL FFV1P1N_2(W(1,12), W(1,44), GC_11(IVEC), TMP(1))
      call CombineAmp(4,
     & (/10,12,2,4/), 
     & (/97,98,99,100/),
     & TMP, W, AMP(1,15))  !  count 1
      CALL FFV2_5P1N_2(W(1,11), W(1,33), -GC_50, GC_58, TMP(1))
      call CombineAmp(4,
     & (/13,14,5,6/), 
     & (/85,86,87,88/),
     & TMP, W, AMP(1,16))
      CALL FFV2_5P1N_2(W(1,11), W(1,34), -GC_50, GC_58, TMP(1))
      call CombineAmp(4,
     & (/15,16,7,8/), 
     & (/85,86,87,88/),
     & TMP, W, AMP(1,16))
      CALL FFV2_5P1N_2(W(1,12), W(1,33), -GC_50, GC_58, TMP(1))
      call CombineAmp(4,
     & (/9,10,1,2/), 
     & (/89,90,91,92/),
     & TMP, W, AMP(1,16))
      CALL FFV2_5P1N_2(W(1,12), W(1,34), -GC_50, GC_58, TMP(1))
      call CombineAmp(4,
     & (/11,12,3,4/), 
     & (/89,90,91,92/),
     & TMP, W, AMP(1,16))  !  count 1
      CALL FFV1_1(W(1,9),W(1,1),GC_11(IVEC),ZERO,FK_ZERO,W(1,101))  !  count 7
      CALL FFV1_1(W(1,9),W(1,2),GC_11(IVEC),ZERO,FK_ZERO,W(1,102))  !  count 7
      CALL FFV1_1(W(1,10),W(1,1),GC_11(IVEC),ZERO,FK_ZERO,W(1,103))  !  count 7
      CALL FFV1_1(W(1,10),W(1,2),GC_11(IVEC),ZERO,FK_ZERO,W(1,104))  !  count 7
      CALL FFV1P0_3(W(1,11),W(1,3),GC_11(IVEC),ZERO,FK_ZERO,W(1,105))  !  count 46
      CALL FFV1P0_3(W(1,12),W(1,4),GC_11(IVEC),ZERO,FK_ZERO,W(1,106))  !  count 46
      CALL FFV1_1(W(1,101),W(1,105),GC_11(IVEC),ZERO,FK_ZERO,W(1,107))  !  count 4
      CALL FFV1_1(W(1,101),W(1,106),GC_11(IVEC),ZERO,FK_ZERO,W(1,108))  !  count 4
      CALL FFV1_1(W(1,102),W(1,105),GC_11(IVEC),ZERO,FK_ZERO,W(1,109))  !  count 4
      CALL FFV1_1(W(1,102),W(1,106),GC_11(IVEC),ZERO,FK_ZERO,W(1,110))  !  count 4
      CALL FFV1_1(W(1,103),W(1,105),GC_11(IVEC),ZERO,FK_ZERO,W(1,111))  !  count 4
      CALL FFV1_1(W(1,103),W(1,106),GC_11(IVEC),ZERO,FK_ZERO,W(1,112))  !  count 4
      CALL FFV1_1(W(1,104),W(1,105),GC_11(IVEC),ZERO,FK_ZERO,W(1,113))  !  count 4
      CALL FFV1_1(W(1,104),W(1,106),GC_11(IVEC),ZERO,FK_ZERO,W(1,114))  !  count 4
      CALL FFV1P1N_2(W(1,13), W(1,19), GC_2, TMP(1))
      call CombineAmp(4,
     & (/13,9,5,1/), 
     & (/111,112,113,114/),
     & TMP, W, AMP(1,17))
      CALL FFV1P1N_2(W(1,13), W(1,20), GC_2, TMP(1))
      call CombineAmp(4,
     & (/15,11,7,3/), 
     & (/111,112,113,114/),
     & TMP, W, AMP(1,17))
      CALL FFV1P1N_2(W(1,14), W(1,19), GC_2, TMP(1))
      call CombineAmp(4,
     & (/14,10,6,2/), 
     & (/107,108,109,110/),
     & TMP, W, AMP(1,17))
      CALL FFV1P1N_2(W(1,14), W(1,20), GC_2, TMP(1))
      call CombineAmp(4,
     & (/16,12,8,4/), 
     & (/107,108,109,110/),
     & TMP, W, AMP(1,17))  !  count 1
      CALL FFV1_1(W(1,101),W(1,19),GC_2,ZERO,FK_ZERO,W(1,115))  !  count 2
      CALL FFV1_1(W(1,101),W(1,20),GC_2,ZERO,FK_ZERO,W(1,116))  !  count 2
      CALL FFV1_1(W(1,102),W(1,19),GC_2,ZERO,FK_ZERO,W(1,117))  !  count 2
      CALL FFV1_1(W(1,102),W(1,20),GC_2,ZERO,FK_ZERO,W(1,118))  !  count 2
      CALL FFV1_1(W(1,103),W(1,19),GC_2,ZERO,FK_ZERO,W(1,119))  !  count 2
      CALL FFV1_1(W(1,103),W(1,20),GC_2,ZERO,FK_ZERO,W(1,120))  !  count 2
      CALL FFV1_1(W(1,104),W(1,19),GC_2,ZERO,FK_ZERO,W(1,121))  !  count 2
      CALL FFV1_1(W(1,104),W(1,20),GC_2,ZERO,FK_ZERO,W(1,122))  !  count 2
      CALL FFV1P1N_2(W(1,13), W(1,105), GC_11(IVEC), TMP(1))
      call CombineAmp(4,
     & (/13,15,5,7/), 
     & (/119,120,121,122/),
     & TMP, W, AMP(1,18))
      CALL FFV1P1N_2(W(1,13), W(1,106), GC_11(IVEC), TMP(1))
      call CombineAmp(4,
     & (/9,11,1,3/), 
     & (/119,120,121,122/),
     & TMP, W, AMP(1,18))
      CALL FFV1P1N_2(W(1,14), W(1,105), GC_11(IVEC), TMP(1))
      call CombineAmp(4,
     & (/14,16,6,8/), 
     & (/115,116,117,118/),
     & TMP, W, AMP(1,18))
      CALL FFV1P1N_2(W(1,14), W(1,106), GC_11(IVEC), TMP(1))
      call CombineAmp(4,
     & (/10,12,2,4/), 
     & (/115,116,117,118/),
     & TMP, W, AMP(1,18))  !  count 1
      CALL FFV2_5P1N_2(W(1,13), W(1,33), -GC_50, GC_58, TMP(1))
      call CombineAmp(4,
     & (/13,9,5,1/), 
     & (/111,112,113,114/),
     & TMP, W, AMP(1,19))
      CALL FFV2_5P1N_2(W(1,13), W(1,34), -GC_50, GC_58, TMP(1))
      call CombineAmp(4,
     & (/15,11,7,3/), 
     & (/111,112,113,114/),
     & TMP, W, AMP(1,19))
      CALL FFV2_5P1N_2(W(1,14), W(1,33), -GC_50, GC_58, TMP(1))
      call CombineAmp(4,
     & (/14,10,6,2/), 
     & (/107,108,109,110/),
     & TMP, W, AMP(1,19))
      CALL FFV2_5P1N_2(W(1,14), W(1,34), -GC_50, GC_58, TMP(1))
      call CombineAmp(4,
     & (/16,12,8,4/), 
     & (/107,108,109,110/),
     & TMP, W, AMP(1,19))  !  count 1
      CALL FFV2_5_1(W(1,101),W(1,33),-GC_50,GC_58,ZERO,FK_ZERO,W(1,123))
     $  !  count 2
      CALL FFV2_5_1(W(1,101),W(1,34),-GC_50,GC_58,ZERO,FK_ZERO,W(1,124))
     $  !  count 2
      CALL FFV2_5_1(W(1,102),W(1,33),-GC_50,GC_58,ZERO,FK_ZERO,W(1,125))
     $  !  count 2
      CALL FFV2_5_1(W(1,102),W(1,34),-GC_50,GC_58,ZERO,FK_ZERO,W(1,126))
     $  !  count 2
      CALL FFV2_5_1(W(1,103),W(1,33),-GC_50,GC_58,ZERO,FK_ZERO,W(1,127))
     $  !  count 2
      CALL FFV2_5_1(W(1,103),W(1,34),-GC_50,GC_58,ZERO,FK_ZERO,W(1,128))
     $  !  count 2
      CALL FFV2_5_1(W(1,104),W(1,33),-GC_50,GC_58,ZERO,FK_ZERO,W(1,129))
     $  !  count 2
      CALL FFV2_5_1(W(1,104),W(1,34),-GC_50,GC_58,ZERO,FK_ZERO,W(1,130))
     $  !  count 2
      CALL FFV1P1N_2(W(1,13), W(1,105), GC_11(IVEC), TMP(1))
      call CombineAmp(4,
     & (/13,15,5,7/), 
     & (/127,128,129,130/),
     & TMP, W, AMP(1,20))
      CALL FFV1P1N_2(W(1,13), W(1,106), GC_11(IVEC), TMP(1))
      call CombineAmp(4,
     & (/9,11,1,3/), 
     & (/127,128,129,130/),
     & TMP, W, AMP(1,20))
      CALL FFV1P1N_2(W(1,14), W(1,105), GC_11(IVEC), TMP(1))
      call CombineAmp(4,
     & (/14,16,6,8/), 
     & (/123,124,125,126/),
     & TMP, W, AMP(1,20))
      CALL FFV1P1N_2(W(1,14), W(1,106), GC_11(IVEC), TMP(1))
      call CombineAmp(4,
     & (/10,12,2,4/), 
     & (/123,124,125,126/),
     & TMP, W, AMP(1,20))  !  count 1
      CALL FFV1P0_3(W(1,13),W(1,103),GC_11(IVEC),ZERO,FK_ZERO,W(1,131))  !  count 16
      CALL FFV1P0_3(W(1,13),W(1,104),GC_11(IVEC),ZERO,FK_ZERO,W(1,132))  !  count 16
      CALL FFV1P0_3(W(1,14),W(1,101),GC_11(IVEC),ZERO,FK_ZERO,W(1,133))  !  count 16
      CALL FFV1P0_3(W(1,14),W(1,102),GC_11(IVEC),ZERO,FK_ZERO,W(1,134))  !  count 16
      CALL FFV1_2(W(1,11),W(1,19),GC_2,ZERO,FK_ZERO,W(1,135))  !  count 16
      CALL FFV1_2(W(1,11),W(1,20),GC_2,ZERO,FK_ZERO,W(1,136))  !  count 16
      CALL FFV1_2(W(1,12),W(1,19),GC_2,ZERO,FK_ZERO,W(1,137))  !  count 16
      CALL FFV1_2(W(1,12),W(1,20),GC_2,ZERO,FK_ZERO,W(1,138))  !  count 16
      CALL FFV1P1N_1(W(1,3), W(1,131), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/13,15/), 
     & (/135,136/),
     & TMP, W, AMP(1,21))
      CALL FFV1P1N_1(W(1,3), W(1,132), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/5,7/), 
     & (/135,136/),
     & TMP, W, AMP(1,21))
      CALL FFV1P1N_1(W(1,3), W(1,133), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/14,16/), 
     & (/135,136/),
     & TMP, W, AMP(1,21))
      CALL FFV1P1N_1(W(1,3), W(1,134), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/6,8/), 
     & (/135,136/),
     & TMP, W, AMP(1,21))
      CALL FFV1P1N_1(W(1,4), W(1,131), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/9,11/), 
     & (/137,138/),
     & TMP, W, AMP(1,21))
      CALL FFV1P1N_1(W(1,4), W(1,132), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/1,3/), 
     & (/137,138/),
     & TMP, W, AMP(1,21))
      CALL FFV1P1N_1(W(1,4), W(1,133), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/10,12/), 
     & (/137,138/),
     & TMP, W, AMP(1,21))
      CALL FFV1P1N_1(W(1,4), W(1,134), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/2,4/), 
     & (/137,138/),
     & TMP, W, AMP(1,21))  !  count 1
      CALL FFV1_1(W(1,3),W(1,19),GC_2,ZERO,FK_ZERO,W(1,139))  !  count 16
      CALL FFV1_1(W(1,3),W(1,20),GC_2,ZERO,FK_ZERO,W(1,140))  !  count 16
      CALL FFV1_1(W(1,4),W(1,19),GC_2,ZERO,FK_ZERO,W(1,141))  !  count 16
      CALL FFV1_1(W(1,4),W(1,20),GC_2,ZERO,FK_ZERO,W(1,142))  !  count 16
      CALL FFV1P1N_2(W(1,11), W(1,131), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/13,15/), 
     & (/139,140/),
     & TMP, W, AMP(1,22))
      CALL FFV1P1N_2(W(1,11), W(1,132), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/5,7/), 
     & (/139,140/),
     & TMP, W, AMP(1,22))
      CALL FFV1P1N_2(W(1,11), W(1,133), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/14,16/), 
     & (/139,140/),
     & TMP, W, AMP(1,22))
      CALL FFV1P1N_2(W(1,11), W(1,134), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/6,8/), 
     & (/139,140/),
     & TMP, W, AMP(1,22))
      CALL FFV1P1N_2(W(1,12), W(1,131), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/9,11/), 
     & (/141,142/),
     & TMP, W, AMP(1,22))
      CALL FFV1P1N_2(W(1,12), W(1,132), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/1,3/), 
     & (/141,142/),
     & TMP, W, AMP(1,22))
      CALL FFV1P1N_2(W(1,12), W(1,133), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/10,12/), 
     & (/141,142/),
     & TMP, W, AMP(1,22))
      CALL FFV1P1N_2(W(1,12), W(1,134), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/2,4/), 
     & (/141,142/),
     & TMP, W, AMP(1,22))  !  count 1
      CALL FFV2_5_2(W(1,11),W(1,33),-GC_50,GC_58,ZERO,FK_ZERO,W(1,143))  !  count 16
      CALL FFV2_5_2(W(1,11),W(1,34),-GC_50,GC_58,ZERO,FK_ZERO,W(1,144))  !  count 16
      CALL FFV2_5_2(W(1,12),W(1,33),-GC_50,GC_58,ZERO,FK_ZERO,W(1,145))  !  count 16
      CALL FFV2_5_2(W(1,12),W(1,34),-GC_50,GC_58,ZERO,FK_ZERO,W(1,146))  !  count 16
      CALL FFV1P1N_1(W(1,3), W(1,131), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/13,15/), 
     & (/143,144/),
     & TMP, W, AMP(1,23))
      CALL FFV1P1N_1(W(1,3), W(1,132), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/5,7/), 
     & (/143,144/),
     & TMP, W, AMP(1,23))
      CALL FFV1P1N_1(W(1,3), W(1,133), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/14,16/), 
     & (/143,144/),
     & TMP, W, AMP(1,23))
      CALL FFV1P1N_1(W(1,3), W(1,134), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/6,8/), 
     & (/143,144/),
     & TMP, W, AMP(1,23))
      CALL FFV1P1N_1(W(1,4), W(1,131), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/9,11/), 
     & (/145,146/),
     & TMP, W, AMP(1,23))
      CALL FFV1P1N_1(W(1,4), W(1,132), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/1,3/), 
     & (/145,146/),
     & TMP, W, AMP(1,23))
      CALL FFV1P1N_1(W(1,4), W(1,133), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/10,12/), 
     & (/145,146/),
     & TMP, W, AMP(1,23))
      CALL FFV1P1N_1(W(1,4), W(1,134), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/2,4/), 
     & (/145,146/),
     & TMP, W, AMP(1,23))  !  count 1
      CALL FFV2_5_1(W(1,3),W(1,33),-GC_50,GC_58,ZERO,FK_ZERO,W(1,147))  !  count 16
      CALL FFV2_5_1(W(1,3),W(1,34),-GC_50,GC_58,ZERO,FK_ZERO,W(1,148))  !  count 16
      CALL FFV2_5_1(W(1,4),W(1,33),-GC_50,GC_58,ZERO,FK_ZERO,W(1,149))  !  count 16
      CALL FFV2_5_1(W(1,4),W(1,34),-GC_50,GC_58,ZERO,FK_ZERO,W(1,150))  !  count 16
      CALL FFV1P1N_2(W(1,11), W(1,131), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/13,15/), 
     & (/147,148/),
     & TMP, W, AMP(1,24))
      CALL FFV1P1N_2(W(1,11), W(1,132), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/5,7/), 
     & (/147,148/),
     & TMP, W, AMP(1,24))
      CALL FFV1P1N_2(W(1,11), W(1,133), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/14,16/), 
     & (/147,148/),
     & TMP, W, AMP(1,24))
      CALL FFV1P1N_2(W(1,11), W(1,134), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/6,8/), 
     & (/147,148/),
     & TMP, W, AMP(1,24))
      CALL FFV1P1N_2(W(1,12), W(1,131), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/9,11/), 
     & (/149,150/),
     & TMP, W, AMP(1,24))
      CALL FFV1P1N_2(W(1,12), W(1,132), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/1,3/), 
     & (/149,150/),
     & TMP, W, AMP(1,24))
      CALL FFV1P1N_2(W(1,12), W(1,133), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/10,12/), 
     & (/149,150/),
     & TMP, W, AMP(1,24))
      CALL FFV1P1N_2(W(1,12), W(1,134), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/2,4/), 
     & (/149,150/),
     & TMP, W, AMP(1,24))  !  count 1
      CALL FFV1_2(W(1,13),W(1,1),GC_11(IVEC),ZERO,FK_ZERO,W(1,151))  !  count 7
      CALL FFV1_2(W(1,13),W(1,2),GC_11(IVEC),ZERO,FK_ZERO,W(1,152))  !  count 7
      CALL FFV1_2(W(1,14),W(1,1),GC_11(IVEC),ZERO,FK_ZERO,W(1,153))  !  count 7
      CALL FFV1_2(W(1,14),W(1,2),GC_11(IVEC),ZERO,FK_ZERO,W(1,154))  !  count 7
      CALL FFV1_2(W(1,151),W(1,105),GC_11(IVEC),ZERO,FK_ZERO,W(1,155))  !  count 4
      CALL FFV1_2(W(1,151),W(1,106),GC_11(IVEC),ZERO,FK_ZERO,W(1,156))  !  count 4
      CALL FFV1_2(W(1,152),W(1,105),GC_11(IVEC),ZERO,FK_ZERO,W(1,157))  !  count 4
      CALL FFV1_2(W(1,152),W(1,106),GC_11(IVEC),ZERO,FK_ZERO,W(1,158))  !  count 4
      CALL FFV1_2(W(1,153),W(1,105),GC_11(IVEC),ZERO,FK_ZERO,W(1,159))  !  count 4
      CALL FFV1_2(W(1,153),W(1,106),GC_11(IVEC),ZERO,FK_ZERO,W(1,160))  !  count 4
      CALL FFV1_2(W(1,154),W(1,105),GC_11(IVEC),ZERO,FK_ZERO,W(1,161))  !  count 4
      CALL FFV1_2(W(1,154),W(1,106),GC_11(IVEC),ZERO,FK_ZERO,W(1,162))  !  count 4
      CALL FFV1P1N_1(W(1,10), W(1,19), GC_2, TMP(1))
      call CombineAmp(4,
     & (/13,9,5,1/), 
     & (/155,156,157,158/),
     & TMP, W, AMP(1,25))
      CALL FFV1P1N_1(W(1,10), W(1,20), GC_2, TMP(1))
      call CombineAmp(4,
     & (/15,11,7,3/), 
     & (/155,156,157,158/),
     & TMP, W, AMP(1,25))
      CALL FFV1P1N_1(W(1,9), W(1,19), GC_2, TMP(1))
      call CombineAmp(4,
     & (/14,10,6,2/), 
     & (/159,160,161,162/),
     & TMP, W, AMP(1,25))
      CALL FFV1P1N_1(W(1,9), W(1,20), GC_2, TMP(1))
      call CombineAmp(4,
     & (/16,12,8,4/), 
     & (/159,160,161,162/),
     & TMP, W, AMP(1,25))  !  count 1
      CALL FFV1_2(W(1,151),W(1,19),GC_2,ZERO,FK_ZERO,W(1,163))  !  count 2
      CALL FFV1_2(W(1,151),W(1,20),GC_2,ZERO,FK_ZERO,W(1,164))  !  count 2
      CALL FFV1_2(W(1,152),W(1,19),GC_2,ZERO,FK_ZERO,W(1,165))  !  count 2
      CALL FFV1_2(W(1,152),W(1,20),GC_2,ZERO,FK_ZERO,W(1,166))  !  count 2
      CALL FFV1_2(W(1,153),W(1,19),GC_2,ZERO,FK_ZERO,W(1,167))  !  count 2
      CALL FFV1_2(W(1,153),W(1,20),GC_2,ZERO,FK_ZERO,W(1,168))  !  count 2
      CALL FFV1_2(W(1,154),W(1,19),GC_2,ZERO,FK_ZERO,W(1,169))  !  count 2
      CALL FFV1_2(W(1,154),W(1,20),GC_2,ZERO,FK_ZERO,W(1,170))  !  count 2
      CALL FFV1P1N_1(W(1,10), W(1,105), GC_11(IVEC), TMP(1))
      call CombineAmp(4,
     & (/13,15,5,7/), 
     & (/163,164,165,166/),
     & TMP, W, AMP(1,26))
      CALL FFV1P1N_1(W(1,10), W(1,106), GC_11(IVEC), TMP(1))
      call CombineAmp(4,
     & (/9,11,1,3/), 
     & (/163,164,165,166/),
     & TMP, W, AMP(1,26))
      CALL FFV1P1N_1(W(1,9), W(1,105), GC_11(IVEC), TMP(1))
      call CombineAmp(4,
     & (/14,16,6,8/), 
     & (/167,168,169,170/),
     & TMP, W, AMP(1,26))
      CALL FFV1P1N_1(W(1,9), W(1,106), GC_11(IVEC), TMP(1))
      call CombineAmp(4,
     & (/10,12,2,4/), 
     & (/167,168,169,170/),
     & TMP, W, AMP(1,26))  !  count 1
      CALL FFV2_5P1N_1(W(1,10), W(1,33), -GC_50, GC_58, TMP(1))
      call CombineAmp(4,
     & (/13,9,5,1/), 
     & (/155,156,157,158/),
     & TMP, W, AMP(1,27))
      CALL FFV2_5P1N_1(W(1,10), W(1,34), -GC_50, GC_58, TMP(1))
      call CombineAmp(4,
     & (/15,11,7,3/), 
     & (/155,156,157,158/),
     & TMP, W, AMP(1,27))
      CALL FFV2_5P1N_1(W(1,9), W(1,33), -GC_50, GC_58, TMP(1))
      call CombineAmp(4,
     & (/14,10,6,2/), 
     & (/159,160,161,162/),
     & TMP, W, AMP(1,27))
      CALL FFV2_5P1N_1(W(1,9), W(1,34), -GC_50, GC_58, TMP(1))
      call CombineAmp(4,
     & (/16,12,8,4/), 
     & (/159,160,161,162/),
     & TMP, W, AMP(1,27))  !  count 1
      CALL FFV2_5_2(W(1,151),W(1,33),-GC_50,GC_58,ZERO,FK_ZERO,W(1,171))
     $  !  count 2
      CALL FFV2_5_2(W(1,151),W(1,34),-GC_50,GC_58,ZERO,FK_ZERO,W(1,172))
     $  !  count 2
      CALL FFV2_5_2(W(1,152),W(1,33),-GC_50,GC_58,ZERO,FK_ZERO,W(1,173))
     $  !  count 2
      CALL FFV2_5_2(W(1,152),W(1,34),-GC_50,GC_58,ZERO,FK_ZERO,W(1,174))
     $  !  count 2
      CALL FFV2_5_2(W(1,153),W(1,33),-GC_50,GC_58,ZERO,FK_ZERO,W(1,175))
     $  !  count 2
      CALL FFV2_5_2(W(1,153),W(1,34),-GC_50,GC_58,ZERO,FK_ZERO,W(1,176))
     $  !  count 2
      CALL FFV2_5_2(W(1,154),W(1,33),-GC_50,GC_58,ZERO,FK_ZERO,W(1,177))
     $  !  count 2
      CALL FFV2_5_2(W(1,154),W(1,34),-GC_50,GC_58,ZERO,FK_ZERO,W(1,178))
     $  !  count 2
      CALL FFV1P1N_1(W(1,10), W(1,105), GC_11(IVEC), TMP(1))
      call CombineAmp(4,
     & (/13,15,5,7/), 
     & (/171,172,173,174/),
     & TMP, W, AMP(1,28))
      CALL FFV1P1N_1(W(1,10), W(1,106), GC_11(IVEC), TMP(1))
      call CombineAmp(4,
     & (/9,11,1,3/), 
     & (/171,172,173,174/),
     & TMP, W, AMP(1,28))
      CALL FFV1P1N_1(W(1,9), W(1,105), GC_11(IVEC), TMP(1))
      call CombineAmp(4,
     & (/14,16,6,8/), 
     & (/175,176,177,178/),
     & TMP, W, AMP(1,28))
      CALL FFV1P1N_1(W(1,9), W(1,106), GC_11(IVEC), TMP(1))
      call CombineAmp(4,
     & (/10,12,2,4/), 
     & (/175,176,177,178/),
     & TMP, W, AMP(1,28))  !  count 1
      CALL FFV1P0_3(W(1,151),W(1,10),GC_11(IVEC),ZERO,FK_ZERO,W(1,179))  !  count 16
      CALL FFV1P0_3(W(1,152),W(1,10),GC_11(IVEC),ZERO,FK_ZERO,W(1,180))  !  count 16
      CALL FFV1P0_3(W(1,153),W(1,9),GC_11(IVEC),ZERO,FK_ZERO,W(1,181))  !  count 16
      CALL FFV1P0_3(W(1,154),W(1,9),GC_11(IVEC),ZERO,FK_ZERO,W(1,182))  !  count 16
      CALL FFV1P1N_1(W(1,3), W(1,179), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/13,15/), 
     & (/135,136/),
     & TMP, W, AMP(1,29))
      CALL FFV1P1N_1(W(1,3), W(1,180), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/5,7/), 
     & (/135,136/),
     & TMP, W, AMP(1,29))
      CALL FFV1P1N_1(W(1,3), W(1,181), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/14,16/), 
     & (/135,136/),
     & TMP, W, AMP(1,29))
      CALL FFV1P1N_1(W(1,3), W(1,182), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/6,8/), 
     & (/135,136/),
     & TMP, W, AMP(1,29))
      CALL FFV1P1N_1(W(1,4), W(1,179), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/9,11/), 
     & (/137,138/),
     & TMP, W, AMP(1,29))
      CALL FFV1P1N_1(W(1,4), W(1,180), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/1,3/), 
     & (/137,138/),
     & TMP, W, AMP(1,29))
      CALL FFV1P1N_1(W(1,4), W(1,181), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/10,12/), 
     & (/137,138/),
     & TMP, W, AMP(1,29))
      CALL FFV1P1N_1(W(1,4), W(1,182), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/2,4/), 
     & (/137,138/),
     & TMP, W, AMP(1,29))  !  count 1
      CALL FFV1P1N_2(W(1,11), W(1,179), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/13,15/), 
     & (/139,140/),
     & TMP, W, AMP(1,30))
      CALL FFV1P1N_2(W(1,11), W(1,180), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/5,7/), 
     & (/139,140/),
     & TMP, W, AMP(1,30))
      CALL FFV1P1N_2(W(1,11), W(1,181), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/14,16/), 
     & (/139,140/),
     & TMP, W, AMP(1,30))
      CALL FFV1P1N_2(W(1,11), W(1,182), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/6,8/), 
     & (/139,140/),
     & TMP, W, AMP(1,30))
      CALL FFV1P1N_2(W(1,12), W(1,179), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/9,11/), 
     & (/141,142/),
     & TMP, W, AMP(1,30))
      CALL FFV1P1N_2(W(1,12), W(1,180), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/1,3/), 
     & (/141,142/),
     & TMP, W, AMP(1,30))
      CALL FFV1P1N_2(W(1,12), W(1,181), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/10,12/), 
     & (/141,142/),
     & TMP, W, AMP(1,30))
      CALL FFV1P1N_2(W(1,12), W(1,182), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/2,4/), 
     & (/141,142/),
     & TMP, W, AMP(1,30))  !  count 1
      CALL FFV1P1N_1(W(1,3), W(1,179), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/13,15/), 
     & (/143,144/),
     & TMP, W, AMP(1,31))
      CALL FFV1P1N_1(W(1,3), W(1,180), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/5,7/), 
     & (/143,144/),
     & TMP, W, AMP(1,31))
      CALL FFV1P1N_1(W(1,3), W(1,181), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/14,16/), 
     & (/143,144/),
     & TMP, W, AMP(1,31))
      CALL FFV1P1N_1(W(1,3), W(1,182), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/6,8/), 
     & (/143,144/),
     & TMP, W, AMP(1,31))
      CALL FFV1P1N_1(W(1,4), W(1,179), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/9,11/), 
     & (/145,146/),
     & TMP, W, AMP(1,31))
      CALL FFV1P1N_1(W(1,4), W(1,180), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/1,3/), 
     & (/145,146/),
     & TMP, W, AMP(1,31))
      CALL FFV1P1N_1(W(1,4), W(1,181), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/10,12/), 
     & (/145,146/),
     & TMP, W, AMP(1,31))
      CALL FFV1P1N_1(W(1,4), W(1,182), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/2,4/), 
     & (/145,146/),
     & TMP, W, AMP(1,31))  !  count 1
      CALL FFV1P1N_2(W(1,11), W(1,179), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/13,15/), 
     & (/147,148/),
     & TMP, W, AMP(1,32))
      CALL FFV1P1N_2(W(1,11), W(1,180), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/5,7/), 
     & (/147,148/),
     & TMP, W, AMP(1,32))
      CALL FFV1P1N_2(W(1,11), W(1,181), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/14,16/), 
     & (/147,148/),
     & TMP, W, AMP(1,32))
      CALL FFV1P1N_2(W(1,11), W(1,182), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/6,8/), 
     & (/147,148/),
     & TMP, W, AMP(1,32))
      CALL FFV1P1N_2(W(1,12), W(1,179), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/9,11/), 
     & (/149,150/),
     & TMP, W, AMP(1,32))
      CALL FFV1P1N_2(W(1,12), W(1,180), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/1,3/), 
     & (/149,150/),
     & TMP, W, AMP(1,32))
      CALL FFV1P1N_2(W(1,12), W(1,181), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/10,12/), 
     & (/149,150/),
     & TMP, W, AMP(1,32))
      CALL FFV1P1N_2(W(1,12), W(1,182), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/2,4/), 
     & (/149,150/),
     & TMP, W, AMP(1,32))  !  count 1
      CALL VVV1P0_1(W(1,1),W(1,105),GC_10(IVEC),ZERO,FK_ZERO,W(1,183))  !  count 16
      CALL VVV1P0_1(W(1,1),W(1,106),GC_10(IVEC),ZERO,FK_ZERO,W(1,184))  !  count 16
      CALL VVV1P0_1(W(1,2),W(1,105),GC_10(IVEC),ZERO,FK_ZERO,W(1,185))  !  count 16
      CALL VVV1P0_1(W(1,2),W(1,106),GC_10(IVEC),ZERO,FK_ZERO,W(1,186))  !  count 16
      CALL FFV1P1N_2(W(1,13), W(1,183), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/13,15/), 
     & (/27,28/),
     & TMP, W, AMP(1,33))
      CALL FFV1P1N_2(W(1,13), W(1,184), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/9,11/), 
     & (/27,28/),
     & TMP, W, AMP(1,33))
      CALL FFV1P1N_2(W(1,13), W(1,185), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/5,7/), 
     & (/27,28/),
     & TMP, W, AMP(1,33))
      CALL FFV1P1N_2(W(1,13), W(1,186), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/1,3/), 
     & (/27,28/),
     & TMP, W, AMP(1,33))
      CALL FFV1P1N_2(W(1,14), W(1,183), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/14,16/), 
     & (/25,26/),
     & TMP, W, AMP(1,33))
      CALL FFV1P1N_2(W(1,14), W(1,184), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/10,12/), 
     & (/25,26/),
     & TMP, W, AMP(1,33))
      CALL FFV1P1N_2(W(1,14), W(1,185), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/6,8/), 
     & (/25,26/),
     & TMP, W, AMP(1,33))
      CALL FFV1P1N_2(W(1,14), W(1,186), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/2,4/), 
     & (/25,26/),
     & TMP, W, AMP(1,33))  !  count 1
      CALL FFV1P1N_1(W(1,10), W(1,183), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/13,15/), 
     & (/29,30/),
     & TMP, W, AMP(1,34))
      CALL FFV1P1N_1(W(1,10), W(1,184), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/9,11/), 
     & (/29,30/),
     & TMP, W, AMP(1,34))
      CALL FFV1P1N_1(W(1,10), W(1,185), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/5,7/), 
     & (/29,30/),
     & TMP, W, AMP(1,34))
      CALL FFV1P1N_1(W(1,10), W(1,186), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/1,3/), 
     & (/29,30/),
     & TMP, W, AMP(1,34))
      CALL FFV1P1N_1(W(1,9), W(1,183), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/14,16/), 
     & (/31,32/),
     & TMP, W, AMP(1,34))
      CALL FFV1P1N_1(W(1,9), W(1,184), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/10,12/), 
     & (/31,32/),
     & TMP, W, AMP(1,34))
      CALL FFV1P1N_1(W(1,9), W(1,185), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/6,8/), 
     & (/31,32/),
     & TMP, W, AMP(1,34))
      CALL FFV1P1N_1(W(1,9), W(1,186), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/2,4/), 
     & (/31,32/),
     & TMP, W, AMP(1,34))  !  count 1
      CALL FFV1_1(W(1,9),W(1,105),GC_11(IVEC),ZERO,FK_ZERO,W(1,187))  !  count 8
      CALL FFV1_1(W(1,9),W(1,106),GC_11(IVEC),ZERO,FK_ZERO,W(1,188))  !  count 8
      CALL FFV1_1(W(1,10),W(1,105),GC_11(IVEC),ZERO,FK_ZERO,W(1,189))  !  count 8
      CALL FFV1_1(W(1,10),W(1,106),GC_11(IVEC),ZERO,FK_ZERO,W(1,190))  !  count 8
      CALL FFV1P1N_1(W(1,189), W(1,1), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/13,15/), 
     & (/29,30/),
     & TMP, W, AMP(1,35))
      CALL FFV1P1N_1(W(1,189), W(1,2), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/5,7/), 
     & (/29,30/),
     & TMP, W, AMP(1,35))
      CALL FFV1P1N_1(W(1,190), W(1,1), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/9,11/), 
     & (/29,30/),
     & TMP, W, AMP(1,35))
      CALL FFV1P1N_1(W(1,190), W(1,2), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/1,3/), 
     & (/29,30/),
     & TMP, W, AMP(1,35))
      CALL FFV1P1N_1(W(1,187), W(1,1), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/14,16/), 
     & (/31,32/),
     & TMP, W, AMP(1,35))
      CALL FFV1P1N_1(W(1,187), W(1,2), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/6,8/), 
     & (/31,32/),
     & TMP, W, AMP(1,35))
      CALL FFV1P1N_1(W(1,188), W(1,1), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/10,12/), 
     & (/31,32/),
     & TMP, W, AMP(1,35))
      CALL FFV1P1N_1(W(1,188), W(1,2), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/2,4/), 
     & (/31,32/),
     & TMP, W, AMP(1,35))  !  count 1
      CALL FFV1_2(W(1,13),W(1,105),GC_11(IVEC),ZERO,FK_ZERO,W(1,191))  !  count 8
      CALL FFV1_2(W(1,13),W(1,106),GC_11(IVEC),ZERO,FK_ZERO,W(1,192))  !  count 8
      CALL FFV1_2(W(1,14),W(1,105),GC_11(IVEC),ZERO,FK_ZERO,W(1,193))  !  count 8
      CALL FFV1_2(W(1,14),W(1,106),GC_11(IVEC),ZERO,FK_ZERO,W(1,194))  !  count 8
      CALL FFV1P1N_1(W(1,27), W(1,1), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/13,9/), 
     & (/191,192/),
     & TMP, W, AMP(1,36))
      CALL FFV1P1N_1(W(1,27), W(1,2), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/5,1/), 
     & (/191,192/),
     & TMP, W, AMP(1,36))
      CALL FFV1P1N_1(W(1,28), W(1,1), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/15,11/), 
     & (/191,192/),
     & TMP, W, AMP(1,36))
      CALL FFV1P1N_1(W(1,28), W(1,2), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/7,3/), 
     & (/191,192/),
     & TMP, W, AMP(1,36))
      CALL FFV1P1N_1(W(1,25), W(1,1), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/14,10/), 
     & (/193,194/),
     & TMP, W, AMP(1,36))
      CALL FFV1P1N_1(W(1,25), W(1,2), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/6,2/), 
     & (/193,194/),
     & TMP, W, AMP(1,36))
      CALL FFV1P1N_1(W(1,26), W(1,1), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/16,12/), 
     & (/193,194/),
     & TMP, W, AMP(1,36))
      CALL FFV1P1N_1(W(1,26), W(1,2), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/8,4/), 
     & (/193,194/),
     & TMP, W, AMP(1,36))  !  count 1
      CALL FFV1P1N_2(W(1,13), W(1,183), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/13,15/), 
     & (/37,38/),
     & TMP, W, AMP(1,37))
      CALL FFV1P1N_2(W(1,13), W(1,184), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/9,11/), 
     & (/37,38/),
     & TMP, W, AMP(1,37))
      CALL FFV1P1N_2(W(1,13), W(1,185), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/5,7/), 
     & (/37,38/),
     & TMP, W, AMP(1,37))
      CALL FFV1P1N_2(W(1,13), W(1,186), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/1,3/), 
     & (/37,38/),
     & TMP, W, AMP(1,37))
      CALL FFV1P1N_2(W(1,14), W(1,183), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/14,16/), 
     & (/35,36/),
     & TMP, W, AMP(1,37))
      CALL FFV1P1N_2(W(1,14), W(1,184), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/10,12/), 
     & (/35,36/),
     & TMP, W, AMP(1,37))
      CALL FFV1P1N_2(W(1,14), W(1,185), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/6,8/), 
     & (/35,36/),
     & TMP, W, AMP(1,37))
      CALL FFV1P1N_2(W(1,14), W(1,186), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/2,4/), 
     & (/35,36/),
     & TMP, W, AMP(1,37))  !  count 1
      CALL FFV1P1N_1(W(1,10), W(1,183), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/13,15/), 
     & (/39,40/),
     & TMP, W, AMP(1,38))
      CALL FFV1P1N_1(W(1,10), W(1,184), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/9,11/), 
     & (/39,40/),
     & TMP, W, AMP(1,38))
      CALL FFV1P1N_1(W(1,10), W(1,185), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/5,7/), 
     & (/39,40/),
     & TMP, W, AMP(1,38))
      CALL FFV1P1N_1(W(1,10), W(1,186), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/1,3/), 
     & (/39,40/),
     & TMP, W, AMP(1,38))
      CALL FFV1P1N_1(W(1,9), W(1,183), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/14,16/), 
     & (/41,42/),
     & TMP, W, AMP(1,38))
      CALL FFV1P1N_1(W(1,9), W(1,184), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/10,12/), 
     & (/41,42/),
     & TMP, W, AMP(1,38))
      CALL FFV1P1N_1(W(1,9), W(1,185), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/6,8/), 
     & (/41,42/),
     & TMP, W, AMP(1,38))
      CALL FFV1P1N_1(W(1,9), W(1,186), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/2,4/), 
     & (/41,42/),
     & TMP, W, AMP(1,38))  !  count 1
      CALL FFV1P1N_1(W(1,189), W(1,1), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/13,15/), 
     & (/39,40/),
     & TMP, W, AMP(1,39))
      CALL FFV1P1N_1(W(1,189), W(1,2), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/5,7/), 
     & (/39,40/),
     & TMP, W, AMP(1,39))
      CALL FFV1P1N_1(W(1,190), W(1,1), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/9,11/), 
     & (/39,40/),
     & TMP, W, AMP(1,39))
      CALL FFV1P1N_1(W(1,190), W(1,2), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/1,3/), 
     & (/39,40/),
     & TMP, W, AMP(1,39))
      CALL FFV1P1N_1(W(1,187), W(1,1), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/14,16/), 
     & (/41,42/),
     & TMP, W, AMP(1,39))
      CALL FFV1P1N_1(W(1,187), W(1,2), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/6,8/), 
     & (/41,42/),
     & TMP, W, AMP(1,39))
      CALL FFV1P1N_1(W(1,188), W(1,1), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/10,12/), 
     & (/41,42/),
     & TMP, W, AMP(1,39))
      CALL FFV1P1N_1(W(1,188), W(1,2), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/2,4/), 
     & (/41,42/),
     & TMP, W, AMP(1,39))  !  count 1
      CALL FFV1P1N_1(W(1,37), W(1,1), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/13,9/), 
     & (/191,192/),
     & TMP, W, AMP(1,40))
      CALL FFV1P1N_1(W(1,37), W(1,2), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/5,1/), 
     & (/191,192/),
     & TMP, W, AMP(1,40))
      CALL FFV1P1N_1(W(1,38), W(1,1), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/15,11/), 
     & (/191,192/),
     & TMP, W, AMP(1,40))
      CALL FFV1P1N_1(W(1,38), W(1,2), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/7,3/), 
     & (/191,192/),
     & TMP, W, AMP(1,40))
      CALL FFV1P1N_1(W(1,35), W(1,1), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/14,10/), 
     & (/193,194/),
     & TMP, W, AMP(1,40))
      CALL FFV1P1N_1(W(1,35), W(1,2), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/6,2/), 
     & (/193,194/),
     & TMP, W, AMP(1,40))
      CALL FFV1P1N_1(W(1,36), W(1,1), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/16,12/), 
     & (/193,194/),
     & TMP, W, AMP(1,40))
      CALL FFV1P1N_1(W(1,36), W(1,2), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/8,4/), 
     & (/193,194/),
     & TMP, W, AMP(1,40))  !  count 1
      CALL VVV1P0_1(W(1,1),W(1,43),GC_10(IVEC),ZERO,FK_ZERO,W(1,195))  !  count 16
      CALL VVV1P0_1(W(1,1),W(1,44),GC_10(IVEC),ZERO,FK_ZERO,W(1,196))  !  count 16
      CALL VVV1P0_1(W(1,2),W(1,43),GC_10(IVEC),ZERO,FK_ZERO,W(1,197))  !  count 16
      CALL VVV1P0_1(W(1,2),W(1,44),GC_10(IVEC),ZERO,FK_ZERO,W(1,198))  !  count 16
      CALL FFV1P1N_1(W(1,3), W(1,195), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/13,15/), 
     & (/135,136/),
     & TMP, W, AMP(1,41))
      CALL FFV1P1N_1(W(1,3), W(1,196), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/14,16/), 
     & (/135,136/),
     & TMP, W, AMP(1,41))
      CALL FFV1P1N_1(W(1,3), W(1,197), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/5,7/), 
     & (/135,136/),
     & TMP, W, AMP(1,41))
      CALL FFV1P1N_1(W(1,3), W(1,198), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/6,8/), 
     & (/135,136/),
     & TMP, W, AMP(1,41))
      CALL FFV1P1N_1(W(1,4), W(1,195), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/9,11/), 
     & (/137,138/),
     & TMP, W, AMP(1,41))
      CALL FFV1P1N_1(W(1,4), W(1,196), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/10,12/), 
     & (/137,138/),
     & TMP, W, AMP(1,41))
      CALL FFV1P1N_1(W(1,4), W(1,197), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/1,3/), 
     & (/137,138/),
     & TMP, W, AMP(1,41))
      CALL FFV1P1N_1(W(1,4), W(1,198), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/2,4/), 
     & (/137,138/),
     & TMP, W, AMP(1,41))  !  count 1
      CALL FFV1P1N_2(W(1,11), W(1,195), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/13,15/), 
     & (/139,140/),
     & TMP, W, AMP(1,42))
      CALL FFV1P1N_2(W(1,11), W(1,196), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/14,16/), 
     & (/139,140/),
     & TMP, W, AMP(1,42))
      CALL FFV1P1N_2(W(1,11), W(1,197), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/5,7/), 
     & (/139,140/),
     & TMP, W, AMP(1,42))
      CALL FFV1P1N_2(W(1,11), W(1,198), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/6,8/), 
     & (/139,140/),
     & TMP, W, AMP(1,42))
      CALL FFV1P1N_2(W(1,12), W(1,195), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/9,11/), 
     & (/141,142/),
     & TMP, W, AMP(1,42))
      CALL FFV1P1N_2(W(1,12), W(1,196), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/10,12/), 
     & (/141,142/),
     & TMP, W, AMP(1,42))
      CALL FFV1P1N_2(W(1,12), W(1,197), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/1,3/), 
     & (/141,142/),
     & TMP, W, AMP(1,42))
      CALL FFV1P1N_2(W(1,12), W(1,198), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/2,4/), 
     & (/141,142/),
     & TMP, W, AMP(1,42))  !  count 1
      CALL FFV1_1(W(1,3),W(1,43),GC_11(IVEC),ZERO,FK_ZERO,W(1,199))  !  count 8
      CALL FFV1_1(W(1,3),W(1,44),GC_11(IVEC),ZERO,FK_ZERO,W(1,200))  !  count 8
      CALL FFV1_1(W(1,4),W(1,43),GC_11(IVEC),ZERO,FK_ZERO,W(1,201))  !  count 8
      CALL FFV1_1(W(1,4),W(1,44),GC_11(IVEC),ZERO,FK_ZERO,W(1,202))  !  count 8
      CALL FFV1P1N_1(W(1,199), W(1,1), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/13,15/), 
     & (/135,136/),
     & TMP, W, AMP(1,43))
      CALL FFV1P1N_1(W(1,199), W(1,2), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/5,7/), 
     & (/135,136/),
     & TMP, W, AMP(1,43))
      CALL FFV1P1N_1(W(1,200), W(1,1), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/14,16/), 
     & (/135,136/),
     & TMP, W, AMP(1,43))
      CALL FFV1P1N_1(W(1,200), W(1,2), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/6,8/), 
     & (/135,136/),
     & TMP, W, AMP(1,43))
      CALL FFV1P1N_1(W(1,201), W(1,1), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/9,11/), 
     & (/137,138/),
     & TMP, W, AMP(1,43))
      CALL FFV1P1N_1(W(1,201), W(1,2), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/1,3/), 
     & (/137,138/),
     & TMP, W, AMP(1,43))
      CALL FFV1P1N_1(W(1,202), W(1,1), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/10,12/), 
     & (/137,138/),
     & TMP, W, AMP(1,43))
      CALL FFV1P1N_1(W(1,202), W(1,2), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/2,4/), 
     & (/137,138/),
     & TMP, W, AMP(1,43))  !  count 1
      CALL FFV1_2(W(1,11),W(1,43),GC_11(IVEC),ZERO,FK_ZERO,W(1,203))  !  count 8
      CALL FFV1_2(W(1,11),W(1,44),GC_11(IVEC),ZERO,FK_ZERO,W(1,204))  !  count 8
      CALL FFV1_2(W(1,12),W(1,43),GC_11(IVEC),ZERO,FK_ZERO,W(1,205))  !  count 8
      CALL FFV1_2(W(1,12),W(1,44),GC_11(IVEC),ZERO,FK_ZERO,W(1,206))  !  count 8
      CALL FFV1P1N_1(W(1,139), W(1,1), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/13,14/), 
     & (/203,204/),
     & TMP, W, AMP(1,44))
      CALL FFV1P1N_1(W(1,139), W(1,2), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/5,6/), 
     & (/203,204/),
     & TMP, W, AMP(1,44))
      CALL FFV1P1N_1(W(1,140), W(1,1), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/15,16/), 
     & (/203,204/),
     & TMP, W, AMP(1,44))
      CALL FFV1P1N_1(W(1,140), W(1,2), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/7,8/), 
     & (/203,204/),
     & TMP, W, AMP(1,44))
      CALL FFV1P1N_1(W(1,141), W(1,1), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/9,10/), 
     & (/205,206/),
     & TMP, W, AMP(1,44))
      CALL FFV1P1N_1(W(1,141), W(1,2), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/1,2/), 
     & (/205,206/),
     & TMP, W, AMP(1,44))
      CALL FFV1P1N_1(W(1,142), W(1,1), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/11,12/), 
     & (/205,206/),
     & TMP, W, AMP(1,44))
      CALL FFV1P1N_1(W(1,142), W(1,2), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/3,4/), 
     & (/205,206/),
     & TMP, W, AMP(1,44))  !  count 1
      CALL FFV1P1N_1(W(1,3), W(1,195), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/13,15/), 
     & (/143,144/),
     & TMP, W, AMP(1,45))
      CALL FFV1P1N_1(W(1,3), W(1,196), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/14,16/), 
     & (/143,144/),
     & TMP, W, AMP(1,45))
      CALL FFV1P1N_1(W(1,3), W(1,197), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/5,7/), 
     & (/143,144/),
     & TMP, W, AMP(1,45))
      CALL FFV1P1N_1(W(1,3), W(1,198), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/6,8/), 
     & (/143,144/),
     & TMP, W, AMP(1,45))
      CALL FFV1P1N_1(W(1,4), W(1,195), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/9,11/), 
     & (/145,146/),
     & TMP, W, AMP(1,45))
      CALL FFV1P1N_1(W(1,4), W(1,196), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/10,12/), 
     & (/145,146/),
     & TMP, W, AMP(1,45))
      CALL FFV1P1N_1(W(1,4), W(1,197), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/1,3/), 
     & (/145,146/),
     & TMP, W, AMP(1,45))
      CALL FFV1P1N_1(W(1,4), W(1,198), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/2,4/), 
     & (/145,146/),
     & TMP, W, AMP(1,45))  !  count 1
      CALL FFV1P1N_2(W(1,11), W(1,195), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/13,15/), 
     & (/147,148/),
     & TMP, W, AMP(1,46))
      CALL FFV1P1N_2(W(1,11), W(1,196), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/14,16/), 
     & (/147,148/),
     & TMP, W, AMP(1,46))
      CALL FFV1P1N_2(W(1,11), W(1,197), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/5,7/), 
     & (/147,148/),
     & TMP, W, AMP(1,46))
      CALL FFV1P1N_2(W(1,11), W(1,198), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/6,8/), 
     & (/147,148/),
     & TMP, W, AMP(1,46))
      CALL FFV1P1N_2(W(1,12), W(1,195), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/9,11/), 
     & (/149,150/),
     & TMP, W, AMP(1,46))
      CALL FFV1P1N_2(W(1,12), W(1,196), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/10,12/), 
     & (/149,150/),
     & TMP, W, AMP(1,46))
      CALL FFV1P1N_2(W(1,12), W(1,197), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/1,3/), 
     & (/149,150/),
     & TMP, W, AMP(1,46))
      CALL FFV1P1N_2(W(1,12), W(1,198), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/2,4/), 
     & (/149,150/),
     & TMP, W, AMP(1,46))  !  count 1
      CALL FFV1P1N_1(W(1,199), W(1,1), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/13,15/), 
     & (/143,144/),
     & TMP, W, AMP(1,47))
      CALL FFV1P1N_1(W(1,199), W(1,2), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/5,7/), 
     & (/143,144/),
     & TMP, W, AMP(1,47))
      CALL FFV1P1N_1(W(1,200), W(1,1), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/14,16/), 
     & (/143,144/),
     & TMP, W, AMP(1,47))
      CALL FFV1P1N_1(W(1,200), W(1,2), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/6,8/), 
     & (/143,144/),
     & TMP, W, AMP(1,47))
      CALL FFV1P1N_1(W(1,201), W(1,1), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/9,11/), 
     & (/145,146/),
     & TMP, W, AMP(1,47))
      CALL FFV1P1N_1(W(1,201), W(1,2), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/1,3/), 
     & (/145,146/),
     & TMP, W, AMP(1,47))
      CALL FFV1P1N_1(W(1,202), W(1,1), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/10,12/), 
     & (/145,146/),
     & TMP, W, AMP(1,47))
      CALL FFV1P1N_1(W(1,202), W(1,2), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/2,4/), 
     & (/145,146/),
     & TMP, W, AMP(1,47))  !  count 1
      CALL FFV1P1N_1(W(1,147), W(1,1), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/13,14/), 
     & (/203,204/),
     & TMP, W, AMP(1,48))
      CALL FFV1P1N_1(W(1,147), W(1,2), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/5,6/), 
     & (/203,204/),
     & TMP, W, AMP(1,48))
      CALL FFV1P1N_1(W(1,148), W(1,1), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/15,16/), 
     & (/203,204/),
     & TMP, W, AMP(1,48))
      CALL FFV1P1N_1(W(1,148), W(1,2), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/7,8/), 
     & (/203,204/),
     & TMP, W, AMP(1,48))
      CALL FFV1P1N_1(W(1,149), W(1,1), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/9,10/), 
     & (/205,206/),
     & TMP, W, AMP(1,48))
      CALL FFV1P1N_1(W(1,149), W(1,2), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/1,2/), 
     & (/205,206/),
     & TMP, W, AMP(1,48))
      CALL FFV1P1N_1(W(1,150), W(1,1), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/11,12/), 
     & (/205,206/),
     & TMP, W, AMP(1,48))
      CALL FFV1P1N_1(W(1,150), W(1,2), GC_11(IVEC), TMP(1))
      call CombineAmp(2,
     & (/3,4/), 
     & (/205,206/),
     & TMP, W, AMP(1,48))  !  count 1

      JAMP(:,:)  = (0d0,0d0)
      DO K = 1, NCOMB
        
        JAMP(:,:) = (0D0,0D0)
C       JAMPs contributing to orders ALL_ORDERS=1
        TMP_JAMP(24) = AMP( K,36) +  AMP( K,40)   !  used 2 times
        TMP_JAMP(23) = AMP( K,35) +  AMP( K,39)   !  used 2 times
        TMP_JAMP(22) = AMP( K,31) +  AMP( K,32)   !  used 2 times
        TMP_JAMP(21) = AMP( K,29) +  AMP( K,30)   !  used 2 times
        TMP_JAMP(20) = AMP( K,27) +  AMP( K,28)   !  used 2 times
        TMP_JAMP(19) = AMP( K,25) +  AMP( K,26)   !  used 2 times
        TMP_JAMP(18) = AMP( K,23) +  AMP( K,24)   !  used 2 times
        TMP_JAMP(17) = AMP( K,21) +  AMP( K,22)   !  used 2 times
        TMP_JAMP(16) = AMP( K,19) +  AMP( K,20)   !  used 2 times
        TMP_JAMP(15) = AMP( K,17) +  AMP( K,18)   !  used 2 times
        TMP_JAMP(14) = AMP( K,45) +  AMP( K,46)   !  used 2 times
        TMP_JAMP(13) = AMP( K,43) +  AMP( K,47)   !  used 2 times
        TMP_JAMP(12) = AMP( K,41) +  AMP( K,42)   !  used 2 times
        TMP_JAMP(11) = AMP( K,37) +  AMP( K,38)   !  used 2 times
        TMP_JAMP(10) = AMP( K,33) +  AMP( K,34)   !  used 2 times
        TMP_JAMP(9) = AMP( K,7) +  AMP( K,8)   !  used 2 times
        TMP_JAMP(8) = AMP( K,5) +  AMP( K,6)   !  used 2 times
        TMP_JAMP(7) = AMP( K,3) +  AMP( K,4)   !  used 2 times
        TMP_JAMP(6) = AMP( K,1) +  AMP( K,2)   !  used 2 times
        TMP_JAMP(5) = AMP( K,44) +  AMP( K,48)   !  used 2 times
        TMP_JAMP(4) = AMP( K,15) +  AMP( K,16)   !  used 2 times
        TMP_JAMP(3) = AMP( K,13) +  AMP( K,14)   !  used 2 times
        TMP_JAMP(2) = AMP( K,11) +  AMP( K,12)   !  used 2 times
        TMP_JAMP(1) = AMP( K,9) +  AMP( K,10)   !  used 2 times
        TMP_JAMP(34) = TMP_JAMP(22) +  TMP_JAMP(21)   !  used 2 times
        TMP_JAMP(33) = TMP_JAMP(20) +  TMP_JAMP(19)   !  used 2 times
        TMP_JAMP(32) = TMP_JAMP(18) +  TMP_JAMP(17)   !  used 2 times
        TMP_JAMP(31) = TMP_JAMP(16) +  TMP_JAMP(15)   !  used 2 times
        TMP_JAMP(30) = TMP_JAMP(14) +  TMP_JAMP(12)   !  used 2 times
        TMP_JAMP(29) = TMP_JAMP(11) +  TMP_JAMP(10)   !  used 2 times
        TMP_JAMP(28) = TMP_JAMP(9) +  TMP_JAMP(8)   !  used 2 times
        TMP_JAMP(27) = TMP_JAMP(7) +  TMP_JAMP(6)   !  used 2 times
        TMP_JAMP(26) = TMP_JAMP(4) +  TMP_JAMP(3)   !  used 2 times
        TMP_JAMP(25) = TMP_JAMP(2) +  TMP_JAMP(1)   !  used 2 times
        TMP_JAMP(39) = TMP_JAMP(33) +  TMP_JAMP(23)   !  used 2 times
        TMP_JAMP(38) = TMP_JAMP(31) +  TMP_JAMP(24)   !  used 2 times
        TMP_JAMP(37) = TMP_JAMP(30) - TMP_JAMP(29)   !  used 2 times
        TMP_JAMP(36) = TMP_JAMP(27) +  TMP_JAMP(13)   !  used 2 times
        TMP_JAMP(35) = TMP_JAMP(25) +  TMP_JAMP(5)   !  used 2 times
        TMP_JAMP(43) = TMP_JAMP(39) +  TMP_JAMP(34)   !  used 2 times
        TMP_JAMP(42) = TMP_JAMP(38) +  TMP_JAMP(32)   !  used 2 times
        TMP_JAMP(41) = TMP_JAMP(36) +  TMP_JAMP(28)   !  used 2 times
        TMP_JAMP(40) = TMP_JAMP(35) +  TMP_JAMP(26)   !  used 2 times
        JAMP(1,1) = (1.666666666666667D-01)*TMP_JAMP(40) +(1.66666666666
     $  6667D-01)*TMP_JAMP(41)
        JAMP(2,1) = ((0.000000000000000D+00,5.000000000000000D-01)) *TMP
     $  _JAMP(37)+(-5.000000000000000D-01)*TMP_JAMP(40)+( -5.000000000000000D-01
     $  )*TMP_JAMP(43)
        JAMP(3,1) = ((0.000000000000000D+00,-5.000000000000000D-01)) *TM
     $  P_JAMP(37)+(-5.000000000000000D-01)*TMP_JAMP(41)+( -5.000000000000000D-0
     $  1)*TMP_JAMP(42)
        JAMP(4,1) = (1.666666666666667D-01)*TMP_JAMP(42) +(1.66666666666
     $  6667D-01)*TMP_JAMP(43)

        TS(K) = 0.D0 
        DO M = 1, NAMPSO
          CF_INDEX = 0
          DO I = 1, NCOLOR
            ZTEMP = (0.D0,0.D0)
            DO J = I, NCOLOR
              CF_INDEX = CF_INDEX + 1
              ZTEMP = ZTEMP + CF(CF_INDEX)*JAMP(J,M)
            ENDDO    !  J
            DO N = 1, NAMPSO

              TS(K) = TS(K) + REAL(ZTEMP*DCONJG(JAMP(I,N)))

            ENDDO    !  N
          ENDDO    !  I
        ENDDO    !  M
        TS(K) = TS(K) / DENOM
        if(sde_strat.eq.1) then
        
        IF(SDE_STRAT.EQ.1)THEN
          AMP2(9)=AMP2(9)+AMP( K,9)*DCONJG(AMP( K,9))
          AMP2(10)=AMP2(10)+AMP( K,10)*DCONJG(AMP( K,10))
          AMP2(11)=AMP2(11)+AMP( K,11)*DCONJG(AMP( K,11))
          AMP2(12)=AMP2(12)+AMP( K,12)*DCONJG(AMP( K,12))
          AMP2(13)=AMP2(13)+AMP( K,13)*DCONJG(AMP( K,13))
          AMP2(14)=AMP2(14)+AMP( K,14)*DCONJG(AMP( K,14))
          AMP2(15)=AMP2(15)+AMP( K,15)*DCONJG(AMP( K,15))
          AMP2(16)=AMP2(16)+AMP( K,16)*DCONJG(AMP( K,16))
          AMP2(17)=AMP2(17)+AMP( K,17)*DCONJG(AMP( K,17))
          AMP2(18)=AMP2(18)+AMP( K,18)*DCONJG(AMP( K,18))
          AMP2(19)=AMP2(19)+AMP( K,19)*DCONJG(AMP( K,19))
          AMP2(20)=AMP2(20)+AMP( K,20)*DCONJG(AMP( K,20))
          AMP2(22)=AMP2(22)+AMP( K,22)*DCONJG(AMP( K,22))
          AMP2(21)=AMP2(21)+AMP( K,21)*DCONJG(AMP( K,21))
          AMP2(24)=AMP2(24)+AMP( K,24)*DCONJG(AMP( K,24))
          AMP2(23)=AMP2(23)+AMP( K,23)*DCONJG(AMP( K,23))
          AMP2(1)=AMP2(1)+AMP( K,1)*DCONJG(AMP( K,1))
          AMP2(2)=AMP2(2)+AMP( K,2)*DCONJG(AMP( K,2))
          AMP2(3)=AMP2(3)+AMP( K,3)*DCONJG(AMP( K,3))
          AMP2(4)=AMP2(4)+AMP( K,4)*DCONJG(AMP( K,4))
          AMP2(5)=AMP2(5)+AMP( K,5)*DCONJG(AMP( K,5))
          AMP2(6)=AMP2(6)+AMP( K,6)*DCONJG(AMP( K,6))
          AMP2(7)=AMP2(7)+AMP( K,7)*DCONJG(AMP( K,7))
          AMP2(8)=AMP2(8)+AMP( K,8)*DCONJG(AMP( K,8))
          AMP2(25)=AMP2(25)+AMP( K,25)*DCONJG(AMP( K,25))
          AMP2(26)=AMP2(26)+AMP( K,26)*DCONJG(AMP( K,26))
          AMP2(27)=AMP2(27)+AMP( K,27)*DCONJG(AMP( K,27))
          AMP2(28)=AMP2(28)+AMP( K,28)*DCONJG(AMP( K,28))
          AMP2(30)=AMP2(30)+AMP( K,30)*DCONJG(AMP( K,30))
          AMP2(29)=AMP2(29)+AMP( K,29)*DCONJG(AMP( K,29))
          AMP2(32)=AMP2(32)+AMP( K,32)*DCONJG(AMP( K,32))
          AMP2(31)=AMP2(31)+AMP( K,31)*DCONJG(AMP( K,31))
          AMP2(33)=AMP2(33)+AMP( K,33)*DCONJG(AMP( K,33))
          AMP2(34)=AMP2(34)+AMP( K,34)*DCONJG(AMP( K,34))
          AMP2(35)=AMP2(35)+AMP( K,35)*DCONJG(AMP( K,35))
          AMP2(36)=AMP2(36)+AMP( K,36)*DCONJG(AMP( K,36))
          AMP2(37)=AMP2(37)+AMP( K,37)*DCONJG(AMP( K,37))
          AMP2(38)=AMP2(38)+AMP( K,38)*DCONJG(AMP( K,38))
          AMP2(39)=AMP2(39)+AMP( K,39)*DCONJG(AMP( K,39))
          AMP2(40)=AMP2(40)+AMP( K,40)*DCONJG(AMP( K,40))
          AMP2(42)=AMP2(42)+AMP( K,42)*DCONJG(AMP( K,42))
          AMP2(41)=AMP2(41)+AMP( K,41)*DCONJG(AMP( K,41))
          AMP2(44)=AMP2(44)+AMP( K,44)*DCONJG(AMP( K,44))
          AMP2(43)=AMP2(43)+AMP( K,43)*DCONJG(AMP( K,43))
          AMP2(46)=AMP2(46)+AMP( K,46)*DCONJG(AMP( K,46))
          AMP2(45)=AMP2(45)+AMP( K,45)*DCONJG(AMP( K,45))
          AMP2(48)=AMP2(48)+AMP( K,48)*DCONJG(AMP( K,48))
          AMP2(47)=AMP2(47)+AMP( K,47)*DCONJG(AMP( K,47))
        ENDIF

        endif
        Do I = 1, NCOLOR
          DO M = 1, NAMPSO
            DO N = 1, NAMPSO

              Jamp2(i)=Jamp2(i)+DABS(DBLE(Jamp(i,m)*dconjg(Jamp(i,n))))

            enddo
          enddo
        Enddo
      ENDDO    !  K

      END


      SUBROUTINE PRINT_ZERO_AMP_9()

      integer i
      i =1
      return
      end

C     Set of functions to handle the array indices of the split orders


      INTEGER FUNCTION SQSOINDEX9(ORDERINDEXA, ORDERINDEXB)
C     
C     This functions plays the role of the interference matrix. It can
C      be hardcoded or 
C     made more elegant using hashtables if its execution speed ever
C      becomes a relevant
C     factor. From two split order indices, it return the
C      corresponding index in the squared 
C     order canonical ordering.
C     
C     CONSTANTS
C     

      INTEGER    NSO, NSQUAREDSO, NAMPSO
      PARAMETER (NSO=1, NSQUAREDSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERINDEXA, ORDERINDEXB
C     
C     LOCAL VARIABLES
C     
      INTEGER I, SQORDERS(NSO)
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      DATA (AMPSPLITORDERS(  1,i),i=  1,  1) /    1/
      COMMON/AMPSPLITORDERS9/AMPSPLITORDERS
C     
C     FUNCTION
C     
      INTEGER SOINDEX_FOR_SQUARED_ORDERS9
C     
C     BEGIN CODE
C     
      DO I=1,NSO
        SQORDERS(I)=AMPSPLITORDERS(ORDERINDEXA,I)
     $   +AMPSPLITORDERS(ORDERINDEXB,I)
      ENDDO
      SQSOINDEX9=SOINDEX_FOR_SQUARED_ORDERS9(SQORDERS)
      END

      INTEGER FUNCTION SOINDEX_FOR_SQUARED_ORDERS9(ORDERS)
C     
C     This functions returns the integer index identifying the squared
C      split orders list passed in argument which corresponds to the
C      values of the following list of couplings (and in this order).
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NSQSO, NAMPSO
      PARAMETER (NSO=1, NSQSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J
      INTEGER SQSPLITORDERS(NSQSO,NSO)
      DATA (SQSPLITORDERS(  1,i),i=  1,  1) /    2/
      COMMON/SQPLITORDERS9/SQPLITORDERS
C     
C     BEGIN CODE
C     
      DO I=1,NSQSO
        DO J=1,NSO
          IF (ORDERS(J).NE.SQSPLITORDERS(I,J)) GOTO 1009
        ENDDO
        SOINDEX_FOR_SQUARED_ORDERS9 = I
        RETURN
 1009   CONTINUE
      ENDDO

      WRITE(*,*) 'ERROR:: Stopping in function' 
      WRITE(*,*) 'SOINDEX_FOR_SQUARED_ORDERS9'
      WRITE(*,*) 'Could not find squared orders ',(ORDERS(I),I=1,NSO)
      STOP

      END

      SUBROUTINE GET_NSQSO_BORN9(NSQSO)
C     
C     Simple subroutine returning the number of squared split order
C     contributions returned when calling smatrix_split_orders 
C     

      INTEGER    NSQUAREDSO
      PARAMETER  (NSQUAREDSO=1)

      INTEGER NSQSO

      NSQSO=NSQUAREDSO

      END

C     This is the inverse subroutine of SOINDEX_FOR_SQUARED_ORDERS.
C      Not directly useful, but provided nonetheless.
      SUBROUTINE GET_SQUARED_ORDERS_FOR_SOINDEX9(SOINDEX,ORDERS)
C     
C     This functions returns the orders identified by the squared
C      split order index in argument. Order values correspond to
C      following list of couplings (and in this order):
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NSQSO
      PARAMETER (NSO=1, NSQSO=1)
C     
C     ARGUMENTS
C     
      INTEGER SOINDEX, ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I
      INTEGER SQPLITORDERS(NSQSO,NSO)
      COMMON/SQPLITORDERS9/SQPLITORDERS	  
C     
C     BEGIN CODE
C     
      IF (SOINDEX.gt.0.and.SOINDEX.le.NSQSO) THEN
        DO I=1,NSO
          ORDERS(I) =  SQPLITORDERS(SOINDEX,I)
        ENDDO
        RETURN
      ENDIF

      WRITE(*,*) 'ERROR:: Stopping function'
     $ //' GET_SQUARED_ORDERS_FOR_SOINDEX9'
      WRITE(*,*) 'Could not find squared orders index ',SOINDEX
      STOP

      END SUBROUTINE

C     This is the inverse subroutine of getting amplitude SO orders.
C      Not directly useful, but provided nonetheless.
      SUBROUTINE GET_ORDERS_FOR_AMPSOINDEX9(SOINDEX,ORDERS)
C     
C     This functions returns the orders identified by the split order
C      index in argument. Order values correspond to following list of
C      couplings (and in this order):
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NAMPSO
      PARAMETER (NSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER SOINDEX, ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      COMMON/AMPSPLITORDERS9/AMPSPLITORDERS
C     
C     BEGIN CODE
C     
      IF (SOINDEX.gt.0.and.SOINDEX.le.NAMPSO) THEN
        DO I=1,NSO
          ORDERS(I) =  AMPSPLITORDERS(SOINDEX,I)
        ENDDO
        RETURN
      ENDIF

      WRITE(*,*) 'ERROR:: Stopping function GET_ORDERS_FOR_AMPSOINDEX9'
      WRITE(*,*) 'Could not find amplitude split orders index ',SOINDEX
      STOP

      END SUBROUTINE

C     This function is not directly useful, but included for
C      completeness
      INTEGER FUNCTION SOINDEX_FOR_AMPORDERS9(ORDERS)
C     
C     This functions returns the integer index identifying the
C      amplitude split orders passed in argument which correspond to
C      the values of the following list of couplings (and in this
C      order):
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NAMPSO
      PARAMETER (NSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      COMMON/AMPSPLITORDERS9/AMPSPLITORDERS
C     
C     BEGIN CODE
C     
      DO I=1,NAMPSO
        DO J=1,NSO
          IF (ORDERS(J).NE.AMPSPLITORDERS(I,J)) GOTO 1009
        ENDDO
        SOINDEX_FOR_AMPORDERS9 = I
        RETURN
 1009   CONTINUE
      ENDDO

      WRITE(*,*) 'ERROR:: Stopping function SOINDEX_FOR_AMPORDERS9'
      WRITE(*,*) 'Could not find squared orders ',(ORDERS(I),I=1,NSO)
      STOP

      END

