ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4)

      DOUBLE PRECISION MDL_MZ,MDL_MT,MDL_MTA,MDL_MW,MDL_MB,MDL_MH

      COMMON/MASSES/ MDL_MZ,MDL_MT,MDL_MTA,MDL_MW,MDL_MB,MDL_MH


      DOUBLE PRECISION MDL_WZ,MDL_WW,MDL_WT,MDL_WH

      COMMON/WIDTHS/ MDL_WZ,MDL_WW,MDL_WT,MDL_WH


      DOUBLE COMPLEX GC_5, R2_GGHB, R2_GGHT, R2_GGHHB, R2_GGHHT, GC_30
     $ , GC_33, GC_37

      COMMON/COUPLINGS/ GC_5, R2_GGHB, R2_GGHT, R2_GGHHB, R2_GGHHT,
     $  GC_30, GC_33, GC_37

