#The particle content of MG5 model, my_smallsm,
#generate from save_model module

particles = [
{
    'name': 've',
    'antiname': 've~',
    'spin': 2,
    'color': 1,
    'charge': 0.00,
    'mass': 'ZERO',
    'width': 'ZERO',
    'pdg_code': 12,
    'texname': 've',
    'antitexname': 've',
    'line': 'straight',
    'propagating': True,
    'is_part': True,
    'self_antipart': False
},{
    'name': 'e-',
    'antiname': 'e+',
    'spin': 2,
    'color': 1,
    'charge': -1.00,
    'mass': 'ZERO',
    'width': 'ZERO',
    'pdg_code': 11,
    'texname': 'e-',
    'antitexname': 'e-',
    'line': 'straight',
    'propagating': True,
    'is_part': True,
    'self_antipart': False
},{
    'name': 't',
    'antiname': 't~',
    'spin': 2,
    'color': 3,
    'charge': 0.67,
    'mass': 'MT',
    'width': 'WT',
    'pdg_code': 6,
    'texname': 't',
    'antitexname': 't',
    'line': 'straight',
    'propagating': True,
    'is_part': True,
    'self_antipart': False
},{
    'name': 'b',
    'antiname': 'b~',
    'spin': 2,
    'color': 3,
    'charge': -0.33,
    'mass': 'MB',
    'width': 'ZERO',
    'pdg_code': 5,
    'texname': 'b',
    'antitexname': 'b',
    'line': 'straight',
    'propagating': True,
    'is_part': True,
    'self_antipart': False
},{
    'name': 'a',
    'antiname': 'a',
    'spin': 3,
    'color': 1,
    'charge': 0.00,
    'mass': 'ZERO',
    'width': 'ZERO',
    'pdg_code': 22,
    'texname': 'A',
    'antitexname': 'A',
    'line': 'wavy',
    'propagating': True,
    'is_part': True,
    'self_antipart': True
},{
    'name': 'w+',
    'antiname': 'w-',
    'spin': 3,
    'color': 1,
    'charge': 1.00,
    'mass': 'MW',
    'width': 'WW',
    'pdg_code': 24,
    'texname': 'W+',
    'antitexname': 'W+',
    'line': 'wavy',
    'propagating': True,
    'is_part': True,
    'self_antipart': False
}]
