      SUBROUTINE P0_BORN(P,NHEL)
C     
C     Generated by MadGraph5_aMC@NLO v. %(version)s, %(date)s
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared summed/avg over colors
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: w+ w- > w+ w- WEIGHTED=4
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=7)
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=4)
      INTEGER    NWAVEFUNCS, NCOLOR
      PARAMETER (NWAVEFUNCS=5, NCOLOR=1)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J
      COMPLEX*16 ZTEMP
      REAL*8 DENOM(NCOLOR), CF(NCOLOR,NCOLOR)
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR)
      COMMON/P0_JAMP/JAMP

      COMPLEX*16 W(18,NWAVEFUNCS)
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
C     
C     GLOBAL VARIABLES
C     
      INCLUDE 'coupl.inc'

C     
C     COLOR DATA
C     
      DATA DENOM(1)/1/
      DATA (CF(I,1),I=1,1) /1/
C     ----------
C     BEGIN CODE
C     ----------
      DO I=1,NEXTERNAL
        IC(I) = 1
      ENDDO

      CALL VXXXXX(P(0,1),MDL_MW,NHEL(1),-1*IC(1),W(1,1))
      CALL VXXXXX(P(0,2),MDL_MW,NHEL(2),-1*IC(2),W(1,2))
      CALL VXXXXX(P(0,3),MDL_MW,NHEL(3),+1*IC(3),W(1,3))
      CALL VXXXXX(P(0,4),MDL_MW,NHEL(4),+1*IC(4),W(1,4))
C     Amplitude(s) for diagram number 1
      CALL VVVV2_0(W(1,1),W(1,4),W(1,2),W(1,3),GC_35,AMP(1))
      CALL VVV1P0_1(W(1,1),W(1,2),GC_4,ZERO,ZERO,W(1,5))
C     Amplitude(s) for diagram number 2
      CALL VVV1_0(W(1,5),W(1,4),W(1,3),GC_4,AMP(2))
      CALL VVS1_3(W(1,1),W(1,2),GC_72,MDL_MH,MDL_WH,W(1,5))
C     Amplitude(s) for diagram number 3
      CALL VVS1_0(W(1,4),W(1,3),W(1,5),GC_72,AMP(3))
      CALL VVV1_3(W(1,1),W(1,2),GC_53,MDL_MZ,MDL_WZ,W(1,5))
C     Amplitude(s) for diagram number 4
      CALL VVV1_0(W(1,4),W(1,3),W(1,5),GC_53,AMP(4))
      CALL VVV1P0_1(W(1,1),W(1,3),GC_4,ZERO,ZERO,W(1,5))
C     Amplitude(s) for diagram number 5
      CALL VVV1_0(W(1,5),W(1,4),W(1,2),GC_4,AMP(5))
      CALL VVS1_3(W(1,1),W(1,3),GC_72,MDL_MH,MDL_WH,W(1,5))
C     Amplitude(s) for diagram number 6
      CALL VVS1_0(W(1,4),W(1,2),W(1,5),GC_72,AMP(6))
      CALL VVV1_3(W(1,1),W(1,3),GC_53,MDL_MZ,MDL_WZ,W(1,5))
C     Amplitude(s) for diagram number 7
      CALL VVV1_0(W(1,4),W(1,2),W(1,5),GC_53,AMP(7))
      JAMP(1)=+AMP(1)+AMP(2)+AMP(3)+AMP(4)+AMP(5)+AMP(6)+AMP(7)

      END

      SUBROUTINE P0_GET_JAMP(NJAMP, ONEJAMP)

      INTEGER     NCOLOR, NJAMP
      PARAMETER (NCOLOR=1)
      COMPLEX*16  JAMP(NCOLOR), ONEJAMP
      COMMON/P0_JAMP/JAMP

      ONEJAMP = JAMP[NJAMP+1]  ! +1 since njamp start at zero (c convention)
      END

      SUBROUTINE P0_GET_NCOLOR(IN1, IN2, OUT)

      INTEGER IN1, IN2, OUT
      OUT = 1
      END

      SUBROUTINE P0_GET_NCOL(NCOL)
      INTEGER NCOL
      NCOL = 1
      RETURN
      END

