ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of sm'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_10 = ', GC_10
      WRITE(*,2) 'GC_11 = ', GC_11
      WRITE(*,2) 'GC_37 = ', GC_37
      WRITE(*,2) 'GC_51 = ', GC_51
      WRITE(*,2) 'GC_58 = ', GC_58
      WRITE(*,2) 'GC_60 = ', GC_60
      WRITE(*,2) 'GC_68 = ', GC_68
      WRITE(*,2) 'GC_72 = ', GC_72
      WRITE(*,2) 'GC_81 = ', GC_81
      WRITE(*,2) 'GC_100 = ', GC_100
      WRITE(*,2) 'GC_FFV_0 = ', GC_FFV_0
      WRITE(*,2) 'GC_FFV_1 = ', GC_FFV_1
      WRITE(*,2) 'GC_FFV_2 = ', GC_FFV_2
      WRITE(*,2) 'GC_FFV_3 = ', GC_FFV_3
