      SUBROUTINE SMATRIX_REAL(P,WGT)
      IMPLICIT NONE
      INCLUDE 'nexternal.inc'
      DOUBLE PRECISION P(0:3,NEXTERNAL),Q(0:3,NEXTERNAL),WGT
      INTEGER NFKSPROCESS
      COMMON/C_NFKSPROCESS/NFKSPROCESS
      SELECT CASE(NFKSPROCESS)
      CASE DEFAULT
      STOP 'Invalid native real sector'
      END SELECT
      END
