# PYTHIA configuration file.
# Generated on Tue Oct 3 17:16:49 CDT 2017 with the user supplied options:
# --prefix=/home/prestel/work/fermi2017/PY8meetsMG5aMC/Pythia/Dire/dire-src/../dire-build
# --with-pythia8=/home/prestel/work/fermi2017/PY8meetsMG5aMC/Pythia/Dire/dire-src/../../Pythia/pythia-src

# Install directory prefixes.
PREFIX_BIN=/home/prestel/work/fermi2017/PY8meetsMG5aMC/Pythia/Dire/dire-src/../dire-build/bin
PREFIX_INCLUDE=/home/prestel/work/fermi2017/PY8meetsMG5aMC/Pythia/Dire/dire-src/../dire-build/include
PREFIX_LIB=/home/prestel/work/fermi2017/PY8meetsMG5aMC/Pythia/Dire/dire-src/../dire-build/lib
PREFIX_SRC=/home/prestel/work/fermi2017/PY8meetsMG5aMC/Pythia/Dire/dire-src/src
PREFIX_SHARE=/home/prestel/work/fermi2017/PY8meetsMG5aMC/Pythia/Dire/dire-src/../dire-build/share/Dire

# Compilation flags (see ./configure --help for further documentation).
ENABLE_SHARED=false
CXX=g++
CXX_COMMON=-O2 -std=c++98 -pedantic -W -Wall -Wshadow -fPIC
CXX_SHARED=-shared
CXX_SONAME=-Wl,-soname,
LIB_SUFFIX=.so

# PYTHIA8 configuration.
PYTHIA8_USE=true
PYTHIA8_BIN=/home/prestel/work/fermi2017/PY8meetsMG5aMC/Pythia/Dire/dire-src/../../Pythia/pythia-src/bin/
PYTHIA8_INCLUDE=/home/prestel/work/fermi2017/PY8meetsMG5aMC/Pythia/Dire/dire-src/../../Pythia/pythia-src/include
PYTHIA8_LIB=/home/prestel/work/fermi2017/PY8meetsMG5aMC/Pythia/Dire/dire-src/../../Pythia/pythia-src/lib
PYTHIA8_PREFIX=/home/prestel/work/fermi2017/PY8meetsMG5aMC/Pythia/Dire/dire-src/../../Pythia/pythia-src
PYTHIA8_SHARE=/home/prestel/work/fermi2017/PY8meetsMG5aMC/Pythia/Dire/dire-src/../../Pythia/pythia-src/share
PYTHIA8_EXAMPLES=/home/prestel/work/fermi2017/PY8meetsMG5aMC/Pythia/Dire/dire-src/../../Pythia/pythia-src/share/Pythia8/examples
