# PYTHIA configuration file.
# Generated on Wed Jan 24 09:16:55 CST 2018 with the user supplied options:
# --prefix=/home/prestel/work/2018/MG5/PY8meetsMG5aMC.bak2/Pythia/Pythia/pythia-build
# --with-hepmc2=/home/prestel/work/2018/HEPMC2
# --enable-debug
# --with-gzip=/home/prestel/work/2018/ZLIB
# --with-boost=/home/prestep/work/2018/BOOST
# --cxx-common=-ldl -fPIC -lstdc++ -DHEPMC2HACK

# Install directory prefixes.
PREFIX_BIN=/home/prestel/work/2018/MG5/PY8meetsMG5aMC.bak2/Pythia/Pythia/pythia-build/bin
PREFIX_INCLUDE=/home/prestel/work/2018/MG5/PY8meetsMG5aMC.bak2/Pythia/Pythia/pythia-build/include
PREFIX_LIB=/home/prestel/work/2018/MG5/PY8meetsMG5aMC.bak2/Pythia/Pythia/pythia-build/lib
PREFIX_SHARE=/home/prestel/work/2018/MG5/PY8meetsMG5aMC.bak2/Pythia/Pythia/pythia-build/share/Pythia8

# Compilation flags (see ./configure --help for further documentation).
ENABLE_SHARED=false
CXX=g++
CXX_COMMON=-ldl -fPIC -lstdc++ -DHEPMC2HACK
CXX_SHARED=-shared
CXX_SONAME=-Wl,-soname,
LIB_SUFFIX=.so

# EVTGEN configuration.
EVTGEN_USE=false
EVTGEN_BIN=
EVTGEN_INCLUDE=./
EVTGEN_LIB=./

# FASTJET3 configuration.
FASTJET3_USE=false
FASTJET3_BIN=
FASTJET3_INCLUDE=./
FASTJET3_LIB=./

# HEPMC2 configuration.
HEPMC2_USE=true
HEPMC2_BIN=/home/prestel/work/2018/HEPMC2/bin/
HEPMC2_INCLUDE=/home/prestel/work/2018/HEPMC2/include
HEPMC2_LIB=/home/prestel/work/2018/HEPMC2/lib

# HEPMC3 configuration.
HEPMC3_USE=false
HEPMC3_BIN=
HEPMC3_INCLUDE=./
HEPMC3_LIB=./

# LHAPDF5 configuration.
LHAPDF5_USE=false
LHAPDF5_BIN=
LHAPDF5_INCLUDE=./
LHAPDF5_LIB=./
LHAPDF5_PLUGIN=LHAPDF5.h

# LHAPDF6 configuration.
LHAPDF6_USE=false
LHAPDF6_BIN=
LHAPDF6_INCLUDE=./
LHAPDF6_LIB=./
LHAPDF6_PLUGIN=LHAPDF5.h

# POWHEG configuration.
POWHEG_USE=false
POWHEG_BIN=
POWHEG_INCLUDE=./
POWHEG_LIB=./

# PROMC configuration.
PROMC_USE=false
PROMC_BIN=
PROMC_INCLUDE=./
PROMC_LIB=./

# ROOT configuration.
ROOT_USE=false
ROOT_BIN=
ROOT_INCLUDE=./
ROOT_LIB=./

# GZIP configuration.
GZIP_USE=true
GZIP_BIN=/home/prestel/work/2018/ZLIB//
GZIP_INCLUDE=/home/prestel/work/2018/ZLIB/include
GZIP_LIB=/home/prestel/work/2018/ZLIB/lib

# BOOST configuration.
BOOST_USE=false
BOOST_BIN=
BOOST_INCLUDE=./
BOOST_LIB=./

# PYTHON configuration.
PYTHON_USE=false
PYTHON_BIN=
PYTHON_INCLUDE=./
PYTHON_LIB=./
