ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE COMPLEX COND
      DOUBLE COMPLEX CONDIF
      DOUBLE COMPLEX REGLOG
      DOUBLE COMPLEX REGLOGP
      DOUBLE COMPLEX REGLOGM
      DOUBLE COMPLEX REGSQRT
      DOUBLE COMPLEX GRREGLOG
      DOUBLE COMPLEX RECMS
      DOUBLE COMPLEX ARG
      DOUBLE COMPLEX B0F
      DOUBLE COMPLEX SQRT_TRAJECTORY
      DOUBLE COMPLEX LOG_TRAJECTORY


