      SUBROUTINE DLUM_NATIVE_7_6(LUM)
      IMPLICIT NONE
      INCLUDE 'genps.inc'
      INCLUDE 'nexternal.inc'
      DOUBLE PRECISION       CONV
      PARAMETER (CONV=389379660D0)  !CONV TO PICOBARNS             
      DOUBLE PRECISION LUM
      INTEGER I, ICROSS,LP
      DOUBLE PRECISION CX1,UX1
      DOUBLE PRECISION G2
      DOUBLE PRECISION PHOTONPDFSQUARE
      DOUBLE PRECISION PDG2PDF
      INTEGER              IPROC
      DOUBLE PRECISION PD(0:MAXPROC)
      COMMON /SUBPROC/ PD, IPROC
      INCLUDE 'coupl.inc'
      INCLUDE 'run.inc'
      INTEGER IMIRROR
      COMMON/CMIRROR/IMIRROR
      INCLUDE 'eepdf.inc'
      DOUBLE PRECISION EE_COMP_PROD
      DOUBLE PRECISION DUMMY_COMPONENTS(N_EE)
      DOUBLE PRECISION CX1_COMPONENTS(N_EE),UX1_COMPONENTS(N_EE)
      DOUBLE PRECISION G2_COMPONENTS(N_EE)
      INTEGER I_EE
      INCLUDE '../../Source/PDF/pdf.inc'
      DATA CX1,UX1/2*1D0/
      DATA G2/1*1D0/
      DATA ICROSS/1/
      LUM = 0D0
      IF (ABS(LPP(1)) .GE. 1) THEN
        CX1=PDG2PDF(LPP(1),-4,1,XBK(1),DSQRT(Q2FACT(1)))
        IF ((ABS(LPP(1)).EQ.4.OR.ABS(LPP(1)).EQ.3)   
     $    .AND.PDLABEL.NE.'none') CX1_COMPONENTS(1:N_EE) =    
     $    EE_COMPONENTS(1:N_EE)
        UX1=PDG2PDF(LPP(1),-2,1,XBK(1),DSQRT(Q2FACT(1)))
        IF ((ABS(LPP(1)).EQ.4.OR.ABS(LPP(1)).EQ.3)   
     $    .AND.PDLABEL.NE.'none') UX1_COMPONENTS(1:N_EE) =    
     $    EE_COMPONENTS(1:N_EE)
      ENDIF
      IF (ABS(LPP(2)) .GE. 1) THEN
        G2=PDG2PDF(LPP(2),0,2,XBK(2),DSQRT(Q2FACT(2)))
        IF ((ABS(LPP(2)).EQ.4.OR.ABS(LPP(2)).EQ.3)   
     $    .AND.PDLABEL.NE.'none') G2_COMPONENTS(1:N_EE) =    
     $    EE_COMPONENTS(1:N_EE)
      ENDIF
      PD(0) = 0D0
      IPROC = 0
      IPROC=IPROC+1  ! u~ g > t t~ u~
      PD(IPROC) = UX1*G2
      IF (ABS(LPP(1)).EQ.ABS(LPP(2)).AND. (ABS(LPP(1)) 
     $  .EQ.3.OR.ABS(LPP(1)).EQ.4).AND.PDLABEL.NE.'none')PD(IPROC) 
     $  =EE_COMP_PROD(UX1_COMPONENTS,G2_COMPONENTS)
      IPROC=IPROC+1  ! c~ g > t t~ c~
      PD(IPROC) = CX1*G2
      IF (ABS(LPP(1)).EQ.ABS(LPP(2)).AND. (ABS(LPP(1)) 
     $  .EQ.3.OR.ABS(LPP(1)).EQ.4).AND.PDLABEL.NE.'none')PD(IPROC) 
     $  =EE_COMP_PROD(CX1_COMPONENTS,G2_COMPONENTS)
      DO I=1,IPROC
        IF (NINCOMING.EQ.2) THEN
          LUM = LUM + PD(I) * CONV
        ELSE
          LUM = LUM + PD(I)
        ENDIF
      ENDDO
      RETURN
      END
