      SUBROUTINE DLUM_NATIVE_2_4(LUM)
      IMPLICIT NONE
      INCLUDE 'genps.inc'
      INCLUDE 'nexternal.inc'
      DOUBLE PRECISION       CONV
      PARAMETER (CONV=389379660D0)  !CONV TO PICOBARNS             
      DOUBLE PRECISION LUM
      INTEGER I, ICROSS,LP
      DOUBLE PRECISION G1
      DOUBLE PRECISION SX2,DX2
      DOUBLE PRECISION PHOTONPDFSQUARE
      DOUBLE PRECISION PDG2PDF
      INTEGER              IPROC
      DOUBLE PRECISION PD(0:MAXPROC)
      COMMON /SUBPROC/ PD, IPROC
      INCLUDE 'coupl.inc'
      INCLUDE 'run.inc'
      INTEGER IMIRROR
      COMMON/CMIRROR/IMIRROR
      INCLUDE 'eepdf.inc'
      DOUBLE PRECISION EE_COMP_PROD
      DOUBLE PRECISION DUMMY_COMPONENTS(N_EE)
      DOUBLE PRECISION G1_COMPONENTS(N_EE)
      DOUBLE PRECISION SX2_COMPONENTS(N_EE),DX2_COMPONENTS(N_EE)
      INTEGER I_EE
      INCLUDE '../../Source/PDF/pdf.inc'
      DATA G1/1*1D0/
      DATA SX2,DX2/2*1D0/
      DATA ICROSS/1/
      LUM = 0D0
      IF (ABS(LPP(1)) .GE. 1) THEN
        G1=PDG2PDF(LPP(1),0,1,XBK(1),DSQRT(Q2FACT(1)))
        IF ((ABS(LPP(1)).EQ.4.OR.ABS(LPP(1)).EQ.3)   
     $    .AND.PDLABEL.NE.'none') G1_COMPONENTS(1:N_EE) =    
     $    EE_COMPONENTS(1:N_EE)
      ENDIF
      IF (ABS(LPP(2)) .GE. 1) THEN
        SX2=PDG2PDF(LPP(2),-3,2,XBK(2),DSQRT(Q2FACT(2)))
        IF ((ABS(LPP(2)).EQ.4.OR.ABS(LPP(2)).EQ.3)   
     $    .AND.PDLABEL.NE.'none') SX2_COMPONENTS(1:N_EE) =    
     $    EE_COMPONENTS(1:N_EE)
        DX2=PDG2PDF(LPP(2),-1,2,XBK(2),DSQRT(Q2FACT(2)))
        IF ((ABS(LPP(2)).EQ.4.OR.ABS(LPP(2)).EQ.3)   
     $    .AND.PDLABEL.NE.'none') DX2_COMPONENTS(1:N_EE) =    
     $    EE_COMPONENTS(1:N_EE)
      ENDIF
      PD(0) = 0D0
      IPROC = 0
      IPROC=IPROC+1  ! g d~ > t t~ d~
      PD(IPROC) = G1*DX2
      IF (ABS(LPP(1)).EQ.ABS(LPP(2)).AND. (ABS(LPP(1)) 
     $  .EQ.3.OR.ABS(LPP(1)).EQ.4).AND.PDLABEL.NE.'none')PD(IPROC) 
     $  =EE_COMP_PROD(G1_COMPONENTS,DX2_COMPONENTS)
      IPROC=IPROC+1  ! g s~ > t t~ s~
      PD(IPROC) = G1*SX2
      IF (ABS(LPP(1)).EQ.ABS(LPP(2)).AND. (ABS(LPP(1)) 
     $  .EQ.3.OR.ABS(LPP(1)).EQ.4).AND.PDLABEL.NE.'none')PD(IPROC) 
     $  =EE_COMP_PROD(G1_COMPONENTS,SX2_COMPONENTS)
      DO I=1,IPROC
        IF (NINCOMING.EQ.2) THEN
          LUM = LUM + PD(I) * CONV
        ELSE
          LUM = LUM + PD(I)
        ENDIF
      ENDDO
      RETURN
      END
