      SUBROUTINE SMATRIXHEL(P,HEL, FLAVOR, ANS)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=5)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=32)
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: HEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
CF2PY INTENT(IN) :: FLAVOR(NEXTERNAL)

C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER HEL
      INTEGER FLAVOR(NEXTERNAL)
C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/HELUSERCHOICE/USERHEL
C     ----------
C     BEGIN CODE
C     ----------
      USERHEL=HEL
      CALL SMATRIX(P,FLAVOR,ANS)
      USERHEL=-1

      END

      SUBROUTINE SMATRIX(P, FLAVOR, ANS)
C     
C     Generated by MadGraph5_aMC@NLO v. %(version)s, %(date)s
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     MadGraph5_aMC@NLO StandAlone Version
C     
C     Returns amplitude squared summed/avg over colors
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL)
C     
C     Process: e+ e- > a a a
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=5)
      INTEGER    NINITIAL
      PARAMETER (NINITIAL=2)
      INTEGER NPOLENTRIES
      PARAMETER (NPOLENTRIES=(NEXTERNAL+1)*6)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=32)
      INTEGER HELAVGFACTOR
      PARAMETER (HELAVGFACTOR=4)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
CF2PY INTENT(IN) :: FLAVOR(NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER NHEL(NEXTERNAL,NCOMB),NTRY
C     put in common block to expose this variable to python interface
      COMMON/PROCESS_NHEL/NHEL
      REAL*8 T
      REAL*8 MATRIX
      INTEGER IHEL,IDEN, I, J
C     For a 1>N process, them BEAMTWO_HELAVGFACTOR would be set to 1.
      INTEGER BEAMS_HELAVGFACTOR(2)
      DATA (BEAMS_HELAVGFACTOR(I),I=1,2)/2,2/
      INTEGER FLAVOR(NEXTERNAL)
      LOGICAL GOODHEL(NCOMB)
      DATA NTRY/0/
      DATA GOODHEL/NCOMB*.FALSE./

C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/HELUSERCHOICE/USERHEL
      DATA USERHEL/-1/
      LOGICAL HELRESET
      COMMON/HELRESET/HELRESET
      DATA HELRESET/.TRUE./

      DATA (NHEL(I,   1),I=1,5) /-1, 1,-1,-1,-1/
      DATA (NHEL(I,   2),I=1,5) /-1, 1,-1,-1, 1/
      DATA (NHEL(I,   3),I=1,5) /-1, 1,-1, 1,-1/
      DATA (NHEL(I,   4),I=1,5) /-1, 1,-1, 1, 1/
      DATA (NHEL(I,   5),I=1,5) /-1, 1, 1,-1,-1/
      DATA (NHEL(I,   6),I=1,5) /-1, 1, 1,-1, 1/
      DATA (NHEL(I,   7),I=1,5) /-1, 1, 1, 1,-1/
      DATA (NHEL(I,   8),I=1,5) /-1, 1, 1, 1, 1/
      DATA (NHEL(I,   9),I=1,5) /-1,-1,-1,-1,-1/
      DATA (NHEL(I,  10),I=1,5) /-1,-1,-1,-1, 1/
      DATA (NHEL(I,  11),I=1,5) /-1,-1,-1, 1,-1/
      DATA (NHEL(I,  12),I=1,5) /-1,-1,-1, 1, 1/
      DATA (NHEL(I,  13),I=1,5) /-1,-1, 1,-1,-1/
      DATA (NHEL(I,  14),I=1,5) /-1,-1, 1,-1, 1/
      DATA (NHEL(I,  15),I=1,5) /-1,-1, 1, 1,-1/
      DATA (NHEL(I,  16),I=1,5) /-1,-1, 1, 1, 1/
      DATA (NHEL(I,  17),I=1,5) / 1, 1,-1,-1,-1/
      DATA (NHEL(I,  18),I=1,5) / 1, 1,-1,-1, 1/
      DATA (NHEL(I,  19),I=1,5) / 1, 1,-1, 1,-1/
      DATA (NHEL(I,  20),I=1,5) / 1, 1,-1, 1, 1/
      DATA (NHEL(I,  21),I=1,5) / 1, 1, 1,-1,-1/
      DATA (NHEL(I,  22),I=1,5) / 1, 1, 1,-1, 1/
      DATA (NHEL(I,  23),I=1,5) / 1, 1, 1, 1,-1/
      DATA (NHEL(I,  24),I=1,5) / 1, 1, 1, 1, 1/
      DATA (NHEL(I,  25),I=1,5) / 1,-1,-1,-1,-1/
      DATA (NHEL(I,  26),I=1,5) / 1,-1,-1,-1, 1/
      DATA (NHEL(I,  27),I=1,5) / 1,-1,-1, 1,-1/
      DATA (NHEL(I,  28),I=1,5) / 1,-1,-1, 1, 1/
      DATA (NHEL(I,  29),I=1,5) / 1,-1, 1,-1,-1/
      DATA (NHEL(I,  30),I=1,5) / 1,-1, 1,-1, 1/
      DATA (NHEL(I,  31),I=1,5) / 1,-1, 1, 1,-1/
      DATA (NHEL(I,  32),I=1,5) / 1,-1, 1, 1, 1/
      DATA IDEN/24/

      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      COMMON/BORN_BEAM_POL/POLARIZATIONS
      DATA ((POLARIZATIONS(I,J),I=0,NEXTERNAL),J=0,5)/NPOLENTRIES*-1/

C     
C     FUNCTIONS
C     
      LOGICAL IS_BORN_HEL_SELECTED
      INTEGER BROKEN_SYM
C     ----------
C     Check if helreset mode is on
C     ---------
      IF (HELRESET) THEN
        NTRY = 0
        DO I=1,NCOMB
          GOODHEL(I) = .FALSE.
        ENDDO
        HELRESET = .FALSE.
      ENDIF

C     ----------
C     BEGIN CODE
C     ----------
      IF(USERHEL.EQ.-1) NTRY=NTRY+1
C     When spin-2 particles are involved, the Helicity filtering is
C      dangerous for the 2->1 topology.
C     This is because depending on the MC setup the initial PS points
C      have back-to-back initial states
C     for which some of the spin-2 helicity configurations are zero.
C      But they are no longer zero
C     if the point is boosted on the z-axis. Remember that HELAS
C      helicity amplitudes are no longer
C     lorentz invariant with expternal spin-2 particles (only the
C      helicity sum is).
C     For this reason, we simply remove the filterin when there is
C      only three external particles.
      IF (NEXTERNAL.LE.3) THEN
        DO IHEL=1,NCOMB
          GOODHEL(IHEL)=.TRUE.
        ENDDO
      ENDIF
      ANS = 0D0
      DO IHEL=1,NCOMB
        IF (USERHEL.EQ.-1.OR.USERHEL.EQ.IHEL) THEN
          IF (GOODHEL(IHEL) .OR. NTRY .LT. 20.OR.USERHEL.NE.-1) THEN
            IF(NTRY.GE.2.AND.POLARIZATIONS(0,0).NE.
     $       -1.AND.(.NOT.IS_BORN_HEL_SELECTED(IHEL))) THEN
              CYCLE
            ENDIF
            T=MATRIX(P ,NHEL(1,IHEL),FLAVOR(1))
            IF(POLARIZATIONS(0,0).EQ.-1.OR.IS_BORN_HEL_SELECTED(IHEL))
     $        THEN
              ANS=ANS+T
            ENDIF
            IF (T .NE. 0D0 .AND. .NOT.    GOODHEL(IHEL)) THEN
              GOODHEL(IHEL)=.TRUE.
            ENDIF
          ENDIF
        ENDIF
      ENDDO
      ANS=ANS/DBLE(IDEN)*BROKEN_SYM(FLAVOR)
      IF(USERHEL.NE.-1) THEN
        ANS=ANS*HELAVGFACTOR
      ELSE
        DO J=1,NINITIAL
          IF (POLARIZATIONS(J,0).NE.-1) THEN
            ANS=ANS*BEAMS_HELAVGFACTOR(J)
            ANS=ANS/POLARIZATIONS(J,0)
          ENDIF
        ENDDO
      ENDIF
      END


      REAL*8 FUNCTION MATRIX(P,NHEL,FLAVOR)
      USE MODEL_OBJECT
C     
C     Generated by MadGraph5_aMC@NLO v. %(version)s, %(date)s
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared -- no average over initial
C      state/symmetry factor
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: e+ e- > a a a
C     
      USE ALOHA_OBJECT
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=6)
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=5)
      INTEGER    NWAVEFUNCS, NCOLOR
      PARAMETER (NWAVEFUNCS=9, NCOLOR=1)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL)
      INTEGER FLAVOR(NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J
      COMPLEX*16 ZTEMP
      INTEGER CF_INDEX
      INTEGER CF(NCOLOR*(NCOLOR+1)/2)
      INTEGER DENOM
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR), TMP_JAMP(0)
      TYPE(ALOHA) W(NWAVEFUNCS)
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
      DOUBLE PRECISION BWCUTOFF
C     
C     GLOBAL VARIABLES
C     
      INCLUDE 'coupl.inc'

C     
C     COLOR DATA
C     
      DATA DENOM/1/
      DATA (CF(I),I=  1,  1) /1/
C     1 ColorOne()
C     ----------
C     BEGIN CODE
C     ----------
      BWCUTOFF=15  ! use if $ syntax is defined in the process
      CALL OXXXXX(P(0,1),ZERO,NHEL(1),-1, FLAVOR(1),W(1))
      CALL IXXXXX(P(0,2),ZERO,NHEL(2),+1, FLAVOR(2),W(2))
      CALL VXXXXX(P(0,3),ZERO,NHEL(3),+1,W(3))
      CALL VXXXXX(P(0,4),ZERO,NHEL(4),+1,W(4))
      CALL VXXXXX(P(0,5),ZERO,NHEL(5),+1,W(5))
      CALL FVOXXX(W(1),W(3),MGVX12,ZERO,ZERO,W(6))
      CALL FVIXXX(W(2),W(4),MGVX12,ZERO,ZERO,W(7))
C     Amplitude(s) for diagram number 1
      CALL IOVXXX(W(7),W(6),W(5),MGVX12,AMP(1))
      CALL FVIXXX(W(2),W(5),MGVX12,ZERO,ZERO,W(8))
C     Amplitude(s) for diagram number 2
      CALL IOVXXX(W(8),W(6),W(4),MGVX12,AMP(2))
      CALL FVOXXX(W(1),W(4),MGVX12,ZERO,ZERO,W(6))
      CALL FVIXXX(W(2),W(3),MGVX12,ZERO,ZERO,W(9))
C     Amplitude(s) for diagram number 3
      CALL IOVXXX(W(9),W(6),W(5),MGVX12,AMP(3))
C     Amplitude(s) for diagram number 4
      CALL IOVXXX(W(8),W(6),W(3),MGVX12,AMP(4))
      CALL FVOXXX(W(1),W(5),MGVX12,ZERO,ZERO,W(6))
C     Amplitude(s) for diagram number 5
      CALL IOVXXX(W(9),W(6),W(4),MGVX12,AMP(5))
C     Amplitude(s) for diagram number 6
      CALL IOVXXX(W(7),W(6),W(3),MGVX12,AMP(6))
      JAMP(1) = (-1.000000000000000D+00)*AMP(1)+(-1.000000000000000D
     $ +00)*AMP(2)+(-1.000000000000000D+00)*AMP(3)+(
     $ -1.000000000000000D+00)*AMP(4)+(-1.000000000000000D+00)*AMP(5)
     $ +(-1.000000000000000D+00)*AMP(6)

      MATRIX = 0.D0
      CF_INDEX = 0
      DO I = 1, NCOLOR
        ZTEMP = (0D0,0D0)
        DO J = I, NCOLOR
          CF_INDEX = CF_INDEX +1
          ZTEMP = ZTEMP + CF(CF_INDEX)*JAMP(J)
        ENDDO
        MATRIX = MATRIX+REAL(ZTEMP*DCONJG(JAMP(I)))
      ENDDO
      MATRIX = MATRIX / DENOM

      END

      SUBROUTINE GET_VALUE(P, ALPHAS, NHEL, FLAVOR ,ANS)
C     This routine is the f2py interface for GET_value_internal which
C      can not be in the interface
C     due to f2py not knowing how to handle the couplings common block
      USE MODEL_OBJECT
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=5)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER NHEL
      DOUBLE PRECISION ALPHAS
      REAL*8 PI
      INTEGER FLAVOR(NEXTERNAL)
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: NHEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
CF2PY INTENT(IN) :: ALPHAS
CF2PY INTENT(IN) :: FLAVOR(NEXTERNAL)
C     ROUTINE FOR F2PY to read the benchmark point.    

      CALL  GET_VALUE_INTERNAL(P, ALPHAS, NHEL, FLAVOR ,ANS)
      RETURN
      END


      SUBROUTINE GET_VALUE_INTERNAL(P, ALPHAS, NHEL, FLAVOR ,ANS)
      USE MODEL_OBJECT
C     This routine is the real value but can not be in the interface
C     due to f2py not knowing how to handle the couplings common block
      USE MODEL_OBJECT
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=5)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER NHEL
      DOUBLE PRECISION ALPHAS
      REAL*8 PI
      INTEGER FLAVOR(NEXTERNAL)
C     ROUTINE FOR F2PY to read the benchmark point.    
C     the include file with the values of the parameters and masses 
      INCLUDE 'coupl.inc'

      PI = 3.141592653589793D0
      G = 2* DSQRT(ALPHAS*PI)
      CALL UPDATE_AS_PARAM()
      IF (NHEL.NE.0) THEN
        CALL SMATRIXHEL(P, NHEL, FLAVOR, ANS)
      ELSE
        CALL SMATRIX(P, FLAVOR, ANS)
      ENDIF
      RETURN
      END

      SUBROUTINE INITIALISEMODEL(PATH)
C     ROUTINE FOR F2PY to read the benchmark point.    
      IMPLICIT NONE
      CHARACTER*512 PATH
CF2PY INTENT(IN) :: PATH
      CALL SETPARA(PATH)  !first call to setup the paramaters    
      RETURN
      END

      LOGICAL FUNCTION IS_BORN_HEL_SELECTED(HELID)
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=5)
      INTEGER    NCOMB
      PARAMETER (NCOMB=32)
C     
C     ARGUMENTS
C     
      INTEGER HELID
C     
C     LOCALS
C     
      INTEGER I,J
      LOGICAL FOUNDIT
C     
C     GLOBALS
C     
      INTEGER HELC(NEXTERNAL,NCOMB)
      COMMON/PROCESS_NHEL/HELC

      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      COMMON/BORN_BEAM_POL/POLARIZATIONS
C     ----------
C     BEGIN CODE
C     ----------

      IS_BORN_HEL_SELECTED = .TRUE.
      IF (POLARIZATIONS(0,0).EQ.-1) THEN
        RETURN
      ENDIF

      DO I=1,NEXTERNAL
        IF (POLARIZATIONS(I,0).EQ.-1) THEN
          CYCLE
        ENDIF
        FOUNDIT = .FALSE.
        DO J=1,POLARIZATIONS(I,0)
          IF (HELC(I,HELID).EQ.POLARIZATIONS(I,J)) THEN
            FOUNDIT = .TRUE.
            EXIT
          ENDIF
        ENDDO
        IF(.NOT.FOUNDIT) THEN
          IS_BORN_HEL_SELECTED = .FALSE.
          RETURN
        ENDIF
      ENDDO

      RETURN
      END


      INTEGER FUNCTION BROKEN_SYM(FLAV)
      INCLUDE 'nexternal.inc'
      INTEGER FLAV(NEXTERNAL)
      INTEGER I,J,K,ICOMP
      INTEGER N_TOT, OLD_FACTOR, TOTAL_FACTOR
      INTEGER NCOMP, NENTRIES
      PARAMETER (NCOMP=1)
      PARAMETER (NENTRIES=3)
      INTEGER COMP_BEG(NCOMP), COMP_END(NCOMP), COMP_OLD(NCOMP)
      INTEGER PID_LIST(NENTRIES), PID_WORK(NENTRIES)
      INTEGER BLOCK_START(NENTRIES), BLOCK_LEN(NENTRIES)
      LOGICAL SAME_BLOCK
      DATA COMP_BEG /1/
      DATA COMP_END /3/
      DATA COMP_OLD /6/
      DATA PID_LIST /22,22,22/
      DATA BLOCK_START /3,4,5/
      DATA BLOCK_LEN /1,1,1/

      PID_WORK = PID_LIST
      TOTAL_FACTOR = 1
      DO ICOMP=1,NCOMP
        OLD_FACTOR = COMP_OLD(ICOMP)
        IF (COMP_OLD(ICOMP).GT.1) THEN
          DO I=COMP_BEG(ICOMP),COMP_END(ICOMP)
            IF (PID_WORK(I).EQ.0) CYCLE
            N_TOT = 1
            DO J=I+1,COMP_END(ICOMP)
              IF (PID_WORK(I).EQ.PID_WORK(J)) THEN
                SAME_BLOCK = .TRUE.
                IF (BLOCK_LEN(I).NE.BLOCK_LEN(J)) SAME_BLOCK = .FALSE.
                DO K=1,BLOCK_LEN(I)
                  IF (FLAV(BLOCK_START(I)+K-1).NE.FLAV(BLOCK_START(J)
     $             +K-1)) THEN
                    SAME_BLOCK = .FALSE.
                  ENDIF
                ENDDO
                IF (SAME_BLOCK) THEN
                  PID_WORK(J) = 0
                  N_TOT = N_TOT + 1
                  OLD_FACTOR = OLD_FACTOR/N_TOT
                ENDIF
              ENDIF
            ENDDO
          ENDDO
        ENDIF
        TOTAL_FACTOR = TOTAL_FACTOR*OLD_FACTOR
      ENDDO
      BROKEN_SYM = TOTAL_FACTOR
      RETURN
      END


