
      SUBROUTINE SMATRIXHEL(P,HEL,ANS_SUMMED)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=3)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=12)
      INTEGER NSQAMPSO
      PARAMETER (NSQAMPSO=1)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS_SUMMED
      INTEGER HEL
CF2PY INTENT(OUT) :: ANS_SUMMED
CF2PY INTENT(IN) ::HEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/HELUSERCHOICE/USERHEL
C     ----------
C     BEGIN CODE
C     ----------
      USERHEL=HEL
      CALL SMATRIX(P,ANS_SUMMED)
      USERHEL=-1

      END

      SUBROUTINE SMATRIX(P,ANS_SUMMED)
C     
C     Simple routine wrapper to provide the same interface for
C     backward compatibility for usage without split orders.
C     
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=3)
      INTEGER NSQAMPSO
      PARAMETER (NSQAMPSO=1)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL), ANS_SUMMED
CF2PY INTENT(OUT) :: ANS_SUMMED
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
C     
C     VARIABLES
C     
      INTEGER I
      REAL*8 ANS(0:NSQAMPSO)
C     
C     BEGIN CODE
C     
      CALL SMATRIX_SPLITORDERS(P,ANS)
      ANS_SUMMED=ANS(0)

      END

      SUBROUTINE SMATRIXHEL_SPLITORDERS(P,HEL,ANS)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=3)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=12)
      INTEGER NSQAMPSO
      PARAMETER (NSQAMPSO=1)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS(0:NSQAMPSO)
      INTEGER HEL
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) ::HEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/HELUSERCHOICE/USERHEL
C     ----------
C     BEGIN CODE
C     ----------
      USERHEL=HEL
      CALL SMATRIX_SPLITORDERS(P,ANS)
      USERHEL=-1

      END

      SUBROUTINE SMATRIX_SPLITORDERS(P,ANS)
C     
C     Generated by MadGraph5_aMC@NLO v. %(version)s, %(date)s
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     MadGraph5_aMC@NLO StandAlone Version
C     
C     Returns amplitude squared summed/avg over colors
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL)
C     
C     Process: u d~ > w+ [ all = QCD QED ] QCD^2<=2 QED^2<=2
C     Process: c s~ > w+ [ all = QCD QED ] QCD^2<=2 QED^2<=2
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=3)
      INTEGER    NINITIAL
      PARAMETER (NINITIAL=2)
      INTEGER NPOLENTRIES
      PARAMETER (NPOLENTRIES=(NEXTERNAL+1)*6)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=12)
      INTEGER NSQAMPSO
      PARAMETER (NSQAMPSO=1)
      INTEGER HELAVGFACTOR
      PARAMETER (HELAVGFACTOR=4)
      LOGICAL CHOSEN_SO_CONFIGS(NSQAMPSO)
      DATA CHOSEN_SO_CONFIGS/.TRUE./
      COMMON/CHOSEN_BORN_SQSO/CHOSEN_SO_CONFIGS
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS(0:NSQAMPSO)
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER NTRY
      REAL*8 T(NSQAMPSO), BUFF
      INTEGER IHEL,IDEN, I, J
C     For a 1>N process, them BEAMTWO_HELAVGFACTOR would be set to 1.
      INTEGER BEAMS_HELAVGFACTOR(2)
      DATA (BEAMS_HELAVGFACTOR(I),I=1,2)/2,2/
      INTEGER JC(NEXTERNAL)
      LOGICAL GOODHEL(NCOMB)
      DATA NTRY/0/
      DATA GOODHEL/NCOMB*.FALSE./
      DATA IDEN/36/
C     
C     GLOBAL VARIABLES
C     
      INTEGER NHEL(NEXTERNAL,NCOMB)
      DATA (NHEL(I,   1),I=1,3) / 1,-1,-1/
      DATA (NHEL(I,   2),I=1,3) / 1,-1, 0/
      DATA (NHEL(I,   3),I=1,3) / 1,-1, 1/
      DATA (NHEL(I,   4),I=1,3) / 1, 1,-1/
      DATA (NHEL(I,   5),I=1,3) / 1, 1, 0/
      DATA (NHEL(I,   6),I=1,3) / 1, 1, 1/
      DATA (NHEL(I,   7),I=1,3) /-1,-1,-1/
      DATA (NHEL(I,   8),I=1,3) /-1,-1, 0/
      DATA (NHEL(I,   9),I=1,3) /-1,-1, 1/
      DATA (NHEL(I,  10),I=1,3) /-1, 1,-1/
      DATA (NHEL(I,  11),I=1,3) /-1, 1, 0/
      DATA (NHEL(I,  12),I=1,3) /-1, 1, 1/
      DATA IDEN/36/
      COMMON/PROCESS_NHEL/NHEL

      INTEGER USERHEL
      DATA USERHEL/-1/
      COMMON/HELUSERCHOICE/USERHEL
      LOGICAL HELRESET
      COMMON/HELRESET/HELRESET
      DATA HELRESET/.TRUE./


      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      COMMON/BORN_BEAM_POL/POLARIZATIONS
      DATA ((POLARIZATIONS(I,J),I=0,NEXTERNAL),J=0,5)/NPOLENTRIES*-1/

C     
C     FUNCTIONS
C     
      LOGICAL IS_BORN_HEL_SELECTED

C     ----------
C     Check if helreset mode is on
C     ---------
      IF (HELRESET) THEN
        NTRY = 0
        DO I=1,NCOMB
          GOODHEL(I) = .FALSE.
        ENDDO
        HELRESET = .FALSE.
      ENDIF


C     ----------
C     BEGIN CODE
C     ----------
      IF(USERHEL.EQ.-1) NTRY=NTRY+1
      DO IHEL=1,NEXTERNAL
        JC(IHEL) = +1
      ENDDO
      ANS(:) = 0D0
C     When spin-2 particles are involved, the Helicity filtering is
C      dangerous for the 2->1 topology.
C     This is because depending on the MC setup the initial PS points
C      have back-to-back initial states
C     for which some of the spin-2 helicity configurations are zero.
C      But they are no longer zero
C     if the point is boosted on the z-axis. Remember that HELAS
C      helicity amplitudes are no longer
C     lorentz invariant with expternal spin-2 particles (only the
C      helicity sum is).
C     For this reason, we simply remove the filterin when there is
C      only three external particles.
      IF (NEXTERNAL.LE.3) THEN
        GOODHEL(:) = .TRUE.
      ENDIF
      DO IHEL=1,NCOMB
        IF (USERHEL.EQ.-1.OR.USERHEL.EQ.IHEL) THEN
          IF (GOODHEL(IHEL) .OR. NTRY .LT. 20 .OR.USERHEL.NE.-1) THEN
            IF(NTRY.GE.2.AND.POLARIZATIONS(0,0).NE.
     $       -1.AND.(.NOT.IS_BORN_HEL_SELECTED(IHEL))) THEN
              CYCLE
            ENDIF
            CALL MATRIX(P ,NHEL(1,IHEL),JC(1), T)
            BUFF=0D0
            DO I=1,NSQAMPSO
              IF(POLARIZATIONS(0,0).EQ.-1.OR.IS_BORN_HEL_SELECTED(IHEL)
     $         ) THEN
                ANS(I)=ANS(I)+T(I)
              ENDIF
              BUFF=BUFF+T(I)
            ENDDO
            IF (BUFF .NE. 0D0 .AND. .NOT.    GOODHEL(IHEL)) THEN
              GOODHEL(IHEL)=.TRUE.
            ENDIF
          ENDIF
        ENDIF
      ENDDO
      ANS(0)=0.0D0
      DO I=1,NSQAMPSO
        ANS(I)=ANS(I)/DBLE(IDEN)
        IF (CHOSEN_SO_CONFIGS(I)) THEN
          ANS(0)=ANS(0)+ANS(I)
        ENDIF
      ENDDO
      IF(USERHEL.NE.-1) THEN
        DO I=0,NSQAMPSO
          ANS(I)=ANS(I)*HELAVGFACTOR
        ENDDO
      ELSE
        DO J=1,NINITIAL
          IF (POLARIZATIONS(J,0).NE.-1) THEN
            DO I=0,NSQAMPSO
              ANS(I)=ANS(I)*BEAMS_HELAVGFACTOR(J)
              ANS(I)=ANS(I)/POLARIZATIONS(J,0)
            ENDDO
          ENDIF
        ENDDO
      ENDIF
      END


      SUBROUTINE MATRIX(P,NHEL,IC,RES)
C     
C     Generated by MadGraph5_aMC@NLO v. %(version)s, %(date)s
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared -- no average over initial
C      state/symmetry factor
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: u d~ > w+ [ all = QCD QED ] QCD^2<=2 QED^2<=2
C     Process: c s~ > w+ [ all = QCD QED ] QCD^2<=2 QED^2<=2
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=1)
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=3)
      INTEGER    NWAVEFUNCS, NCOLOR
      PARAMETER (NWAVEFUNCS=3, NCOLOR=1)
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=1, NSQAMPSO=1)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
      INTEGER DENOM
      INTEGER CF(1)
      COMMON /COLOR_MATRIX/ CF,DENOM
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
      REAL*8 RES(NSQAMPSO)
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J,M,N
      COMPLEX*16 ZTEMP
      COMPLEX*16 AMP(NGRAPHS)
      INTEGER CF_INDEX
      COMPLEX*16 JAMP(NCOLOR,NAMPSO)
      COMPLEX*16 TMP_JAMP(0)
      COMPLEX*16 W(20,NWAVEFUNCS)
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
C     
C     FUNCTION
C     
      INTEGER SQSOINDEX
C     
C     GLOBAL VARIABLES
C     
      INCLUDE 'coupl.inc'

C     
C     COLOR DATA
C     
      DATA DENOM/1/
      DATA (CF(I),I=  1,  1) /3/
C     1 T(2,1)
C     ----------
C     BEGIN CODE
C     ----------
      CALL GET_AMP(P,NHEL,IC,AMP)
C     WRITE (*,*) '  -> AMP = ', AMP
      CALL GET_JAMP(AMP,JAMP)
C     WRITE (*,*) '  -> JAMP = ', JAMP
      CALL GET_MATRIX(JAMP, RES)
C     write (*,*) "  -> col.ave. |M|^2 for HEL=[", NHEL ,"] = ", MATRIX



      END


      SUBROUTINE GET_NHEL(IDEN_STAR,NHEL_STAR)
C     CONSTANTS
C     
CF2PY INTENT(OUT) :: NHEL_STAR
CF2PY INTENT(OUT) :: IDEN_STAR
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=3)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=12)

      INTEGER NHEL(NEXTERNAL,NCOMB),NHEL_STAR(NEXTERNAL,NCOMB)
      INTEGER IDEN,IDEN_STAR

      DATA (NHEL(I,   1),I=1,3) / 1,-1,-1/
      DATA (NHEL(I,   2),I=1,3) / 1,-1, 0/
      DATA (NHEL(I,   3),I=1,3) / 1,-1, 1/
      DATA (NHEL(I,   4),I=1,3) / 1, 1,-1/
      DATA (NHEL(I,   5),I=1,3) / 1, 1, 0/
      DATA (NHEL(I,   6),I=1,3) / 1, 1, 1/
      DATA (NHEL(I,   7),I=1,3) /-1,-1,-1/
      DATA (NHEL(I,   8),I=1,3) /-1,-1, 0/
      DATA (NHEL(I,   9),I=1,3) /-1,-1, 1/
      DATA (NHEL(I,  10),I=1,3) /-1, 1,-1/
      DATA (NHEL(I,  11),I=1,3) /-1, 1, 0/
      DATA (NHEL(I,  12),I=1,3) /-1, 1, 1/
      DATA IDEN/36/
      IDEN_STAR = IDEN
      NHEL_STAR = NHEL
      END


      SUBROUTINE GET_AMP(P,NHEL,IC,AMP)
C     
C     Process: u d~ > w+ [ all = QCD QED ] QCD^2<=2 QED^2<=2
C     Process: c s~ > w+ [ all = QCD QED ] QCD^2<=2 QED^2<=2
C     
CF2PY INTENT(OUT) :: AMP
CF2PY INTENT(IN) :: NHEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
CF2PY INTENT(IN) :: IC

      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=1)
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=3)
      INTEGER    NWAVEFUNCS, NCOLOR
      PARAMETER (NWAVEFUNCS=3, NCOLOR=1)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
C     
C     ARGUMENTS
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
C     
C     LOCAL VARIABLES
C     
      COMPLEX*16 AMP(NGRAPHS)
      COMPLEX*16 W(20,NWAVEFUNCS)
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
C     
C     GLOBAL VARIABLES
C     
      INCLUDE 'coupl.inc'

C     
C     
      CALL IXXXXX(P(0,1),ZERO,NHEL(1),+1*IC(1),W(1,1))
      CALL OXXXXX(P(0,2),ZERO,NHEL(2),-1*IC(2),W(1,2))
      CALL VXXXXX(P(0,3),MDL_MW,NHEL(3),+1*IC(3),W(1,3))
C     Amplitude(s) for diagram number 1
      CALL FFV2_0(W(1,1),W(1,2),W(1,3),GC_11,AMP(1))

      END


      SUBROUTINE GET_JAMP(AMP,JAMP)
C     
C     Process: u d~ > w+ [ all = QCD QED ] QCD^2<=2 QED^2<=2
C     Process: c s~ > w+ [ all = QCD QED ] QCD^2<=2 QED^2<=2
C     
CF2PY INTENT(OUT) :: JAMP
CF2PY INTENT(IN) :: AMP

      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=1)
      INTEGER    NCOLOR
      PARAMETER ( NCOLOR=1)
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=1, NSQAMPSO=1)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
      COMPLEX*16 AMP(NGRAPHS), TMP_JAMP(0)
      COMPLEX*16 JAMP(NCOLOR,NAMPSO)

      JAMP(:,:) = 0D0
C     JAMPs contributing to orders QCD=0 QED=1
      JAMP(1,1) = AMP(1)
      END

      SUBROUTINE GET_MATRIX(JAMP, RES)
C     
C     Process: u d~ > w+ [ all = QCD QED ] QCD^2<=2 QED^2<=2
C     Process: c s~ > w+ [ all = QCD QED ] QCD^2<=2 QED^2<=2
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
CF2PY INTENT(OUT) :: MATRIX
CF2PY INTENT(IN) :: JAMP(NCOLOR,NAMPSO)


      INTEGER    NCOLOR
      PARAMETER (NCOLOR=1)
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=1, NSQAMPSO=1)
      REAL*8     ZERO,RES(NSQAMPSO)
      PARAMETER (ZERO=0D0)
      INTEGER SQSOINDEX
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J,M,N
      COMPLEX*16 ZTEMP

      INTEGER CF_INDEX
      INTEGER CF(NCOLOR*(NCOLOR+1)/2)
      INTEGER DENOM
      COMMON /COLOR_MATRIX/ CF,DENOM
      COMPLEX*16 JAMP(NCOLOR,NAMPSO), TMP_JAMP(0)
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
C     
C     COLOR DATA
C     

      RES(:) = 0.D0
      DO M = 1, NAMPSO
        CF_INDEX= 0
        DO I = 1, NCOLOR
          ZTEMP = (0.D0,0.D0)
          DO J = I, NCOLOR
            CF_INDEX = CF_INDEX +1
            ZTEMP = ZTEMP + CF(CF_INDEX)*JAMP(J,M)
          ENDDO
          DO N = 1, NAMPSO
            RES(SQSOINDEX(M,N)) = RES(SQSOINDEX(M,N)) + REAL(ZTEMP
     $       *DCONJG(JAMP(I,N)))
          ENDDO
        ENDDO
      ENDDO
      RES(:) = RES(:)/DENOM
      END

      SUBROUTINE GET_INTER(JAMP_1,JAMP_2, INTER)
      IMPLICIT NONE
CF2PY INTENT(OUT) :: INTER(NSQAMPSO)
CF2PY INTENT(IN) :: JAMP_1(NCOLOR,NAMPSO)
CF2PY INTENT(IN) :: JAMP_2(NCOLOR,NAMPSO)

      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=1, NSQAMPSO=1)
      INTEGER SQSOINDEX

      INTEGER I,J,M,N
      INTEGER NCOLOR
      PARAMETER (NCOLOR=1)
      INTEGER CF_INDEX
      INTEGER CF(NCOLOR*(NCOLOR+1)/2)
      INTEGER DENOM
      COMMON /COLOR_MATRIX/ CF,DENOM
      COMPLEX*16 JAMP_1(NCOLOR,NAMPSO),JAMP_2(NCOLOR,NAMPSO),ZTEMP
     $ ,INTER(NSQAMPSO)
C     
C     COLOR DATA
C     

      INTER(:) = 0.D0
      DO M = 1, NAMPSO
        CF_INDEX= 0
        DO I = 1, NCOLOR
          DO J = I, NCOLOR
            CF_INDEX = CF_INDEX +1
            DO N = 1, NAMPSO
              INTER(SQSOINDEX(M,N)) =
     $            INTER(SQSOINDEX(M,N)) + 
     $            CF(CF_INDEX)*(DCONJG(JAMP_2(I,N))*
     $            JAMP_1(J,M)+DCONJG(JAMP_2(J,N))*JAMP_1(I,M))             
            ENDDO
          ENDDO
        ENDDO
      ENDDO
      INTER(:) = INTER(:)/(2D0*DENOM)
      RETURN
      END

      SUBROUTINE  GET_DENSITY(P, POS, N_CHANGING, ALLOW_HEL, N_COMB,
     $  ALPHAS, INTER_SUM)
C     P momenta
C     NHEL base of helicity that are not changing
C     POS(N_CHNGING): position of the changing helicity
C     n_changing: number of changing helicity
C     ALLOW_HEL(NCOMB, N_CHANGING): combination of helicity to
C      consider (all jamp computed)
C     INTER((NCOMB*NCOMB+1)/2i,NSQAMPSO) : all interference term (not
C      the symmetric one)
      IMPLICIT NONE
CF2PY INTENT(IN) :: P(0:3,3)
CF2PY INTENT(IN) :: POS(N_CHANGING)
CF2PY INTENT(IN) :: N_CHANGING
CF2PY INTENT(IN) :: ALLOW_HEL(N_CHANGING*N_COMB)
CF2PY INTENT(IN) :: N_COMB
CF2PY INTENT(IN) :: ALPHAS
CF2PY INTENT(OUT) :: INTER_SUM(N_COMB*(N_COMB+1)/2)
C     

      INTEGER NB_NHEL
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NB_NHEL=12)
      PARAMETER (NAMPSO=1, NSQAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=3)
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER THISNHEL(NEXTERNAL)
      INTEGER N_CHANGING, N_COMB
      INTEGER NINTER
      INTEGER POS(*)
      INTEGER ALLOW_HEL(*)
      DOUBLE COMPLEX, ALLOCATABLE :: TMP_INTER(:,:)
      DOUBLE PRECISION ALPHAS
      DOUBLE COMPLEX INTER_SUM(*)
C     LOCAL
      INTEGER I,IHEL,IPART
      INTEGER J
      DOUBLE PRECISION PI
C     
C     GLOBAL
C     
      LOGICAL CHOSEN_SO_CONFIGS(NSQAMPSO)
      COMMON/CHOSEN_BORN_SQSO/CHOSEN_SO_CONFIGS

      INTEGER NHEL(NEXTERNAL,NB_NHEL),NTRY
C     put in common block to expose this variable to python interface
      COMMON/PROCESS_NHEL/NHEL
C     
C     include coupling definition to update the value of alphas
C     
      INCLUDE 'coupl.inc'

      NINTER = N_COMB*(N_COMB+1)/2
      ALLOCATE(TMP_INTER(NSQAMPSO, NINTER))
      TMP_INTER(:,:) = (0D0, 0D0)

      DO I = 1,  N_COMB*(N_COMB+1)/2
        INTER_SUM(I) = 0D0
      ENDDO

      IF (ALPHAS.NE.0D0) THEN
        PI = 3.141592653589793D0
        G = 2* DSQRT(ALPHAS*PI)
        CALL UPDATE_AS_PARAM()
      ENDIF

      DO IHEL =1, NB_NHEL
        THISNHEL(:) = NHEL(:, IHEL)
        DO IPART=1,N_CHANGING
          IF(THISNHEL(POS(IPART)).NE.ALLOW_HEL(IPART)) GOTO 10  !BYPASS COMPUTATION FOR HELICITY
        ENDDO
        TMP_INTER(:,:) = 0
        CALL  GET_ALL_INTER(P, THISNHEL, POS, N_CHANGING, ALLOW_HEL,
     $    N_COMB, TMP_INTER)
        DO J =1, NSQAMPSO
          IF (CHOSEN_SO_CONFIGS(J)) THEN
            DO I = 1, N_COMB*(N_COMB+1)/2
              INTER_SUM(I) = INTER_SUM(I) + TMP_INTER(J,I)
            ENDDO
          ENDIF
        ENDDO
 10   ENDDO
      RETURN
      DEALLOCATE(TMP_INTER)
      END



      SUBROUTINE  GET_ALL_INTER(P, NHEL, POS, N_CHANGING, ALLOW_HEL,
     $  N_COMB, INTER)
C     P momenta
C     NHEL base of helicity that are not changing
C     POS(N_CHNGING): position of the changing helicity
C     n_changing: number of changing helicity
C     ALLOW_HEL(NCOMB, N_CHANGING): combination of helicity to
C      consider (all jamp computed)
C     INTER(NSO, (NCOMB*NCOMB+1)/2): all interference term (not the
C      symmetric one)
      IMPLICIT NONE
CF2PY INTENT(IN) :: P(0:3,3)
CF2PY INTENT(IN) :: NHEL(3)
CF2PY INTENT(IN) :: POS(N_CHANGING)
CF2PY INTENT(IN) :: N_CHANGING
CF2PY INTENT(IN) :: ALLOW_HEL(N_CHANGING*N_COMB)
CF2PY INTENT(IN) :: N_COMB
CF2PY INTENT(OUT) :: INTER(NSQAMPSO,NCOMB*(NCOMB+1)/2)
C     
C     
C     ARGUMENTS
C     
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=1, NSQAMPSO=1)
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=3)
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL)
      INTEGER N_CHANGING, N_COMB
      INTEGER POS(*)
      INTEGER ALLOW_HEL(*)
      DOUBLE COMPLEX INTER(NSQAMPSO,*)
C     
C     Intermediate array
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=1)
      INTEGER    NCOLOR
      PARAMETER (NCOLOR=1)
      INTEGER IC(NEXTERNAL)

      DOUBLE COMPLEX AMP(NGRAPHS)
      DOUBLE COMPLEX, ALLOCATABLE:: JAMP(:,:,:)
      INTEGER, SAVE :: S_NCOMB = -1
C     
C     LOCAL
C     
      INTEGER I,J,SOL,N

C     ----------
C     BEGIN CODE
C     ----------
      IF (ALLOCATED(JAMP).AND. N_COMB.NE.S_NCOMB)THEN
        DEALLOCATE(JAMP)
      ENDIF
      IF (.NOT.ALLOCATED(JAMP))THEN
        ALLOCATE(JAMP(NCOLOR, NAMPSO, N_COMB))
        S_NCOMB=N_COMB
      ENDIF
      IC(:)=1
      DO I = 1, N_COMB
        DO N = 1, N_CHANGING
          NHEL(POS(N)) = ALLOW_HEL((I-1)*N_CHANGING+N)
        ENDDO
        CALL GET_AMP(P,NHEL,IC,AMP)
        CALL GET_JAMP(AMP,JAMP(1,1,I))
      ENDDO

      SOL = 0
      DO I = 1, N_COMB
        DO J= I, N_COMB
          SOL = SOL +1
          CALL GET_INTER(JAMP(1,1,I), JAMP(1,1,J), INTER(1,SOL))
        ENDDO
      ENDDO


      RETURN
      END





      SUBROUTINE GET_VALUE(P, ALPHAS, NHEL ,ANS)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=3)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER NHEL
      DOUBLE PRECISION ALPHAS
      REAL*8 PI
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: NHEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
CF2PY INTENT(IN) :: ALPHAS
C     ROUTINE FOR F2PY to read the benchmark point.    
C     the include file with the values of the parameters and masses 
      INCLUDE 'coupl.inc'

      PI = 3.141592653589793D0
      G = 2* DSQRT(ALPHAS*PI)
      CALL UPDATE_AS_PARAM()
      IF (NHEL.NE.0) THEN
        CALL SMATRIXHEL(P, NHEL, ANS)
      ELSE
        CALL SMATRIX(P, ANS)
      ENDIF
      RETURN
      END

      SUBROUTINE INITIALISEMODEL(PATH)
C     ROUTINE FOR F2PY to read the benchmark point.    
      IMPLICIT NONE
      CHARACTER*512 PATH
CF2PY INTENT(IN) :: PATH
      CALL SETPARA(PATH)  !first call to setup the paramaters    
      RETURN
      END

      LOGICAL FUNCTION IS_BORN_HEL_SELECTED(HELID)
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=3)
      INTEGER    NCOMB
      PARAMETER (NCOMB=12)
C     
C     ARGUMENTS
C     
      INTEGER HELID
C     
C     LOCALS
C     
      INTEGER I,J
      LOGICAL FOUNDIT
C     
C     GLOBALS
C     
      INTEGER HELC(NEXTERNAL,NCOMB)
      COMMON/PROCESS_NHEL/HELC

      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      COMMON/BORN_BEAM_POL/POLARIZATIONS
C     ----------
C     BEGIN CODE
C     ----------

      IS_BORN_HEL_SELECTED = .TRUE.
      IF (POLARIZATIONS(0,0).EQ.-1) THEN
        RETURN
      ENDIF

      DO I=1,NEXTERNAL
        IF (POLARIZATIONS(I,0).EQ.-1) THEN
          CYCLE
        ENDIF
        FOUNDIT = .FALSE.
        DO J=1,POLARIZATIONS(I,0)
          IF (HELC(I,HELID).EQ.POLARIZATIONS(I,J)) THEN
            FOUNDIT = .TRUE.
            EXIT
          ENDIF
        ENDDO
        IF(.NOT.FOUNDIT) THEN
          IS_BORN_HEL_SELECTED = .FALSE.
          RETURN
        ENDIF
      ENDDO

      RETURN
      END


C     Set of functions to handle the array indices of the split orders


      INTEGER FUNCTION SQSOINDEX(ORDERINDEXA, ORDERINDEXB)
C     
C     This functions plays the role of the interference matrix. It can
C      be hardcoded or 
C     made more elegant using hashtables if its execution speed ever
C      becomes a relevant
C     factor. From two split order indices, it return the
C      corresponding index in the squared 
C     order canonical ordering.
C     
C     CONSTANTS
C     

      INTEGER    NSO, NSQUAREDSO, NAMPSO
      PARAMETER (NSO=2, NSQUAREDSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERINDEXA, ORDERINDEXB
C     
C     LOCAL VARIABLES
C     
      INTEGER I, SQORDERS(NSO)
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      DATA (AMPSPLITORDERS(  1,I),I=  1,  2) /    0,    1/
      COMMON/AMPSPLITORDERS/AMPSPLITORDERS
C     
C     FUNCTION
C     
      INTEGER SOINDEX_FOR_SQUARED_ORDERS
C     
C     BEGIN CODE
C     
      DO I=1,NSO
        SQORDERS(I)=AMPSPLITORDERS(ORDERINDEXA,I)
     $   +AMPSPLITORDERS(ORDERINDEXB,I)
      ENDDO
      SQSOINDEX=SOINDEX_FOR_SQUARED_ORDERS(SQORDERS)
      END

      INTEGER FUNCTION SOINDEX_FOR_SQUARED_ORDERS(ORDERS)
C     
C     This functions returns the integer index identifying the squared
C      split orders list passed in argument which corresponds to the
C      values of the following list of couplings (and in this order).
C     ['QCD', 'QED']
C     
C     CONSTANTS
C     
      INTEGER    NSO, NSQSO, NAMPSO
      PARAMETER (NSO=2, NSQSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J
      INTEGER SQSPLITORDERS(NSQSO,NSO)
      DATA (SQSPLITORDERS(  1,I),I=  1,  2) /    0,    2/
      COMMON/SQPLITORDERS/SQPLITORDERS
C     
C     BEGIN CODE
C     
      DO I=1,NSQSO
        DO J=1,NSO
          IF (ORDERS(J).NE.SQSPLITORDERS(I,J)) GOTO 1009
        ENDDO
        SOINDEX_FOR_SQUARED_ORDERS = I
        RETURN
 1009   CONTINUE
      ENDDO

      WRITE(*,*) 'ERROR:: Stopping in function'
      WRITE(*,*) 'SOINDEX_FOR_SQUARED_ORDERS'
      WRITE(*,*) 'Could not find squared orders ',(ORDERS(I),I=1,NSO)
      STOP

      END

      SUBROUTINE GET_NSQSO_BORN(NSQSO)
C     
C     Simple subroutine returning the number of squared split order
C     contributions returned when calling smatrix_split_orders 
C     

      INTEGER    NSQUAREDSO
      PARAMETER  (NSQUAREDSO=1)

      INTEGER NSQSO

      NSQSO=NSQUAREDSO

      END

C     This is the inverse subroutine of SOINDEX_FOR_SQUARED_ORDERS.
C      Not directly useful, but provided nonetheless.
      SUBROUTINE GET_SQUARED_ORDERS_FOR_SOINDEX(SOINDEX,ORDERS)
C     
C     This functions returns the orders identified by the squared
C      split order index in argument. Order values correspond to
C      following list of couplings (and in this order):
C     ['QCD', 'QED']
C     
C     CONSTANTS
C     
      INTEGER    NSO, NSQSO
      PARAMETER (NSO=2, NSQSO=1)
C     
C     ARGUMENTS
C     
      INTEGER SOINDEX, ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I
      INTEGER SQPLITORDERS(NSQSO,NSO)
      COMMON/SQPLITORDERS/SQPLITORDERS
C     
C     BEGIN CODE
C     
      IF (SOINDEX.GT.0.AND.SOINDEX.LE.NSQSO) THEN
        DO I=1,NSO
          ORDERS(I) =  SQPLITORDERS(SOINDEX,I)
        ENDDO
        RETURN
      ENDIF

      WRITE(*,*) 'ERROR:: Stopping function'
     $ //' GET_SQUARED_ORDERS_FOR_SOINDEX'
      WRITE(*,*) 'Could not find squared orders index ',SOINDEX
      STOP

      END SUBROUTINE

C     This is the inverse subroutine of getting amplitude SO orders.
C      Not directly useful, but provided nonetheless.
      SUBROUTINE GET_ORDERS_FOR_AMPSOINDEX(SOINDEX,ORDERS)
C     
C     This functions returns the orders identified by the split order
C      index in argument. Order values correspond to following list of
C      couplings (and in this order):
C     ['QCD', 'QED']
C     
C     CONSTANTS
C     
      INTEGER    NSO, NAMPSO
      PARAMETER (NSO=2, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER SOINDEX, ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      COMMON/AMPSPLITORDERS/AMPSPLITORDERS
C     
C     BEGIN CODE
C     
      IF (SOINDEX.GT.0.AND.SOINDEX.LE.NAMPSO) THEN
        DO I=1,NSO
          ORDERS(I) =  AMPSPLITORDERS(SOINDEX,I)
        ENDDO
        RETURN
      ENDIF

      WRITE(*,*) 'ERROR:: Stopping function GET_ORDERS_FOR_AMPSOINDEX'
      WRITE(*,*) 'Could not find amplitude split orders index ',SOINDEX
      STOP

      END SUBROUTINE

C     This function is not directly useful, but included for
C      completeness
      INTEGER FUNCTION SOINDEX_FOR_AMPORDERS(ORDERS)
C     
C     This functions returns the integer index identifying the
C      amplitude split orders passed in argument which correspond to
C      the values of the following list of couplings (and in this
C      order):
C     ['QCD', 'QED']
C     
C     CONSTANTS
C     
      INTEGER    NSO, NAMPSO
      PARAMETER (NSO=2, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      COMMON/AMPSPLITORDERS/AMPSPLITORDERS
C     
C     BEGIN CODE
C     
      DO I=1,NAMPSO
        DO J=1,NSO
          IF (ORDERS(J).NE.AMPSPLITORDERS(I,J)) GOTO 1009
        ENDDO
        SOINDEX_FOR_AMPORDERS = I
        RETURN
 1009   CONTINUE
      ENDDO

      WRITE(*,*) 'ERROR:: Stopping function SOINDEX_FOR_AMPORDERS'
      WRITE(*,*) 'Could not find squared orders ',(ORDERS(I),I=1,NSO)
      STOP

      END

