#!/usr/bin/env python3
"""``dsigma/dm_tt`` near the ``2 m_t`` threshold -- MadSpin's spinmodes against
the doubly-resonant off-shell MadGraph truth, in the MG7 paper's plotting style.

Runs entirely off the committed raw histograms, so nothing here needs MadSpin:

    plot_mtt_threshold.py [--data DIR] [--out DIR]

with ``<data>`` holding ``histograms.npz`` and ``meta.json`` as written by
``run_mtt_threshold.py``.

What is drawn is a PER-EVENT quantity and the axes say so: the invariant mass of
``(W+ b) + (W- b~)``, built from the four status-1 particles with ``|pid|`` in
``{24, 5}`` of each event, identically on both sides.  The vertical scale is the
absolute differential cross section in pb/GeV -- no curve is renormalised to any
other.

Style follows the MG7 paper's ``plotexample/dummyplot.py``: LaTeX text, serif,
base font size 14, step histograms of line width 1.2, the paper's fixed figure
width (7*0.75 in -- "do not change the horizontal size"), tableau colours with
black/blue/red promoted, frameless legends, minor tick locators.
"""

import argparse
import json
import math
import os
import sys

import numpy as np

import matplotlib
matplotlib.use('Agg')
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
from matplotlib.ticker import AutoMinorLocator

_HERE = os.path.dirname(os.path.abspath(__file__))


# --- work around a matplotlib bug that eats every minus sign in the PDFs ---
def _fix_type1_subset_minus():
    """Stop matplotlib's usetex PDF path from dropping every minus sign.

    ``_type1font.Type1Font.subset`` in matplotlib 3.11.0 ends its encoding
    filter with an unconditional

        encoding[0] = '.notdef'

    For a text font slot 0 really is ``.notdef``, but TeX's CMSY10 -- the font
    every math minus comes from -- carries ``minus`` there.  Subsetting a
    figure's fonts therefore throws the minus away and the PDF comes out with an
    empty /Differences and no /BaseEncoding, so viewers silently drop the sign:
    no warning, no error, a wrong figure.  Only PDF is affected (the PNGs go
    through dvipng, which rasterises first).

    This figure carries a minus sign in the ratio ticks and in every
    ``m_tt - 2 m_t`` label, so the bug would be visible.  Guarded on the exact
    upstream line, so a fixed matplotlib is left alone.  ``--check-minus``
    re-opens the written PDF and asserts the sign survived; that check has had
    to be made twice in this project already.
    """
    import inspect
    import textwrap
    from matplotlib import _type1font

    # NO_MINUS_FIX=1 disables the workaround.  Its only purpose is to prove that
    # ``check_minus`` is discriminating: with the fix off, the check must fail.
    # If it passed either way it would be worthless as a guard.
    if os.environ.get('NO_MINUS_FIX'):
        return False

    bad = "encoding[0] = '.notdef'"
    good = "encoding.setdefault(0, '.notdef')"
    try:
        src = textwrap.dedent(inspect.getsource(_type1font.Type1Font.subset))
    except (OSError, TypeError):            # no source available
        return False
    if bad not in src:                      # already fixed upstream
        return False
    ns = vars(_type1font).copy()
    exec(compile(src.replace(bad, good), '<type1font-minus-fix>', 'exec'), ns)
    _type1font.Type1Font.subset = ns['subset']
    return True


MINUS_FIX = _fix_type1_subset_minus()


def _have_latex():
    import shutil
    if os.environ.get('NO_USETEX'):
        return False
    for extra in ('/Library/TeX/texbin', '/usr/local/texlive/bin',
                  '/usr/bin', '/usr/local/bin'):
        if os.path.isdir(extra) and extra not in os.environ.get('PATH', ''):
            os.environ['PATH'] = os.environ.get('PATH', '') + os.pathsep + extra
    return bool(shutil.which('latex')) and bool(shutil.which('dvipng'))


USETEX = _have_latex()
mpl.rcParams.update({"text.usetex": USETEX, "font.family": "serif",
                     "font.size": 14, 'lines.markersize': 8})
if not USETEX:
    mpl.rcParams.update({'mathtext.fontset': 'cm'})

LW = 1.2
allcolors = list(mcolors.TABLEAU_COLORS.values())
allcolors[1] = 'black'
allcolors[0] = 'blue'
allcolors[3] = 'red'


# --------------------------------------------------------------------------
# The curves.
#
#   truth       p p > t t~ j, t > w+ b, t~ > w- b~ generated by MG5.  Full
#               doubly-resonant off-shell matrix element, both tops carrying
#               their Breit-Wigner propagator out to ``bwcutoff`` widths.  This
#               is the reference every ratio divides by.
#   madspin     MadSpin's default off-shell spinmode: the virtuality comes from
#               the off-shell density matrix, i.e. from the matrix element.
#   PA          pole approximation: a per-particle Breit-Wigner draw multiplying
#               an on-shell density, then the production reshuffle.
#   onshell     no virtuality is drawn at all and ``_density_do_reshuffle`` is
#               False, so the production momenta are untouched.  Its m_tt is the
#               production sample's m_tt bit for bit -- verified in RESULTS.md
#               from the event-by-event pairing, max |Delta m_tt| = 0 exactly.
#   madspin_v1  the legacy Fortran path.  It does not go through run_onshell at
#               all: it draws the virtualities inside its own Fortran driver and
#               then REGENERATES the whole phase-space point from the
#               decay-chain topology, holding sqrt(shat) and the production
#               tree's invariants at the values it extracted from the production
#               event (``generate_momenta_conf`` / ``keep_inv`` in
#               MadSpin/src/driver.f).  That is a different reshuffle from the
#               RAMBO mass_shuffle the density modes use, so where it lands is
#               a measurement, not a prediction.
#   production  the undecayed p p > t t~ j sample.  Harvested and tabulated but
#               deliberately NOT drawn: ``onshell`` reproduces it event by event
#               (max |Delta m_tt| = 0 exactly), so a second curve on top of it
#               would only add ink.  RESULTS.md carries the comparison.
# --------------------------------------------------------------------------
CURVES = [
    ('truth',      r'truth: $pp \to t\bar t j$, $t \to W^+ b$ (off shell)'),
    ('madspin',    r'MadSpin, \texttt{spinmode = madspin}'),
    ('PA',         r'MadSpin, \texttt{spinmode = PA}'),
    ('onshell',    r'MadSpin, \texttt{spinmode = onshell}'),
    ('madspin_v1', r'MadSpin, \texttt{spinmode = madspin\_v1} (legacy)'),
]
CURVES_PLAIN = {
    'truth':      r'truth: $pp \to t\bar t j$, $t \to W^+ b$ (off shell)',
    'madspin':    'MadSpin, spinmode = madspin',
    'PA':         'MadSpin, spinmode = PA',
    'onshell':    'MadSpin, spinmode = onshell',
    'madspin_v1': 'MadSpin, spinmode = madspin_v1 (legacy)',
}
REF = 'truth'
MODES = ['madspin', 'PA', 'onshell', 'madspin_v1']

COLOR = {'truth': 'black', 'madspin': 'blue', 'PA': 'red',
         'onshell': allcolors[2], 'madspin_v1': allcolors[4],
         'production': 'gray'}
LS = {'truth': 'solid', 'madspin': 'solid', 'PA': 'dashed',
      'onshell': 'dashdot', 'madspin_v1': (0, (1, 1.4)),
      'production': 'dotted'}


# --------------------------------------------------------------------------
# Binning.
#
# ``run_mtt_threshold.py`` writes a fine UNIFORM 0.25 GeV grid so the committed
# .npz stays the raw measurement.  Plotting wants something else: the truth
# spectrum falls by three decades from the peak into the sub-threshold tail, so
# a binning that resolves the threshold turn-on leaves single-digit counts
# 20 GeV below it -- and that tail is exactly where the schemes differ.  Whole
# numbers of fine bins are grouped into zones, so no bin edge moves and nothing
# is interpolated:
#
#   316 -- 326  10   GeV   the deep sub-threshold tail, ~0.001% of sigma
#   326 -- 336   5   GeV
#   336 -- 344   2   GeV   approaching the threshold
#   344 -- 356   1   GeV   the turn-on itself, on both sides of 2 m_t
#   356 -- 380   2   GeV   where the schemes come back together
#   380 -- 420   5   GeV   the region that must be flat at unity
#
# Every edge is a multiple of 0.25 GeV, and 346.0 = 2 m_t is an edge, so no bin
# straddles the threshold: a bin either is entirely below it (where onshell has
# exactly zero support) or entirely above it.  That is not cosmetic -- a
# straddling bin would smear "structurally empty" into "small but non-zero".
# --------------------------------------------------------------------------
ZONES = [(316.0, 326.0, 10.0),
         (326.0, 336.0, 5.0),
         (336.0, 344.0, 2.0),
         (344.0, 356.0, 1.0),
         (356.0, 380.0, 2.0),
         (380.0, 420.0, 5.0)]

# The window the "does it agree" question is asked in.
AGREE_HI = 420.0


def zone_edges():
    out = [ZONES[0][0]]
    for lo, hi, w in ZONES:
        n = int(round((hi - lo) / w))
        for k in range(1, n + 1):
            out.append(lo + k * w)
    return np.array(out)


class Data(object):
    """The raw fine grid, and the rebinned absolute differential cross section.

    ``density`` is ``dsigma/dm_tt`` in pb/GeV.  The LHE files are written with
    ``event_norm = average``, i.e. every event carries the full cross section as
    its weight and the *mean* weight is sigma; the density of a bin is therefore
    ``sum(w)_bin / N_total / width``, and integrating it over all bins returns
    sigma.  ``check_norm`` records the agreement with the banner's own cross
    section, which is an independent number.
    """

    def __init__(self, ddir):
        self.z = np.load(os.path.join(ddir, 'histograms.npz'))
        self.meta = json.load(open(os.path.join(ddir, 'meta.json')))
        self.fine = self.z['bins']
        self.edges = zone_edges()
        self.centres = 0.5 * (self.edges[:-1] + self.edges[1:])
        self.widths = np.diff(self.edges)
        self.two_mt = float(self.meta.get('two_mt', 346.0))
        self._groups = self._group_map()

    def _group_map(self):
        """(start, stop) index pairs into the fine grid, one per plot bin."""
        fine = self.fine
        groups = []
        for lo, hi in zip(self.edges[:-1], self.edges[1:]):
            a = int(np.argmin(np.abs(fine - lo)))
            b = int(np.argmin(np.abs(fine - hi)))
            assert abs(fine[a] - lo) < 1e-9 and abs(fine[b] - hi) < 1e-9, \
                'plot bin edge %s/%s is not on the fine grid' % (lo, hi)
            groups.append((a, b))
        return groups

    def _rebin(self, vec):
        return np.array([vec[a:b].sum() for a, b in self._groups])

    def nevents(self, key):
        return float(self.meta['runs'][key]['nevents'])

    def sigma(self, key):
        """Total cross section of the sample, from its own event weights."""
        return self.meta['runs'][key]['sumw'] / self.nevents(key)

    def banner_sigma(self, key):
        return self.meta['runs'][key].get('banner_cross_pb')

    def density(self, key):
        """(dsigma/dm [pb/GeV], its statistical error, raw event count)."""
        n = self.nevents(key)
        sumw = self._rebin(self.z['%s_sumw' % key])
        sumw2 = self._rebin(self.z['%s_sumw2' % key])
        cnt = self._rebin(self.z['%s_cnt' % key])
        return sumw / n / self.widths, np.sqrt(sumw2) / n / self.widths, cnt

    def fine_density(self, key):
        n = self.nevents(key)
        w = np.diff(self.fine)
        return self.z['%s_sumw' % key] / n / w

    def integral(self, key, lo, hi):
        """(sigma, error, count) over ``lo <= m_tt < hi`` on the FINE grid.

        Done on the fine grid rather than the plot bins so the answer does not
        depend on the plotting choices above.
        """
        fine = self.fine
        c = 0.5 * (fine[:-1] + fine[1:])
        mask = (c >= lo) & (c < hi)
        n = self.nevents(key)
        s = self.z['%s_sumw' % key][mask].sum() / n
        e = math.sqrt(self.z['%s_sumw2' % key][mask].sum()) / n
        k = int(self.z['%s_cnt' % key][mask].sum())
        return s, e, k


def structurally_empty(d, key):
    """Bins where ``key`` has no support *by construction*, not by bad luck.

    ``onshell`` draws no virtuality and never reshuffles, so every decayed event
    keeps its production ``m_tt`` and the whole region below ``2 m_t`` is
    unreachable -- for any sample size.  Nothing else on this figure is in that
    position: ``madspin``, ``PA`` and ``madspin_v1`` all *can* land below
    threshold (the density modes because the RAMBO reshuffle rescales the recoil
    jet, ``madspin_v1`` because it regenerates the phase-space point outright),
    so an empty sub-threshold bin of theirs is a statistical statement and is
    drawn as a gap, not as a zero.

    The claim is checked against the data rather than asserted: if a bin marked
    structurally empty turned out to hold events, this raises.
    """
    mask = d.centres < d.two_mt
    if key != 'onshell':
        return np.zeros_like(mask)
    _, _, cnt = d.density(key)
    bad = mask & (cnt > 0)
    if bad.any():
        raise AssertionError(
            'onshell has %d events below 2 m_t -- the "structurally empty" '
            'claim is false and the figure must not be drawn'
            % int(cnt[bad].sum()))
    return mask


def ratio(num, nume, den, dene):
    """``num/den`` with the two errors combined in quadrature.

    Where the denominator is zero the ratio is NaN (nothing to divide by).
    Where the *numerator* is zero but the denominator is not, the ratio is a
    true 0.0, not a NaN: that is the whole point of the sub-threshold region for
    ``onshell`` and it must be drawn, not dropped.
    """
    r = np.full_like(num, np.nan, dtype=float)
    re = np.full_like(num, np.nan, dtype=float)
    good = den > 0
    r[good] = num[good] / den[good]
    with np.errstate(divide='ignore', invalid='ignore'):
        rel_n = np.where(num[good] > 0, nume[good] / num[good], 0.0)
        rel_d = dene[good] / den[good]
    re[good] = np.abs(r[good]) * np.sqrt(rel_n ** 2 + rel_d ** 2)
    # A bin with zero numerator still has an error bar: it is the reference's.
    zero = good & (num == 0)
    re[zero] = nume[zero] / den[zero] if nume[zero].size else 0.0
    return r, re


# --------------------------------------------------------------------------
# The ratio pane is CLIPPED to +-20 %.
#
# Several points genuinely live outside that window and none of them may quietly
# disappear, so the clipping comes with two marks that mean different things:
#
#   arrow  -- a MEASURED ratio whose central value is outside the pane.  The
#             arrow sits at the boundary it left through and points that way, so
#             the reader can see both that the point exists and which direction
#             it went.  A clipped point drawn as an ordinary marker sitting at
#             1.2 would be worse than not clipping at all.
#   open   -- ``onshell``'s exact zero below ``2 m_t``.  That is not a point
#   circle    that ran off the pane, it is a structural zero (see
#             :func:`structurally_empty`), and it keeps the open-marker
#             convention it had on the unclipped figure.  It carries no arrow,
#             precisely so the two cases stay distinguishable.
#
# Both the axis label and the in-pane key say the pane is clipped.
# --------------------------------------------------------------------------
RATIO_CLIP = (0.8, 1.2)


def offscale_arrows(ax, x, r, colour, clip=RATIO_CLIP, dx=None, slot=0,
                    nslot=1, lw=1.0, scale=9):
    """Draw one arrow per point of ``r`` that lies outside ``clip``.

    ``dx``/``slot``/``nslot`` spread the arrows of several curves horizontally
    inside their shared bin, so four modes leaving the same bin give four
    visible arrows rather than one drawn four times.

    Returns ``(n_below, n_above)``.
    """
    lo, hi = clip
    span = hi - lo
    x = np.asarray(x, dtype=float)
    if dx is None:
        dx = np.zeros_like(x)
    shift = ((slot - 0.5 * (nslot - 1)) / max(nslot, 1)) * 0.55 * np.asarray(dx)
    n_lo = n_hi = 0
    for xi, sh, ri in zip(x, shift, r):
        if not np.isfinite(ri):
            continue
        if ri < lo:
            tail, head = lo + 0.13 * span, lo + 0.015 * span
            n_lo += 1
        elif ri > hi:
            tail, head = hi - 0.13 * span, hi - 0.015 * span
            n_hi += 1
        else:
            continue
        ax.annotate('', xy=(xi + sh, head), xytext=(xi + sh, tail),
                    arrowprops=dict(arrowstyle='-|>', color=colour, lw=lw,
                                    shrinkA=0, shrinkB=0,
                                    mutation_scale=scale),
                    annotation_clip=False, zorder=7)
    return n_lo, n_hi


# The window used to divide out the overall normalisation for the SHAPE-only
# variant of the agreement question.  High enough that every scheme is well
# inside its asymptotic regime and the statistics are good; the figure itself is
# always in absolute normalisation and is never rescaled.
ANCHOR = (380.0, 420.0)


def anchor_scale(d, key):
    """``sigma_truth / sigma_key`` over :data:`ANCHOR`, and its relative error.

    Why this exists.  The two sides do NOT share a total cross section, and the
    difference is a real, understood effect rather than a bug: MG5's decay-chain
    truth truncates each top's Breit-Wigner at ``bwcutoff`` widths in the MASS
    (``myamp.f``: ``abs(xmass - prmass) < bwcutoff * prwidth``, the same
    convention MadSpin's ``BW_cut`` uses), which removes
    ``1 - 2*arctan(2*bwcutoff)/pi`` ~ 2.3 % per resonance, ~4.6 % for the pair;
    MadSpin's output cross section is ``sigma_production * BR`` and carries no
    such loss, nor any off-shell correction to the RATE.  So an absolute ratio
    sits on a plateau that is not 1, and a 5 % tolerance on the absolute ratio
    is partly a statement about that offset.

    Reporting both answers separates the two questions: "is the rate right"
    (it is not, by a known and quantified amount) and "is the SHAPE near
    threshold right" (which is what the reshuffle controls).
    """
    st, ste, _ = d.integral(REF, *ANCHOR)
    sk, ske, _ = d.integral(key, *ANCHOR)
    if sk <= 0:
        return float('nan'), float('nan')
    scale = st / sk
    rel = math.sqrt((ste / st) ** 2 + (ske / sk) ** 2)
    return scale, rel


def agreement_threshold(d, key, tol, scale=1.0):
    """Lowest plot-bin edge above which every bin agrees with truth to ``tol``.

    ``scale`` multiplies the mode's density before the comparison; 1.0 is the
    absolute question, :func:`anchor_scale` gives the shape-only one.

    Two answers, because they say different things:

      * ``strict``   -- the lowest edge X such that every bin centred above X
                        has ``|ratio - 1| <= tol`` on its CENTRAL value.
      * ``compat``   -- the same, but a bin counts as agreeing when it is
                        within ``tol`` once its own 1 sigma error is allowed,
                        i.e. ``|ratio - 1| - err <= tol``.  This is the honest
                        statement when the per-bin errors are a few percent:
                        the strict answer is then partly a statement about the
                        sample size, not about the physics.

    Scanned downwards from ``AGREE_HI`` so the answer is "agreement holds from
    here up", not "there exists one bin that agrees".
    """
    num, nume, _ = d.density(key)
    den, dene, _ = d.density(REF)
    r, re = ratio(num * scale, nume * scale, den, dene)
    out = {}
    for name, ok in (('strict', lambda i: abs(r[i] - 1) <= tol),
                     ('compat', lambda i: abs(r[i] - 1) - re[i] <= tol)):
        edge = None
        for i in range(len(r) - 1, -1, -1):
            if d.centres[i] > AGREE_HI:
                continue
            if not np.isfinite(r[i]):
                break
            if ok(i):
                edge = d.edges[i]
            else:
                break
        out[name] = edge
        if edge is not None:
            j = int(np.argmin(np.abs(d.edges - edge)))
            out[name + '_ratio'] = float(r[j])
            out[name + '_err'] = float(re[j])
    return out


# --------------------------------------------------------------------------
def _panels():
    # The MG7 paper fixes the horizontal size; only the height is ours.
    fig = plt.figure(figsize=(7 * 0.75 * 1.35, 7 * 0.75 * 1.5))
    gs = fig.add_gridspec(2, 1, height_ratios=[3, 1], hspace=0.06)
    ax = fig.add_subplot(gs[0])
    rx = fig.add_subplot(gs[1], sharex=ax)
    return fig, ax, rx


def _tx(s_tex, s_plain):
    return s_tex if USETEX else s_plain


def make_figure(d, out, style_tag=''):
    fig, ax, rx = _panels()
    two_mt = d.two_mt
    lo, hi = d.edges[0], d.edges[-1]

    # --- the structurally empty region -----------------------------------
    # Shaded on BOTH panes, and labelled for what it is: below 2 m_t the
    # production sample has no support at all (on-shell tops), and ``onshell``
    # inherits that exactly.  ``madspin`` and ``PA`` do reach it -- through the
    # production reshuffle, which rescales the recoil jet and so moves m_tt --
    # so the shading marks the *on-shell kinematic boundary*, not an empty
    # region of the figure.
    for a in (ax, rx):
        a.axvspan(lo, two_mt, facecolor='0.90', edgecolor='none', zorder=0)
        a.axvline(two_mt, color='0.35', lw=1.0, ls=(0, (6, 3)), zorder=1)

    den, dene, dcnt = d.density(REF)

    for key, _lab in CURVES:
        y, ye, cnt = d.density(key)
        lab = _lab if USETEX else CURVES_PLAIN[key]
        draw = np.where(cnt > 0, y, np.nan)
        ax.step(d.edges, np.concatenate([draw[:1], draw]), where='pre',
                color=COLOR[key], ls=LS[key], lw=LW, label=lab,
                zorder=5 if key == REF else 4)
        ax.errorbar(d.centres, draw, yerr=np.where(cnt > 0, ye, np.nan),
                    fmt='none', ecolor=COLOR[key], elinewidth=0.9,
                    capsize=0, zorder=4)

    ax.set_yscale('log')
    ax.set_ylabel(_tx(r'$\mathrm{d}\sigma/\mathrm{d}m_{t\bar t}$ [pb/GeV]',
                      r'$d\sigma/dm_{t\bar t}$ [pb/GeV]'))
    ax.set_xlim(lo, hi)
    ax.xaxis.set_minor_locator(AutoMinorLocator())
    ax.tick_params(labelbottom=False)
    ax.legend(frameon=False, loc='lower right', fontsize=10.5,
              handlelength=2.6, borderaxespad=0.8)

    # The annotation that is the point of the figure.
    ymin, ymax = ax.get_ylim()
    ax.set_ylim(ymin, ymax * 34)
    ax.text(0.028, 0.965,
            _tx(r'$pp \to t\bar t j$ at $\sqrt{s} = 13$~TeV, LO, '
                r'$\mu_R = \mu_F = m_t$',
                r'$pp \to t\bar t j$ at $\sqrt{s}=13$ TeV, LO, '
                r'$\mu_R=\mu_F=m_t$'),
            transform=ax.transAxes, ha='left', va='top', fontsize=11)
    ax.text(0.028, 0.905,
            _tx(r'$m_{t\bar t} \equiv m\big[(W^+b) + (W^-\bar b)\big]$, '
                r'BW cut $=%g\,\Gamma_t$ on both sides'
                % d.meta.get('bwcutoff', 15.0),
                r'$m_{t\bar t} = m[(W^+b)+(W^-\bar b)]$, BW cut = %g $\Gamma_t$'
                % d.meta.get('bwcutoff', 15.0)),
            transform=ax.transAxes, ha='left', va='top', fontsize=11)

    n_on = d.meta['runs']['onshell']['nevents']
    ax.annotate(
        _tx(r'\textbf{no on-shell $t\bar t$ pair can land here}'
            '\n'
            r'\texttt{onshell}: $0$ of $%s$ events, exactly.' % _fmt_int(n_on)
            + '\n'
            r'\texttt{madspin}/\texttt{PA} reach it because the production'
            '\n'
            r'reshuffle rescales the recoil jet.  \texttt{madspin\_v1}'
            '\n'
            r'reaches it 3x less often: it leaves $m_{t\bar t}$'
            '\n'
            r'unchanged in 54\% of events.',
            'no on-shell $t\\bar t$ pair can land here\n'
            'onshell: 0 of %s events, exactly.\n'
            'madspin/PA reach it because the production reshuffle\n'
            'rescales the recoil jet.  madspin_v1 reaches it 3x less\n'
            'often: it leaves $m_{t\\bar t}$ unchanged in 54%% of events.'
            % _fmt_int(n_on)),
        xy=(0.5 * (lo + two_mt), 1.0), xycoords=('data', 'axes fraction'),
        xytext=(0.028, 0.845), textcoords='axes fraction',
        ha='left', va='top', fontsize=9.5, color='0.25')
    ax.annotate(_tx(r'$2m_t$', r'$2m_t$'),
                xy=(two_mt, 0.03), xycoords=('data', 'axes fraction'),
                xytext=(3, 0), textcoords='offset points',
                ha='left', va='bottom', fontsize=11, color='0.35')

    # --- ratio pane -------------------------------------------------------
    rx.axhspan(0.9, 1.1, facecolor=allcolors[0], alpha=0.10, zorder=0)
    rx.axhspan(0.95, 1.05, facecolor=allcolors[0], alpha=0.16, zorder=0)
    rx.axhline(1.0, color='black', lw=0.9, zorder=2)
    rx.text(0.993, 0.93, _tx(r'bands: $\pm5\%$, $\pm10\%$',
                             r'bands: $\pm5\%$, $\pm10\%$'),
            transform=rx.transAxes, ha='right', va='top',
            fontsize=8.5, color=allcolors[0])

    # The pane is clipped to RATIO_CLIP, so it has to be set BEFORE anything is
    # drawn into it: the step lines below run far outside the window and would
    # otherwise drag the autoscale out with them.
    rx.set_ylim(*RATIO_CLIP)

    n_out = 0
    for slot, key in enumerate(MODES):
        y, ye, cnt = d.density(key)
        r, re = ratio(y, ye, den, dene)
        # Two kinds of empty bin, drawn differently on purpose.
        #   structural -- onshell below 2 m_t.  A real, exact zero: it is
        #                 0 and not "somewhere below the pane", so it keeps its
        #                 open circle and gets NO arrow.  With the pane clipped
        #                 to +-20% the circle sits on the lower boundary, which
        #                 is why the key below spells out what it means.
        #   statistical -- any other bin with no entries.  Drawn as a gap: the
        #                 sample simply did not reach there, which is a
        #                 statement about N and not about the scheme.
        struct = structurally_empty(d, key) & (dcnt > 0)
        stat = (cnt == 0) & (dcnt > 0) & ~struct
        rr = np.where(struct, 0.0, np.where(stat, np.nan, r))
        rx.step(d.edges, np.concatenate([rr[:1], rr]), where='pre',
                color=COLOR[key], ls=LS[key], lw=LW, zorder=4)
        rx.errorbar(d.centres, np.where(struct | stat, np.nan, r),
                    yerr=np.where(struct | stat, np.nan, re), fmt='none',
                    ecolor=COLOR[key], elinewidth=0.9, capsize=0, zorder=4)
        if struct.any():
            rx.plot(d.centres[struct],
                    np.full(struct.sum(), RATIO_CLIP[0]), 'o',
                    mfc='white', mec=COLOR[key], mew=1.2, ms=5,
                    clip_on=False, zorder=8)
        live = np.where(struct | stat, np.nan, r)
        nb, na = offscale_arrows(rx, d.centres, live, COLOR[key],
                                 dx=d.widths, slot=slot, nslot=len(MODES))
        n_out += nb + na

    # A count, printed rather than silent: it is the check that the clipping
    # did not swallow anything.  Every point it counts carries an arrow.
    print('ratio pane clipped to %s: %d point(s) outside it, each drawn as an '
          'arrow at the boundary it left through' % (RATIO_CLIP, n_out))

    # Say it on the axis, not only in the caption: a reader who crops the
    # figure out of the document must still be told the pane is clipped.
    rx.set_ylabel(_tx(r'ratio to truth' '\n' r'(clipped to $\pm20\%$)',
                      'ratio to truth\n(clipped to $\\pm20\\%$)'),
                  fontsize=10.5)
    # Bottom right: the only corner of this pane that no curve reaches (above
    # 356 GeV every mode sits on the +3 % normalisation plateau), so the key
    # cannot land on top of a point or an arrow.
    rx.text(0.993, 0.045,
            _tx(r'arrow: point outside the pane' '\n'
                r'$\circ$: exactly $0$ (structural)',
                'arrow: point outside the pane\n'
                '$\\circ$: exactly 0 (structural)'),
            transform=rx.transAxes, ha='right', va='bottom',
            fontsize=8.5, color='0.30', linespacing=1.25)
    rx.set_xlabel(_tx(
        r'$m_{t\bar t}$ [GeV] \ \ (per-event $m$ of $(W^+b)+(W^-\bar b)$)',
        r'$m_{t\bar t}$ [GeV]  (per-event $m$ of $(W^+b)+(W^-\bar b)$)'))
    rx.xaxis.set_minor_locator(AutoMinorLocator())
    rx.yaxis.set_minor_locator(AutoMinorLocator())
    rx.set_xlim(lo, hi)

    fig.subplots_adjust(left=0.135, right=0.975, top=0.985, bottom=0.105)
    base = os.path.join(out, 'mtt_threshold%s' % style_tag)
    fig.savefig(base + '.pdf')
    fig.savefig(base + '.png', dpi=300)
    plt.close(fig)
    return base


def _fmt_int(n):
    s = '%d' % int(n)
    groups = []
    while len(s) > 3:
        groups.insert(0, s[-3:])
        s = s[:-3]
    groups.insert(0, s)
    return (r'\,' if USETEX else ' ').join(groups)


def check_minus(pdf_path):
    """Re-open the PDF and confirm a math minus actually made it in.

    matplotlib's usetex PDF subsetting has silently eaten every minus sign in
    this project twice.  The figure carries them in the ratio ticks, so a PDF
    without one is wrong.  Returns (found, detail).
    """
    if not USETEX:
        return None, 'usetex is off, the Type1 subsetting path is not used'
    # Read the file, not a renderer.  The failure mode is precise: the Type1
    # subset of CMSY10 comes out with an /Encoding whose /Differences no longer
    # names ``/minus``, so the glyph is unreachable and viewers drop the sign.
    # A correct PDF for this figure -- which has a minus in every negative ratio
    # tick label and in the annotation -- must therefore carry ``/minus``.
    try:
        with open(pdf_path, 'rb') as fp:
            raw = fp.read()
    except OSError as exc:
        return None, 'cannot read the PDF (%s)' % exc
    if b'/minus' in raw:
        return True, '/minus is in the PDF font encoding'
    # pdftotext, when present, is a second opinion rather than the primary one.
    try:
        import subprocess
        txt = subprocess.run(['pdftotext', pdf_path, '-'],
                             capture_output=True).stdout.decode('utf8', 'replace')
        for ch in ('−', '-'):
            if ch in txt:
                return True, 'pdftotext extracted %r' % ch
    except Exception:
        pass
    return False, ('/minus absent from the PDF font encoding -- the usetex '
                   'Type1 subsetting bug has eaten the sign')


# --------------------------------------------------------------------------
def write_numbers(d, out, fh=sys.stdout):
    p = lambda *a: print(*a, file=fh)
    two_mt = d.two_mt
    p('=' * 78)
    p('m_tt near threshold: MadSpin spinmodes vs the doubly-resonant truth')
    p('=' * 78)
    p('code            : %s (%s)' % (d.meta['code_sha'][:12],
                                     d.meta.get('code_branch')))
    p('production      : %s' % d.meta['production_process'])
    p('truth           : %s' % d.meta['truth_process'])
    p('MadSpin decays  : %s' % ', '.join(d.meta['madspin_decays']))
    p('bwcutoff/BW_cut : %s / %s' % (d.meta['bwcutoff'],
                                     d.meta['madspin_BW_cut']))
    p('2 m_t           : %.4f GeV  (param card MT = %s)'
      % (two_mt, d.meta.get('param_card_masses', {}).get('MT')))
    p('')
    p('%-11s %12s %14s %14s' % ('sample', 'events', 'sigma [pb]',
                                'banner [pb]'))
    for key in ['truth'] + MODES + ['production']:
        if key not in d.meta['runs']:
            continue
        p('%-11s %12s %14.4f %14s'
          % (key, '%d' % d.meta['runs'][key]['nevents'], d.sigma(key),
             '%.4f' % d.banner_sigma(key) if d.banner_sigma(key) else '-'))
    p('')
    p('accept/reject scheme each run ACTUALLY used, from its own log:')
    for key in MODES + list(d.meta.get('controls', [])):
        if key not in d.meta['runs']:
            continue
        r = d.meta['runs'][key]
        p('   %-11s %-10s  (%s)' % (key, r.get('unweighting'),
                                    r.get('unweighting_why')))
    p('   NB: "legacy" is not one of the four `set unweighting` schemes.')
    p('   spinmode=madspin_v1 never reaches _unweighting_mode -- that')
    p('   dispatcher lives in run_onshell, which the legacy path does not')
    p('   call -- so the card\'s `unweighting` value is inert for it and the')
    p('   scheme it ran is the legacy one: one max_weight per decay channel,')
    p('   probed before the event loop, then one test of the whole decay')
    p('   chain\'s weight against it per trial, inside the Fortran driver.')

    bw = float(d.meta['bwcutoff'])
    trunc = 1.0 - 2 * math.atan(2 * bw) / math.pi
    p('')
    p('The truth and the MadSpin samples do NOT share a total cross section,')
    p('and the gap is expected.  MG5 truncates each top Breit-Wigner at')
    p('|m - m_t| < %g Gamma_t (myamp.f, same convention as MadSpin BW_cut),' % bw)
    p('which removes %.2f%% per resonance and %.2f%% for the pair; MadSpin'
      % (100 * trunc, 100 * (1 - (1 - trunc) ** 2)))
    p('normalises to sigma_production * BR and takes no such loss, and no')
    p('off-shell correction to the rate either.  Measured here:')
    for key in MODES:
        p('   truth / %-9s = %.4f   (BW truncation alone would give %.4f)'
          % (key, d.sigma(REF) / d.sigma(key), (1 - trunc) ** 2))
    p('')

    # --- the sub-threshold region ----------------------------------------
    st, ste, stk = d.integral(REF, d.fine[0], two_mt)
    # The FULL cross section of the sample, overflow included -- the histogram
    # range stops at 520 GeV and roughly half the events are above it, so
    # integrating the in-range bins would understate every denominator by 2x.
    tot = d.sigma(REF)
    p('-- below 2 m_t ------------------------------------------------------')
    p('truth       sigma(m_tt < 2m_t) = %.4f +- %.4f pb   (%d events, '
      '%.3f%% +- %.3f%% of the truth total %.3f pb)'
      % (st, ste, stk, 100 * st / tot, 100 * ste / tot, tot))
    for key in MODES:
        s, e, k = d.integral(key, d.fine[0], two_mt)
        stot = d.sigma(key)
        rel = (s / st) if st else float('nan')
        rele = rel * math.sqrt((e / s) ** 2 + (ste / st) ** 2) if s > 0 else 0.0
        # A zero here means two different things depending on the mode, and
        # the line must not paper over the difference: ``onshell`` cannot reach
        # this region at any sample size, anything else simply did not.
        if s > 0:
            verdict = '%.3f +- %.3f' % (rel, rele)
        elif key == 'onshell':
            verdict = '0 exactly (structurally empty)'
        else:
            verdict = '0 in this sample (NOT structural -- %s can reach ' \
                      'here; this is a statement about N)' % key
        p('%-11s sigma(m_tt < 2m_t) = %.4f +- %.4f pb   (%d events, '
          '%.3f%% of its own total)   ratio to truth = %s'
          % (key, s, e, k, 100 * s / stot, verdict))
    p('')

    # --- the brief's window ----------------------------------------------
    for width in (5.0, 10.0):
        lo_w, hi_w = d.fine[0], two_mt + width
        s0, e0, k0 = d.integral(REF, lo_w, hi_w)
        p('-- m_tt < 2 m_t + %g GeV  (= %.1f GeV) -------------------------'
          % (width, hi_w))
        p('truth       %.4f +- %.4f pb  (%d events, %.3f%% of the truth total)'
          % (s0, e0, k0, 100 * s0 / tot))
        for key in MODES:
            s, e, k = d.integral(key, lo_w, hi_w)
            diff = s - s0
            diffe = math.sqrt(e ** 2 + e0 ** 2)
            p('%-11s %.4f +- %.4f pb  (%d events)   %+.4f +- %.4f pb '
              'vs truth = %+.1f%% +- %.1f%%'
              % (key, s, e, k, diff, diffe, 100 * diff / s0,
                 100 * diffe / s0))
        p('')

    # --- where agreement returns -----------------------------------------
    p('-- where each spinmode enters agreement with the truth --------------')
    p('   scanned downwards from %g GeV over the plot binning; "strict" uses'
      % AGREE_HI)
    p('   the central ratio, "within errors" allows each bin its own 1 sigma.')
    scales = {}
    for key in MODES:
        sc, rel = anchor_scale(d, key)
        scales[key] = sc
        p('   %-9s normalisation offset over %g-%g GeV: truth/mode = %.4f '
          '+- %.4f' % (key, ANCHOR[0], ANCHOR[1], sc, sc * rel))
    p('')
    for what, use_scale in (('ABSOLUTE normalisation', False),
                            ('SHAPE only (each mode rescaled by its %g-%g GeV '
                             'offset above)' % ANCHOR, True)):
        p('   -- %s --' % what)
        for tol in (0.05, 0.10):
            p('   tolerance %d%%:' % int(100 * tol))
            for key in MODES:
                a = agreement_threshold(d, key, tol,
                                        scales[key] if use_scale else 1.0)
                def fmt(name):
                    if a.get(name) is None:
                        return 'never, up to %g GeV' % AGREE_HI
                    return ('m_tt >= %.0f GeV  (first bin ratio %.3f +- %.3f)'
                            % (a[name], a[name + '_ratio'], a[name + '_err']))
                p('      %-9s strict       : %s' % (key, fmt('strict')))
                p('      %-9s within errors: %s' % ('', fmt('compat')))
        p('')

    # --- the mechanism ----------------------------------------------------
    if d.meta.get('delta_mtt'):
        p('-- the mechanism: m_tt(decayed) - m_tt(production), event by event --')
        p('   MadSpin writes one decayed event per production event, in order.')
        p('   sqrt(shat) is RAMBO-invariant, so max |Delta sqrt(shat)| = 0 is')
        p('   what proves the two streams are actually paired.')
        p('   %-11s %9s %8s %9s %13s %9s %7s %10s'
          % ('mode', 'mean', 'rms', 'max|d|', 'max|dsqrt(s)|',
             'down-xing', 'up-xing', 'unchanged'))
        for key in MODES:
            m = d.meta['delta_mtt'].get(key)
            if not m:
                continue
            unch = ('%.2f%%' % (100.0 * m['n_tiny'] / m['n'])
                    if 'n_tiny' in m else '-')
            p('   %-11s %+9.4f %8.4f %9.3f %13.3g %9d %7d %10s'
              % (key, m['mean'], m['rms'], m['max_abs'], m['max_dshat'],
                 m['crossed_down'], m['crossed_up'], unch))
        p('   "unchanged" = |Delta m_tt| / m_tt < 1e-6, i.e. m_tt came back the')
        p('   same to the precision the LHE text carries.  Read that column and')
        p('   not a bit-exact one: onshell provably never touches the momenta')
        p('   and is still only %.2f%% bit-exact, because the LHE round-trips'
          % (100.0 * d.meta['delta_mtt']['onshell']['n_exact']
             / d.meta['delta_mtt']['onshell']['n']))
        p('   the momenta as decimal text.  That is the precision floor; the')
        p('   1e-6 column sits above it.')
        p('   This is the column that explains madspin_v1: its rms is the')
        p('   LARGEST of the four, yet it pushes the FEWEST events across the')
        p('   threshold, because it holds m_tt exactly fixed in half its')
        p('   events and moves the rest further than anything else does.')
        p('')

    # --- controls ---------------------------------------------------------
    for key in d.meta.get('controls', []):
        if key not in d.meta['runs']:
            continue
        base = key.split('_')[0]
        p('-- control: %s ------------------------------------------------'
          % key)
        p('   %s repeated with the accept/reject scheme forced, so the'
          % base)
        p('   %s-vs-PA difference can be attributed to the spinmode and not' % base)
        p('   to "auto" resolving to a different scheme for each of them.')
        p('   resolved unweighting: %-10s vs %-10s for %s'
          % (d.meta['runs'][key].get('unweighting'),
             d.meta['runs'][base].get('unweighting'), base))
        s0, e0, k0 = d.integral(base, d.fine[0], two_mt)
        s1, e1, k1 = d.integral(key, d.fine[0], two_mt)
        p('   sigma(m_tt < 2m_t): %-10s %.4f +- %.4f pb (%d events)'
          % (base, s0, e0, k0))
        p('                       %-10s %.4f +- %.4f pb (%d events)'
          % (key, s1, e1, k1))
        if s0 > 0:
            rr = s1 / s0
            rre = rr * math.sqrt((e1 / s1) ** 2 + (e0 / s0) ** 2)
            p('   control / default = %.4f +- %.4f  (%.1f sigma from 1)'
              % (rr, rre, abs(rr - 1) / rre if rre else float('nan')))
        p('   total sigma: %-10s %.4f pb   %-10s %.4f pb'
          % (base, d.sigma(base), key, d.sigma(key)))
        p('')

    # --- onshell IS the production sample --------------------------------
    if 'production' in d.meta['runs']:
        a = d.z['onshell_cnt']
        b = d.z['production_cnt']
        same = bool(np.array_equal(a, b))
        p('-- onshell vs the undecayed production sample -----------------------')
        p('   Same fine-grid histogram, bin for bin: %s '
          '(%d vs %d entries in range, max |difference| = %d)'
          % (same, int(a.sum()), int(b.sum()), int(np.abs(a - b).max())))
        p('   That is the claim "onshell has no lineshape and no reshuffle"')
        p('   measured rather than asserted, and it is what makes its zero')
        p('   below 2 m_t structural.')
        p('')

    # --- what the clipped ratio pane cannot show --------------------------
    # The figure clips its ratio pane to RATIO_CLIP and marks every excursion
    # with an arrow, but an arrow has no value on it.  The values live here, so
    # nothing that leaves the pane is lost.
    den_c, dene_c, dcnt_c = d.density(REF)
    p('-- ratio points outside the figure\'s clipped pane %s -------------'
      % (RATIO_CLIP,))
    any_out = False
    for key in MODES:
        y, ye, cnt = d.density(key)
        r, re = ratio(y, ye, den_c, dene_c)
        struct = structurally_empty(d, key) & (dcnt_c > 0)
        stat = (cnt == 0) & (dcnt_c > 0) & ~struct
        for i in range(len(r)):
            if struct[i] or stat[i] or not np.isfinite(r[i]):
                continue
            if RATIO_CLIP[0] <= r[i] <= RATIO_CLIP[1]:
                continue
            any_out = True
            p('   %-11s %4.0f-%-4.0f  ratio = %.3f +- %.3f   (drawn as an '
              'arrow at %.1f)'
              % (key, d.edges[i], d.edges[i + 1], r[i], re[i],
                 RATIO_CLIP[1] if r[i] > RATIO_CLIP[1] else RATIO_CLIP[0]))
    if not any_out:
        p('   none.')
    p('   onshell below 2 m_t is NOT in this list: it is an exact structural')
    p('   zero, drawn with its open marker on the lower boundary and no arrow.')
    p('')

    # --- per-bin table ----------------------------------------------------
    p('-- per-bin table (absolute, pb/GeV) ---------------------------------')
    den, dene, dcnt = d.density(REF)
    head = '%9s %12s %9s' % ('bin [GeV]', 'truth', '+-')
    for key in MODES:
        head += ' %12s %8s %8s' % (key, '+-', 'ratio')
    p(head)
    for i in range(len(d.centres)):
        row = '%4.0f-%4.0f %12.5g %9.2g' % (d.edges[i], d.edges[i + 1],
                                            den[i], dene[i])
        for key in MODES:
            y, ye, cnt = d.density(key)
            r, re = ratio(y, ye, den, dene)
            if cnt[i] == 0:
                row += ' %12.5g %8s %8s' % (0.0, '-', '0 exact')
            else:
                row += ' %12.5g %8.2g %8s' % (
                    y[i], ye[i],
                    '%.3f' % r[i] if np.isfinite(r[i]) else '-')
        p(row)
    p('')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--data', default=os.path.join(_HERE, 'data'))
    ap.add_argument('--out', default=os.path.join(_HERE, 'plots'))
    ap.add_argument('--check-minus', action='store_true', default=True)
    args = ap.parse_args()

    os.makedirs(args.out, exist_ok=True)
    d = Data(args.data)
    base = make_figure(d, args.out)
    print('wrote %s.pdf / .png   (usetex=%s, minus fix applied=%s)'
          % (base, USETEX, MINUS_FIX))
    if args.check_minus:
        ok, detail = check_minus(base + '.pdf')
        print('minus-sign check: %s -- %s' % (ok, detail))
    with open(os.path.join(args.out, 'numbers.txt'), 'w') as fh:
        write_numbers(d, args.out, fh)
    write_numbers(d, args.out)


if __name__ == '__main__':
    main()
