ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE COMPLEX COND
      DOUBLE COMPLEX CONDIF
      DOUBLE COMPLEX REGLOG
      DOUBLE COMPLEX REGLOGP
      DOUBLE COMPLEX REGLOGM
      DOUBLE COMPLEX REGSQRT
      DOUBLE COMPLEX GRREGLOG
      DOUBLE COMPLEX RECMS
      DOUBLE COMPLEX CRECMS
      DOUBLE COMPLEX ARG


      COMPLEX*32 MP_COND
      COMPLEX*32 MP_CONDIF
      COMPLEX*32 MP_REGLOG
      COMPLEX*32 MP_REGLOGP
      COMPLEX*32 MP_REGLOGM
      COMPLEX*32 MP_REGSQRT
      COMPLEX*32 MP_GRREGLOG
      COMPLEX*32 MP_RECMS
      COMPLEX*32 MP_CRECMS
      COMPLEX*32 MP_ARG


