ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4)

      DOUBLE PRECISION MDL_MTA,MDL_MT,MDL_MB,MDL_MW,MDL_MH,MDL_MZ

      COMMON/MASSES/ MDL_MTA,MDL_MT,MDL_MB,MDL_MW,MDL_MH,MDL_MZ


      DOUBLE PRECISION MDL_WZ,MDL_WT,MDL_WH,MDL_WW

      COMMON/WIDTHS/ MDL_WZ,MDL_WT,MDL_WH,MDL_WW


      DOUBLE COMPLEX GC_4, GC_5, R2_GQQ, R2_QQQ, UV_GQQG_1EPS,
     $  UV_GQQB_1EPS, UVWFCT_G_1_1EPS, R2_BXTW, UV_GQQB, UV_GQQT,
     $  UVWFCT_G_1, UVWFCT_G_2, GC_11

      COMMON/COUPLINGS/ GC_4, GC_5, R2_GQQ, R2_QQQ, UV_GQQG_1EPS,
     $  UV_GQQB_1EPS, UVWFCT_G_1_1EPS, R2_BXTW, UV_GQQB, UV_GQQT,
     $  UVWFCT_G_1, UVWFCT_G_2, GC_11

