ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G
      
      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL
      
      DOUBLE PRECISION DUM0
      COMMON/FRDUM0/ DUM0
      
      DOUBLE PRECISION DUM1
      COMMON/FRDUM1/ DUM1
      
      DOUBLE PRECISION MTA,MC,MT,MB,MZ,MH
      COMMON/MASSES/ MTA,MC,MT,MB,MZ,MH
      
      DOUBLE PRECISION WT,WZ,WW,WH
      COMMON/WIDTHS/ WT,WZ,WW,WH
      
      DOUBLE COMPLEX GC_1, GC_2, GC_3, GC_4, GC_5, GC_6, GC_7, GC_8
     $ , GC_9, GC_10, GC_11, GC_12, GC_13, GC_14, GC_15, GC_16, GC_17
     $ , GC_18, GC_19, GC_20, GC_21, GC_22, GC_23, GC_24, GC_25, GC_26
     $ , GC_27, GC_28, GC_29, GC_30, GC_31, GC_32, GC_33, GC_34, GC_35
     $ , GC_36
      COMMON/COUPLINGS/ GC_1, GC_2, GC_3, GC_4, GC_5, GC_6, GC_7, GC_8
     $ , GC_9, GC_10, GC_11, GC_12, GC_13, GC_14, GC_15, GC_16, GC_17
     $ , GC_18, GC_19, GC_20, GC_21, GC_22, GC_23, GC_24, GC_25, GC_26
     $ , GC_27, GC_28, GC_29, GC_30, GC_31, GC_32, GC_33, GC_34, GC_35
     $ , GC_36
