ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of sm'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_1 = ', GC_1
      WRITE(*,2) 'GC_2 = ', GC_2
      WRITE(*,2) 'GC_3 = ', GC_3
      WRITE(*,2) 'GC_4 = ', GC_4
      WRITE(*,2) 'GC_5 = ', GC_5
      WRITE(*,2) 'GC_6 = ', GC_6
      WRITE(*,2) 'GC_7 = ', GC_7
      WRITE(*,2) 'GC_8 = ', GC_8
      WRITE(*,2) 'GC_9 = ', GC_9
      WRITE(*,2) 'GC_10 = ', GC_10
      WRITE(*,2) 'GC_11 = ', GC_11
      WRITE(*,2) 'GC_12 = ', GC_12
      WRITE(*,2) 'GC_13 = ', GC_13
      WRITE(*,2) 'GC_14 = ', GC_14
      WRITE(*,2) 'GC_15 = ', GC_15
      WRITE(*,2) 'GC_16 = ', GC_16
      WRITE(*,2) 'GC_17 = ', GC_17
      WRITE(*,2) 'GC_18 = ', GC_18
      WRITE(*,2) 'GC_19 = ', GC_19
      WRITE(*,2) 'GC_20 = ', GC_20
      WRITE(*,2) 'GC_21 = ', GC_21
      WRITE(*,2) 'GC_22 = ', GC_22
      WRITE(*,2) 'GC_23 = ', GC_23
      WRITE(*,2) 'GC_24 = ', GC_24
      WRITE(*,2) 'GC_25 = ', GC_25
      WRITE(*,2) 'GC_26 = ', GC_26
      WRITE(*,2) 'GC_27 = ', GC_27
      WRITE(*,2) 'GC_28 = ', GC_28
      WRITE(*,2) 'GC_29 = ', GC_29
      WRITE(*,2) 'GC_30 = ', GC_30
      WRITE(*,2) 'GC_31 = ', GC_31
      WRITE(*,2) 'GC_32 = ', GC_32
      WRITE(*,2) 'GC_33 = ', GC_33
      WRITE(*,2) 'GC_34 = ', GC_34
      WRITE(*,2) 'GC_35 = ', GC_35
      WRITE(*,2) 'GC_36 = ', GC_36
