ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G__EXP__2,AEW,SQRT__AS,MZ__EXP__2,MZ__EXP__4
     $ ,SQRT__2,MW,SQRT__AEW,EE,MW__EXP__2,SW2,CW,SQRT__SW2,SW,G1,GW,V
     $ ,MH__EXP__2,V__EXP__2,LAM,YB,YC,YT,YTAU,MUH,GW__EXP__2
     $ ,CW__EXP__2,EE__EXP__2,SW__EXP__2,CABI,AEWM1,GF,AS,YMC,YMB,YMT
     $ ,YMTAU
      COMMON/PARAMS_R/ G__EXP__2,AEW,SQRT__AS,MZ__EXP__2,MZ__EXP__4
     $ ,SQRT__2,MW,SQRT__AEW,EE,MW__EXP__2,SW2,CW,SQRT__SW2,SW,G1,GW,V
     $ ,MH__EXP__2,V__EXP__2,LAM,YB,YC,YT,YTAU,MUH,GW__EXP__2
     $ ,CW__EXP__2,EE__EXP__2,SW__EXP__2,CABI,AEWM1,GF,AS,YMC,YMB,YMT
     $ ,YMTAU
      
      DOUBLE COMPLEX CKM11,CKM12,CKM21,CKM22,COMPLEXI,CONJG__CKM11
     $ ,CONJG__CKM12,CONJG__CKM21,CONJG__CKM22
      COMMON/PARAMS_C/ CKM11,CKM12,CKM21,CKM22,COMPLEXI,CONJG__CKM11
     $ ,CONJG__CKM12,CONJG__CKM21,CONJG__CKM22
      
