C     This File Automatically generated by MadGraph 5/FeynRules HELAS
C      writer 
C     The process calculated in this file is: 
C     number of lorentz index :0
      NUMBER OF SPIN INDEX :0
      OTHER INFO SET(['V2', 'V3'])
      (0,) --> ( 1J * ( V3_1 * V2_1 ) + -1J * ( V3_2 * V2_2 ) 
     $ + -1J * ( V3_3 * V2_3 ) + -1J * ( V3_4 * V2_4 ) )
      / NUMBER OF LORENTZ INDEX :0
      NUMBER OF SPIN INDEX :0
      OTHER INFO SET(['P1', 'M1', 'W1'])
      (0,) --> ( ( M1 * ( -1 * M1 + 1J * W1 ) ) + ( ( P1_0**2 ) 
     $ + -1 * ( P1_1**2 ) + -1 * ( P1_2**2 ) + -1 * ( P1_3**2 ) ) )
      
      SUBROUTINE /USERS/OMATT/DOCUMENTS/ECLIPSE2/EXPORT_MODEL/MODELS
     $ /SM2/FORTRAN/L_10_011(C,V2,V3,M1,W1,V3)
      IMPLICIT NONE
      DOUBLE PRECISION C
      DOUBLE COMPLEX S1(3)
      DOUBLE COMPLEX V2(6)
      DOUBLE COMPLEX V3(6)
      DOUBLE COMPLEX DENOM
      DOUBLE PRECISION M1,W1
      DOUBLE PRECISION P1(0:3)
      V3(5)=-(-S1(2)-V2(5))
      V3(6)=-(-S1(3)-V2(6))
      P1(0) =  DBLE(S1(2))
      P1(1) =  DBLE(S1(3))
      P1(2) =  DIMAG(S1(3))
      P1(3) =  DIMAG(S1(2))
      DENOM =1D0/(((M1*(-M1+(0.000000000D0, 1.000000000D0)*W1))
     $ +((P1(0)**2)-(P1(1)**2)-(P1(2)**2)-(P1(3)**2))))
      S1(1)= C*DENOM*((0.000000000D0, 1.000000000D0)*(V3(1)*V2(1))
     $ +(-0.000000000D0, -1.000000000D0)*(V3(2)*V2(2))+(-0.000000000D0
     $ , -1.000000000D0)*(V3(3)*V2(3))+(-0.000000000D0, -1.000000000D0
     $ )*(V3(4)*V2(4)))
      END
