C     This File Automatically generated by MadGraph 5/FeynRules HELAS
C      writer 
C     The process calculated in this file is: 
C     number of lorentz index :0
      NUMBER OF SPIN INDEX :0
      OTHER INFO SET(['P2', 'V1', 'P1', 'S3'])
      (0,) --> ( S3_1 * ( ( V1_1 * ( 1J * P1_0 + 1J * P2_0 ) ) 
     $ + ( ( V1_2 * ( -1J * P1_1 + -1J * P2_1 ) ) + ( ( V1_3 * ( 
     $ -1J * P1_2 + -1J * P2_2 ) ) + ( V1_4 * ( -1J * P1_3 + 
     $ -1J * P2_3 ) ) ) ) ) )
      / NUMBER OF LORENTZ INDEX :0
      NUMBER OF SPIN INDEX :0
      OTHER INFO SET(['P2', 'W2', 'M2'])
      (0,) --> ( ( M2 * ( -1 * M2 + 1J * W2 ) ) + ( ( P2_0**2 ) 
     $ + -1 * ( P2_1**2 ) + -1 * ( P2_2**2 ) + -1 * ( P2_3**2 ) ) )
      
      SUBROUTINE /USERS/OMATT/DOCUMENTS/ECLIPSE2/EXPORT_MODEL/MODELS
     $ /SM2/FORTRAN/L_11_101(C,V1,S2,M2,W2,S3)
      IMPLICIT NONE
      DOUBLE PRECISION C
      DOUBLE COMPLEX V1(6)
      DOUBLE COMPLEX S2(3)
      DOUBLE COMPLEX S3(3)
      DOUBLE COMPLEX DENOM
      DOUBLE PRECISION M2,W2
      DOUBLE PRECISION P2(0:3),P1(0:3)
      S3(2)=-(-V1(5)-S2(2))
      S3(3)=-(-V1(6)-S2(3))
      P2(0) =  DBLE(S2(2))
      P2(1) =  DBLE(S2(3))
      P2(2) =  DIMAG(S2(3))
      P2(3) =  DIMAG(S2(2))
      P1(0) =  DBLE(V1(5))
      P1(1) =  DBLE(V1(6))
      P1(2) =  DIMAG(V1(6))
      P1(3) =  DIMAG(V1(5))
      DENOM =1D0/(((M2*(-M2+(0.000000000D0, 1.000000000D0)*W2))
     $ +((P2(0)**2)-(P2(1)**2)-(P2(2)**2)-(P2(3)**2))))
      S2(1)= C*DENOM*(S3(1)*((V1(1)*((0.000000000D0, 1.000000000D0)
     $ *P1(0)+(0.000000000D0, 1.000000000D0)*P2(0)))+((V1(2)*((0.000000
     $ 000D0, -1.000000000D0)*P1(1)+(0.000000000D0, -1.000000000D0)
     $ *P2(1)))+((V1(3)*((0.000000000D0, -1.000000000D0)*P1(2)
     $ +(0.000000000D0, -1.000000000D0)*P2(2)))+(V1(4)*((0.000000000D0
     $ , -1.000000000D0)*P1(3)+(0.000000000D0, -1.000000000D0)
     $ *P2(3)))))))
      END
