C     This File Automatically generated by MadGraph 5/FeynRules HELAS
C      writer 
C     The process calculated in this file is: 
C     number of lorentz index :0
      NUMBER OF SPIN INDEX :0
      OTHER INFO SET(['V1', 'F2', 'F3'])
      (0,) --> ( ( F2_3 * ( ( F3_2 * ( -1J * V1_2 + (-1+0J) * V1_3 ) 
     $ ) + ( F3_1 * ( -1J * V1_1 + -1J * V1_4 ) ) ) ) + ( ( F2_4 
     $ * ( ( F3_1 * ( -1J * V1_2 + V1_3 ) ) + ( F3_2 * ( -1J * V1_1 
     $ + 1J * V1_4 ) ) ) ) + ( ( F2_1 * ( ( F3_4 * ( -2J * V1_2 + (-2
     $ +0J) * V1_3 ) ) + ( F3_3 * ( 2J * V1_1 + -2J * V1_4 ) ) ) ) 
     $ + ( F2_2 * ( ( F3_3 * ( -2J * V1_2 + (2+0J) * V1_3 ) ) 
     $ + ( F3_4 * ( 2J * V1_1 + 2J * V1_4 ) ) ) ) ) ) )
      
      SUBROUTINE /USERS/OMATT/DOCUMENTS/ECLIPSE2/EXPORT_MODEL/MODELS
     $ /SM2/FORTRAN/L_16_111(C,F2,F3,F3)
      IMPLICIT NONE
      DOUBLE PRECISION C
      DOUBLE COMPLEX V1(6)
      DOUBLE COMPLEX F2(6)
      DOUBLE COMPLEX F3(6)
      DOUBLE COMPLEX DENOM
      F3(5)=-(-V1(5)-F2(5))
      F3(6)=-(-V1(6)-F2(6))
      VERTEX = C*((F2(3)*((F3(2)*((0.000000000D0, -1.000000000D0)
     $ *V1(2)-V1(3)))+(F3(1)*((0.000000000D0, -1.000000000D0)*V1(1)
     $ +(0.000000000D0, -1.000000000D0)*V1(4)))))+((F2(4)*((F3(1)
     $ *((0.000000000D0, -1.000000000D0)*V1(2)+V1(3)))+(F3(2)
     $ *((0.000000000D0, -1.000000000D0)*V1(1)+(0.000000000D0
     $ , 1.000000000D0)*V1(4)))))+((F2(1)*((F3(4)*((0.000000000D0, 
     $ -2.000000000D0)*V1(2)+(-2.000000000D0, 0.000000000D0)*V1(3)))
     $ +(F3(3)*((0.000000000D0, 2.000000000D0)*V1(1)+(0.000000000D0, 
     $ -2.000000000D0)*V1(4)))))+(F2(2)*((F3(3)*((0.000000000D0, 
     $ -2.000000000D0)*V1(2)+(2.000000000D0, 0.000000000D0)*V1(3)))
     $ +(F3(4)*((0.000000000D0, 2.000000000D0)*V1(1)+(0.000000000D0
     $ , 2.000000000D0)*V1(4))))))))
      END
