C     This File Automatically generated by MadGraph 5/FeynRules HELAS
C      writer 
C     The process calculated in this file is: 
C     number of lorentz index :0
      NUMBER OF SPIN INDEX :1
      OTHER INFO SET(['P3', 'F2', 'S1', 'M3'])
      (0,) --> ( S1_1 * ( ( F2_4 * ( -1J * P3_1 + (-1+0J) * P3_2 ) ) 
     $ + ( ( F2_3 * ( 1J * P3_0 + -1J * P3_3 ) ) + ( 1J * ( F2_1 
     $ * M3 ) ) ) ) )
      (1,) --> ( S1_1 * ( ( F2_3 * ( -1J * P3_1 + P3_2 ) ) + ( ( F2_4 
     $ * ( 1J * P3_0 + 1J * P3_3 ) ) + ( 1J * ( F2_2 * M3 ) ) ) ) )
      (2,) --> ( S1_1 * ( ( F2_2 * ( 1J * P3_1 + P3_2 ) ) + ( ( F2_1 
     $ * ( 1J * P3_0 + 1J * P3_3 ) ) + ( 1J * ( F2_3 * M3 ) ) ) ) )
      (3,) --> ( S1_1 * ( ( F2_1 * ( 1J * P3_1 + (-1+0J) * P3_2 ) ) 
     $ + ( ( F2_2 * ( 1J * P3_0 + -1J * P3_3 ) ) + ( 1J * ( F2_4 
     $ * M3 ) ) ) ) )
      / NUMBER OF LORENTZ INDEX :0
      NUMBER OF SPIN INDEX :0
      OTHER INFO SET(['P3', 'W3', 'M3'])
      (0,) --> ( ( M3 * ( -1 * M3 + 1J * W3 ) ) + ( ( P3_0**2 ) 
     $ + -1 * ( P3_1**2 ) + -1 * ( P3_2**2 ) + -1 * ( P3_3**2 ) ) )
      
      SUBROUTINE /USERS/OMATT/DOCUMENTS/ECLIPSE2/EXPORT_MODEL/MODELS
     $ /SM2/FORTRAN/L_7_110(C,F2,S1,M3,W3,F2)
      IMPLICIT NONE
      DOUBLE PRECISION C
      DOUBLE COMPLEX S1(3)
      DOUBLE COMPLEX F2(6)
      DOUBLE COMPLEX F3(6)
      DOUBLE COMPLEX DENOM
      DOUBLE PRECISION M3,W3
      DOUBLE PRECISION P3(0:3)
      F2(5)=(-S1(2)+F3(5))
      F2(6)=(-S1(3)+F3(6))
      P3(0) =  DBLE(F3(5))
      P3(1) =  DBLE(F3(6))
      P3(2) =  DIMAG(F3(6))
      P3(3) =  DIMAG(F3(5))
      DENOM =1D0/(((M3*(-M3+(0.000000000D0, 1.000000000D0)*W3))
     $ +((P3(0)**2)-(P3(1)**2)-(P3(2)**2)-(P3(3)**2))))
      F3(1)= C*DENOM*(S1(1)*((F2(4)*((0.000000000D0, -1.000000000D0)
     $ *P3(1)+-P3(2)))+((F2(3)*((0.000000000D0, 1.000000000D0)*P3(0)
     $ +(0.000000000D0, -1.000000000D0)*P3(3)))+((0.000000000D0
     $ , 1.000000000D0)*(F2(1)*M3)))))
      F3(2)= C*DENOM*(S1(1)*((F2(3)*((0.000000000D0, -1.000000000D0)
     $ *P3(1)+P3(2)))+((F2(4)*((0.000000000D0, 1.000000000D0)*P3(0)
     $ +(0.000000000D0, 1.000000000D0)*P3(3)))+((0.000000000D0
     $ , 1.000000000D0)*(F2(2)*M3)))))
      F3(3)= C*DENOM*(S1(1)*((F2(2)*((0.000000000D0, 1.000000000D0)
     $ *P3(1)+P3(2)))+((F2(1)*((0.000000000D0, 1.000000000D0)*P3(0)
     $ +(0.000000000D0, 1.000000000D0)*P3(3)))+((0.000000000D0
     $ , 1.000000000D0)*(F2(3)*M3)))))
      F3(4)= C*DENOM*(S1(1)*((F2(1)*((0.000000000D0, 1.000000000D0)
     $ *P3(1)+-P3(2)))+((F2(2)*((0.000000000D0, 1.000000000D0)*P3(0)
     $ +(0.000000000D0, -1.000000000D0)*P3(3)))+((0.000000000D0
     $ , 1.000000000D0)*(F2(4)*M3)))))
      END
