ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' External Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'cabi = ', CABI
      WRITE(*,*) 'aEWM1 = ', AEWM1
      WRITE(*,*) 'Gf = ', GF
      WRITE(*,*) 'aS = ', AS
      WRITE(*,*) 'ymc = ', YMC
      WRITE(*,*) 'ymb = ', YMB
      WRITE(*,*) 'ymt = ', YMT
      WRITE(*,*) 'ymtau = ', YMTAU
      WRITE(*,*) 'MTA = ', MTA
      WRITE(*,*) 'MC = ', MC
      WRITE(*,*) 'MT = ', MT
      WRITE(*,*) 'MB = ', MB
      WRITE(*,*) 'MZ = ', MZ
      WRITE(*,*) 'MH = ', MH
      WRITE(*,*) 'WT = ', WT
      WRITE(*,*) 'WZ = ', WZ
      WRITE(*,*) 'WW = ', WW
      WRITE(*,*) 'WH = ', WH
      WRITE(*,*)  ' Internal Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'aEW = ', AEW
      WRITE(*,*) 'G = ', G
      WRITE(*,*) 'CKM11 = ', CKM11
      WRITE(*,*) 'CKM12 = ', CKM12
      WRITE(*,*) 'CKM21 = ', CKM21
      WRITE(*,*) 'CKM22 = ', CKM22
      WRITE(*,*) 'MW = ', MW
      WRITE(*,*) 'ee = ', EE
      WRITE(*,*) 'sw2 = ', SW2
      WRITE(*,*) 'cw = ', CW
      WRITE(*,*) 'sw = ', SW
      WRITE(*,*) 'g1 = ', G1
      WRITE(*,*) 'gw = ', GW
      WRITE(*,*) 'v = ', V
      WRITE(*,*) 'lam = ', LAM
      WRITE(*,*) 'yb = ', YB
      WRITE(*,*) 'yc = ', YC
      WRITE(*,*) 'yt = ', YT
      WRITE(*,*) 'ytau = ', YTAU
      WRITE(*,*) 'muH = ', MUH
      WRITE(*,*) 'COMPLEXI = ', COMPLEXI
      WRITE(*,*) 'gw__EXP__2 = ', GW__EXP__2
      WRITE(*,*) 'cw__EXP__2 = ', CW__EXP__2
      WRITE(*,*) 'ee__EXP__2 = ', EE__EXP__2
      WRITE(*,*) 'sw__EXP__2 = ', SW__EXP__2
      WRITE(*,*) 'SQRT__2 = ', SQRT__2
      WRITE(*,*) 'CONJG__CKM11 = ', CONJG__CKM11
      WRITE(*,*) 'CONJG__CKM12 = ', CONJG__CKM12
      WRITE(*,*) 'CONJG__CKM21 = ', CONJG__CKM21
      WRITE(*,*) 'CONJG__CKM22 = ', CONJG__CKM22
      WRITE(*,*)  ' Internal Params evaluated point by point'
      WRITE(*,*)  ' ----------------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'G__EXP__2 = ', G__EXP__2
