WORK=/home/prestel/work/2020/MG5/PY8meetsMG5aMC_release/Pythia/
PYTHIA8INCLUDE=$(WORK)/Pythia/pythia8245MultiscalesFix/include
PYTHIA8LIB=$(WORK)/Pythia/pythia8245MultiscalesFix/lib
PYTHIA8FLAGS=-lstdc++ -lz -ldl -fPIC
