#!/usr/bin/env python3
"""The event-level observables of the ``g g > z z`` loop-induced comparison.

One module, imported by the harvester and by both plotting scripts, so the
definition a number was made with is the definition it is plotted with.  Nothing
here needs MadGraph: it reads Les Houches files and returns numpy arrays.

Every observable is built from the four status-1 charged leptons of an event --
``e+ e- mu+ mu-``, one of each -- and from nothing else.  That is what makes the
two sides comparable: sample B (``g g > e+ e- mu+ mu- / a``, loop-induced) has
no ``z`` in its final state at all, and sample A only has one before MadSpin
decays it, so any observable that mentions a ``z`` would be measurable on one
side and not the other.  The pair masses are *reconstructed*, exactly as an
experiment would have to.

The angular conventions follow the H -> ZZ -> 4l literature
(Gao et al., arXiv:0708.0458), specialised to a ``ZZ`` system that is not a
resonance:

``cos_theta1`` / ``cos_theta2``
    the ``l+`` direction in its own pair's rest frame, measured against that
    pair's direction of flight in the four-lepton rest frame.  The two boosts
    are SEQUENTIAL -- lab -> four-lepton frame -> pair rest frame -- and that is
    not a detail: taking the axis in one frame while boosting the lepton in from
    another composes two non-collinear boosts, and the Wigner rotation of that
    composition makes the angle depend on the observer.  This module got it
    wrong until 2026-08-27; ``_selftest_helicity_frame`` is the guard and
    POLWEIGHT_CLOSURE_DIAGNOSIS.md is the story.  Flat for an
    unpolarised parent; the ``1 + cos^2`` / ``cos`` structure of a real ``Z``
    decay is what a spin-correlated MadSpin mode has to reproduce.  These
    respond to the polarisation of ONE ``Z``.

``cos1cos2``
    their product, and the observable that isolates the correlation *between*
    the two decays.  Each factor is separately odd under ``l+ <-> l-`` for an
    unpolarised parent, so ``<cos theta1 . cos theta2>`` is exactly zero for any
    scheme that decays the two ``z`` independently -- however well that scheme
    gets each ``z``'s own polarisation.  It is therefore the strict test of what
    MadSpin's density matrix carries and nothing else.

``phi_planes``
    the angle between the two decay planes in the four-lepton rest frame,
    signed by the ``(e+ e-)`` flight direction so that it runs over the full
    ``[-pi, pi]``.  Also zero-information for factorised decays -- it is
    generated by the interference between the ``ZZ`` helicity amplitudes -- and
    it is the observable the ``H -> ZZ -> 4l`` literature leads with, which is
    why it is here.

    It turns out **not** to discriminate for this process.  ``gg -> ZZ`` is a
    continuum, not a spin-0 resonance, and once the modulation is integrated
    over the production angle and over ``m_4l`` it averages away: all four
    MadSpin modes and the off-shell truth agree on a flat ``Phi`` to within the
    statistics of 50 000 events.  That is a measurement, not a defect of the
    definition -- ``cos1cos2``, computed from the same boosts, does separate the
    modes -- and it is reported as such in RESULTS.md.

``m_epmum``
    the ``(e+ mu-)`` invariant mass: a cross-pair combination, so it is built
    from one lepton out of each decay and cannot be reproduced by any
    single-``Z`` observable.

``dphi_epmum`` / ``dphi_ee`` / ``dphi_mumu``
    lab-frame azimuthal separations, all three folded to ``[0, pi]`` by the same
    ``abs((dphi + pi) % (2 pi) - pi)`` so that they are directly comparable.
    ``dphi_epmum`` is CROSS-pair -- one lepton from each ``Z`` -- and is the
    cheapest handle on the correlation between the two decays.  The other two
    are INTRA-pair, both leptons out of the same ``Z``, and they are a different
    kind of observable: not a correlation at all, but a proxy for that ``Z``'s
    own transverse momentum.  A ``Z`` at rest in the transverse plane gives
    back-to-back leptons at ``Delta phi = pi``; a boosted ``Z`` collimates them
    towards ``Delta phi = 0``.  So ``dphi_ee`` is a monotone (and rather tight)
    re-reading of ``pt_ee``, which is why it inherits ``pt_ee``'s support
    problem: the ``m_4l < 2 m_Z`` region that no spinmode can reach lives at low
    ``pt`` and therefore at LARGE ``Delta phi``.  See PA_LOWPT_DIAGNOSIS.md;
    the number to quote on these is the agreement on both supports, not one of
    them.  ``dphi_ee`` and ``dphi_mumu`` measure the same thing on the two ``Z``,
    which are equivalent apart from which pair the positional decay rule writes
    first, so they are each other's control.
"""

import gzip
import math

import numpy as np


# --------------------------------------------------------------------------
# Les Houches reading
# --------------------------------------------------------------------------
def _open(path):
    if path.endswith('.gz'):
        return gzip.open(path, 'rt', errors='replace')
    return open(path, 'rt', errors='replace')


def read_lhe(path, want=(-11, 11, -13, 13)):
    """Return ``(weights, {pdg: (N, 4) array of (E, px, py, pz)})``.

    Only status-1 particles are looked at, and exactly one of each pdg in
    ``want`` is required per event -- an event with two ``e+`` would mean the
    positional decay rule did not do what this study assumes, and is a hard
    error rather than something to average over.
    """
    weights = []
    cols = {p: [] for p in want}
    nbad = 0
    with _open(path) as fh:
        inev = False
        wgt = None
        found = {}
        for line in fh:
            s = line.strip()
            if s.startswith('<event'):
                inev, wgt, found = True, None, {}
                continue
            if not inev:
                continue
            if s.startswith('</event>'):
                inev = False
                if set(found) != set(want):
                    nbad += 1
                    continue
                weights.append(wgt)
                for p in want:
                    cols[p].append(found[p])
                continue
            if not s or s.startswith('<') or s.startswith('#'):
                continue
            f = s.split()
            if wgt is None:
                if len(f) >= 6:
                    try:
                        wgt = float(f[2])
                    except ValueError:
                        wgt = None
                continue
            if len(f) < 13:
                continue
            try:
                pdg, status = int(f[0]), int(f[1])
            except ValueError:
                continue
            if status != 1 or pdg not in want:
                continue
            if pdg in found:
                raise ValueError(
                    'two status-1 particles with pdg %d in one event of %s: the '
                    'positional decay rule did not give one e+e- and one mu+mu- '
                    'pair, so this sample is not comparable' % (pdg, path))
            found[pdg] = (float(f[9]), float(f[6]), float(f[7]), float(f[8]))
    if nbad:
        raise ValueError('%d events of %s did not carry exactly one each of '
                         'e+ e- mu+ mu-' % (nbad, path))
    return (np.array(weights, dtype=float),
            {p: np.array(cols[p], dtype=float) for p in want})


# --------------------------------------------------------------------------
# four-vector helpers.  Arrays are (N, 4) with the LHE ordering (E, px, py, pz).
# --------------------------------------------------------------------------
def mass(v):
    m2 = v[:, 0] ** 2 - v[:, 1] ** 2 - v[:, 2] ** 2 - v[:, 3] ** 2
    return np.sqrt(np.clip(m2, 0.0, None))


def pt(v):
    return np.hypot(v[:, 1], v[:, 2])


def boost_to_rest(v, ref):
    """Boost ``v`` into the rest frame of ``ref`` (both (N, 4)).

    ``beta = -p_ref / E_ref`` and ``gamma = E_ref / m_ref``, then

        E'      = gamma (E + beta.p)
        p'_i    = p_i + (gamma - 1)/beta^2 (beta.p) beta_i + gamma beta_i E

    Written out because getting it subtly wrong is easy and silent: an earlier
    version of this function used ``p_ref/m_ref`` where ``beta`` belongs, which
    leaves the *energy* exactly right -- so ``mass()`` of the boosted vector
    still looks plausible -- while multiplying the last term by an extra
    ``gamma``.  Every angular observable in this study is built out of this
    function, so :func:`_selftest_boost` checks it against the three properties
    that pin it down, and is run on import.
    """
    m = mass(ref)
    m = np.where(m > 0, m, 1.0)
    g = ref[:, 0] / m
    e = np.where(ref[:, 0] > 0, ref[:, 0], 1.0)
    bx, by, bz = (-ref[:, 1] / e, -ref[:, 2] / e, -ref[:, 3] / e)
    b2 = bx ** 2 + by ** 2 + bz ** 2
    bp = bx * v[:, 1] + by * v[:, 2] + bz * v[:, 3]
    fac = np.where(b2 > 0, (g - 1.0) / np.where(b2 > 0, b2, 1.0), 0.0)
    out = np.empty_like(v)
    out[:, 0] = g * (v[:, 0] + bp)
    out[:, 1] = v[:, 1] + fac * bp * bx + g * bx * v[:, 0]
    out[:, 2] = v[:, 2] + fac * bp * by + g * by * v[:, 0]
    out[:, 3] = v[:, 3] + fac * bp * bz + g * bz * v[:, 0]
    return out


def _selftest_boost():
    """Three properties that pin :func:`boost_to_rest` down, checked on import.

    1. boosting a vector into its own rest frame leaves ``(m, 0, 0, 0)``;
    2. a boost preserves invariant mass;
    3. the two halves of a two-body system come out back to back in the
       parent's rest frame.

    Property 1 alone is not enough -- it is satisfied by more than one wrong
    formula -- which is why all three are here.
    """
    rng = np.random.default_rng(20260822)
    m = rng.uniform(1.0, 200.0, size=64)
    p3 = rng.normal(0.0, 150.0, size=(64, 3))
    v = np.column_stack([np.sqrt(m ** 2 + (p3 ** 2).sum(1)), p3])
    r = boost_to_rest(v, v)
    assert np.abs(r[:, 1:]).max() < 1e-6, 'boost: self rest frame not at rest'
    assert np.abs(r[:, 0] - m).max() < 1e-8, 'boost: self rest frame energy'

    q3 = rng.normal(0.0, 150.0, size=(64, 3))
    ref = np.column_stack([np.sqrt(300.0 ** 2 + (q3 ** 2).sum(1)), q3])
    b = boost_to_rest(v, ref)
    assert np.abs(mass(b) - mass(v)).max() < 1e-6, 'boost: mass not preserved'

    a, c = v[:32], v[32:]
    par = a + c
    ar, cr = boost_to_rest(a, par), boost_to_rest(c, par)
    assert np.abs(ar[:, 1:] + cr[:, 1:]).max() < 1e-6, \
        'boost: two-body not back to back in the parent rest frame'


_selftest_boost()


def _unit(a):
    n = np.linalg.norm(a, axis=1, keepdims=True)
    return a / np.where(n > 0, n, 1.0)


def phi_of(v):
    return np.arctan2(v[:, 2], v[:, 1])


def _dphi(a, b):
    """Lab azimuthal separation of two momenta, folded to ``[0, pi]``.

    One function so that every ``Delta phi`` in this study is folded the same
    way and the three of them are directly comparable.  The fold is
    ``abs((dphi + pi) % (2 pi) - pi)``, which is the convention ``dphi_epmum``
    has always used; :func:`_selftest_dphi` pins it to the unsigned angle
    between the two transverse projections, ``arccos(cos(phi_a - phi_b))``.
    """
    d = phi_of(a) - phi_of(b)
    return np.abs((d + np.pi) % (2 * np.pi) - np.pi)


def _selftest_dphi():
    """The fold has to be the unsigned transverse angle, and nothing else.

    Two properties, both checked on import:

    1. it agrees with ``arccos(cos(phi_a - phi_b))`` -- i.e. it really is the
       angle in ``[0, pi]``, and the ``%`` does not leave a branch anywhere
       (getting the fold wrong shows up as a step at ``+-pi``, which on a
       distribution that PEAKS at ``pi`` -- and both intra-pair ones do -- would
       land exactly on the interesting bin);
    2. it is invariant under a common rotation about the beam, which is what
       makes it a lab observable one can compare between two samples that were
       generated with different random azimuths.
    """
    rng = np.random.default_rng(20260828)
    n = 512
    pt1 = rng.uniform(0.5, 200.0, size=n)
    pt2 = rng.uniform(0.5, 200.0, size=n)
    f1 = rng.uniform(-np.pi, np.pi, size=n)
    f2 = rng.uniform(-np.pi, np.pi, size=n)

    def _vec(p, f):
        pz = rng.normal(0.0, 300.0, size=n)
        return np.column_stack([np.hypot(p, pz), p * np.cos(f), p * np.sin(f), pz])

    a, b = _vec(pt1, f1), _vec(pt2, f2)
    got = _dphi(a, b)
    assert got.min() >= 0.0 and got.max() <= np.pi + 1e-12, \
        'dphi: not folded into [0, pi]'
    want = np.arccos(np.clip(np.cos(f1 - f2), -1.0, 1.0))
    assert np.abs(got - want).max() < 1e-9, \
        'dphi: the fold is not arccos(cos(dphi)) -- there is a branch left'

    rot = rng.uniform(-np.pi, np.pi, size=n)
    c, s = np.cos(rot), np.sin(rot)
    def _spin(v):
        out = v.copy()
        out[:, 1] = c * v[:, 1] - s * v[:, 2]
        out[:, 2] = s * v[:, 1] + c * v[:, 2]
        return out
    assert np.abs(_dphi(_spin(a), _spin(b)) - got).max() < 1e-9, \
        'dphi: not invariant under a rotation about the beam'


_selftest_dphi()


# --------------------------------------------------------------------------
# The observables
# --------------------------------------------------------------------------
def compute(p):
    """``p`` is the dict returned by :func:`read_lhe`; returns a dict of arrays."""
    ep, em, mup, mum = p[-11], p[11], p[-13], p[13]
    zee = ep + em
    zmm = mup + mum
    four = zee + zmm

    out = {
        'm_ee': mass(zee),
        'm_mumu': mass(zmm),
        'm_4l': mass(four),
        'pt_ee': pt(zee),
        'pt_mumu': pt(zmm),
        'm_epmum': mass(ep + mum),
        'm_epmup': mass(ep + mup),
    }

    # --- delta phi in the lab, all three folded to [0, pi] the same way ------
    # (e+, mu-) is CROSS-pair: the cheapest correlation handle.  (e+, e-) and
    # (mu+, mu-) are INTRA-pair -- both leptons out of one z -- so they are not
    # inter-decay correlations at all; they are a proxy for that z's own pt,
    # anti-correlated with it because a boosted z collimates its decay products
    # and a z at rest gives them back to back.  See the module docstring.
    out['dphi_epmum'] = _dphi(ep, mum)
    out['dphi_ee'] = _dphi(ep, em)
    out['dphi_mumu'] = _dphi(mup, mum)

    # --- cos theta1 / cos theta2: the l+ in its own pair's rest frame, against
    #     that pair's flight direction in the four-lepton rest frame ---
    # The two boosts are SEQUENTIAL -- lab -> four-lepton frame -> pair rest
    # frame -- and they have to be.  Taking the axis in the four-lepton frame
    # while boosting the lepton into the pair's rest frame straight from the lab
    # composes two boosts that are not collinear, and the Wigner rotation of
    # that composition tilts the analysing frame away from the axis by an angle
    # that is zero only when the four-lepton system is at rest in the lab or the
    # pair flies along the boost.  It is not a small effect here: the median
    # tilt on a 13 TeV ``p p > z z`` sample is 8 degrees and the tail reaches 80,
    # and it damps every rank-2 moment towards the isotropic value -- it moved
    # ``f_0`` from 0.170 to 0.210 on the sample of ``polweight_closure.py``.
    # ``_selftest_helicity_frame`` below is the guard: the angle defined this
    # way is a Lorentz invariant of the four momenta, and the mixed composition
    # is not.  See POLWEIGHT_CLOSURE_DIAGNOSIS.md.
    zee_in4 = boost_to_rest(zee, four)
    zmm_in4 = boost_to_rest(zmm, four)
    d1 = _unit(zee_in4[:, 1:4])
    d2 = _unit(zmm_in4[:, 1:4])
    e1 = _unit(boost_to_rest(boost_to_rest(ep, four), zee_in4)[:, 1:4])
    e2 = _unit(boost_to_rest(boost_to_rest(mup, four), zmm_in4)[:, 1:4])
    out['cos_theta1'] = np.clip(np.sum(d1 * e1, axis=1), -1.0, 1.0)
    out['cos_theta2'] = np.clip(np.sum(d2 * e2, axis=1), -1.0, 1.0)
    # The product is the strict INTER-decay correlation: each factor is
    # separately symmetric under l+ <-> l- for an unpolarised parent, so
    # <cos theta1 . cos theta2> can only be non-zero if the two decays are
    # correlated with each other.  A mode that decays each z independently --
    # spinmode = none -- gives exactly zero, no matter what it does to a single
    # z's polarisation, which is what makes this and not Phi the observable
    # that isolates the thing the density matrix carries.
    out['cos1cos2'] = out['cos_theta1'] * out['cos_theta2']

    # --- phi between the two decay planes, in the four-lepton rest frame ---
    ep4 = boost_to_rest(ep, four)[:, 1:4]
    em4 = boost_to_rest(em, four)[:, 1:4]
    mup4 = boost_to_rest(mup, four)[:, 1:4]
    mum4 = boost_to_rest(mum, four)[:, 1:4]
    n1 = _unit(np.cross(ep4, em4))
    n2 = _unit(np.cross(mup4, mum4))
    zdir = _unit(zee_in4[:, 1:4])
    cosphi = np.clip(-np.sum(n1 * n2, axis=1), -1.0, 1.0)
    sign = np.sign(np.sum(zdir * np.cross(n1, n2), axis=1))
    sign = np.where(sign == 0, 1.0, sign)
    out['phi_planes'] = sign * np.arccos(cosphi)

    # --- the polarisation projectors (see POL_0 below) --------------------
    # <pol0_1> is the longitudinal fraction of the (e+ e-) parent, <pol0_2>
    # that of the (mu+ mu-) one, and <pol00> the JOINT longitudinal fraction.
    # They are event-level estimators, so they carry an ordinary error of the
    # mean and the joint one is simply the product of the two single ones.
    out['pol0_1'] = POL_0(out['cos_theta1'])
    out['pol0_2'] = POL_0(out['cos_theta2'])
    out['pol00'] = out['pol0_1'] * out['pol0_2']
    out['polTT'] = (1.0 - out['pol0_1']) * (1.0 - out['pol0_2'])
    return out


# --------------------------------------------------------------------------
# Binning.  Fixed here so the harvester and the plotters cannot drift apart.
# --------------------------------------------------------------------------
M_Z = 91.1880
W_Z = 2.441404
BW_CUT = 15
M_LO = M_Z - BW_CUT * W_Z
M_HI = M_Z + BW_CUT * W_Z
# --------------------------------------------------------------------------
# What a cos(theta) moment is worth: the Z polarisation, and the price of
# using a Z as a spin analyser
# --------------------------------------------------------------------------
# For a Z of helicity ``lambda`` along its own flight direction, decaying to
# massless leptons, the ``l+`` polar angle in the Z rest frame is distributed as
#
#     W_{+-1}(c) = (3/8) (1 + c^2 +- 2 eta_l c)      W_0(c) = (3/4) (1 - c^2)
#
# each normalised to 1 over ``c in [-1, 1]``.  Only the PARITY-VIOLATING term
# carries the analysing power
#
#     eta_l = 2 g_V g_A / (g_V^2 + g_A^2) = (1 - 4 sw2) / (1 - 4 sw2 + 8 sw2^2)
#
# which is small because the Z's coupling to charged leptons is nearly pure
# vector.  The ``(1 + c^2)`` versus ``sin^2`` SHAPE difference carries no
# ``eta_l`` at all.  So the two kinds of moment are not on the same footing:
#
#   * the rank-1 (vector polarisation) moments -- <cos theta>, and the
#     inter-decay <cos theta1 cos theta2> -- are diluted by eta_l and eta_l^2;
#   * the rank-2 (alignment) moments -- <cos^2 theta> and the joint
#     <cos^2 theta1 cos^2 theta2> -- are NOT diluted at all.
#
# Writing f_0 for the longitudinal fraction, the rank-2 relation is
#
#     <cos^2 theta> = (2 - f_0) / 5      i.e.   f_0 = 2 - 5 <cos^2 theta>
#
# and ``POL_0`` below is exactly that, per event, so that <POL_0> = f_0 with an
# ordinary error of the mean.  f_0 = 1/3 is the isotropic (unpolarised) value.
#
# The rank-1 inter-decay one is
#
#     <cos theta1 cos theta2> = (eta_l^2 / 4) C_kk,
#     C_kk = <S_k(1) S_k(2)>, S_k the spin-1 projection on each Z's own
#            helicity axis, eigenvalues +1, 0, -1
#
# so the calibration constant is 4 / eta_l^2 -- NOT the 9 of the t t~ case.
# The 9 there is the spin-1/2 version of the same algebra: for a decay
# (1/2)(1 + kappa c) one gets <c1 c2> = (kappa^2 / 9) C_nn, and kappa = 1 for a
# charged lepton from a top.  For spin 1 the coefficient is 4 even at eta_l = 1.
#
# Numbers: this study runs the MG5 default SM param_card in the on-shell EW
# scheme, where MW is derived from (aEWM1, Gf, MZ) and sw2 = 1 - MW^2/MZ^2.
SM_AEWM1 = 132.507
SM_GF = 1.166390e-05


def _mw_from_sminputs(aewm1=SM_AEWM1, gf=SM_GF, mz=M_Z):
    """MW as the SM UFO builds it: the on-shell solution of the Gf relation."""
    aew = 1.0 / aewm1
    return math.sqrt(mz ** 2 / 2.0
                     + math.sqrt(mz ** 4 / 4.0
                                 - (aew * math.pi * mz ** 2) / (gf * math.sqrt(2.0))))


M_W = _mw_from_sminputs()
SW2 = 1.0 - M_W ** 2 / M_Z ** 2
ETA_L = (1.0 - 4.0 * SW2) / (1.0 - 4.0 * SW2 + 8.0 * SW2 ** 2)


def POL_0(cos_theta):
    """Per-event estimator of the longitudinal fraction: <2 - 5 cos^2> = f_0.

    Not a probability event by event -- it runs from -3 to +2 -- but its mean
    is f_0 exactly, and the mean of the PRODUCT of the two Z's estimators is
    the joint fraction f_00.  1 - POL_0 is the transverse estimator.
    """
    return 2.0 - 5.0 * cos_theta ** 2


def c_kk_from_moment(mean, err):
    """(C_kk, error) from <cos theta1 cos theta2>: C_kk = 4 <c1 c2> / eta_l^2."""
    k = 4.0 / ETA_L ** 2
    return k * mean, k * err


def _selftest_polarisation():
    """The projector has to give 1/3 on an isotropic decay and the right value
    on each pure helicity, or every number built on it is decoration."""
    c = np.linspace(-1.0, 1.0, 200001)

    def _integral(y):
        # trapezoid by hand: np.trapz is deprecated in numpy 2 and
        # np.trapezoid does not exist in numpy 1, and this module has to
        # import under both
        return float(np.sum(0.5 * (y[1:] + y[:-1]) * np.diff(c)))

    def mean(w, v):
        return _integral(w * v) / _integral(w)
    flat = np.ones_like(c)
    w_t = 0.375 * (1.0 + c ** 2)
    w_l = 0.75 * (1.0 - c ** 2)
    assert abs(mean(flat, POL_0(c)) - 1.0 / 3.0) < 1e-6, 'POL_0: isotropic'
    assert abs(mean(w_t, POL_0(c)) - 0.0) < 1e-6, 'POL_0: pure transverse'
    assert abs(mean(w_l, POL_0(c)) - 1.0) < 1e-6, 'POL_0: pure longitudinal'
    # and the eta_l term must not touch it, which is the whole point
    w_p = 0.375 * (1.0 + c ** 2 + 2.0 * ETA_L * c)
    assert abs(mean(w_p, POL_0(c)) - 0.0) < 1e-6, 'POL_0: eta_l leaks in'
    assert 0.20 < ETA_L < 0.24, 'eta_l off its on-shell-scheme value: %r' % ETA_L


_selftest_polarisation()


def _selftest_helicity_frame():
    """``cos_theta1/2`` must be Lorentz INVARIANT, and ``compute`` must not
    disagree with an explicit two-step construction.

    Both angles are built out of nothing but the four lepton momenta and two
    rest frames those momenta define, so no observer can measure a different
    value: boosting the whole event -- along the beam, or in any other
    direction -- has to leave every angular observable of ``compute``
    untouched.  That single property is what the study got wrong for its first
    pass and what this test exists to keep it from getting wrong again.

    The version this replaces took ``d1`` in the four-lepton frame but boosted
    the ``l+`` into its pair's rest frame straight from the LAB.  Those two
    boosts are not collinear, so their composition carries a Wigner rotation:
    the analysing frame is tilted away from the axis by an angle that grows
    with the rapidity of the four-lepton system and vanishes when it is at
    rest.  The observable was therefore a function of the observer, and it
    damped every rank-2 moment towards the isotropic value.  This test FAILS on
    that version -- the boosted event gives different angles -- and passes on
    the sequential one.  See POLWEIGHT_CLOSURE_DIAGNOSIS.md.

    Property 2 pins the frame down positively rather than only forbidding the
    old one: a decay generated as a pure ``sin^2(theta)`` about the parent's
    own direction in the four-lepton frame has to come back with
    ``<cos^2 theta> = 1/5``, which is exactly the closure MadSpin's polarised
    matrix-element weights were failing.
    """
    rng = np.random.default_rng(20260827)
    n = 4000

    # --- a synthetic ZZ -> 4l sample, built in the four-lepton rest frame ---
    m1 = rng.normal(M_Z, 2.5, size=n)
    m2 = rng.normal(M_Z, 2.5, size=n)
    s = (rng.uniform(0.0, 1.0, size=n) ** 2) * 600.0 + m1 + m2 + 20.0
    # back-to-back Z of the pair, isotropic production angle
    e1z = (s ** 2 + m1 ** 2 - m2 ** 2) / (2.0 * s)
    pz = np.sqrt(np.maximum(e1z ** 2 - m1 ** 2, 0.0))
    ct = rng.uniform(-1.0, 1.0, size=n)
    st = np.sqrt(1.0 - ct ** 2)
    fi = rng.uniform(0.0, 2.0 * np.pi, size=n)
    nz = np.column_stack([st * np.cos(fi), st * np.sin(fi), ct])
    Z1 = np.column_stack([e1z, pz[:, None] * nz])
    Z2 = np.column_stack([s - e1z, -pz[:, None] * nz])

    def _decay(parent, m, cos_hel):
        """Two massless daughters, ``cos_hel`` measured against the parent's own
        direction in the frame ``parent`` is written in.  Returns the l+ and l-
        in that same frame."""
        # local triad with z along the parent's direction
        z = _unit(parent[:, 1:4])
        ref = np.tile(np.array([0.0, 0.0, 1.0]), (len(z), 1))
        bad = np.abs(z[:, 2]) > 0.99
        ref[bad] = np.array([1.0, 0.0, 0.0])
        x = _unit(ref - z * np.sum(ref * z, axis=1)[:, None])
        y = np.cross(z, x)
        sh = np.sqrt(1.0 - cos_hel ** 2)
        ph = rng.uniform(0.0, 2.0 * np.pi, size=len(z))
        k = (z * cos_hel[:, None] + x * (sh * np.cos(ph))[:, None]
             + y * (sh * np.sin(ph))[:, None])
        half = m / 2.0
        lp = np.column_stack([half, half[:, None] * k])
        lm = np.column_stack([half, -half[:, None] * k])
        # from the parent rest frame out to the frame ``parent`` lives in
        back = parent.copy()
        back[:, 1:4] *= -1.0
        return boost_to_rest(lp, back), boost_to_rest(lm, back)

    # pure longitudinal: sin^2 theta, drawn by inverting its cumulative
    u = rng.uniform(-1.0, 1.0, size=n)
    cos_hel = 2.0 * np.sin(np.arcsin(u) / 3.0)          # root of (3c - c^3)/2 = u
    ep, em = _decay(Z1, m1, cos_hel)
    mup, mum = _decay(Z2, m2, cos_hel[::-1].copy())
    p = {-11: ep, 11: em, -13: mup, 13: mum}

    got = compute(p)
    assert abs(float(np.mean(got['cos_theta1'] ** 2)) - 0.2) < 5e-3, \
        'helicity frame: a pure sin^2 decay does not give <cos^2 theta> = 1/5 ' \
        '(got %.5f)' % float(np.mean(got['cos_theta1'] ** 2))

    # --- property 1: invariance under an arbitrary boost of the whole event --
    for beta in ((0.0, 0.0, 0.90), (0.0, 0.0, -0.55), (0.31, -0.18, 0.62)):
        b = np.array(beta)
        g = 1.0 / math.sqrt(1.0 - float(b @ b))
        ref = np.tile(np.concatenate([[g], -g * b]), (n, 1))  # boost_to_rest(-beta)
        ref *= 100.0                                          # any positive scale
        moved = {k: boost_to_rest(v, ref) for k, v in p.items()}
        again = compute(moved)
        for name in ('cos_theta1', 'cos_theta2', 'cos1cos2', 'phi_planes'):
            d = float(np.abs(again[name] - got[name]).max())
            assert d < 1e-6, (
                'helicity frame: %s is not Lorentz invariant -- boosting the '
                'event by beta = %s moves it by %.4g. The two boosts into the '
                'pair rest frame have to be sequential (lab -> 4l -> pair); a '
                'mixed composition carries a Wigner rotation.' % (name, beta, d))


_selftest_helicity_frame()


BINS = {
    # the headline cross-pair mass
    'm_epmum':    np.linspace(0.0, 400.0, 81),
    'm_epmup':    np.linspace(0.0, 400.0, 81),
    # the correlation angles
    'phi_planes': np.linspace(-math.pi, math.pi, 33),
    'cos_theta1': np.linspace(-1.0, 1.0, 41),
    'cos_theta2': np.linspace(-1.0, 1.0, 41),
    'cos1cos2':   np.linspace(-1.0, 1.0, 41),
    'dphi_epmum': np.linspace(0.0, math.pi, 33),
    # the intra-pair azimuthal separations: same binning as the cross-pair one
    # above, so the three are read off the same grid
    'dphi_ee':    np.linspace(0.0, math.pi, 33),
    'dphi_mumu':  np.linspace(0.0, math.pi, 33),
    # lineshape / window sanity
    'm_ee':       np.linspace(M_LO, M_HI, 76),
    'm_mumu':     np.linspace(M_LO, M_HI, 76),
    # global
    'm_4l':       np.linspace(150.0, 800.0, 66),
    'pt_ee':      np.concatenate([np.linspace(0.0, 100.0, 51),
                                  np.linspace(110.0, 300.0, 20)]),
}

LABELS = {
    'm_epmum':    (r'$m(e^{+}\mu^{-})$ [GeV]',
                   r'$\mathrm{d}\sigma/\mathrm{d}m(e^{+}\mu^{-})$ [pb/GeV]'),
    'm_epmup':    (r'$m(e^{+}\mu^{+})$ [GeV]',
                   r'$\mathrm{d}\sigma/\mathrm{d}m(e^{+}\mu^{+})$ [pb/GeV]'),
    'phi_planes': (r'$\Phi$ between the $Z$ decay planes [rad]',
                   r'$\mathrm{d}\sigma/\mathrm{d}\Phi$ [pb/rad]'),
    'cos_theta1': (r'$\cos\theta_{1}$ of $e^{+}$ in the $(e^{+}e^{-})$ rest frame',
                   r'$\mathrm{d}\sigma/\mathrm{d}\cos\theta_{1}$ [pb]'),
    'cos_theta2': (r'$\cos\theta_{2}$ of $\mu^{+}$ in the $(\mu^{+}\mu^{-})$ rest frame',
                   r'$\mathrm{d}\sigma/\mathrm{d}\cos\theta_{2}$ [pb]'),
    'cos1cos2':   (r'$\cos\theta_{1}\cos\theta_{2}$ (inter-decay correlation)',
                   r'$\mathrm{d}\sigma/\mathrm{d}(\cos\theta_{1}\cos\theta_{2})$ [pb]'),
    'dphi_epmum': (r'$\Delta\phi(e^{+},\mu^{-})$ in the lab [rad]',
                   r'$\mathrm{d}\sigma/\mathrm{d}\Delta\phi$ [pb/rad]'),
    'dphi_ee':    (r'$\Delta\phi(e^{+},e^{-})$ in the lab [rad]',
                   r'$\mathrm{d}\sigma/\mathrm{d}\Delta\phi$ [pb/rad]'),
    'dphi_mumu':  (r'$\Delta\phi(\mu^{+},\mu^{-})$ in the lab [rad]',
                   r'$\mathrm{d}\sigma/\mathrm{d}\Delta\phi$ [pb/rad]'),
    'm_ee':       (r'$m(e^{+}e^{-})$ [GeV]',
                   r'$\mathrm{d}\sigma/\mathrm{d}m(e^{+}e^{-})$ [pb/GeV]'),
    'm_mumu':     (r'$m(\mu^{+}\mu^{-})$ [GeV]',
                   r'$\mathrm{d}\sigma/\mathrm{d}m(\mu^{+}\mu^{-})$ [pb/GeV]'),
    'm_4l':       (r'$m(e^{+}e^{-}\mu^{+}\mu^{-})$ [GeV]',
                   r'$\mathrm{d}\sigma/\mathrm{d}m_{4\ell}$ [pb/GeV]'),
    'pt_ee':      (r'$p_{T}(e^{+}e^{-})$ [GeV]',
                   r'$\mathrm{d}\sigma/\mathrm{d}p_{T}(e^{+}e^{-})$ [pb/GeV]'),
}

# Plain-text twins of LABELS, for numbers.txt and for a non-usetex fallback.
LABELS_TXT = {
    'm_epmum':    'm(e+ mu-) [GeV]',
    'm_epmup':    'm(e+ mu+) [GeV]',
    'phi_planes': 'Phi between the Z decay planes [rad]',
    'cos_theta1': 'cos(theta1) of e+ in the (e+ e-) rest frame',
    'cos_theta2': 'cos(theta2) of mu+ in the (mu+ mu-) rest frame',
    'cos1cos2':   'cos(theta1) x cos(theta2)  (inter-decay correlation)',
    'dphi_epmum': 'Delta phi(e+, mu-) in the lab [rad]',
    # the two intra-pair ones say "same Z" in their own description: they are
    # not correlations between the decays, they track that Z's own pt, and a
    # reader of numbers.txt who takes them for the cross-pair kind will read
    # the low-pt support hole of PA_LOWPT_DIAGNOSIS.md as a spin defect
    'dphi_ee':    'Delta phi(e+, e-) in the lab [rad]  (same Z; tracks pt(e+e-))',
    'dphi_mumu':  'Delta phi(mu+, mu-) in the lab [rad]  (same Z; tracks pt(mu+mu-))',
    'm_ee':       'm(e+ e-) [GeV]',
    'm_mumu':     'm(mu+ mu-) [GeV]',
    'm_4l':       'm(e+ e- mu+ mu-) [GeV]',
    'pt_ee':      'pt(e+ e-) [GeV]',
}


def histogram(values, weights, edges):
    """Weighted histogram plus its Monte-Carlo error, both as densities.

    Returned in ``d sigma / d x`` units: the sum of weights in a bin divided by
    the number of events in the *file* (the LHE is IDWTUP = -4, so mean(w) is
    the cross section) and by the bin width.  The error is
    ``sqrt(sum w^2)`` carried through the same normalisation, which is the
    right one for a sample of nearly-equal weights and stays right when
    MadSpin's overweight carry makes them not quite equal.
    """
    n = len(weights)
    s, _ = np.histogram(values, bins=edges, weights=weights)
    s2, _ = np.histogram(values, bins=edges, weights=weights ** 2)
    width = np.diff(edges)
    return s / n / width, np.sqrt(s2) / n / width
