#!/usr/bin/env python3
"""The event-level observables of the ``g g > z z`` loop-induced comparison.

One module, imported by the harvester and by both plotting scripts, so the
definition a number was made with is the definition it is plotted with.  Nothing
here needs MadGraph: it reads Les Houches files and returns numpy arrays.

Every observable is built from the four status-1 charged leptons of an event --
``e+ e- mu+ mu-``, one of each -- and from nothing else.  That is what makes the
two sides comparable: sample B (``g g > e+ e- mu+ mu- / a``, loop-induced) has
no ``z`` in its final state at all, and sample A only has one before MadSpin
decays it, so any observable that mentions a ``z`` would be measurable on one
side and not the other.  The pair masses are *reconstructed*, exactly as an
experiment would have to.

The angular conventions follow the H -> ZZ -> 4l literature
(Gao et al., arXiv:0708.0458), specialised to a ``ZZ`` system that is not a
resonance:

``cos_theta1`` / ``cos_theta2``
    the ``l+`` direction in its own pair's rest frame, measured against that
    pair's direction of flight in the four-lepton rest frame.  Flat for an
    unpolarised parent; the ``1 + cos^2`` / ``cos`` structure of a real ``Z``
    decay is what a spin-correlated MadSpin mode has to reproduce.  These
    respond to the polarisation of ONE ``Z``.

``cos1cos2``
    their product, and the observable that isolates the correlation *between*
    the two decays.  Each factor is separately odd under ``l+ <-> l-`` for an
    unpolarised parent, so ``<cos theta1 . cos theta2>`` is exactly zero for any
    scheme that decays the two ``z`` independently -- however well that scheme
    gets each ``z``'s own polarisation.  It is therefore the strict test of what
    MadSpin's density matrix carries and nothing else.

``phi_planes``
    the angle between the two decay planes in the four-lepton rest frame,
    signed by the ``(e+ e-)`` flight direction so that it runs over the full
    ``[-pi, pi]``.  Also zero-information for factorised decays -- it is
    generated by the interference between the ``ZZ`` helicity amplitudes -- and
    it is the observable the ``H -> ZZ -> 4l`` literature leads with, which is
    why it is here.

    It turns out **not** to discriminate for this process.  ``gg -> ZZ`` is a
    continuum, not a spin-0 resonance, and once the modulation is integrated
    over the production angle and over ``m_4l`` it averages away: all four
    MadSpin modes and the off-shell truth agree on a flat ``Phi`` to within the
    statistics of 50 000 events.  That is a measurement, not a defect of the
    definition -- ``cos1cos2``, computed from the same boosts, does separate the
    modes -- and it is reported as such in RESULTS.md.

``m_epmum``
    the ``(e+ mu-)`` invariant mass: a cross-pair combination, so it is built
    from one lepton out of each decay and cannot be reproduced by any
    single-``Z`` observable.
"""

import gzip
import math

import numpy as np


# --------------------------------------------------------------------------
# Les Houches reading
# --------------------------------------------------------------------------
def _open(path):
    if path.endswith('.gz'):
        return gzip.open(path, 'rt', errors='replace')
    return open(path, 'rt', errors='replace')


def read_lhe(path, want=(-11, 11, -13, 13)):
    """Return ``(weights, {pdg: (N, 4) array of (E, px, py, pz)})``.

    Only status-1 particles are looked at, and exactly one of each pdg in
    ``want`` is required per event -- an event with two ``e+`` would mean the
    positional decay rule did not do what this study assumes, and is a hard
    error rather than something to average over.
    """
    weights = []
    cols = {p: [] for p in want}
    nbad = 0
    with _open(path) as fh:
        inev = False
        wgt = None
        found = {}
        for line in fh:
            s = line.strip()
            if s.startswith('<event'):
                inev, wgt, found = True, None, {}
                continue
            if not inev:
                continue
            if s.startswith('</event>'):
                inev = False
                if set(found) != set(want):
                    nbad += 1
                    continue
                weights.append(wgt)
                for p in want:
                    cols[p].append(found[p])
                continue
            if not s or s.startswith('<') or s.startswith('#'):
                continue
            f = s.split()
            if wgt is None:
                if len(f) >= 6:
                    try:
                        wgt = float(f[2])
                    except ValueError:
                        wgt = None
                continue
            if len(f) < 13:
                continue
            try:
                pdg, status = int(f[0]), int(f[1])
            except ValueError:
                continue
            if status != 1 or pdg not in want:
                continue
            if pdg in found:
                raise ValueError(
                    'two status-1 particles with pdg %d in one event of %s: the '
                    'positional decay rule did not give one e+e- and one mu+mu- '
                    'pair, so this sample is not comparable' % (pdg, path))
            found[pdg] = (float(f[9]), float(f[6]), float(f[7]), float(f[8]))
    if nbad:
        raise ValueError('%d events of %s did not carry exactly one each of '
                         'e+ e- mu+ mu-' % (nbad, path))
    return (np.array(weights, dtype=float),
            {p: np.array(cols[p], dtype=float) for p in want})


# --------------------------------------------------------------------------
# four-vector helpers.  Arrays are (N, 4) with the LHE ordering (E, px, py, pz).
# --------------------------------------------------------------------------
def mass(v):
    m2 = v[:, 0] ** 2 - v[:, 1] ** 2 - v[:, 2] ** 2 - v[:, 3] ** 2
    return np.sqrt(np.clip(m2, 0.0, None))


def pt(v):
    return np.hypot(v[:, 1], v[:, 2])


def boost_to_rest(v, ref):
    """Boost ``v`` into the rest frame of ``ref`` (both (N, 4)).

    ``beta = -p_ref / E_ref`` and ``gamma = E_ref / m_ref``, then

        E'      = gamma (E + beta.p)
        p'_i    = p_i + (gamma - 1)/beta^2 (beta.p) beta_i + gamma beta_i E

    Written out because getting it subtly wrong is easy and silent: an earlier
    version of this function used ``p_ref/m_ref`` where ``beta`` belongs, which
    leaves the *energy* exactly right -- so ``mass()`` of the boosted vector
    still looks plausible -- while multiplying the last term by an extra
    ``gamma``.  Every angular observable in this study is built out of this
    function, so :func:`_selftest_boost` checks it against the three properties
    that pin it down, and is run on import.
    """
    m = mass(ref)
    m = np.where(m > 0, m, 1.0)
    g = ref[:, 0] / m
    e = np.where(ref[:, 0] > 0, ref[:, 0], 1.0)
    bx, by, bz = (-ref[:, 1] / e, -ref[:, 2] / e, -ref[:, 3] / e)
    b2 = bx ** 2 + by ** 2 + bz ** 2
    bp = bx * v[:, 1] + by * v[:, 2] + bz * v[:, 3]
    fac = np.where(b2 > 0, (g - 1.0) / np.where(b2 > 0, b2, 1.0), 0.0)
    out = np.empty_like(v)
    out[:, 0] = g * (v[:, 0] + bp)
    out[:, 1] = v[:, 1] + fac * bp * bx + g * bx * v[:, 0]
    out[:, 2] = v[:, 2] + fac * bp * by + g * by * v[:, 0]
    out[:, 3] = v[:, 3] + fac * bp * bz + g * bz * v[:, 0]
    return out


def _selftest_boost():
    """Three properties that pin :func:`boost_to_rest` down, checked on import.

    1. boosting a vector into its own rest frame leaves ``(m, 0, 0, 0)``;
    2. a boost preserves invariant mass;
    3. the two halves of a two-body system come out back to back in the
       parent's rest frame.

    Property 1 alone is not enough -- it is satisfied by more than one wrong
    formula -- which is why all three are here.
    """
    rng = np.random.default_rng(20260822)
    m = rng.uniform(1.0, 200.0, size=64)
    p3 = rng.normal(0.0, 150.0, size=(64, 3))
    v = np.column_stack([np.sqrt(m ** 2 + (p3 ** 2).sum(1)), p3])
    r = boost_to_rest(v, v)
    assert np.abs(r[:, 1:]).max() < 1e-6, 'boost: self rest frame not at rest'
    assert np.abs(r[:, 0] - m).max() < 1e-8, 'boost: self rest frame energy'

    q3 = rng.normal(0.0, 150.0, size=(64, 3))
    ref = np.column_stack([np.sqrt(300.0 ** 2 + (q3 ** 2).sum(1)), q3])
    b = boost_to_rest(v, ref)
    assert np.abs(mass(b) - mass(v)).max() < 1e-6, 'boost: mass not preserved'

    a, c = v[:32], v[32:]
    par = a + c
    ar, cr = boost_to_rest(a, par), boost_to_rest(c, par)
    assert np.abs(ar[:, 1:] + cr[:, 1:]).max() < 1e-6, \
        'boost: two-body not back to back in the parent rest frame'


_selftest_boost()


def _unit(a):
    n = np.linalg.norm(a, axis=1, keepdims=True)
    return a / np.where(n > 0, n, 1.0)


def phi_of(v):
    return np.arctan2(v[:, 2], v[:, 1])


# --------------------------------------------------------------------------
# The observables
# --------------------------------------------------------------------------
def compute(p):
    """``p`` is the dict returned by :func:`read_lhe`; returns a dict of arrays."""
    ep, em, mup, mum = p[-11], p[11], p[-13], p[13]
    zee = ep + em
    zmm = mup + mum
    four = zee + zmm

    out = {
        'm_ee': mass(zee),
        'm_mumu': mass(zmm),
        'm_4l': mass(four),
        'pt_ee': pt(zee),
        'pt_mumu': pt(zmm),
        'm_epmum': mass(ep + mum),
        'm_epmup': mass(ep + mup),
    }

    # --- delta phi (e+, mu-) in the lab: the cheapest correlation handle ---
    dphi = phi_of(ep) - phi_of(mum)
    out['dphi_epmum'] = np.abs((dphi + np.pi) % (2 * np.pi) - np.pi)

    # --- cos theta1 / cos theta2: the l+ in its own pair's rest frame, against
    #     that pair's flight direction in the four-lepton rest frame ---
    zee_in4 = boost_to_rest(zee, four)
    zmm_in4 = boost_to_rest(zmm, four)
    d1 = _unit(zee_in4[:, 1:4])
    d2 = _unit(zmm_in4[:, 1:4])
    e1 = _unit(boost_to_rest(ep, zee)[:, 1:4])
    e2 = _unit(boost_to_rest(mup, zmm)[:, 1:4])
    out['cos_theta1'] = np.clip(np.sum(d1 * e1, axis=1), -1.0, 1.0)
    out['cos_theta2'] = np.clip(np.sum(d2 * e2, axis=1), -1.0, 1.0)
    # The product is the strict INTER-decay correlation: each factor is
    # separately symmetric under l+ <-> l- for an unpolarised parent, so
    # <cos theta1 . cos theta2> can only be non-zero if the two decays are
    # correlated with each other.  A mode that decays each z independently --
    # spinmode = none -- gives exactly zero, no matter what it does to a single
    # z's polarisation, which is what makes this and not Phi the observable
    # that isolates the thing the density matrix carries.
    out['cos1cos2'] = out['cos_theta1'] * out['cos_theta2']

    # --- phi between the two decay planes, in the four-lepton rest frame ---
    ep4 = boost_to_rest(ep, four)[:, 1:4]
    em4 = boost_to_rest(em, four)[:, 1:4]
    mup4 = boost_to_rest(mup, four)[:, 1:4]
    mum4 = boost_to_rest(mum, four)[:, 1:4]
    n1 = _unit(np.cross(ep4, em4))
    n2 = _unit(np.cross(mup4, mum4))
    zdir = _unit(zee_in4[:, 1:4])
    cosphi = np.clip(-np.sum(n1 * n2, axis=1), -1.0, 1.0)
    sign = np.sign(np.sum(zdir * np.cross(n1, n2), axis=1))
    sign = np.where(sign == 0, 1.0, sign)
    out['phi_planes'] = sign * np.arccos(cosphi)
    return out


# --------------------------------------------------------------------------
# Binning.  Fixed here so the harvester and the plotters cannot drift apart.
# --------------------------------------------------------------------------
M_Z = 91.1880
W_Z = 2.441404
BW_CUT = 15
M_LO = M_Z - BW_CUT * W_Z
M_HI = M_Z + BW_CUT * W_Z

BINS = {
    # the headline cross-pair mass
    'm_epmum':    np.linspace(0.0, 400.0, 81),
    'm_epmup':    np.linspace(0.0, 400.0, 81),
    # the correlation angles
    'phi_planes': np.linspace(-math.pi, math.pi, 33),
    'cos_theta1': np.linspace(-1.0, 1.0, 41),
    'cos_theta2': np.linspace(-1.0, 1.0, 41),
    'cos1cos2':   np.linspace(-1.0, 1.0, 41),
    'dphi_epmum': np.linspace(0.0, math.pi, 33),
    # lineshape / window sanity
    'm_ee':       np.linspace(M_LO, M_HI, 76),
    'm_mumu':     np.linspace(M_LO, M_HI, 76),
    # global
    'm_4l':       np.linspace(150.0, 800.0, 66),
    'pt_ee':      np.concatenate([np.linspace(0.0, 100.0, 51),
                                  np.linspace(110.0, 300.0, 20)]),
}

LABELS = {
    'm_epmum':    (r'$m(e^{+}\mu^{-})$ [GeV]',
                   r'$\mathrm{d}\sigma/\mathrm{d}m(e^{+}\mu^{-})$ [pb/GeV]'),
    'm_epmup':    (r'$m(e^{+}\mu^{+})$ [GeV]',
                   r'$\mathrm{d}\sigma/\mathrm{d}m(e^{+}\mu^{+})$ [pb/GeV]'),
    'phi_planes': (r'$\Phi$ between the $Z$ decay planes [rad]',
                   r'$\mathrm{d}\sigma/\mathrm{d}\Phi$ [pb/rad]'),
    'cos_theta1': (r'$\cos\theta_{1}$ of $e^{+}$ in the $(e^{+}e^{-})$ rest frame',
                   r'$\mathrm{d}\sigma/\mathrm{d}\cos\theta_{1}$ [pb]'),
    'cos_theta2': (r'$\cos\theta_{2}$ of $\mu^{+}$ in the $(\mu^{+}\mu^{-})$ rest frame',
                   r'$\mathrm{d}\sigma/\mathrm{d}\cos\theta_{2}$ [pb]'),
    'cos1cos2':   (r'$\cos\theta_{1}\cos\theta_{2}$ (inter-decay correlation)',
                   r'$\mathrm{d}\sigma/\mathrm{d}(\cos\theta_{1}\cos\theta_{2})$ [pb]'),
    'dphi_epmum': (r'$\Delta\phi(e^{+},\mu^{-})$ in the lab [rad]',
                   r'$\mathrm{d}\sigma/\mathrm{d}\Delta\phi$ [pb/rad]'),
    'm_ee':       (r'$m(e^{+}e^{-})$ [GeV]',
                   r'$\mathrm{d}\sigma/\mathrm{d}m(e^{+}e^{-})$ [pb/GeV]'),
    'm_mumu':     (r'$m(\mu^{+}\mu^{-})$ [GeV]',
                   r'$\mathrm{d}\sigma/\mathrm{d}m(\mu^{+}\mu^{-})$ [pb/GeV]'),
    'm_4l':       (r'$m(e^{+}e^{-}\mu^{+}\mu^{-})$ [GeV]',
                   r'$\mathrm{d}\sigma/\mathrm{d}m_{4\ell}$ [pb/GeV]'),
    'pt_ee':      (r'$p_{T}(e^{+}e^{-})$ [GeV]',
                   r'$\mathrm{d}\sigma/\mathrm{d}p_{T}(e^{+}e^{-})$ [pb/GeV]'),
}

# Plain-text twins of LABELS, for numbers.txt and for a non-usetex fallback.
LABELS_TXT = {
    'm_epmum':    'm(e+ mu-) [GeV]',
    'm_epmup':    'm(e+ mu+) [GeV]',
    'phi_planes': 'Phi between the Z decay planes [rad]',
    'cos_theta1': 'cos(theta1) of e+ in the (e+ e-) rest frame',
    'cos_theta2': 'cos(theta2) of mu+ in the (mu+ mu-) rest frame',
    'cos1cos2':   'cos(theta1) x cos(theta2)  (inter-decay correlation)',
    'dphi_epmum': 'Delta phi(e+, mu-) in the lab [rad]',
    'm_ee':       'm(e+ e-) [GeV]',
    'm_mumu':     'm(mu+ mu-) [GeV]',
    'm_4l':       'm(e+ e- mu+ mu-) [GeV]',
    'pt_ee':      'pt(e+ e-) [GeV]',
}


def histogram(values, weights, edges):
    """Weighted histogram plus its Monte-Carlo error, both as densities.

    Returned in ``d sigma / d x`` units: the sum of weights in a bin divided by
    the number of events in the *file* (the LHE is IDWTUP = -4, so mean(w) is
    the cross section) and by the bin width.  The error is
    ``sqrt(sum w^2)`` carried through the same normalisation, which is the
    right one for a sample of nearly-equal weights and stays right when
    MadSpin's overweight carry makes them not quite equal.
    """
    n = len(weights)
    s, _ = np.histogram(values, bins=edges, weights=weights)
    s2, _ = np.histogram(values, bins=edges, weights=weights ** 2)
    width = np.diff(edges)
    return s / n / width, np.sqrt(s2) / n / width
