#!/usr/bin/env python3
"""The spin coefficients of the ``q qbar`` continuum, for the side-by-side table.

Why this file exists
--------------------
``data/numbers.txt`` is written by ``plot_zz_loopinduced.py`` out of
``data/meta.json`` and ``data/histograms.npz``, which carry the loop-induced
``g g`` study and nothing else.  Anything hand-added to it is silently
overwritten the next time the plotter runs, so it is **not** the natural home
for a second production mechanism.  This script is: it produces
``data/numbers_qq.txt``, the ``q qbar`` half of Table 1 of
``spin_definitions.tex`` and of section 4 of ``SPIN_COEFFICIENTS.md``, from the
events, reproducibly.

Everything angular comes from :mod:`observables` -- the same module, unchanged,
that the ``g g`` numbers come from -- so the two halves of the table are on one
frame convention (the sequential-boost helicity frame of
``POLWEIGHT_CLOSURE_DIAGNOSIS.md``), one set of estimators, and one ``eta_l``.
Importing it runs its self-tests, ``_selftest_boost``,
``_selftest_helicity_frame`` and ``_selftest_polarisation`` among them; a
regression in any of those stops this script before it writes a number.

The samples
-----------
``truth``
    ``p p > e+ e- mu+ mu- / a [QCD]``, the fully off-shell four-lepton NLO
    calculation, 4 x 50 000 events.  Generated by task T114 and kept outside
    ``/tmp`` at ``$ZZ_SPIN_EVENTS/qq_pp4l_nlo``.
``madspin`` / ``onshell`` / ``none`` / ``PA``
    ``p p > z z [QCD]`` at 200 000 events with \\MadSpin{} in each mode, made by
    ``../zz_nlo/run_zz_nlo.py`` with ``NEVENTS`` raised to 200 000 and nothing
    else changed, so the cuts, scale, PDF and beam energy are the sibling
    study's own.

Both carry the selection the ``g g`` study carries: ``pt > 1 GeV`` and
``|m - m_Z| < 15 Gamma_Z`` on each reconstructed lepton pair.  On the
production samples that is ``pt_min_pdg = {23: 1}`` on the two ``z`` plus
\\MadSpin's ``BW_cut = 15``; on the four-lepton truth it is
``../zz_nlo/zz_equivalent_cuts_nlo.f``, which reads both thresholds out of the
run card rather than carrying a typed-in number.  ``--recut`` re-imposes the
same window event by event as an analysis filter, so that the selection of the
two halves of the table is not merely believed to match but is measured to.

Weights
-------
The truth is an MC@NLO sample and carries negative weights, so every bar here is
the error of a *weighted* mean, ``sqrt(sum w^2 (x - xbar)^2) / |sum w|``, and
the count that sets it is ``N_eff = (sum w)^2 / sum w^2``.  On a unit-weight
sample that expression reduces to ``sqrt(Var / N)``, which is what
``run_zz_loopinduced.moment`` uses for the ``g g`` rows.

Usage::

    export PATH="$HOME/.pyenv/versions/mg-3.14/bin:$PATH"
    python3 qq_coefficients.py --recut
"""

import argparse
import glob
import json
import os
import sys

import numpy as np

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _HERE)
import observables as O                                          # noqa: E402

pjoin = os.path.join

DEFAULT_EVENTS = os.path.expanduser(
    '~/Documents/git_workspace/zz_spin_events')
MODES = ('madspin', 'onshell', 'none', 'PA')

# The pt threshold of both studies, in GeV: ``ptheavy = 1`` on the loop-induced
# side and ``pt_min_pdg = {23: 1}`` on the NLO one, which ``setcuts.f`` writes
# into the same per-particle ``etmin`` array, so they are one cut.  The mass
# window is not repeated here -- ``observables.M_LO`` / ``M_HI`` own it.
PT_MIN = 1.0


# --------------------------------------------------------------------------
# estimators
# --------------------------------------------------------------------------
def wmean(x, w):
    """Weighted mean and the error of that mean, valid for signed weights."""
    sw = w.sum()
    m = float(np.dot(w, x) / sw)
    e = float(np.sqrt(np.dot(w ** 2, (x - m) ** 2)) / abs(sw))
    return m, e


def coefficients(w, obs, recut):
    """The seven table entries, plus the diagnostics that qualify them."""
    n_all = len(w)
    if recut:
        sel = ((obs['m_ee'] > O.M_LO) & (obs['m_ee'] < O.M_HI)
               & (obs['m_mumu'] > O.M_LO) & (obs['m_mumu'] < O.M_HI)
               & (obs['pt_ee'] > PT_MIN) & (obs['pt_mumu'] > PT_MIN))
    else:
        sel = np.ones(n_all, dtype=bool)
    w = w[sel]
    obs = {k: v[sel] for k, v in obs.items()}
    sw = w.sum()

    f01, e01 = wmean(obs['pol0_1'], w)
    f02, e02 = wmean(obs['pol0_2'], w)
    out = {
        'N': int(len(w)),
        'N_cut': int(n_all - len(w)),
        'N_eff': float(sw ** 2 / (w ** 2).sum()),
        # IDWTUP = -4 on these files, so the cross section is the MEAN weight;
        # ``sumw`` is kept separately because it is what the bars divide by
        'sumw': float(sw),
        'sigma_pb': float(sw / len(w)),
        'negative_weights': int((w < 0).sum()),
        'm_4l_min': float(obs['m_4l'].min()),
        # the support statement of PA_LOWPT_DIAGNOSIS.md, as a number
        'weight_below_2mZ': float(w[obs['m_4l'] < 2 * O.M_Z].sum() / sw),
        'f_0 (e+ e-)': [f01, e01],
        'f_0 (mu+ mu-)': [f02, e02],
        'f_0 (both)': list(wmean(0.5 * (obs['pol0_1'] + obs['pol0_2']), w)),
        'f_00': list(wmean(obs['pol00'], w)),
        # the rank-2 correlation, as a per-event estimator so that the bar
        # keeps the covariance of the two sides instead of assuming them
        # independent
        'f_00 - f_0 f_0': list(wmean(obs['pol00'] - f01 * f02, w)),
        'f_TT': list(wmean(obs['polTT'], w)),
        'cos1cos2': list(wmean(obs['cos1cos2'], w)),
    }
    out['C_kk'] = list(O.c_kk_from_moment(*out['cos1cos2']))
    return out


# --------------------------------------------------------------------------
# reading
# --------------------------------------------------------------------------
def read_many(paths):
    ws, cols = [], None
    for p in paths:
        w, mom = O.read_lhe(p)
        obs = O.compute(mom)
        ws.append(w)
        if cols is None:
            cols = {k: [v] for k, v in obs.items()}
        else:
            for k, v in obs.items():
                cols[k].append(v)
    return np.concatenate(ws), {k: np.concatenate(v) for k, v in cols.items()}


def collect(args):
    """``{tag: [lhe, ...]}`` for every sample this run can see."""
    files = {}
    truth = sorted(glob.glob(pjoin(args.events, 'qq_pp4l_nlo', '*.lhe*')))
    if truth:
        files['truth'] = truth
    for mode in MODES:
        # ../zz_nlo/run_zz_nlo.stage_madspin writes ms_<mode>/events_decayed.lhe.gz.
        # Matched EXACTLY, not by a glob: MadSpin leaves its per-core
        # ``events_decayed.lhe.shard*.lhe`` and ``.prodshard*.lhe`` pieces
        # beside the finished file, and a wildcard picks those up too -- the
        # ``prodshard`` ones are the UNDECAYED production events, which have no
        # leptons at all and would be silently mixed in if read_lhe were less
        # strict than it is.
        got = pjoin(args.madspin, 'ms_%s' % mode, 'events_decayed.lhe.gz')
        if os.path.exists(got):
            files[mode] = [got]
    return files


# --------------------------------------------------------------------------
# report
# --------------------------------------------------------------------------
NAMES = ['f_0 (e+ e-)', 'f_0 (mu+ mu-)', 'f_0 (both)', 'f_00',
         'f_00 - f_0 f_0', 'f_TT', 'C_kk']

# the g g column of the same table, from data/numbers.txt.  Written here so the
# report can put the two mechanisms next to each other; every entry is
# reproduced from the g g event columns by the check in RESULTS, and none of
# them is recomputed or modified by this script.
GG = {
    'truth':   [0.0666, 0.0671, 0.0669, 0.0417, 0.0372, 0.9079, 0.3804],
    'madspin': [0.0618, 0.0729, 0.0673, 0.0513, 0.0468, 0.9166, 0.4599],
    'PA':      [0.0776, 0.0664, 0.0720, 0.0538, 0.0487, 0.9099, 0.4909],
    'onshell': [0.0706, 0.0748, 0.0727, 0.0525, 0.0472, 0.9072, 0.4311],
    'none':    [0.3320, 0.3305, 0.3313, 0.1065, -0.0033, 0.4439, -0.0337],
}
GG_ERR = {
    'truth':   [0.0035, 0.0035, 0.0025, 0.0054, 0.0054, 0.0071, 0.0722],
    'madspin': [0.0035, 0.0035, 0.0025, 0.0054, 0.0054, 0.0071, 0.0723],
    'PA':      [0.0035, 0.0035, 0.0025, 0.0054, 0.0054, 0.0071, 0.0722],
    'onshell': [0.0035, 0.0035, 0.0025, 0.0054, 0.0054, 0.0071, 0.0721],
    'none':    [0.0033, 0.0033, 0.0024, 0.0052, 0.0050, 0.0059, 0.0620],
}


def report(res, args, lines):
    A = lines.append
    A('p p > z z [QCD] + MadSpin   against   p p > e+ e- mu+ mu- / a [QCD]')
    A('the q qbar half of the two-mechanism table; the g g half is in '
      'numbers.txt')
    A('')
    A('m_Z = %.4f GeV   Gamma_Z = %.6f GeV   BW_cut = %d'
      % (O.M_Z, O.W_Z, O.BW_CUT))
    A('mass window on both reconstructed pairs: %.5f .. %.5f GeV'
      % (O.M_LO, O.M_HI))
    A('pt(l+ l-) > %.1f GeV on both reconstructed pairs' % PT_MIN)
    A('analysis re-cut applied: %s' % ('yes' if args.recut else 'no'))
    A('')
    A('  eta_l = 2 g_V g_A / (g_V^2 + g_A^2) = %.5f, from MW = %.4f built out'
      % (O.ETA_L, O.M_W))
    A('  of (aEWM1, Gf, MZ) and sw2 = 1 - MW^2/MZ^2 = %.6f.  4 / eta_l^2 = %.4f.'
      % (O.SW2, 4.0 / O.ETA_L ** 2))
    A('  Both mechanisms decay Z > l+ l- in the same model with the same')
    A('  param card, so this is one number for the whole table, not two.')
    A('')

    A('--- sample sizes, weights and support ---')
    A('%-10s %8s %8s %10s %13s %10s %10s'
      % ('sample', 'N', 'N_cut', 'N_eff', 'sigma [pb]', 'w < 0', 'min m_4l'))
    for tag, r in res.items():
        A('%-10s %8d %8d %10.0f %13.6f %10d %10.3f'
          % (tag, r['N'], r['N_cut'], r['N_eff'], r['sigma_pb'],
             r['negative_weights'], r['m_4l_min']))
    A('')
    if 'truth' in res:
        t = res['truth']['sigma_pb']
        A('  sigma is the mean weight (IDWTUP = -4).  Against the truth, the')
        A('  MadSpin rows should reproduce it, except that onshell and none do')
        A('  not apply the Breit-Wigner truncation 1/f^2 = 1.045714:')
        for tag, r in res.items():
            if tag == 'truth':
                continue
            A('    %-10s %+.2f %%' % (tag, 100 * (r['sigma_pb'] / t - 1)))
        A('')
    A('  "min m_4l" is the support statement, and it does NOT come out the same')
    A('  here as on the g g side.  The truth is fully off shell and reaches well')
    A('  below 2 m_Z = %.3f GeV.  A MadSpin row on an LO 2 -> 2 production'
      % (2 * O.M_Z))
    A('  sample cannot: m_4l = m_zz there, and on-shell z put that at 2 m_Z --')
    A('  which is what every g g row does, and what p p > z z at LO with')
    A('  spinmode = madspin does too (min m_4l = 182.394).  On THIS sample,')
    A('  which is MC@NLO, the modes that redraw the virtuality do reach below:')
    A('  the reshuffling has somewhere to put the imbalance that an LO 2 -> 2')
    A('  event does not.  onshell, which changes no mass, still starts at 2 m_Z.')
    A('  So the g g and q qbar MadSpin rows are on slightly different supports,')
    A('  and this is the number that says by how much.')
    A('  Weight below 2 m_Z, as a fraction of the total:')
    for tag, r in res.items():
        A('    %-10s %.5f' % (tag, r['weight_below_2mZ']))
    A('')

    A('--- the coefficients ---')
    A('%-10s %s' % ('sample', ' '.join('%-22s' % n for n in NAMES)))
    for tag, r in res.items():
        A('%-10s %s' % (tag, ' '.join(
            '%-22s' % ('%+.4f +- %.4f' % tuple(r[n])) for n in NAMES)))
    A('')

    if 'truth' in res:
        ref = res['truth']
        A('  Against the q qbar truth, in sigma (independent samples, so the')
        A('  bars add in quadrature).  The truth carries far more of the')
        A('  m_4l < 2 m_Z region than any mode does, so a part of every pull')
        A('  below is a support difference and not a spin one; the size of that')
        A('  part is bounded by the weight fractions printed above.')
        for tag, r in res.items():
            if tag == 'truth':
                continue
            bits = []
            for n in NAMES:
                s = (r[n][1] ** 2 + ref[n][1] ** 2) ** 0.5
                bits.append('%s %+.1f' % (n.split(' ')[0], (r[n][0] - ref[n][0]) / s))
            A('    %-10s %s' % (tag, '   '.join(bits)))
        A('')

    A('--- the same coefficients on the g g box, from numbers.txt ---')
    A('  Not recomputed here.  Quoted so that the two mechanisms can be read')
    A('  off one page; the g g numbers are owned by plot_zz_loopinduced.py.')
    A('%-10s %s' % ('sample', ' '.join('%-22s' % n for n in NAMES)))
    for tag in ('truth', 'madspin', 'PA', 'onshell', 'none'):
        A('%-10s %s' % (tag, ' '.join(
            '%-22s' % ('%+.4f +- %.4f' % (v, e))
            for v, e in zip(GG[tag], GG_ERR[tag]))))
    A('')

    if 'truth' in res:
        g, ge = GG['truth'][-1], GG_ERR['truth'][-1]
        q, qe = res['truth']['C_kk']
        A('--- the headline ---')
        A('  C_kk(g g -> ZZ, box)       = %+.3f +- %.3f' % (g, ge))
        A('  C_kk(q qbar -> ZZ, contin) = %+.3f +- %.3f' % (q, qe))
        A('  separation = (%+.3f - (%+.3f)) / sqrt(%.3f^2 + %.3f^2) = %.1f sigma'
          % (g, q, ge, qe, (g - q) / (ge ** 2 + qe ** 2) ** 0.5))
        A('  The two mechanisms correlate the two Z helicities with OPPOSITE')
        A('  sign.  Each is large against its own ceiling |C_kk| <= f_TT:')
        A('    g g    |C_kk| / f_TT = %.2f' % (abs(g) / GG['truth'][5]))
        A('    q qbar |C_kk| / f_TT = %.2f'
          % (abs(q) / res['truth']['f_TT'][0]))
        A('')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--events', default=DEFAULT_EVENTS,
                    help='directory holding qq_pp4l_nlo/ (the NLO truth)')
    ap.add_argument('--madspin', default='',
                    help='the p p > z z [QCD] output directory whose Events/ '
                         'holds the MadSpin-decayed runs')
    ap.add_argument('--recut', action='store_true',
                    help='re-impose the mass window and the pt cut event by '
                         'event, as an analysis filter')
    ap.add_argument('--out', default=pjoin(_HERE, 'data', 'numbers_qq.txt'))
    ap.add_argument('--json', default=pjoin(_HERE, 'data', 'numbers_qq.json'))
    ap.add_argument('--dump-columns', default='',
                    help='also write the per-event columns to this directory. '
                         'They are what a differential re-reading needs and a '
                         '1-D histogram cannot give, so they belong somewhere '
                         'durable rather than in /tmp -- see '
                         '../zz_ckk_mass/README.md.')
    args = ap.parse_args()

    files = collect(args)
    if not files:
        raise SystemExit('no samples found under %s / %s'
                         % (args.events, args.madspin))
    order = [t for t in ('truth',) + MODES if t in files]
    res = {}
    if args.dump_columns:
        os.makedirs(args.dump_columns, exist_ok=True)
    for tag in order:
        print('%-10s %d file(s)' % (tag, len(files[tag])), flush=True)
        w, obs = read_many(files[tag])
        res[tag] = coefficients(w, obs, args.recut)
        res[tag]['files'] = files[tag]
        if args.dump_columns:
            path = pjoin(args.dump_columns, 'events_%s.npz' % tag)
            np.savez_compressed(path, w=w, **obs)
            res[tag]['event_columns'] = path
            print('%-10s columns -> %s' % (tag, path), flush=True)

    lines = []
    report(res, args, lines)
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, 'w') as fp:
        fp.write('\n'.join(lines) + '\n')
    with open(args.json, 'w') as fp:
        json.dump({'recut': args.recut, 'eta_l': O.ETA_L,
                   'mass_window': [O.M_LO, O.M_HI], 'runs': res}, fp, indent=1)
    print('\n'.join(lines))
    print('written %s' % args.out)


if __name__ == '__main__':
    main()
