      SUBROUTINE SMATRIXHEL(P,HEL, FLAVOR, ANS)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=7)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=64)
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: HEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
CF2PY INTENT(IN) :: FLAVOR(NEXTERNAL)

C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER HEL
      INTEGER FLAVOR(NEXTERNAL)
C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/HELUSERCHOICE/USERHEL
C     ----------
C     BEGIN CODE
C     ----------
      USERHEL=HEL
      CALL SMATRIX(P,FLAVOR,ANS)
      USERHEL=-1

      END

      SUBROUTINE SMATRIX(P, FLAVOR, ANS)
C     
C     Generated by MadGraph5_aMC@NLO v. 3.7.1, 2026-04-29
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     MadGraph5_aMC@NLO StandAlone Version
C     
C     Returns amplitude squared summed/avg over colors
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL)
C     
C     Process: _quark _quark > h _quark _quark g g WEIGHTED<=8 @1
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=7)
      INTEGER    NINITIAL
      PARAMETER (NINITIAL=2)
      INTEGER NPOLENTRIES
      PARAMETER (NPOLENTRIES=(NEXTERNAL+1)*6)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=64)
      INTEGER HELAVGFACTOR
      PARAMETER (HELAVGFACTOR=4)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
CF2PY INTENT(IN) :: FLAVOR(NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER NHEL(NEXTERNAL,NCOMB),NTRY
C     put in common block to expose this variable to python interface
      COMMON/PROCESS_NHEL/NHEL
      REAL*8 T
      REAL*8 MATRIX
      INTEGER IHEL,IDEN, I, J
C     For a 1>N process, them BEAMTWO_HELAVGFACTOR would be set to 1.
      INTEGER BEAMS_HELAVGFACTOR(2)
      DATA (BEAMS_HELAVGFACTOR(I),I=1,2)/2,2/
      INTEGER FLAVOR(NEXTERNAL)
      LOGICAL GOODHEL(NCOMB)
      DATA NTRY/0/
      DATA GOODHEL/NCOMB*.FALSE./

C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/HELUSERCHOICE/USERHEL
      DATA USERHEL/-1/
      LOGICAL HELRESET
      COMMON/HELRESET/HELRESET
      DATA HELRESET/.TRUE./

      DATA (NHEL(I,   1),I=1,7) / 1, 1, 0,-1,-1,-1,-1/
      DATA (NHEL(I,   2),I=1,7) / 1, 1, 0,-1,-1,-1, 1/
      DATA (NHEL(I,   3),I=1,7) / 1, 1, 0,-1,-1, 1,-1/
      DATA (NHEL(I,   4),I=1,7) / 1, 1, 0,-1,-1, 1, 1/
      DATA (NHEL(I,   5),I=1,7) / 1, 1, 0,-1, 1,-1,-1/
      DATA (NHEL(I,   6),I=1,7) / 1, 1, 0,-1, 1,-1, 1/
      DATA (NHEL(I,   7),I=1,7) / 1, 1, 0,-1, 1, 1,-1/
      DATA (NHEL(I,   8),I=1,7) / 1, 1, 0,-1, 1, 1, 1/
      DATA (NHEL(I,   9),I=1,7) / 1, 1, 0, 1,-1,-1,-1/
      DATA (NHEL(I,  10),I=1,7) / 1, 1, 0, 1,-1,-1, 1/
      DATA (NHEL(I,  11),I=1,7) / 1, 1, 0, 1,-1, 1,-1/
      DATA (NHEL(I,  12),I=1,7) / 1, 1, 0, 1,-1, 1, 1/
      DATA (NHEL(I,  13),I=1,7) / 1, 1, 0, 1, 1,-1,-1/
      DATA (NHEL(I,  14),I=1,7) / 1, 1, 0, 1, 1,-1, 1/
      DATA (NHEL(I,  15),I=1,7) / 1, 1, 0, 1, 1, 1,-1/
      DATA (NHEL(I,  16),I=1,7) / 1, 1, 0, 1, 1, 1, 1/
      DATA (NHEL(I,  17),I=1,7) / 1,-1, 0,-1,-1,-1,-1/
      DATA (NHEL(I,  18),I=1,7) / 1,-1, 0,-1,-1,-1, 1/
      DATA (NHEL(I,  19),I=1,7) / 1,-1, 0,-1,-1, 1,-1/
      DATA (NHEL(I,  20),I=1,7) / 1,-1, 0,-1,-1, 1, 1/
      DATA (NHEL(I,  21),I=1,7) / 1,-1, 0,-1, 1,-1,-1/
      DATA (NHEL(I,  22),I=1,7) / 1,-1, 0,-1, 1,-1, 1/
      DATA (NHEL(I,  23),I=1,7) / 1,-1, 0,-1, 1, 1,-1/
      DATA (NHEL(I,  24),I=1,7) / 1,-1, 0,-1, 1, 1, 1/
      DATA (NHEL(I,  25),I=1,7) / 1,-1, 0, 1,-1,-1,-1/
      DATA (NHEL(I,  26),I=1,7) / 1,-1, 0, 1,-1,-1, 1/
      DATA (NHEL(I,  27),I=1,7) / 1,-1, 0, 1,-1, 1,-1/
      DATA (NHEL(I,  28),I=1,7) / 1,-1, 0, 1,-1, 1, 1/
      DATA (NHEL(I,  29),I=1,7) / 1,-1, 0, 1, 1,-1,-1/
      DATA (NHEL(I,  30),I=1,7) / 1,-1, 0, 1, 1,-1, 1/
      DATA (NHEL(I,  31),I=1,7) / 1,-1, 0, 1, 1, 1,-1/
      DATA (NHEL(I,  32),I=1,7) / 1,-1, 0, 1, 1, 1, 1/
      DATA (NHEL(I,  33),I=1,7) /-1, 1, 0,-1,-1,-1,-1/
      DATA (NHEL(I,  34),I=1,7) /-1, 1, 0,-1,-1,-1, 1/
      DATA (NHEL(I,  35),I=1,7) /-1, 1, 0,-1,-1, 1,-1/
      DATA (NHEL(I,  36),I=1,7) /-1, 1, 0,-1,-1, 1, 1/
      DATA (NHEL(I,  37),I=1,7) /-1, 1, 0,-1, 1,-1,-1/
      DATA (NHEL(I,  38),I=1,7) /-1, 1, 0,-1, 1,-1, 1/
      DATA (NHEL(I,  39),I=1,7) /-1, 1, 0,-1, 1, 1,-1/
      DATA (NHEL(I,  40),I=1,7) /-1, 1, 0,-1, 1, 1, 1/
      DATA (NHEL(I,  41),I=1,7) /-1, 1, 0, 1,-1,-1,-1/
      DATA (NHEL(I,  42),I=1,7) /-1, 1, 0, 1,-1,-1, 1/
      DATA (NHEL(I,  43),I=1,7) /-1, 1, 0, 1,-1, 1,-1/
      DATA (NHEL(I,  44),I=1,7) /-1, 1, 0, 1,-1, 1, 1/
      DATA (NHEL(I,  45),I=1,7) /-1, 1, 0, 1, 1,-1,-1/
      DATA (NHEL(I,  46),I=1,7) /-1, 1, 0, 1, 1,-1, 1/
      DATA (NHEL(I,  47),I=1,7) /-1, 1, 0, 1, 1, 1,-1/
      DATA (NHEL(I,  48),I=1,7) /-1, 1, 0, 1, 1, 1, 1/
      DATA (NHEL(I,  49),I=1,7) /-1,-1, 0,-1,-1,-1,-1/
      DATA (NHEL(I,  50),I=1,7) /-1,-1, 0,-1,-1,-1, 1/
      DATA (NHEL(I,  51),I=1,7) /-1,-1, 0,-1,-1, 1,-1/
      DATA (NHEL(I,  52),I=1,7) /-1,-1, 0,-1,-1, 1, 1/
      DATA (NHEL(I,  53),I=1,7) /-1,-1, 0,-1, 1,-1,-1/
      DATA (NHEL(I,  54),I=1,7) /-1,-1, 0,-1, 1,-1, 1/
      DATA (NHEL(I,  55),I=1,7) /-1,-1, 0,-1, 1, 1,-1/
      DATA (NHEL(I,  56),I=1,7) /-1,-1, 0,-1, 1, 1, 1/
      DATA (NHEL(I,  57),I=1,7) /-1,-1, 0, 1,-1,-1,-1/
      DATA (NHEL(I,  58),I=1,7) /-1,-1, 0, 1,-1,-1, 1/
      DATA (NHEL(I,  59),I=1,7) /-1,-1, 0, 1,-1, 1,-1/
      DATA (NHEL(I,  60),I=1,7) /-1,-1, 0, 1,-1, 1, 1/
      DATA (NHEL(I,  61),I=1,7) /-1,-1, 0, 1, 1,-1,-1/
      DATA (NHEL(I,  62),I=1,7) /-1,-1, 0, 1, 1,-1, 1/
      DATA (NHEL(I,  63),I=1,7) /-1,-1, 0, 1, 1, 1,-1/
      DATA (NHEL(I,  64),I=1,7) /-1,-1, 0, 1, 1, 1, 1/
      DATA IDEN/144/

      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      COMMON/BORN_BEAM_POL/POLARIZATIONS
      DATA ((POLARIZATIONS(I,J),I=0,NEXTERNAL),J=0,5)/NPOLENTRIES*-1/

C     
C     FUNCTIONS
C     
      LOGICAL IS_BORN_HEL_SELECTED
      INTEGER BROKEN_SYM
C     ----------
C     Check if helreset mode is on
C     ---------
      IF (HELRESET) THEN
        NTRY = 0
        DO I=1,NCOMB
          GOODHEL(I) = .FALSE.
        ENDDO
        HELRESET = .FALSE.
      ENDIF

C     ----------
C     BEGIN CODE
C     ----------
      IF(USERHEL.EQ.-1) NTRY=NTRY+1
C     When spin-2 particles are involved, the Helicity filtering is
C      dangerous for the 2->1 topology.
C     This is because depending on the MC setup the initial PS points
C      have back-to-back initial states
C     for which some of the spin-2 helicity configurations are zero.
C      But they are no longer zero
C     if the point is boosted on the z-axis. Remember that HELAS
C      helicity amplitudes are no longer
C     lorentz invariant with expternal spin-2 particles (only the
C      helicity sum is).
C     For this reason, we simply remove the filterin when there is
C      only three external particles.
      IF (NEXTERNAL.LE.3) THEN
        DO IHEL=1,NCOMB
          GOODHEL(IHEL)=.TRUE.
        ENDDO
      ENDIF
      ANS = 0D0
      DO IHEL=1,NCOMB
        IF (USERHEL.EQ.-1.OR.USERHEL.EQ.IHEL) THEN
          IF (GOODHEL(IHEL) .OR. NTRY .LT. 20.OR.USERHEL.NE.-1) THEN
            IF(NTRY.GE.2.AND.POLARIZATIONS(0,0).NE.
     $       -1.AND.(.NOT.IS_BORN_HEL_SELECTED(IHEL))) THEN
              CYCLE
            ENDIF
            T=MATRIX(P ,NHEL(1,IHEL),FLAVOR(1))
            IF(POLARIZATIONS(0,0).EQ.-1.OR.IS_BORN_HEL_SELECTED(IHEL))
     $        THEN
              ANS=ANS+T
            ENDIF
            IF (T .NE. 0D0 .AND. .NOT.    GOODHEL(IHEL)) THEN
              GOODHEL(IHEL)=.TRUE.
            ENDIF
          ENDIF
        ENDIF
      ENDDO
      ANS=ANS/DBLE(IDEN)*BROKEN_SYM(FLAVOR)
      IF(USERHEL.NE.-1) THEN
        ANS=ANS*HELAVGFACTOR
      ELSE
        DO J=1,NINITIAL
          IF (POLARIZATIONS(J,0).NE.-1) THEN
            ANS=ANS*BEAMS_HELAVGFACTOR(J)
            ANS=ANS/POLARIZATIONS(J,0)
          ENDIF
        ENDDO
      ENDIF
      END


      REAL*8 FUNCTION MATRIX(P,NHEL,FLAVOR)
      USE MODEL_OBJECT
C     
C     Generated by MadGraph5_aMC@NLO v. 3.7.1, 2026-04-29
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared -- no average over initial
C      state/symmetry factor
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: _quark _quark > h _quark _quark g g WEIGHTED<=8 @1
C     
      USE ALOHA_OBJECT
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=144)
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=7)
      INTEGER    NWAVEFUNCS, NCOLOR
      PARAMETER (NWAVEFUNCS=47, NCOLOR=12)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL)
      INTEGER FLAVOR(NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J
      COMPLEX*16 ZTEMP
      INTEGER CF_INDEX
      INTEGER CF(NCOLOR*(NCOLOR+1)/2)
      INTEGER DENOM
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR), TMP_JAMP(20)
      TYPE(ALOHA) W(NWAVEFUNCS)
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
      DOUBLE PRECISION BWCUTOFF
C     
C     GLOBAL VARIABLES
C     
      INCLUDE 'coupl.inc'

C     
C     COLOR DATA
C     
      DATA DENOM/3/
      DATA (CF(I),I=  1, 12) /48,-12,32,-4,32,-4,12,12,0,-4,32,0/
C     1 T(4,1) T(6,7,5,2)
      DATA (CF(I),I= 13, 23) /48,-4,32,-4,32,12,12,0,32,-4,0/
C     1 T(4,1) T(7,6,5,2)
      DATA (CF(I),I= 24, 33) /48,-12,12,12,32,-4,-4,0,0,32/
C     1 T(4,2) T(6,7,5,1)
      DATA (CF(I),I= 34, 42) /48,12,12,-4,32,32,0,0,-4/
C     1 T(4,2) T(7,6,5,1)
      DATA (CF(I),I= 43, 50) /48,-12,32,-4,32,0,0,-4/
C     1 T(5,1) T(6,7,4,2)
      DATA (CF(I),I= 51, 57) /48,-4,32,-4,0,0,32/
C     1 T(5,1) T(7,6,4,2)
      DATA (CF(I),I= 58, 63) /48,-12,0,32,-4,0/
C     1 T(5,2) T(6,7,4,1)
      DATA (CF(I),I= 64, 68) /48,0,-4,32,0/
C     1 T(5,2) T(7,6,4,1)
      DATA (CF(I),I= 69, 72) /48,32,32,12/
C     1 T(6,4,1) T(7,5,2)
      DATA (CF(I),I= 73, 75) /48,12,32/
C     1 T(6,4,2) T(7,5,1)
      DATA (CF(I),I= 76, 77) /48,32/
C     1 T(6,5,1) T(7,4,2)
      DATA (CF(I),I= 78, 78) /48/
C     1 T(6,5,2) T(7,4,1)
C     ----------
C     BEGIN CODE
C     ----------
      BWCUTOFF=15  ! use if $ syntax is defined in the process
      CALL IXXXXX(P(0,1),ZERO,NHEL(1),+1, FLAVOR(1),W(1))
      CALL IXXXXX(P(0,2),ZERO,NHEL(2),+1, FLAVOR(2),W(2))
      CALL SXXXXX(P(0,3),+1,W(3))
      CALL OXXXXX(P(0,4),ZERO,NHEL(4),+1, FLAVOR(4),W(4))
      CALL OXXXXX(P(0,5),ZERO,NHEL(5),+1, FLAVOR(5),W(5))
      CALL VXXXXX(P(0,6),ZERO,NHEL(6),+1,W(6))
      CALL VXXXXX(P(0,7),ZERO,NHEL(7),+1,W(7))
      CALL FFV6_2M_3(W(1),W(4),FLV_3,FLV_4,MDL_MZ,MDL_WZ,W(8))
      CALL FFV1_2(W(2),W(6),GC_11,ZERO,ZERO,W(9))
      CALL VVS1_SSS1_VSS1_SVS1_1(W(8),W(3),GC_81,GC_68,GC_60,GC_60
     $ ,MDL_MZ,MDL_WZ,W(10))
      CALL FFV1_2(W(9),W(7),GC_11,ZERO,ZERO,W(8))
C     Amplitude(s) for diagram number 1
      CALL FFV6_2M_0(W(8),W(5),W(10),FLV_3,FLV_4,AMP(1))
      CALL FFV2M_3(W(1),W(4),FLV_5,MDL_MW,MDL_WW,W(11))
      CALL VVS1_VSS1_SVS1_SSS1_2(W(11),W(3),GC_72,GC_37,GC_37,GC_68
     $ ,MDL_MW,MDL_WW,W(12))
C     Amplitude(s) for diagram number 2
      CALL FFV2M_0(W(8),W(5),W(12),FLV_6,AMP(2))
      CALL FFV2M_3(W(1),W(4),FLV_6,MDL_MW,MDL_WW,W(11))
      CALL VVS1_VSS1_SVS1_SSS1_1(W(11),W(3),GC_72,GC_37,GC_37,GC_68
     $ ,MDL_MW,MDL_WW,W(13))
C     Amplitude(s) for diagram number 3
      CALL FFV2M_0(W(8),W(5),W(13),FLV_5,AMP(3))
      CALL FFV1_1(W(5),W(7),GC_11,ZERO,ZERO,W(11))
C     Amplitude(s) for diagram number 4
      CALL FFV6_2M_0(W(9),W(11),W(10),FLV_3,FLV_4,AMP(4))
C     Amplitude(s) for diagram number 5
      CALL FFV2M_0(W(9),W(11),W(12),FLV_6,AMP(5))
C     Amplitude(s) for diagram number 6
      CALL FFV2M_0(W(9),W(11),W(13),FLV_5,AMP(6))
      CALL FFV1_2(W(2),W(7),GC_11,ZERO,ZERO,W(14))
      CALL FFV1_2(W(14),W(6),GC_11,ZERO,ZERO,W(15))
C     Amplitude(s) for diagram number 7
      CALL FFV6_2M_0(W(15),W(5),W(10),FLV_3,FLV_4,AMP(7))
C     Amplitude(s) for diagram number 8
      CALL FFV2M_0(W(15),W(5),W(12),FLV_6,AMP(8))
C     Amplitude(s) for diagram number 9
      CALL FFV2M_0(W(15),W(5),W(13),FLV_5,AMP(9))
      CALL FFV1_1(W(5),W(6),GC_11,ZERO,ZERO,W(16))
C     Amplitude(s) for diagram number 10
      CALL FFV6_2M_0(W(14),W(16),W(10),FLV_3,FLV_4,AMP(10))
C     Amplitude(s) for diagram number 11
      CALL FFV2M_0(W(14),W(16),W(12),FLV_6,AMP(11))
C     Amplitude(s) for diagram number 12
      CALL FFV2M_0(W(14),W(16),W(13),FLV_5,AMP(12))
      CALL FFV1_1(W(16),W(7),GC_11,ZERO,ZERO,W(17))
C     Amplitude(s) for diagram number 13
      CALL FFV6_2M_0(W(2),W(17),W(10),FLV_3,FLV_4,AMP(13))
C     Amplitude(s) for diagram number 14
      CALL FFV2M_0(W(2),W(17),W(12),FLV_6,AMP(14))
C     Amplitude(s) for diagram number 15
      CALL FFV2M_0(W(2),W(17),W(13),FLV_5,AMP(15))
      CALL FFV1_1(W(11),W(6),GC_11,ZERO,ZERO,W(18))
C     Amplitude(s) for diagram number 16
      CALL FFV6_2M_0(W(2),W(18),W(10),FLV_3,FLV_4,AMP(16))
C     Amplitude(s) for diagram number 17
      CALL FFV2M_0(W(2),W(18),W(12),FLV_6,AMP(17))
C     Amplitude(s) for diagram number 18
      CALL FFV2M_0(W(2),W(18),W(13),FLV_5,AMP(18))
      CALL VVV1P0_1(W(6),W(7),GC_10,ZERO,ZERO,W(19))
      CALL FFV1_2(W(2),W(19),GC_11,ZERO,ZERO,W(20))
C     Amplitude(s) for diagram number 19
      CALL FFV6_2M_0(W(20),W(5),W(10),FLV_3,FLV_4,AMP(19))
      CALL FFV1_1(W(5),W(19),GC_11,ZERO,ZERO,W(21))
C     Amplitude(s) for diagram number 20
      CALL FFV6_2M_0(W(2),W(21),W(10),FLV_3,FLV_4,AMP(20))
C     Amplitude(s) for diagram number 21
      CALL FFV2M_0(W(20),W(5),W(12),FLV_6,AMP(21))
C     Amplitude(s) for diagram number 22
      CALL FFV2M_0(W(2),W(21),W(12),FLV_6,AMP(22))
C     Amplitude(s) for diagram number 23
      CALL FFV2M_0(W(20),W(5),W(13),FLV_5,AMP(23))
C     Amplitude(s) for diagram number 24
      CALL FFV2M_0(W(2),W(21),W(13),FLV_5,AMP(24))
      CALL FFV6_2M_3(W(1),W(5),FLV_3,FLV_4,MDL_MZ,MDL_WZ,W(13))
      CALL VVS1_SSS1_VSS1_SVS1_1(W(13),W(3),GC_81,GC_68,GC_60,GC_60
     $ ,MDL_MZ,MDL_WZ,W(12))
C     Amplitude(s) for diagram number 25
      CALL FFV6_2M_0(W(8),W(4),W(12),FLV_3,FLV_4,AMP(25))
      CALL FFV2M_3(W(1),W(5),FLV_5,MDL_MW,MDL_WW,W(13))
      CALL VVS1_VSS1_SVS1_SSS1_2(W(13),W(3),GC_72,GC_37,GC_37,GC_68
     $ ,MDL_MW,MDL_WW,W(10))
C     Amplitude(s) for diagram number 26
      CALL FFV2M_0(W(8),W(4),W(10),FLV_6,AMP(26))
      CALL FFV2M_3(W(1),W(5),FLV_6,MDL_MW,MDL_WW,W(13))
      CALL VVS1_VSS1_SVS1_SSS1_1(W(13),W(3),GC_72,GC_37,GC_37,GC_68
     $ ,MDL_MW,MDL_WW,W(22))
C     Amplitude(s) for diagram number 27
      CALL FFV2M_0(W(8),W(4),W(22),FLV_5,AMP(27))
      CALL FFV1_1(W(4),W(7),GC_11,ZERO,ZERO,W(8))
C     Amplitude(s) for diagram number 28
      CALL FFV6_2M_0(W(9),W(8),W(12),FLV_3,FLV_4,AMP(28))
C     Amplitude(s) for diagram number 29
      CALL FFV2M_0(W(9),W(8),W(10),FLV_6,AMP(29))
C     Amplitude(s) for diagram number 30
      CALL FFV2M_0(W(9),W(8),W(22),FLV_5,AMP(30))
C     Amplitude(s) for diagram number 31
      CALL FFV6_2M_0(W(15),W(4),W(12),FLV_3,FLV_4,AMP(31))
C     Amplitude(s) for diagram number 32
      CALL FFV2M_0(W(15),W(4),W(10),FLV_6,AMP(32))
C     Amplitude(s) for diagram number 33
      CALL FFV2M_0(W(15),W(4),W(22),FLV_5,AMP(33))
      CALL FFV1_1(W(4),W(6),GC_11,ZERO,ZERO,W(15))
C     Amplitude(s) for diagram number 34
      CALL FFV6_2M_0(W(14),W(15),W(12),FLV_3,FLV_4,AMP(34))
C     Amplitude(s) for diagram number 35
      CALL FFV2M_0(W(14),W(15),W(10),FLV_6,AMP(35))
C     Amplitude(s) for diagram number 36
      CALL FFV2M_0(W(14),W(15),W(22),FLV_5,AMP(36))
      CALL FFV1_1(W(15),W(7),GC_11,ZERO,ZERO,W(13))
C     Amplitude(s) for diagram number 37
      CALL FFV6_2M_0(W(2),W(13),W(12),FLV_3,FLV_4,AMP(37))
C     Amplitude(s) for diagram number 38
      CALL FFV2M_0(W(2),W(13),W(10),FLV_6,AMP(38))
C     Amplitude(s) for diagram number 39
      CALL FFV2M_0(W(2),W(13),W(22),FLV_5,AMP(39))
      CALL FFV1_1(W(8),W(6),GC_11,ZERO,ZERO,W(23))
C     Amplitude(s) for diagram number 40
      CALL FFV6_2M_0(W(2),W(23),W(12),FLV_3,FLV_4,AMP(40))
C     Amplitude(s) for diagram number 41
      CALL FFV2M_0(W(2),W(23),W(10),FLV_6,AMP(41))
C     Amplitude(s) for diagram number 42
      CALL FFV2M_0(W(2),W(23),W(22),FLV_5,AMP(42))
C     Amplitude(s) for diagram number 43
      CALL FFV6_2M_0(W(20),W(4),W(12),FLV_3,FLV_4,AMP(43))
      CALL FFV1_1(W(4),W(19),GC_11,ZERO,ZERO,W(24))
C     Amplitude(s) for diagram number 44
      CALL FFV6_2M_0(W(2),W(24),W(12),FLV_3,FLV_4,AMP(44))
C     Amplitude(s) for diagram number 45
      CALL FFV2M_0(W(20),W(4),W(10),FLV_6,AMP(45))
C     Amplitude(s) for diagram number 46
      CALL FFV2M_0(W(2),W(24),W(10),FLV_6,AMP(46))
C     Amplitude(s) for diagram number 47
      CALL FFV2M_0(W(20),W(4),W(22),FLV_5,AMP(47))
C     Amplitude(s) for diagram number 48
      CALL FFV2M_0(W(2),W(24),W(22),FLV_5,AMP(48))
      CALL FFV1_2(W(1),W(6),GC_11,ZERO,ZERO,W(22))
      CALL FFV6_2M_3(W(2),W(4),FLV_3,FLV_4,MDL_MZ,MDL_WZ,W(20))
      CALL FFV1_2(W(22),W(7),GC_11,ZERO,ZERO,W(10))
      CALL VVS1_SSS1_VSS1_SVS1_1(W(20),W(3),GC_81,GC_68,GC_60,GC_60
     $ ,MDL_MZ,MDL_WZ,W(12))
C     Amplitude(s) for diagram number 49
      CALL FFV6_2M_0(W(10),W(5),W(12),FLV_3,FLV_4,AMP(49))
      CALL FFV2M_3(W(2),W(4),FLV_5,MDL_MW,MDL_WW,W(25))
      CALL VVS1_VSS1_SVS1_SSS1_2(W(25),W(3),GC_72,GC_37,GC_37,GC_68
     $ ,MDL_MW,MDL_WW,W(26))
C     Amplitude(s) for diagram number 50
      CALL FFV2M_0(W(10),W(5),W(26),FLV_6,AMP(50))
      CALL FFV2M_3(W(2),W(4),FLV_6,MDL_MW,MDL_WW,W(27))
      CALL VVS1_VSS1_SVS1_SSS1_1(W(27),W(3),GC_72,GC_37,GC_37,GC_68
     $ ,MDL_MW,MDL_WW,W(28))
C     Amplitude(s) for diagram number 51
      CALL FFV2M_0(W(10),W(5),W(28),FLV_5,AMP(51))
      CALL FFV6_2M_3(W(22),W(11),FLV_3,FLV_4,MDL_MZ,MDL_WZ,W(29))
C     Amplitude(s) for diagram number 52
      CALL VVS1_SSS1_VSS1_SVS1_0(W(20),W(29),W(3),GC_81,GC_68,GC_60
     $ ,GC_60,AMP(52))
      CALL FFV2M_3(W(22),W(11),FLV_6,MDL_MW,MDL_WW,W(29))
C     Amplitude(s) for diagram number 53
      CALL VVS1_VSS1_SVS1_SSS1_0(W(25),W(29),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(53))
      CALL FFV2M_3(W(22),W(11),FLV_5,MDL_MW,MDL_WW,W(29))
C     Amplitude(s) for diagram number 54
      CALL VVS1_VSS1_SVS1_SSS1_0(W(29),W(27),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(54))
      CALL FFV6_2M_3(W(2),W(5),FLV_3,FLV_4,MDL_MZ,MDL_WZ,W(29))
      CALL VVS1_SSS1_VSS1_SVS1_1(W(29),W(3),GC_81,GC_68,GC_60,GC_60
     $ ,MDL_MZ,MDL_WZ,W(30))
C     Amplitude(s) for diagram number 55
      CALL FFV6_2M_0(W(10),W(4),W(30),FLV_3,FLV_4,AMP(55))
      CALL FFV2M_3(W(2),W(5),FLV_5,MDL_MW,MDL_WW,W(31))
      CALL VVS1_VSS1_SVS1_SSS1_2(W(31),W(3),GC_72,GC_37,GC_37,GC_68
     $ ,MDL_MW,MDL_WW,W(32))
C     Amplitude(s) for diagram number 56
      CALL FFV2M_0(W(10),W(4),W(32),FLV_6,AMP(56))
      CALL FFV2M_3(W(2),W(5),FLV_6,MDL_MW,MDL_WW,W(33))
      CALL VVS1_VSS1_SVS1_SSS1_1(W(33),W(3),GC_72,GC_37,GC_37,GC_68
     $ ,MDL_MW,MDL_WW,W(34))
C     Amplitude(s) for diagram number 57
      CALL FFV2M_0(W(10),W(4),W(34),FLV_5,AMP(57))
      CALL FFV6_2M_3(W(22),W(8),FLV_3,FLV_4,MDL_MZ,MDL_WZ,W(10))
C     Amplitude(s) for diagram number 58
      CALL VVS1_SSS1_VSS1_SVS1_0(W(29),W(10),W(3),GC_81,GC_68,GC_60
     $ ,GC_60,AMP(58))
      CALL FFV2M_3(W(22),W(8),FLV_6,MDL_MW,MDL_WW,W(10))
C     Amplitude(s) for diagram number 59
      CALL VVS1_VSS1_SVS1_SSS1_0(W(31),W(10),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(59))
      CALL FFV2M_3(W(22),W(8),FLV_5,MDL_MW,MDL_WW,W(10))
C     Amplitude(s) for diagram number 60
      CALL VVS1_VSS1_SVS1_SSS1_0(W(10),W(33),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(60))
      CALL FFV6_2M_3(W(22),W(4),FLV_3,FLV_4,MDL_MZ,MDL_WZ,W(10))
      CALL FFV6_2M_3(W(14),W(5),FLV_3,FLV_4,MDL_MZ,MDL_WZ,W(35))
C     Amplitude(s) for diagram number 61
      CALL VVS1_SSS1_VSS1_SVS1_0(W(10),W(35),W(3),GC_81,GC_68,GC_60
     $ ,GC_60,AMP(61))
      CALL FFV2M_3(W(22),W(4),FLV_5,MDL_MW,MDL_WW,W(36))
      CALL FFV2M_3(W(14),W(5),FLV_6,MDL_MW,MDL_WW,W(37))
C     Amplitude(s) for diagram number 62
      CALL VVS1_VSS1_SVS1_SSS1_0(W(36),W(37),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(62))
      CALL FFV2M_3(W(22),W(4),FLV_6,MDL_MW,MDL_WW,W(38))
      CALL FFV2M_3(W(14),W(5),FLV_5,MDL_MW,MDL_WW,W(39))
C     Amplitude(s) for diagram number 63
      CALL VVS1_VSS1_SVS1_SSS1_0(W(39),W(38),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(63))
      CALL FFV6_2M_3(W(22),W(5),FLV_3,FLV_4,MDL_MZ,MDL_WZ,W(40))
      CALL FFV6_2M_3(W(14),W(4),FLV_3,FLV_4,MDL_MZ,MDL_WZ,W(41))
C     Amplitude(s) for diagram number 64
      CALL VVS1_SSS1_VSS1_SVS1_0(W(40),W(41),W(3),GC_81,GC_68,GC_60
     $ ,GC_60,AMP(64))
      CALL FFV2M_3(W(22),W(5),FLV_5,MDL_MW,MDL_WW,W(42))
      CALL FFV2M_3(W(14),W(4),FLV_6,MDL_MW,MDL_WW,W(43))
C     Amplitude(s) for diagram number 65
      CALL VVS1_VSS1_SVS1_SSS1_0(W(42),W(43),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(65))
      CALL FFV2M_3(W(22),W(5),FLV_6,MDL_MW,MDL_WW,W(44))
      CALL FFV2M_3(W(14),W(4),FLV_5,MDL_MW,MDL_WW,W(22))
C     Amplitude(s) for diagram number 66
      CALL VVS1_VSS1_SVS1_SSS1_0(W(22),W(44),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(66))
      CALL FFV6_2M_3(W(2),W(8),FLV_3,FLV_4,MDL_MZ,MDL_WZ,W(14))
C     Amplitude(s) for diagram number 67
      CALL VVS1_SSS1_VSS1_SVS1_0(W(40),W(14),W(3),GC_81,GC_68,GC_60
     $ ,GC_60,AMP(67))
      CALL FFV2M_3(W(2),W(8),FLV_6,MDL_MW,MDL_WW,W(40))
C     Amplitude(s) for diagram number 68
      CALL VVS1_VSS1_SVS1_SSS1_0(W(42),W(40),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(68))
      CALL FFV2M_3(W(2),W(8),FLV_5,MDL_MW,MDL_WW,W(42))
C     Amplitude(s) for diagram number 69
      CALL VVS1_VSS1_SVS1_SSS1_0(W(42),W(44),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(69))
      CALL FFV6_2M_3(W(2),W(11),FLV_3,FLV_4,MDL_MZ,MDL_WZ,W(44))
C     Amplitude(s) for diagram number 70
      CALL VVS1_SSS1_VSS1_SVS1_0(W(10),W(44),W(3),GC_81,GC_68,GC_60
     $ ,GC_60,AMP(70))
      CALL FFV2M_3(W(2),W(11),FLV_6,MDL_MW,MDL_WW,W(10))
C     Amplitude(s) for diagram number 71
      CALL VVS1_VSS1_SVS1_SSS1_0(W(36),W(10),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(71))
      CALL FFV2M_3(W(2),W(11),FLV_5,MDL_MW,MDL_WW,W(36))
C     Amplitude(s) for diagram number 72
      CALL VVS1_VSS1_SVS1_SSS1_0(W(36),W(38),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(72))
      CALL FFV1_2(W(1),W(7),GC_11,ZERO,ZERO,W(38))
      CALL FFV1_2(W(38),W(6),GC_11,ZERO,ZERO,W(7))
C     Amplitude(s) for diagram number 73
      CALL FFV6_2M_0(W(7),W(5),W(12),FLV_3,FLV_4,AMP(73))
C     Amplitude(s) for diagram number 74
      CALL FFV2M_0(W(7),W(5),W(26),FLV_6,AMP(74))
C     Amplitude(s) for diagram number 75
      CALL FFV2M_0(W(7),W(5),W(28),FLV_5,AMP(75))
      CALL FFV6_2M_3(W(38),W(16),FLV_3,FLV_4,MDL_MZ,MDL_WZ,W(6))
C     Amplitude(s) for diagram number 76
      CALL VVS1_SSS1_VSS1_SVS1_0(W(20),W(6),W(3),GC_81,GC_68,GC_60
     $ ,GC_60,AMP(76))
      CALL FFV2M_3(W(38),W(16),FLV_6,MDL_MW,MDL_WW,W(6))
C     Amplitude(s) for diagram number 77
      CALL VVS1_VSS1_SVS1_SSS1_0(W(25),W(6),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(77))
      CALL FFV2M_3(W(38),W(16),FLV_5,MDL_MW,MDL_WW,W(6))
C     Amplitude(s) for diagram number 78
      CALL VVS1_VSS1_SVS1_SSS1_0(W(6),W(27),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(78))
C     Amplitude(s) for diagram number 79
      CALL FFV6_2M_0(W(7),W(4),W(30),FLV_3,FLV_4,AMP(79))
C     Amplitude(s) for diagram number 80
      CALL FFV2M_0(W(7),W(4),W(32),FLV_6,AMP(80))
C     Amplitude(s) for diagram number 81
      CALL FFV2M_0(W(7),W(4),W(34),FLV_5,AMP(81))
      CALL FFV6_2M_3(W(38),W(15),FLV_3,FLV_4,MDL_MZ,MDL_WZ,W(7))
C     Amplitude(s) for diagram number 82
      CALL VVS1_SSS1_VSS1_SVS1_0(W(29),W(7),W(3),GC_81,GC_68,GC_60
     $ ,GC_60,AMP(82))
      CALL FFV2M_3(W(38),W(15),FLV_6,MDL_MW,MDL_WW,W(7))
C     Amplitude(s) for diagram number 83
      CALL VVS1_VSS1_SVS1_SSS1_0(W(31),W(7),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(83))
      CALL FFV2M_3(W(38),W(15),FLV_5,MDL_MW,MDL_WW,W(7))
C     Amplitude(s) for diagram number 84
      CALL VVS1_VSS1_SVS1_SSS1_0(W(7),W(33),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(84))
      CALL FFV6_2M_3(W(38),W(4),FLV_3,FLV_4,MDL_MZ,MDL_WZ,W(7))
      CALL FFV6_2M_3(W(9),W(5),FLV_3,FLV_4,MDL_MZ,MDL_WZ,W(33))
C     Amplitude(s) for diagram number 85
      CALL VVS1_SSS1_VSS1_SVS1_0(W(7),W(33),W(3),GC_81,GC_68,GC_60
     $ ,GC_60,AMP(85))
      CALL FFV2M_3(W(38),W(4),FLV_5,MDL_MW,MDL_WW,W(31))
      CALL FFV2M_3(W(9),W(5),FLV_6,MDL_MW,MDL_WW,W(29))
C     Amplitude(s) for diagram number 86
      CALL VVS1_VSS1_SVS1_SSS1_0(W(31),W(29),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(86))
      CALL FFV2M_3(W(38),W(4),FLV_6,MDL_MW,MDL_WW,W(6))
      CALL FFV2M_3(W(9),W(5),FLV_5,MDL_MW,MDL_WW,W(27))
C     Amplitude(s) for diagram number 87
      CALL VVS1_VSS1_SVS1_SSS1_0(W(27),W(6),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(87))
      CALL FFV6_2M_3(W(38),W(5),FLV_3,FLV_4,MDL_MZ,MDL_WZ,W(25))
      CALL FFV6_2M_3(W(9),W(4),FLV_3,FLV_4,MDL_MZ,MDL_WZ,W(20))
C     Amplitude(s) for diagram number 88
      CALL VVS1_SSS1_VSS1_SVS1_0(W(25),W(20),W(3),GC_81,GC_68,GC_60
     $ ,GC_60,AMP(88))
      CALL FFV2M_3(W(38),W(5),FLV_5,MDL_MW,MDL_WW,W(45))
      CALL FFV2M_3(W(9),W(4),FLV_6,MDL_MW,MDL_WW,W(46))
C     Amplitude(s) for diagram number 89
      CALL VVS1_VSS1_SVS1_SSS1_0(W(45),W(46),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(89))
      CALL FFV2M_3(W(38),W(5),FLV_6,MDL_MW,MDL_WW,W(47))
      CALL FFV2M_3(W(9),W(4),FLV_5,MDL_MW,MDL_WW,W(38))
C     Amplitude(s) for diagram number 90
      CALL VVS1_VSS1_SVS1_SSS1_0(W(38),W(47),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(90))
      CALL FFV6_2M_3(W(2),W(15),FLV_3,FLV_4,MDL_MZ,MDL_WZ,W(9))
C     Amplitude(s) for diagram number 91
      CALL VVS1_SSS1_VSS1_SVS1_0(W(25),W(9),W(3),GC_81,GC_68,GC_60
     $ ,GC_60,AMP(91))
      CALL FFV2M_3(W(2),W(15),FLV_6,MDL_MW,MDL_WW,W(25))
C     Amplitude(s) for diagram number 92
      CALL VVS1_VSS1_SVS1_SSS1_0(W(45),W(25),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(92))
      CALL FFV2M_3(W(2),W(15),FLV_5,MDL_MW,MDL_WW,W(45))
C     Amplitude(s) for diagram number 93
      CALL VVS1_VSS1_SVS1_SSS1_0(W(45),W(47),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(93))
      CALL FFV6_2M_3(W(2),W(16),FLV_3,FLV_4,MDL_MZ,MDL_WZ,W(47))
C     Amplitude(s) for diagram number 94
      CALL VVS1_SSS1_VSS1_SVS1_0(W(7),W(47),W(3),GC_81,GC_68,GC_60
     $ ,GC_60,AMP(94))
      CALL FFV2M_3(W(2),W(16),FLV_6,MDL_MW,MDL_WW,W(7))
C     Amplitude(s) for diagram number 95
      CALL VVS1_VSS1_SVS1_SSS1_0(W(31),W(7),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(95))
      CALL FFV2M_3(W(2),W(16),FLV_5,MDL_MW,MDL_WW,W(31))
C     Amplitude(s) for diagram number 96
      CALL VVS1_VSS1_SVS1_SSS1_0(W(31),W(6),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(96))
C     Amplitude(s) for diagram number 97
      CALL FFV6_2M_0(W(1),W(17),W(12),FLV_3,FLV_4,AMP(97))
C     Amplitude(s) for diagram number 98
      CALL FFV2M_0(W(1),W(17),W(26),FLV_6,AMP(98))
C     Amplitude(s) for diagram number 99
      CALL FFV2M_0(W(1),W(17),W(28),FLV_5,AMP(99))
C     Amplitude(s) for diagram number 100
      CALL FFV6_2M_0(W(1),W(18),W(12),FLV_3,FLV_4,AMP(100))
C     Amplitude(s) for diagram number 101
      CALL FFV2M_0(W(1),W(18),W(26),FLV_6,AMP(101))
C     Amplitude(s) for diagram number 102
      CALL FFV2M_0(W(1),W(18),W(28),FLV_5,AMP(102))
      CALL FFV1_2(W(1),W(19),GC_11,ZERO,ZERO,W(18))
C     Amplitude(s) for diagram number 103
      CALL FFV6_2M_0(W(18),W(5),W(12),FLV_3,FLV_4,AMP(103))
C     Amplitude(s) for diagram number 104
      CALL FFV6_2M_0(W(1),W(21),W(12),FLV_3,FLV_4,AMP(104))
C     Amplitude(s) for diagram number 105
      CALL FFV2M_0(W(18),W(5),W(26),FLV_6,AMP(105))
C     Amplitude(s) for diagram number 106
      CALL FFV2M_0(W(1),W(21),W(26),FLV_6,AMP(106))
C     Amplitude(s) for diagram number 107
      CALL FFV2M_0(W(18),W(5),W(28),FLV_5,AMP(107))
C     Amplitude(s) for diagram number 108
      CALL FFV2M_0(W(1),W(21),W(28),FLV_5,AMP(108))
C     Amplitude(s) for diagram number 109
      CALL FFV6_2M_0(W(1),W(13),W(30),FLV_3,FLV_4,AMP(109))
C     Amplitude(s) for diagram number 110
      CALL FFV2M_0(W(1),W(13),W(32),FLV_6,AMP(110))
C     Amplitude(s) for diagram number 111
      CALL FFV2M_0(W(1),W(13),W(34),FLV_5,AMP(111))
C     Amplitude(s) for diagram number 112
      CALL FFV6_2M_0(W(1),W(23),W(30),FLV_3,FLV_4,AMP(112))
C     Amplitude(s) for diagram number 113
      CALL FFV2M_0(W(1),W(23),W(32),FLV_6,AMP(113))
C     Amplitude(s) for diagram number 114
      CALL FFV2M_0(W(1),W(23),W(34),FLV_5,AMP(114))
C     Amplitude(s) for diagram number 115
      CALL FFV6_2M_0(W(18),W(4),W(30),FLV_3,FLV_4,AMP(115))
C     Amplitude(s) for diagram number 116
      CALL FFV6_2M_0(W(1),W(24),W(30),FLV_3,FLV_4,AMP(116))
C     Amplitude(s) for diagram number 117
      CALL FFV2M_0(W(18),W(4),W(32),FLV_6,AMP(117))
C     Amplitude(s) for diagram number 118
      CALL FFV2M_0(W(1),W(24),W(32),FLV_6,AMP(118))
C     Amplitude(s) for diagram number 119
      CALL FFV2M_0(W(18),W(4),W(34),FLV_5,AMP(119))
C     Amplitude(s) for diagram number 120
      CALL FFV2M_0(W(1),W(24),W(34),FLV_5,AMP(120))
      CALL FFV6_2M_3(W(1),W(8),FLV_3,FLV_4,MDL_MZ,MDL_WZ,W(34))
C     Amplitude(s) for diagram number 121
      CALL VVS1_SSS1_VSS1_SVS1_0(W(34),W(33),W(3),GC_81,GC_68,GC_60
     $ ,GC_60,AMP(121))
      CALL FFV2M_3(W(1),W(8),FLV_5,MDL_MW,MDL_WW,W(33))
C     Amplitude(s) for diagram number 122
      CALL VVS1_VSS1_SVS1_SSS1_0(W(33),W(29),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(122))
      CALL FFV2M_3(W(1),W(8),FLV_6,MDL_MW,MDL_WW,W(29))
C     Amplitude(s) for diagram number 123
      CALL VVS1_VSS1_SVS1_SSS1_0(W(27),W(29),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(123))
      CALL FFV6_2M_3(W(1),W(11),FLV_3,FLV_4,MDL_MZ,MDL_WZ,W(27))
C     Amplitude(s) for diagram number 124
      CALL VVS1_SSS1_VSS1_SVS1_0(W(27),W(20),W(3),GC_81,GC_68,GC_60
     $ ,GC_60,AMP(124))
      CALL FFV2M_3(W(1),W(11),FLV_5,MDL_MW,MDL_WW,W(20))
C     Amplitude(s) for diagram number 125
      CALL VVS1_VSS1_SVS1_SSS1_0(W(20),W(46),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(125))
      CALL FFV2M_3(W(1),W(11),FLV_6,MDL_MW,MDL_WW,W(46))
C     Amplitude(s) for diagram number 126
      CALL VVS1_VSS1_SVS1_SSS1_0(W(38),W(46),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(126))
      CALL FFV6_2M_3(W(1),W(15),FLV_3,FLV_4,MDL_MZ,MDL_WZ,W(38))
C     Amplitude(s) for diagram number 127
      CALL VVS1_SSS1_VSS1_SVS1_0(W(38),W(35),W(3),GC_81,GC_68,GC_60
     $ ,GC_60,AMP(127))
      CALL FFV2M_3(W(1),W(15),FLV_5,MDL_MW,MDL_WW,W(35))
C     Amplitude(s) for diagram number 128
      CALL VVS1_VSS1_SVS1_SSS1_0(W(35),W(37),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(128))
      CALL FFV2M_3(W(1),W(15),FLV_6,MDL_MW,MDL_WW,W(37))
C     Amplitude(s) for diagram number 129
      CALL VVS1_VSS1_SVS1_SSS1_0(W(39),W(37),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(129))
      CALL FFV6_2M_3(W(1),W(16),FLV_3,FLV_4,MDL_MZ,MDL_WZ,W(39))
C     Amplitude(s) for diagram number 130
      CALL VVS1_SSS1_VSS1_SVS1_0(W(39),W(41),W(3),GC_81,GC_68,GC_60
     $ ,GC_60,AMP(130))
      CALL FFV2M_3(W(1),W(16),FLV_5,MDL_MW,MDL_WW,W(41))
C     Amplitude(s) for diagram number 131
      CALL VVS1_VSS1_SVS1_SSS1_0(W(41),W(43),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(131))
      CALL FFV2M_3(W(1),W(16),FLV_6,MDL_MW,MDL_WW,W(43))
C     Amplitude(s) for diagram number 132
      CALL VVS1_VSS1_SVS1_SSS1_0(W(22),W(43),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(132))
C     Amplitude(s) for diagram number 133
      CALL VVS1_SSS1_VSS1_SVS1_0(W(38),W(44),W(3),GC_81,GC_68,GC_60
     $ ,GC_60,AMP(133))
C     Amplitude(s) for diagram number 134
      CALL VVS1_VSS1_SVS1_SSS1_0(W(35),W(10),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(134))
C     Amplitude(s) for diagram number 135
      CALL VVS1_VSS1_SVS1_SSS1_0(W(36),W(37),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(135))
C     Amplitude(s) for diagram number 136
      CALL VVS1_SSS1_VSS1_SVS1_0(W(27),W(9),W(3),GC_81,GC_68,GC_60
     $ ,GC_60,AMP(136))
C     Amplitude(s) for diagram number 137
      CALL VVS1_VSS1_SVS1_SSS1_0(W(20),W(25),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(137))
C     Amplitude(s) for diagram number 138
      CALL VVS1_VSS1_SVS1_SSS1_0(W(45),W(46),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(138))
C     Amplitude(s) for diagram number 139
      CALL VVS1_SSS1_VSS1_SVS1_0(W(34),W(47),W(3),GC_81,GC_68,GC_60
     $ ,GC_60,AMP(139))
C     Amplitude(s) for diagram number 140
      CALL VVS1_VSS1_SVS1_SSS1_0(W(33),W(7),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(140))
C     Amplitude(s) for diagram number 141
      CALL VVS1_VSS1_SVS1_SSS1_0(W(31),W(29),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(141))
C     Amplitude(s) for diagram number 142
      CALL VVS1_SSS1_VSS1_SVS1_0(W(39),W(14),W(3),GC_81,GC_68,GC_60
     $ ,GC_60,AMP(142))
C     Amplitude(s) for diagram number 143
      CALL VVS1_VSS1_SVS1_SSS1_0(W(41),W(40),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(143))
C     Amplitude(s) for diagram number 144
      CALL VVS1_VSS1_SVS1_SSS1_0(W(42),W(43),W(3),GC_72,GC_37,GC_37
     $ ,GC_68,AMP(144))
      TMP_JAMP(12) = AMP(119) +  AMP(120)  ! used 2 times
      TMP_JAMP(11) = AMP(117) +  AMP(118)  ! used 2 times
      TMP_JAMP(10) = AMP(115) +  AMP(116)  ! used 2 times
      TMP_JAMP(9) = AMP(47) +  AMP(48)  ! used 2 times
      TMP_JAMP(8) = AMP(45) +  AMP(46)  ! used 2 times
      TMP_JAMP(7) = AMP(43) +  AMP(44)  ! used 2 times
      TMP_JAMP(6) = AMP(107) +  AMP(108)  ! used 2 times
      TMP_JAMP(5) = AMP(105) +  AMP(106)  ! used 2 times
      TMP_JAMP(4) = AMP(103) +  AMP(104)  ! used 2 times
      TMP_JAMP(3) = AMP(23) +  AMP(24)  ! used 2 times
      TMP_JAMP(2) = AMP(21) +  AMP(22)  ! used 2 times
      TMP_JAMP(1) = AMP(19) +  AMP(20)  ! used 2 times
      TMP_JAMP(16) = TMP_JAMP(11) +  TMP_JAMP(10)  ! used 2 times
      TMP_JAMP(15) = TMP_JAMP(8) +  TMP_JAMP(7)  ! used 2 times
      TMP_JAMP(14) = TMP_JAMP(5) +  TMP_JAMP(4)  ! used 2 times
      TMP_JAMP(13) = TMP_JAMP(2) +  TMP_JAMP(1)  ! used 2 times
      TMP_JAMP(20) = TMP_JAMP(16) +  TMP_JAMP(12)  ! used 2 times
      TMP_JAMP(19) = TMP_JAMP(15) +  TMP_JAMP(9)  ! used 2 times
      TMP_JAMP(18) = TMP_JAMP(14) +  TMP_JAMP(6)  ! used 2 times
      TMP_JAMP(17) = TMP_JAMP(13) +  TMP_JAMP(3)  ! used 2 times
      JAMP(1) = (-1.000000000000000D+00)*AMP(7)+(-1.000000000000000D
     $ +00)*AMP(8)+(-1.000000000000000D+00)*AMP(9)+(
     $ -1.000000000000000D+00)*AMP(10)+(-1.000000000000000D+00)*AMP(11)
     $ +(-1.000000000000000D+00)*AMP(12)+(-1.000000000000000D+00)
     $ *AMP(13)+(-1.000000000000000D+00)*AMP(14)+(-1.000000000000000D
     $ +00)*AMP(15)+((0.000000000000000D+00,1.000000000000000D+00))
     $ *TMP_JAMP(17)
      JAMP(2) = (-1.000000000000000D+00)*AMP(1)+(-1.000000000000000D
     $ +00)*AMP(2)+(-1.000000000000000D+00)*AMP(3)+(
     $ -1.000000000000000D+00)*AMP(4)+(-1.000000000000000D+00)*AMP(5)
     $ +(-1.000000000000000D+00)*AMP(6)+(-1.000000000000000D+00)
     $ *AMP(16)+(-1.000000000000000D+00)*AMP(17)+(-1.000000000000000D
     $ +00)*AMP(18)+((0.000000000000000D+00,-1.000000000000000D+00))
     $ *TMP_JAMP(17)
      JAMP(3) = AMP(73)+AMP(74)+AMP(75)+AMP(76)+AMP(77)+AMP(78)+AMP(97)
     $ +AMP(98)+AMP(99)+((0.000000000000000D+00,-1.000000000000000D+00)
     $ )*TMP_JAMP(18)
      JAMP(4) = AMP(49)+AMP(50)+AMP(51)+AMP(52)+AMP(53)+AMP(54)
     $ +AMP(100)+AMP(101)+AMP(102)+((0.000000000000000D+00
     $ ,1.000000000000000D+00))*TMP_JAMP(18)
      JAMP(5) = AMP(31)+AMP(32)+AMP(33)+AMP(34)+AMP(35)+AMP(36)+AMP(37)
     $ +AMP(38)+AMP(39)+((0.000000000000000D+00,-1.000000000000000D+00)
     $ )*TMP_JAMP(19)
      JAMP(6) = AMP(25)+AMP(26)+AMP(27)+AMP(28)+AMP(29)+AMP(30)+AMP(40)
     $ +AMP(41)+AMP(42)+((0.000000000000000D+00,1.000000000000000D+00))
     $ *TMP_JAMP(19)
      JAMP(7) = (-1.000000000000000D+00)*AMP(79)+(-1.000000000000000D
     $ +00)*AMP(80)+(-1.000000000000000D+00)*AMP(81)+(
     $ -1.000000000000000D+00)*AMP(82)+(-1.000000000000000D+00)*AMP(83)
     $ +(-1.000000000000000D+00)*AMP(84)+(-1.000000000000000D+00)
     $ *AMP(109)+(-1.000000000000000D+00)*AMP(110)+(
     $ -1.000000000000000D+00)*AMP(111)+((0.000000000000000D+00
     $ ,1.000000000000000D+00))*TMP_JAMP(20)
      JAMP(8) = (-1.000000000000000D+00)*AMP(55)+(-1.000000000000000D
     $ +00)*AMP(56)+(-1.000000000000000D+00)*AMP(57)+(
     $ -1.000000000000000D+00)*AMP(58)+(-1.000000000000000D+00)*AMP(59)
     $ +(-1.000000000000000D+00)*AMP(60)+(-1.000000000000000D+00)
     $ *AMP(112)+(-1.000000000000000D+00)*AMP(113)+(
     $ -1.000000000000000D+00)*AMP(114)+((0.000000000000000D+00,
     $ -1.000000000000000D+00))*TMP_JAMP(20)
      JAMP(9) = (-1.000000000000000D+00)*AMP(61)+(-1.000000000000000D
     $ +00)*AMP(62)+(-1.000000000000000D+00)*AMP(63)+(
     $ -1.000000000000000D+00)*AMP(70)+(-1.000000000000000D+00)*AMP(71)
     $ +(-1.000000000000000D+00)*AMP(72)+(-1.000000000000000D+00)
     $ *AMP(127)+(-1.000000000000000D+00)*AMP(128)+(
     $ -1.000000000000000D+00)*AMP(129)+(-1.000000000000000D+00)
     $ *AMP(133)+(-1.000000000000000D+00)*AMP(134)+(
     $ -1.000000000000000D+00)*AMP(135)
      JAMP(10) = AMP(88)+AMP(89)+AMP(90)+AMP(91)+AMP(92)+AMP(93)
     $ +AMP(124)+AMP(125)+AMP(126)+AMP(136)+AMP(137)+AMP(138)
      JAMP(11) = AMP(64)+AMP(65)+AMP(66)+AMP(67)+AMP(68)+AMP(69)
     $ +AMP(130)+AMP(131)+AMP(132)+AMP(142)+AMP(143)+AMP(144)
      JAMP(12) = (-1.000000000000000D+00)*AMP(85)+(-1.000000000000000D
     $ +00)*AMP(86)+(-1.000000000000000D+00)*AMP(87)+(
     $ -1.000000000000000D+00)*AMP(94)+(-1.000000000000000D+00)*AMP(95)
     $ +(-1.000000000000000D+00)*AMP(96)+(-1.000000000000000D+00)
     $ *AMP(121)+(-1.000000000000000D+00)*AMP(122)+(
     $ -1.000000000000000D+00)*AMP(123)+(-1.000000000000000D+00)
     $ *AMP(139)+(-1.000000000000000D+00)*AMP(140)+(
     $ -1.000000000000000D+00)*AMP(141)

      MATRIX = 0.D0
      CF_INDEX = 0
      DO I = 1, NCOLOR
        ZTEMP = (0D0,0D0)
        DO J = I, NCOLOR
          CF_INDEX = CF_INDEX +1
          ZTEMP = ZTEMP + CF(CF_INDEX)*JAMP(J)
        ENDDO
        MATRIX = MATRIX+REAL(ZTEMP*DCONJG(JAMP(I)))
      ENDDO
      MATRIX = MATRIX / DENOM

      END

      SUBROUTINE GET_VALUE(P, ALPHAS, NHEL, FLAVOR ,ANS)
C     This routine is the f2py interface for GET_value_internal which
C      can not be in the interface
C     due to f2py not knowing how to handle the couplings common block
      USE MODEL_OBJECT
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=7)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER NHEL
      DOUBLE PRECISION ALPHAS
      REAL*8 PI
      INTEGER FLAVOR(NEXTERNAL)
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: NHEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
CF2PY INTENT(IN) :: ALPHAS
CF2PY INTENT(IN) :: FLAVOR(NEXTERNAL)
C     ROUTINE FOR F2PY to read the benchmark point.    

      CALL  GET_VALUE_INTERNAL(P, ALPHAS, NHEL, FLAVOR ,ANS)
      RETURN
      END


      SUBROUTINE GET_VALUE_INTERNAL(P, ALPHAS, NHEL, FLAVOR ,ANS)
C     This routine is the real value but can not be in the interface
C     due to f2py not knowing how to handle the couplings common block
      USE MODEL_OBJECT
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=7)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER NHEL
      DOUBLE PRECISION ALPHAS
      REAL*8 PI
      INTEGER FLAVOR(NEXTERNAL)
C     ROUTINE FOR F2PY to read the benchmark point.    
C     the include file with the values of the parameters and masses 
      INCLUDE 'coupl.inc'

      PI = 3.141592653589793D0
      G = 2* DSQRT(ALPHAS*PI)
      CALL UPDATE_AS_PARAM()
      IF (NHEL.NE.0) THEN
        CALL SMATRIXHEL(P, NHEL, FLAVOR, ANS)
      ELSE
        CALL SMATRIX(P, FLAVOR, ANS)
      ENDIF
      RETURN
      END

      SUBROUTINE INITIALISEMODEL(PATH)
C     ROUTINE FOR F2PY to read the benchmark point.    
      IMPLICIT NONE
      CHARACTER*512 PATH
CF2PY INTENT(IN) :: PATH
      CALL SETPARA(PATH)  !first call to setup the paramaters    
      RETURN
      END

      LOGICAL FUNCTION IS_BORN_HEL_SELECTED(HELID)
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=7)
      INTEGER    NCOMB
      PARAMETER (NCOMB=64)
C     
C     ARGUMENTS
C     
      INTEGER HELID
C     
C     LOCALS
C     
      INTEGER I,J
      LOGICAL FOUNDIT
C     
C     GLOBALS
C     
      INTEGER HELC(NEXTERNAL,NCOMB)
      COMMON/PROCESS_NHEL/HELC

      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      COMMON/BORN_BEAM_POL/POLARIZATIONS
C     ----------
C     BEGIN CODE
C     ----------

      IS_BORN_HEL_SELECTED = .TRUE.
      IF (POLARIZATIONS(0,0).EQ.-1) THEN
        RETURN
      ENDIF

      DO I=1,NEXTERNAL
        IF (POLARIZATIONS(I,0).EQ.-1) THEN
          CYCLE
        ENDIF
        FOUNDIT = .FALSE.
        DO J=1,POLARIZATIONS(I,0)
          IF (HELC(I,HELID).EQ.POLARIZATIONS(I,J)) THEN
            FOUNDIT = .TRUE.
            EXIT
          ENDIF
        ENDDO
        IF(.NOT.FOUNDIT) THEN
          IS_BORN_HEL_SELECTED = .FALSE.
          RETURN
        ENDIF
      ENDDO

      RETURN
      END


      INTEGER FUNCTION BROKEN_SYM(FLAV)

      INCLUDE 'nexternal.inc'
      INTEGER FLAV(NEXTERNAL)
      INTEGER PID(NINCOMING+1:NEXTERNAL)
      INTEGER I,J
      INTEGER N_BROK, N_TOT
      INTEGER OLD_FACTOR

      OLD_FACTOR = 4

      PID = [25, 81, 81, 21, 21]
C     get new symmetry factor      
      DO I=NINCOMING+1, NEXTERNAL
        IF (PID(I).EQ.0) CYCLE
        N_TOT=1
        DO J = I+1,NEXTERNAL
          IF (PID(I).EQ.PID(J).AND.FLAV(I).EQ.FLAV(J))THEN
            PID(J) = 0
            N_TOT = N_TOT + 1
            OLD_FACTOR = OLD_FACTOR/N_TOT
          ENDIF
        ENDDO
      ENDDO
      BROKEN_SYM = OLD_FACTOR
      RETURN
      END


