      SUBROUTINE SMATRIX_REAL(P,WGT)
      USE MC_NATIVE_CONTEXT, ONLY: SHARED_REAL_ACTIVE
     $ ,SHARED_REAL_EPOCH,SHARED_REAL_POINT,ACTIVE_HISTORY
     $ ,HISTORY_PERMUTATIONS
      USE MC_BORN_TYPES, ONLY: BORNMODELSTATE,BORN_MODEL_STATE_EQUAL
      IMPLICIT NONE
      INCLUDE 'nexternal.inc'
      INCLUDE 'orders.inc'
      INTEGER,PARAMETER::CACHE_SIZE=16
      LOGICAL,PARAMETER::SHARE_REAL_FRAME(8)=[.TRUE.,.TRUE.,.TRUE.
     $ ,.TRUE.,.TRUE.,.TRUE.,.TRUE.,.TRUE.]
      TYPE REALCACHEENTRY
        INTEGER::EVALUATOR=0
        REAL(8) MOMENTA(0:3,NEXTERNAL),WEIGHT
     $   ,AMPLITUDES(AMP_SPLIT_SIZE)
        TYPE(BORNMODELSTATE) MODEL
        END TYPE
        TYPE(REALCACHEENTRY),SAVE::CACHE(CACHE_SIZE)
        TYPE(BORNMODELSTATE),SAVE::STATE
        INTEGER,SAVE::EPOCH=-1,NEXT_ENTRY=1
        DOUBLE PRECISION P(0:3,NEXTERNAL),Q(0:3,NEXTERNAL),R(0:3
     $   ,NEXTERNAL),WGT
        DOUBLE PRECISION WGT_ME_BORN,WGT_ME_REAL
        COMMON/C_WGT_ME_TREE/WGT_ME_BORN,WGT_ME_REAL
        INTEGER NFKSPROCESS,EVALUATOR,I,J
        COMMON/C_NFKSPROCESS/NFKSPROCESS
        IF(NFKSPROCESS.LT.1.OR.NFKSPROCESS.GT.8)STOP 'Invalid native'
     $   //' real sector'
        R=P
        IF(SHARED_REAL_ACTIVE.AND.SHARE_REAL_FRAME(NFKSPROCESS))THEN
          R=SHARED_REAL_POINT
          IF(ACTIVE_HISTORY.GT.0)THEN
            DO I=1,NEXTERNAL
              R(:,I)=SHARED_REAL_POINT(:,HISTORY_PERMUTATIONS(I
     $         ,ACTIVE_HISTORY))
            ENDDO
          ENDIF
        ENDIF
        SELECT CASE(NFKSPROCESS)
        CASE(1)
        Q=R
        EVALUATOR=1
        CASE(2)
        Q=R
        EVALUATOR=1
        CASE(3)
        Q=R
        EVALUATOR=1
        CASE(4)
        Q=R
        EVALUATOR=1
        CASE(5)
        Q=R
        EVALUATOR=2
        CASE(6)
        Q=R
        EVALUATOR=3
        CASE(7)
        Q(:,1)=R(:,1)
        Q(:,2)=R(:,2)
        Q(:,3)=R(:,3)
        Q(:,4)=R(:,4)
        Q(:,5)=R(:,5)
        EVALUATOR=3
        CASE(8)
        Q(:,1)=R(:,1)
        Q(:,2)=R(:,2)
        Q(:,3)=R(:,3)
        Q(:,4)=R(:,4)
        Q(:,5)=R(:,5)
        EVALUATOR=2
        CASE DEFAULT
        STOP 'Invalid native real sector'
        END SELECT
        IF(SHARED_REAL_ACTIVE)THEN
          IF(EPOCH.NE.SHARED_REAL_EPOCH)THEN
            CACHE%%EVALUATOR=0
            NEXT_ENTRY=1
            EPOCH=SHARED_REAL_EPOCH
          ENDIF
          CALL MC_CAPTURE_MODEL_STATE(STATE)
          DO J=1,CACHE_SIZE
            IF(CACHE(J)%%EVALUATOR.NE.EVALUATOR)CYCLE
            IF(ANY(CACHE(J)%%MOMENTA.NE.Q))CYCLE
            IF(.NOT.BORN_MODEL_STATE_EQUAL(CACHE(J)%%MODEL,STATE))CYCLE
            WGT=CACHE(J)%%WEIGHT
            AMP_SPLIT=CACHE(J)%%AMPLITUDES
            WGT_ME_REAL=WGT
            RETURN
          ENDDO
        ENDIF
        SELECT CASE(EVALUATOR)
        CASE(1)
        CALL SMATRIX1(Q,WGT)
        CASE(2)
        CALL SMATRIX2(Q,WGT)
        CASE(3)
        CALL SMATRIX3(Q,WGT)
        CASE DEFAULT
        STOP 'Invalid local real evaluator'
        END SELECT
        IF(SHARED_REAL_ACTIVE)THEN
          J=NEXT_ENTRY
          CACHE(J)%%EVALUATOR=EVALUATOR
          CACHE(J)%%MOMENTA=Q
          CACHE(J)%%MODEL%%REAL_VALUES=STATE%%REAL_VALUES
          CACHE(J)%%MODEL%%COMPLEX_VALUES=STATE%%COMPLEX_VALUES
          CACHE(J)%%WEIGHT=WGT
          CACHE(J)%%AMPLITUDES=AMP_SPLIT
          NEXT_ENTRY=MOD(NEXT_ENTRY,CACHE_SIZE)+1
        ENDIF
        END
