      DOUBLE PRECISION FUNCTION DLUM()
      IMPLICIT NONE
      INTEGER NFKSPROCESS
      COMMON/C_NFKSPROCESS/NFKSPROCESS
      SELECT CASE(NFKSPROCESS)
      CASE(1)
      CALL DLUM_1(DLUM)
      CASE(2)
      CALL DLUM_1(DLUM)
      CASE(3)
      CALL DLUM_1(DLUM)
      CASE(4)
      CALL DLUM_1(DLUM)
      CASE(5)
      CALL DLUM_2(DLUM)
      CASE(6)
      CALL DLUM_3(DLUM)
      CASE(7)
      CALL DLUM_4(DLUM)
      CASE(8)
      CALL DLUM_5(DLUM)
      CASE(9)
      CALL DLUM_NATIVE_2_2(DLUM)
      CASE(10)
      CALL DLUM_NATIVE_2_3(DLUM)
      CASE(11)
      CALL DLUM_NATIVE_3_2(DLUM)
      CASE(12)
      CALL DLUM_NATIVE_3_3(DLUM)
      CASE DEFAULT
      STOP 'Invalid native PDF sector'
      END SELECT
      CALL MC_FILTER_NATIVE_LUM(DLUM)
      END
