#!/bin/bash
script=ajob1.$1.$2.$3.$4
rm -f wait.$script >& /dev/null
touch run.$script
echo $script
TAGTAGTAGTAGTAGTAGTAG  for i in 1 ; do
    echo $i
    echo $i >& run.$script
    if [[ $1 == '0' || $1 == '1' ]]; then
        j=$2\_G$i
        if [[ ! -e $j ]]; then
            mkdir $j
        fi
        cd $j
        if [[ "$4" != "" ]]; then
            if [[ -e ../$4\_G$i ]]; then
                if [[ $1 == '0' ]]; then
                    cp -f ../$4\_G$i/*.sv1 . >/dev/null 2>&1
                    cp -f ../$4\_G$i/grid.MC_integer . >/dev/null 2>&1
                elif [[ $1 == '1' ]]; then
                    cp -f ../$4\_G$i/mint_grids . >/dev/null 2>&1
                    cp -f ../$4\_G$i/grid.MC_integer . >/dev/null 2>&1
                fi
            else
                echo "Cannot find direcotry ../$4\_G$i/" > log.txt
                exit
            fi
        fi
    elif [[ $1 == '2' ]]; then
        j=G$2$i
        if [[ ! -e $j ]]; then
            mkdir $j
        fi
        cd $j
        if [[ "$4" != "" ]]; then
            if [[ -e ../G$4$i ]]; then
                cp -f ../G$4$i/mint_grids ./preset_mint_grids
                cp -f ../G$4$i/grid.MC_integer . >/dev/null 2>&1
            else
                echo "Cannot find direcotry ../G$4$i/" > log.txt
                exit
            fi
        fi
    fi
    ln -sf ../../randinit .
    ln -sf ../symfact.dat .
    if [[ -e ../MadLoopParams.dat ]]; then
	ln -sf ../MadLoopParams.dat .
    fi
    if [[ -e ../ColorDenomFactors.dat ]]; then
	ln -sf ../ColorDenomFactors.dat .
    fi
    if [[ -e ../HelConfigs.dat ]]; then
	ln -sf ../HelConfigs.dat .
    fi
    if [[ -e ../ColorNumFactors.dat ]]; then
	ln -sf ../ColorNumFactors.dat .
    fi
    if [[ $1 == '0' ]]; then
        head -n 5 ../../madin.$2 >& input_app.txt
        echo $i >> input_app.txt
        tail -n 4 ../../madin.$2 >> input_app.txt
        T="$(date +%s)"
        time ../madevent_vegas > log.txt <input_app.txt
        T="$(($(date +%s)-T))"
        echo "Time in seconds: ${T}" >>log.txt
    elif [[ $1 == '1' ]]; then
        head -n 5 ../../madinM.$2 >& input_app.txt
        echo $i >> input_app.txt
        tail -n 3 ../../madinM.$2 >> input_app.txt
        T="$(date +%s)"
        time ../madevent_mint > log.txt <input_app.txt
        T="$(($(date +%s)-T))"
        echo "Time in seconds: ${T}" >>log.txt
    elif [[ $1 == '2' ]]; then
        if [[ $3 == '0' || $3 == '2' ]]; then
            head -n 6 ../../madinMMC_$2.2 >& input_app.txt
            echo $i >> input_app.txt
            tail -n 3 ../../madinMMC_$2.2 >> input_app.txt
        elif [[ $3 == '1' ]] ; then
            head -n 6 madinM1 >& input_app.txt
            echo $i >> input_app.txt
            tail -n 3 madinM1 >> input_app.txt
        fi
        T="$(date +%s)"
        time ../madevent_mintMC > log.txt <input_app.txt
        T="$(($(date +%s)-T))"
        echo "Time in seconds: ${T}" >>log.txt
        cp -f log.txt log_MINT$3.txt
    fi
    cd ../
done
rm -f run.$script
touch done.$script

