#!/bin/bash
if [ -n "$_CONDOR_SCRATCH_DIR" ]; then
    CONDOR_INITIAL_DIR=`pwd`
    cd $_CONDOR_SCRATCH_DIR
fi
script=mg1.cmd.$1.$2.$4
rm -f $CONDOR_INITIAL_DIR/wait.$script >& /dev/null
touch $CONDOR_INITIAL_DIR/run.$script
mkdir lib
mkdir Cards
mkdir SubProcesses
cp -af  $CONDOR_INITIAL_DIR/../../MGMEVersion.txt .
cp -af  $CONDOR_INITIAL_DIR/../../Cards/* ./Cards/
cp -af  $CONDOR_INITIAL_DIR/../../lib/Pdfdata ./lib/
ln -sf  $CONDOR_INITIAL_DIR/../../lib/PDFsets ./lib/
# Go to the SubProcesses directory
cd SubProcesses
cp -af $CONDOR_INITIAL_DIR/../randinit .
cp -af $CONDOR_INITIAL_DIR/symfact.dat .
cp -af $CONDOR_INITIAL_DIR/iproc.dat .
if [[ -e $CONDOR_INITIAL_DIR/MadLoopParams.dat ]]; then
    cp -af  $CONDOR_INITIAL_DIR/MadLoopParams.dat .
fi
if [[ -e $CONDOR_INITIAL_DIR/ColorDenomFactors.dat ]]; then
    cp -af  $CONDOR_INITIAL_DIR/ColorDenomFactors.dat .
fi
if [[ -e $CONDOR_INITIAL_DIR/ColorNumFactors.dat ]]; then
    cp -af  $CONDOR_INITIAL_DIR/ColorNumFactors.dat .
fi
if [[ -e $CONDOR_INITIAL_DIR/HelConfigs.dat ]]; then
    cp -af  $CONDOR_INITIAL_DIR/HelConfigs.dat .
fi
if [[ $1 == '0' ]]; then
    cp -af  $CONDOR_INITIAL_DIR/madevent_vegas .
elif [[ $1 == '1' ]]; then
    cp -af  $CONDOR_INITIAL_DIR/madevent_mint .
elif [[ $1 == '2' ]]; then
    cp -af  $CONDOR_INITIAL_DIR/madevent_mintMC .
fi
TAGTAGTAGTAGTAGTAGTAG for i in 1 ; do
    echo $i >& $CONDOR_INITIAL_DIR/run.$script
    runnumber=0
    if [[ $1 == '0' || $1 == '1' ]]; then
        j=$2\_G$i
        if [[ ! -e $j ]]; then
            mkdir $j
        fi
        cd $j
        cp -af $CONDOR_INITIAL_DIR/$j/* .
        if [[ "$4" != "" ]]; then
            if [[ -e $CONDOR_INITIAL_DIR/$4\_G$i ]]; then
                if [[ $1 == '0' ]]; then
                    cp -af $CONDOR_INITIAL_DIR/$4\_G$i/*.sv1 . >/dev/null 2>&1
                    cp -af $CONDOR_INITIAL_DIR/$4\_G$i/grid.MC_integer . >/dev/null 2>&1
                elif [[ $1 == '1' ]]; then
                    cp -af $CONDOR_INITIAL_DIR/$4\_G$i/mint_grids . >/dev/null 2>&1
                    cp -af $CONDOR_INITIAL_DIR/$4\_G$i/grid.MC_integer . >/dev/null 2>&1
                fi
            else
                echo "Cannot find direcotry ../$4\_G$i/" > log2.txt
            fi
        fi
    elif [[ $1 == '2' ]]; then
        j=G$2$i
        if [[ ! -e $j ]]; then
            mkdir $j
        fi
        cd $j
        cp -af $CONDOR_INITIAL_DIR/$j/* .
        if [[ "$4" != "" ]]; then
            if [[ "$4" == "H" ||"$4" == "S" || "$4" == "V" || "$4" == "B" || "$4" == "F" ]]; then
                if [[ -e $CONDOR_INITIAL_DIR/G$4$i ]]; then
                    cp -af $CONDOR_INITIAL_DIR/G$4$i/mint_grids ./preset_mint_grids
                    cp -af $CONDOR_INITIAL_DIR/G$4$i/grid.MC_integer . >/dev/null 2>&1
                else
                    echo "Cannot find direcotry ../G$4$i/" > log.txt
                    exit
                fi
            else
                runnumber=$4
            fi
        fi
    fi
    if  [[ ! -e randinit ]] ; then
	ln -sf ../randinit .
    fi
    if  [[ ! -e symfact ]] ; then
	ln -sf ../symfact .
    fi
    if  [[ ! -e MadLoopParams.dat ]] ; then
	ln -sf ../MadLoopParams.dat .
    fi
    if  [[ ! -e ColorDenomFactors.dat ]] ; then
	ln -sf ../ColorDenomFactors.dat .
    fi
    if  [[ ! -e HelConfigs.dat ]] ; then
	ln -sf ../HelConfigs.dat .
    fi
    if  [[ ! -e ColorNumFactors.dat ]] ; then
	ln -sf ../ColorNumFactors.dat .
    fi
    if [[ $1 == '0' ]]; then
        head -n 5 $CONDOR_INITIAL_DIR/../madin.$2 >& input_app.txt
        echo $i >> input_app.txt
        tail -n 4 $CONDOR_INITIAL_DIR/../madin.$2 >> input_app.txt
        T="$(date +%s)"
        time ../madevent_vegas > log.txt <input_app.txt 2>&1
        T="$(($(date +%s)-T))"
        echo "Time in seconds: ${T}" >>log.txt
    elif [[ $1 == '1' ]]; then
        head -n 5 $CONDOR_INITIAL_DIR/../madinM.$2 >& input_app.txt
        echo $i >> input_app.txt
        tail -n 3 $CONDOR_INITIAL_DIR/../madinM.$2 >> input_app.txt
        T="$(date +%s)"
        time ../madevent_mint > log.txt <input_app.txt 2>&1
        T="$(($(date +%s)-T))"
        echo "Time in seconds: ${T}" >>log.txt
    elif [[ $1 == '2' ]]; then
        if [[ $runnumber != 0 ]]; then
            mv -f nevts__$runnumber nevts
            echo "$runnumber" >& moffset.dat
        fi
        if [[ $3 == '0' || $3 == '2' ]]; then
            head -n 6 $CONDOR_INITIAL_DIR/../madinMMC_$2.2 >& input_app.txt
            echo $i >> input_app.txt
            tail -n 4 $CONDOR_INITIAL_DIR/../madinMMC_$2.2 >> input_app.txt
        elif [[ $3 == '1' ]]; then
            head -n 6 madinM1 >& input_app.txt
            echo $i >> input_app.txt
            tail -n 4 madinM1 >> input_app.txt
        fi
        T="$(date +%s)"
        time ../madevent_mintMC > log.txt <input_app.txt 2>&1
        T="$(($(date +%s)-T))"
        echo "Time in seconds: ${T}" >>log.txt
        cp -af log.txt log_MINT$3.txt
    fi
    if [[ $1 == '2' && $runnumber != 0 ]]; then
        cp -af events.lhe $CONDOR_INITIAL_DIR/G$2$i/events_$runnumber.lhe
        cp -af log.txt $CONDOR_INITIAL_DIR/G$2$i/log_MINT$3_$runnumber.txt
    fi
    cd ../
done
if [[ $1 == '0' || $1 == '1' ]]; then
    cp -af $2\_G* $CONDOR_INITIAL_DIR/
elif [[ $1 == '2' && $runnumber == 0 ]]; then
    cp -af G$2* $CONDOR_INITIAL_DIR/

fi
rm -f $CONDOR_INITIAL_DIR/run.$script
touch $CONDOR_INITIAL_DIR/done.$script

