      Program DRIVER
c**************************************************************************
c     This is the driver for the whole calculation
c**************************************************************************
      use extra_weights
      use mint_module
      use FKSParams
      implicit none
C
C     CONSTANTS
C
      double precision zero
      parameter       (ZERO = 0d0)
      include 'nexternal.inc'
      include 'genps.inc'
      integer ncall_virt,ncall_novi
      character*4 abrv
      common /to_abrv/ abrv
C
C     LOCAL
C
      integer i,j,k,l,l1,l2,nndim,nevts

      integer lunlhe
      parameter (lunlhe=98)
c
c     Global
c
cc
      include 'run.inc'
      include 'coupl.inc'
c
c     Properly initialize PY8 controls
c
      include 'pythia8_control.inc'
      include 'pythia8_control_setup.inc'
c Vegas stuff
      common/tosigint/nndim

      real*8 sigintF
      external sigintF

      logical            flat_grid
      common/to_readgrid/flat_grid                !Tells if grid read from file

      integer i_momcmp_count
      double precision xratmax
      common/ccheckcnt/i_momcmp_count,xratmax

      double precision virtual_over_born
      common/c_vob/virtual_over_born
      include 'orders.inc'

      double precision weight,event_weight,inv_bias
      character*7 event_norm
      common /event_normalisation/event_norm
      integer ixi_i,iphi_i,iy_ij,vn
      logical putonshell
      logical unwgt
      double precision evtsgn
      common /c_unwgt/evtsgn,unwgt
      double precision ran2,x(ndimmax)
      external ran2
      
      integer ifile,ievents,ievent
      double precision inter,absint,uncer
      common /to_write_header_init/inter,absint,uncer,ifile,ievents

      logical SHsep
      logical Hevents
      common/SHevents/Hevents
      character*10 dum
      integer iFKS_picked
c statistics for MadLoop      
      integer ntot,nsun,nsps,nups,neps,n100,nddp,nqdp,nini,n10,n1(0:9)
      common/ups_stats/ntot,nsun,nsps,nups,neps,n100,nddp,nqdp,nini,n10,n1

c timing statistics
      include "timing_variables.inc"
      real*4 tOther, tTot
c general MadFKS parameters
      integer ifold_picked
      double precision x_save(ndimmax,max_fold)
      common /c_vegas_x_fold/x_save,ifold_picked
      double precision deravg,derstd,dermax,xi_i_fks_ev_der_max
     &     ,y_ij_fks_ev_der_max
      integer ntot_granny,derntot,ncase(0:6)
      common /c_granny_counters/ ntot_granny,ncase,derntot,deravg,derstd
     &     ,dermax,xi_i_fks_ev_der_max,y_ij_fks_ev_der_max
      integer                     n_MC_subt_diverge
      common/counter_subt_diverge/n_MC_subt_diverge


      character*10 MonteCarlo
      common/cMonteCarloType/MonteCarlo

      integer maxpup
      parameter(maxpup=100)
      integer idbmup(2),pdfgup(2),pdfsup(2),idwtup,nprup,lprup(maxpup)
      double precision ebmup(2),xsecup(maxpup),xerrup(maxpup)
     $     ,xmaxup(maxpup)

      INTEGER MAXNUP
      PARAMETER (MAXNUP=500)
      INTEGER NUP,IDPRUP,IDUP(MAXNUP),ISTUP(MAXNUP),
     # MOTHUP(2,MAXNUP),ICOLUP(2,MAXNUP)
      DOUBLE PRECISION XWGTUP,AQEDUP,AQCDUP,
     # PUP(5,MAXNUP),VTIMUP(MAXNUP),SPINUP(MAXNUP),
     # SCALUP_a(MAXNUP,MAXNUP),SCALUP

      character*1000 buff,buff2
      double precision ratio,showerscale

      logical do_only_Sevents
      common /c_do_only_Sevents/do_only_Sevents

      
C-----
C  BEGIN CODE
C-----

!  WHAT NEEDS TO BE DONE?

!     - MAKE SURE CODE IS SETUP SIMILARLY TO NORMAL MINTMC RUNS SKIP ALL
!     - THE MINT STUFF (we already have the events, no need to do a
!     numerical integration of the complete process)
!     - READ IN AN EVENT. (use the subroutines in handling_lhe_events.f)
!     - GO DIRECTLY TO THE INTEGRAND, TO COMPUTE THE REWEIGHT RATIO.
!     o. What to do with the sum over FKS configurations?
!     o. How to generate the real-emission momenta used in these configurations?
!     o. ...
!     - WRITE OUT THE EVENT. (use the subroutines in handling_lhe_events.f)

      ! TO TEST: compare cross section and distributions from reweighted
      ! events with original events. Make sure to only check S-events,
      ! since H-events are not generated by the reweighting method.
      
c Write the process PID in the log.txt files (i.e., to the screen)
      write (*,*) getpid()

      call cpu_time(tBefore)
      fixed_order=.false.
      nlo_ps=.true.
      if (nincoming.ne.2) then
         write (*,*) 'Decay processes not supported for'/
     &        /' event generation'
         stop 1
      endif

c     Read general MadFKS parameters
c
      call FKSParamReader(paramFileName,.TRUE.,.FALSE.)
      min_virt_fraction_mint=min_virt_fraction
      do i=0,n_ave_virt
         average_virtual(i,1)=0d0
      enddo
      virtual_fraction(1)=virt_fraction
      n_ord_virt=amp_split_size
      n_MC_subt_diverge=0
      ntot_granny=0
      derntot=0
      do i=0,6
         ncase(i)=0
      enddo
      
      ntot=0
      nsun=0
      nsps=0
      nups=0
      neps=0
      n100=0
      nddp=0
      nqdp=0
      nini=0
      n10=0
      do i=0,9
        n1(i)=0
      enddo

      call setrun                !Sets up run parameters
      call setpara('param_card.dat')   !Sets up couplings and masses
      call setcuts               !Sets up cuts and particle masses
      call printout              !Prints out a summary of paramaters
      call run_printout          !Prints out a summary of the run settings
      call fill_configurations_common
      call check_amp_split 
c     
c     Get user input
c
      write(*,*) "getting user params"
      call get_user_params(ncalls0,itmax,
     &     ixi_i,iphi_i,iy_ij,SHsep)

      do_only_Sevents=.true.
      
      ! Set folding to one (instead of reading it in get_user_params)
c$$$      ixi_i=1
c$$$      iphi_i=1
c$$$      iy_ij=1

      i_momcmp_count=0
      xratmax=0.d0
      unwgt=.false.
c     Prepare the MINT folding
      do j=1,ndimmax
         if (j.le.ndim) then
            ifold(j)=1
         else
            ifold(j)=0
         endif
      enddo
      ifold_energy=1
      ifold_yij=2
      ifold_phi=3
      ifold(ifold_energy)=ixi_i
      ifold(ifold_phi)=iphi_i
      ifold(ifold_yij)=iy_ij

      
      ndim = 3*(nexternal-nincoming)-4
      if (abs(lpp(1)) .ge. 1) ndim=ndim+1
      if (abs(lpp(2)) .ge. 1) ndim=ndim+1


      open (unit=99,file='nevts',status='old',err=999)
      if (event_norm(1:4).ne.'bias') then
         read (99,*) nevts
      else
         read (99,*) nevts,event_weight
      endif
      close(99)
      write(*,*) 'Reweighting ', nevts, 'events'


! open the existing event file for reading:
      open(unit=99,file='events.lhe.rwgt',status='old',err=999)
      open(unit=98,file='events.lhe.rwgt.RW',status='unknown',err=999)
      
      call read_lhef_header(99,nevts,MonteCarlo)
      call read_lhef_init(99,IDBMUP,EBMUP,PDFGUP,PDFSUP,IDWTUP,NPRUP,
     $     XSECUP,XERRUP,XMAXUP,LPRUP)

      call write_lhef_header(98,nevts,MonteCarlo)
      call write_lhef_init(98,IDBMUP,EBMUP,PDFGUP,PDFSUP,IDWTUP,NPRUP,
     $     XSECUP,XERRUP,XMAXUP,LPRUP)
      
      do ievent=1,nevts
!     read the event:
         call read_lhef_event(99, NUP,IDPRUP,XWGTUP,SCALUP
     $        ,AQEDUP,AQCDUP, IDUP,ISTUP,MOTHUP,ICOLUP,PUP,VTIMUP,SPINUP
     $        ,buff,buff2,SCALUP_a)
         read(buff2(8:),*) ichan,iFKS_picked,(x(i),i=1,ndim)
!     compute the NLOoverBorn ratio:
         call compute_Born2NLO_RW_factor(iFKS_picked,ratio,x
     $        ,showerscale)
         XWGTUP=XWGTUP*ratio
         SCALUP=showerscale
!     write the event:
         call write_lhef_event(98, NUP,IDPRUP,XWGTUP,SCALUP,AQEDUP
     $        ,AQCDUP, IDUP,ISTUP,MOTHUP,ICOLUP,PUP,VTIMUP,SPINUP,buff
     $        ,buff2,SCALUP_a)

      enddo

      write (98,'(a)') "</LesHouchesEvents>"
      close(98)
      close(99)

       
      return
 999  write (*,*) 'nevts file not found'
      stop
      end


      block data timing
c timing statistics
      include "timing_variables.inc"
      data tOLP/0.0/
      data tGenPS/0.0/
      data tBorn/0.0/
      data tIS/0.0/
      data tReal/0.0/
      data tCount/0.0/
      data tFxFx/0.0/
      data tf_nb/0.0/
      data tf_all/0.0/
      data t_as/0.0/
      data tr_s/0.0/
      data tr_pdf/0.0/
      data t_plot/0.0/
      data t_cuts/0.0/
      data t_MC_subt/0.0/
      data t_isum/0.0/
      data t_p_unw/0.0/
      data t_write/0.0/
      data t_coupl/0.0/
      end

      subroutine compute_Born2NLO_RW_factor(iFKS_picked,ratio,x
     $     ,showerscale)
      use mint_module
      use weight_lines
      implicit none
      include 'nexternal.inc'
      include 'nFKSconfigs.inc'
      include 'run.inc'
      include "coupl.inc"
      double precision x(ndimmax),ratio,jac,p(0:3,nexternal),vegas_wgt
     $     ,probne,gfactsf,gfactcl,replace_MC_subt,sudakov_damp,rwgt
     $     ,vol1,showerscale
      integer nndim,i,iFKS_picked,nFKS_picked_nbody,sum
     $     ,proc_map(0:fks_configs,0:fks_configs),iFKS
      save proc_map,sum
      double precision p_born(0:3,nexternal-1)
      common/pborn/p_born
      integer izero,ione,itwo,mohdr
      parameter (izero=0,ione=1,itwo=2,mohdr=-100)
      double precision p1_cnt(0:3,nexternal,-2:2),wgt_cnt(-2:2)
     $     ,pswgt_cnt(-2:2),jac_cnt(-2:2)
      common/counterevnts/p1_cnt,wgt_cnt,pswgt_cnt,jac_cnt
      integer             ini_fin_fks
      common/fks_channels/ini_fin_fks
      logical       nbody
      common/cnbody/nbody
      logical calculatedBorn
      common/ccalculatedBorn/calculatedBorn
      double precision       wgt_ME_born,wgt_ME_real
      common /c_wgt_ME_tree/ wgt_ME_born,wgt_ME_real
      integer icolup_s(2,nexternal-1),icolup_h(2,nexternal)
      common /colour_connections/ icolup_s,icolup_h
      logical firsttime,passcuts,passcuts_nbody,passcuts_n1body
      data firsttime/.true./
      integer ifold_picked
      double precision x_save(ndimmax,max_fold)
      common /c_vegas_x_fold/x_save,ifold_picked
      integer              MCcntcalled
      common/c_MCcntcalled/MCcntcalled
      integer     fold,ifold_counter
      common /cfl/fold,ifold_counter
      double precision SCALUP(fks_configs*2)
      common /cshowerscale/SCALUP

      if (firsttime) then
         firsttime=.false.
         ndim = 3*(nexternal-nincoming)-4
         if (abs(lpp(1)) .ge. 1) ndim=ndim+1
         if (abs(lpp(2)) .ge. 1) ndim=ndim+1
         nndim=ndim
         call setup_proc_map(sum,proc_map,ini_fin_fks)
         call find_iproc_map()
         call setup_event_attributes
      endif

      icontr=0
      MCcntcalled=0
      nbody=.true.
      calculatedBorn=.false.

      vegas_wgt=1d0
      vol1=1d0
      
      ifold_counter=1

      do i=1,proc_map(0,0)
         if (any(proc_map(i,1:proc_map(i,0)).eq.iFKS_picked)) then
            proc_map(0,1)=i
            exit
         endif
      enddo

      call update_fks_dir(iFKS_picked)
      icolup_s(1,1)=-1          ! set colour connection to -1: i.e., complete_xmcsubt has not been called
      if (ini_fin_fks.eq.0) then
         jac=1d0
      else
         jac=0.5d0
      endif

      jac=jac/(proc_map(0,0)*vol1)
         
      call generate_momenta(nndim,iconfig,jac,x,p)
      
      call compute_prefactors_nbody(vegas_wgt)

      call set_cms_stuff(izero)
      nFKS_picked_nbody=iFKS_picked
      call set_shower_scale_noshape(p,nFKS_picked_nbody*2-1)

      call set_alphaS(p1_cnt(0,1,0))
      
      call compute_born
      call compute_nbody_noborn
      call include_shape_in_shower_scale(p,nFKS_picked_nbody
     $     ,ifold_counter)
      call set_colour_connections(nFKS_picked_nbody,ifold_counter)

      
      nbody=.false.
      calculatedBorn=.false.
      do i=1,proc_map(proc_map(0,1),0)
         wgt_me_real=0d0
         wgt_me_born=0d0
         iFKS=proc_map(proc_map(0,1),i)
         call update_fks_dir(iFKS)
         jac=1d0/vol1
         probne=1d0
         gfactsf=1.d0
         gfactcl=1.d0
         MCcntcalled=0
         icolup_s(1,1)=-1       ! set colour connection to -1: i.e., complete_xmcsubt has not been called
         call generate_momenta(nndim,iconfig,jac,x,p)
c     Every contribution has to have a viable set of Born momenta (even if
c     counter-event momenta do not exist).
         if (p_born(0,1).lt.0d0) cycle
c     Set the shower scales            
         call set_cms_stuff(izero)
         call set_shower_scale_noshape(p,iFKS*2-1)
         call set_cms_stuff(mohdr)
         call set_shower_scale_noshape(p,iFKS*2)
c     Compute the n1-body prefactors
         call compute_prefactors_n1body(vegas_wgt,jac)
c     check if event or counter-event passes cuts
         call set_cms_stuff(izero)
         passcuts_nbody=passcuts(p1_cnt(0,1,0),rwgt)
         call set_cms_stuff(mohdr)
         passcuts_n1body=passcuts(p,rwgt)
         if (.not. (passcuts_nbody.or.passcuts_n1body)) cycle
         if (passcuts_nbody) then
            pass_cuts_check=.true.
            call set_cms_stuff(mohdr)
            call set_alphaS(p)
            call compute_MC_subt_term(p,passcuts_nbody,gfactsf
     $           ,gfactcl,probne)
         endif
         if (passcuts_nbody) then
c     Include the FKS counter terms. When close to the soft or collinear
c     limits, the MC subtraction terms should be replaced by the FKS
c     ones. This is set via the gfactsf, gfactcl and probne functions (set
c     by the call to compute_MC_subt_term) through the 'replace_MC_subt'.
            call set_cms_stuff(izero)
            call set_alphaS(p1_cnt(0,1,0))
            replace_MC_subt=(1d0-gfactsf)*probne
            call compute_soft_counter_term(replace_MC_subt)
            call set_cms_stuff(ione)
            replace_MC_subt=(1d0-gfactcl)*(1d0-gfactsf)*probne
            call compute_collinear_counter_term(replace_MC_subt)
            call set_cms_stuff(itwo)
            replace_MC_subt=(1d0-gfactcl)*(1d0-gfactsf)*probne
            call compute_soft_collinear_counter_term(replace_MC_subt)
         endif
c     Include the real-emission contribution.
         if (passcuts_n1body) then
            pass_cuts_check=.true.
            call set_cms_stuff(mohdr)
            call set_alphaS(p)
            sudakov_damp=probne
            call compute_real_emission(p,sudakov_damp)
         endif
c     Update the shower starting scale with the shape from the MC
c     subtraction terms.
         call include_shape_in_shower_scale(p,iFKS,ifold_counter)
         call set_colour_connections(iFKS,ifold_counter)
      enddo

c Special check: in rare cases there can be S-event contributions,
c without a single FKS configuration that contains a soft singularity
c passing cuts (this only happens if n-body configuration does not pass
c the cuts and DELTA (from complete_xmcsubt) is not equal to 1). Need to
c add a bogus contribution corresponding to an FKS configuration that
c contains a soft singularity to make sure that the code continues
c correctly.
      call special_check_SoftSing(proc_map(proc_map(0,1),1))
c Include PDFs and alpha_S and reweight to include the uncertainties
      call include_PDF_and_alphas
c Include the weight from the bias_function
      call include_bias_wgt
c Sum the contributions that can be summed before taking the ABS value
      call sum_identical_contributions
c Update the shower starting scale for the S-events after we have
c determined which contributions are identical.
      call update_shower_scale_Sevents(ifold_counter,ifold_picked)

      call fill_mint_function_RATIO(ratio)

      
      call pick_unweight_contr(iFKS_picked,ifold_picked)
      call update_fks_dir(iFKS_picked)
      showerscale=SCALUP(iFKS_picked*2-1)
      
      end

      
      function sigintF(xx,vegas_wgt,ifl,f)
      use weight_lines
      use mint_module
      implicit none
      include 'nexternal.inc'
      include 'nFKSconfigs.inc'
      include 'run.inc'
      include 'orders.inc'
      include 'fks_info.inc'
      logical firsttime,passcuts,passcuts_nbody,passcuts_n1body
      integer i,j,ifl,proc_map(0:fks_configs,0:fks_configs)
     $     ,nFKS_picked_nbody,nFKS_in,nFKS_out,izero,ione,itwo,mohdr
     $     ,iFKS,sum
      double precision xx(ndimmax),vegas_wgt,f(nintegrals),jac,p(0:3
     $     ,nexternal),rwgt,vol,sig,x(99),MC_int_wgt,vol1,probne,gfactsf
     $     ,gfactcl,replace_MC_subt,sudakov_damp,sigintF,n1body_wgt
      save vol1,proc_map
      integer             ini_fin_fks
      common/fks_channels/ini_fin_fks
      external passcuts
      parameter (izero=0,ione=1,itwo=2,mohdr=-100)
      data firsttime/.true./
      double precision p_born(0:3,nexternal-1)
      common /pborn/   p_born
      integer     fold,ifold_counter
      common /cfl/fold,ifold_counter
      logical calculatedBorn
      common/ccalculatedBorn/calculatedBorn
      integer              MCcntcalled
      common/c_MCcntcalled/MCcntcalled
      double precision virtual_over_born
      common /c_vob/   virtual_over_born
      logical       nbody
      common/cnbody/nbody
      integer         nndim
      common/tosigint/nndim
      character*4      abrv
      common /to_abrv/ abrv
      double precision p1_cnt(0:3,nexternal,-2:2),wgt_cnt(-2:2)
     $     ,pswgt_cnt(-2:2),jac_cnt(-2:2)
      common/counterevnts/p1_cnt,wgt_cnt,pswgt_cnt,jac_cnt
      double precision       wgt_ME_born,wgt_ME_real
      common /c_wgt_ME_tree/ wgt_ME_born,wgt_ME_real
      integer ifold_picked
      double precision x_save(ndimmax,max_fold)
      common /c_vegas_x_fold/x_save,ifold_picked
      integer icolup_s(2,nexternal-1),icolup_h(2,nexternal)
      common /colour_connections/ icolup_s,icolup_h
c
      if (new_point .and. ifl.ne.2) then
         pass_cuts_check=.false.
      endif
      sigintF=0d0
c Find the nFKSprocess for which we compute the Born-like contributions
      if (firsttime) then
         firsttime=.false.
c Determines the proc_map that sets which FKS configuration can be
c summed explicitly and which by MC-ing.
         call setup_proc_map(sum,proc_map,ini_fin_fks)
c For the S-events, we can combine processes when they give identical
c processes at the Born. Make sure we check that we get indeed identical
c IRPOC's
         call find_iproc_map()
c For FxFx or UNLOPS matching with pythia8, set the correct attributes
c for the <event> tag in the LHEF file. "npNLO" are the number of Born
c partons in this multiplicity when running the code at NLO accuracy
c ("npLO" is -1 in that case). When running LO only, invert "npLO" and
c "npNLO".
         call setup_event_attributes
      endif

      if (ifl.eq.0) then
         ifold_counter=1
      elseif(ifl.eq.1) then
         ifold_counter=ifold_counter+1
      endif

      fold=ifl
      if (ifl.eq.0 .or. ifl.eq.1) then
         if (ifl.eq.0) then
            icontr=0
            virt_wgt_mint(0:amp_split_size)=0d0
            born_wgt_mint(0:amp_split_size)=0d0
            virtual_over_born=0d0
         endif
         MCcntcalled=0
         wgt_me_real=0d0
         wgt_me_born=0d0
         if (ickkw.eq.3) call set_FxFx_scale(0,p)
         call update_vegas_x(xx,x)
         do i=1,nndim
            x_save(i,ifold_counter)=x(i)
         enddo
         if (ifl.eq.0)
     &        call get_MC_integer(1,proc_map(0,0),proc_map(0,1),vol1)

c The nbody contributions
         if (abrv.eq.'real') goto 11
         nbody=.true.
         calculatedBorn=.false.
c Pick the first one because that's the one with the soft singularity
         nFKS_picked_nbody=proc_map(proc_map(0,1),1)
         if (sum.eq.0) then
c For sum=0, determine nFKSprocess so that the soft limit gives a non-zero Born
            nFKS_in=nFKS_picked_nbody
            call get_born_nFKSprocess(nFKS_in,nFKS_out)
            nFKS_picked_nbody=nFKS_out
         endif
         call update_fks_dir(nFKS_picked_nbody)
         icolup_s(1,1)=-1 ! set colour connection to -1: i.e., complete_xmcsubt has not been called
         if (ini_fin_fks.eq.0) then
            jac=1d0
         else
            jac=0.5d0
         endif
c Also the Born needs to be included in the Importance Sampling over the
c FKS configurations (for the shower scale) (multiply by
c 1/proc_map(0,0)*vol1)
         jac=jac/(proc_map(0,0)*vol1)
         call generate_momenta(nndim,iconfig,jac,x,p)
         if (p_born(0,1).lt.0d0) goto 12
         call compute_prefactors_nbody(vegas_wgt)
         call set_cms_stuff(izero)
         call set_shower_scale_noshape(p,nFKS_picked_nbody*2-1)
         if (ickkw.eq.3) call set_FxFx_scale(1,p1_cnt(0,1,0))
         passcuts_nbody=passcuts(p1_cnt(0,1,0),rwgt)
         if (passcuts_nbody) then
            pass_cuts_check=.true.
            call set_alphaS(p1_cnt(0,1,0))
            call include_multichannel_enhance(1)
            if (abrv(1:2).ne.'vi') then
               call compute_born
               if(abrv.ne.'born'.and.abrv.ne.'bovi') call compute_ewsudakov

            endif
            if (abrv.ne.'born') then
               call compute_nbody_noborn
            endif
         endif
c Update the shower starting scale. This might be updated again below if
c the nFKSprocess is the same.
         call include_shape_in_shower_scale(p,nFKS_picked_nbody
     $        ,ifold_counter)
         call set_colour_connections(nFKS_picked_nbody,ifold_counter)
            
         
 11      continue
c The n+1-body contributions (including counter terms)
         if (abrv.eq.'born'.or.abrv(1:2).eq.'vi') goto 12
c Set calculated Born to zero to prevent numerical inaccuracies: not
c always exactly the same momenta in computation of Born when computed
c for different nFKSprocess.
         if(sum.eq.0) calculatedBorn=.false.
         nbody=.false.
         do i=1,proc_map(proc_map(0,1),0)
            wgt_me_real=0d0
            wgt_me_born=0d0
            iFKS=proc_map(proc_map(0,1),i)
            call update_fks_dir(iFKS)
            jac=1d0/vol1
            probne=1d0
            gfactsf=1.d0
            gfactcl=1.d0
            MCcntcalled=0
            icolup_s(1,1)=-1    ! set colour connection to -1: i.e., complete_xmcsubt has not been called
            call generate_momenta(nndim,iconfig,jac,x,p)
c Every contribution has to have a viable set of Born momenta (even if
c counter-event momenta do not exist).
            if (p_born(0,1).lt.0d0) cycle
c Set the shower scales            
            if (ickkw.eq.3) then
               call set_FxFx_scale(0,p) ! reset the FxFx scales
            endif
            call set_cms_stuff(izero)
            call set_shower_scale_noshape(p,iFKS*2-1)
            if (ickkw.eq.3) then
               call set_FxFx_scale(2,p1_cnt(0,1,0))
            endif
            call set_cms_stuff(mohdr)
            call set_shower_scale_noshape(p,iFKS*2)
            if (ickkw.eq.3) then
               if (p(0,1).gt.0d0) then
                  call set_FxFx_scale(3,p)
               endif
            endif              
c Compute the n1-body prefactors
            call compute_prefactors_n1body(vegas_wgt,jac)
c check if event or counter-event passes cuts
            call set_cms_stuff(izero)
            if (ickkw.eq.3) call set_FxFx_scale(-2,p1_cnt(0,1,0))
            passcuts_nbody=passcuts(p1_cnt(0,1,0),rwgt)
            call set_cms_stuff(mohdr)
            if (ickkw.eq.3) call set_FxFx_scale(-3,p)
            passcuts_n1body=passcuts(p,rwgt)
            if (.not. (passcuts_nbody.or.passcuts_n1body)) cycle
            if (passcuts_nbody .and. abrv.ne.'real') then
               pass_cuts_check=.true.
c Include the MonteCarlo subtraction terms
               if (ickkw.ne.4) then
                  call set_cms_stuff(mohdr)
                  if (ickkw.eq.3) call set_FxFx_scale(-3,p)
                  call set_alphaS(p)
                  call include_multichannel_enhance(4)
                  call compute_MC_subt_term(p,passcuts_nbody,gfactsf
     $                 ,gfactcl,probne)
               else
c For UNLOPS all real-emission contributions need to be added to the
c S-events. Do this by setting probne to 0. For UNLOPS, no MC counter
c events are called, so this will remain 0.
                  probne=0d0
               endif
            endif
            if (passcuts_nbody .and. abrv.ne.'real') then
c Include the FKS counter terms. When close to the soft or collinear
c limits, the MC subtraction terms should be replaced by the FKS
c ones. This is set via the gfactsf, gfactcl and probne functions (set
c by the call to compute_MC_subt_term) through the 'replace_MC_subt'.
               call set_cms_stuff(izero)
               if (ickkw.eq.3) call set_FxFx_scale(-2,p1_cnt(0,1,0))
               call set_alphaS(p1_cnt(0,1,0))
               call include_multichannel_enhance(3)
               replace_MC_subt=(1d0-gfactsf)*probne
               call compute_soft_counter_term(replace_MC_subt)
               call set_cms_stuff(ione)
               replace_MC_subt=(1d0-gfactcl)*(1d0-gfactsf)*probne
               call compute_collinear_counter_term(replace_MC_subt)
               call set_cms_stuff(itwo)
               replace_MC_subt=(1d0-gfactcl)*(1d0-gfactsf)*probne
               call compute_soft_collinear_counter_term(replace_MC_subt)
            endif
c Include the real-emission contribution.
            if (passcuts_n1body) then
               pass_cuts_check=.true.
               call set_cms_stuff(mohdr)
               if (ickkw.eq.3) call set_FxFx_scale(-3,p)
               call set_alphaS(p)
               call include_multichannel_enhance(2)
               sudakov_damp=probne
               call compute_real_emission(p,sudakov_damp)
            endif
c Update the shower starting scale with the shape from the MC
c subtraction terms.
            call include_shape_in_shower_scale(p,iFKS,ifold_counter)
            call set_colour_connections(iFKS,ifold_counter)
         enddo
 12      continue
      elseif(ifl.eq.2) then
         if (ifold_counter .ne.
     $       ifold(ifold_energy)*ifold(ifold_yij)*ifold(ifold_phi)) then
            write (*,*) "ERROR in folding parameters (driver_mintMC.f)"
     $           ,ifold_counter,ifold_energy,ifold_yij,ifold_phi
            write (*,*) ifold(:)
            stop 1
         endif
c Special check: in rare cases there can be S-event contributions,
c without a single FKS configuration that contains a soft singularity
c passing cuts (this only happens if n-body configuration does not pass
c the cuts and DELTA (from complete_xmcsubt) is not equal to 1). Need to
c add a bogus contribution corresponding to an FKS configuration that
c contains a soft singularity to make sure that the code continues
c correctly.
         call special_check_SoftSing(proc_map(proc_map(0,1),1))
c Include PDFs and alpha_S and reweight to include the uncertainties
         call include_PDF_and_alphas
c Include the weight from the bias_function
         call include_bias_wgt
c Sum the contributions that can be summed before taking the ABS value
         call sum_identical_contributions
c Update the shower starting scale for the S-events after we have
c determined which contributions are identical.
         call update_shower_scale_Sevents(ifold_counter,ifold_picked)
         call fill_mint_function_NLOPS(f,n1body_wgt)
         call fill_MC_integer(1,proc_map(0,1),n1body_wgt*vol1)
      endif
      return
      end


      subroutine setup_proc_map(sum,proc_map,ini_fin_fks)
c Determines the proc_map that sets which FKS configuration can be
c summed explicitly and which by MC-ing.
      implicit none
      include 'nexternal.inc'
      include 'run.inc'
      include 'genps.inc'
      include 'nFKSconfigs.inc'
      double precision lum,dlum
      external dlum
      logical found_ini1,found_ini2,found_fnl
      integer proc_map(0:fks_configs,0:fks_configs)
     $     ,j_fks_proc(fks_configs),i_fks_pdg_proc(fks_configs)
     $     ,j_fks_pdg_proc(fks_configs),i,sum,j,ini_fin_fks
      integer              nFKSprocess
      common/c_nFKSprocess/nFKSprocess
      INTEGER              IPROC
      DOUBLE PRECISION PD(0:MAXPROC)
      COMMON /SUBPROC/ PD, IPROC
      integer            i_fks,j_fks
      common/fks_indices/i_fks,j_fks
      integer fks_j_from_i(nexternal,0:nexternal)
     &     ,particle_type(nexternal),pdg_type(nexternal)
      common /c_fks_inc/fks_j_from_i,particle_type,pdg_type
      logical need_color_links, need_charge_links
      common /c_need_links/need_color_links, need_charge_links
      sum=3
      if (ickkw.eq.4) then
         sum=0
         write (*,*)'Using ickkw=4, include only 1 FKS dir per'/
     $        /' Born PS point (sum=0)'
      endif
      do nFKSprocess=1,fks_configs
         call fks_inc_chooser()
c Set Bjorken x's to some random value before calling the dlum() function
         xbk(1)=0.5d0
         xbk(2)=0.5d0
         lum=dlum()  ! updates IPROC
      enddo
      write (*,*) 'Total number of FKS directories is', fks_configs
c For sum over identical FKS pairs, need to find the identical structures
      if (sum.eq.3) then
c MC over FKS pairs that have soft singularity
         proc_map(0,0)=0
         do i=1,fks_configs
            proc_map(i,0)=0
            i_fks_pdg_proc(i)=0
            j_fks_pdg_proc(i)=0
            j_fks_proc(i)=0
         enddo
c First find all the nFKSprocesses that have a soft singularity and put
c them in the process map
         do nFKSprocess=1,fks_configs
            call fks_inc_chooser()
            if (ini_fin_fks.eq.1 .and. j_fks.le.nincoming) cycle
            if (ini_fin_fks.eq.2 .and. j_fks.gt.nincoming) cycle
            if (need_color_links.or.need_charge_links) then
               proc_map(0,0)=proc_map(0,0)+1
               proc_map(proc_map(0,0),0)=proc_map(proc_map(0,0),0)+1
               proc_map(proc_map(0,0),proc_map(proc_map(0,0),0))
     $              =nFKSprocess
               i_fks_pdg_proc(proc_map(0,0))=PDG_type(i_fks)
               j_fks_pdg_proc(proc_map(0,0))=PDG_type(j_fks)
               j_fks_proc(proc_map(0,0))=j_fks
            endif
         enddo
c Check to make sure that there is at most two initial and one final
c state all gluon
         found_ini1=.false.
         found_ini2=.false.
         found_fnl=.false.
         do i=1,proc_map(0,0)
            if ((abs(i_fks_pdg_proc(i)).eq.21.or.i_fks_pdg_proc(i).eq.22)
     &       .and. j_fks_proc(i).eq.1 .and. .not.found_ini1) then
               found_ini1=.true.
            elseif ((abs(i_fks_pdg_proc(i)).eq.21.or.i_fks_pdg_proc(i).eq.22)
     $       .and. j_fks_proc(i).eq.1.and. found_ini1) then
               write (*,*)'Initial state 1 g->gg already'/
     $              /' found in driver_mintMC'
               write (*,*) i_fks_pdg_proc
               write (*,*) j_fks_pdg_proc
               write (*,*) j_fks_proc
               stop
            elseif ((abs(i_fks_pdg_proc(i)).eq.21.or.i_fks_pdg_proc(i).eq.22)
     $       .and. j_fks_proc(i).eq.2.and. .not.found_ini2) then
               found_ini2=.true.
            elseif ((abs(i_fks_pdg_proc(i)).eq.21.or.i_fks_pdg_proc(i).eq.22)
     $       .and. j_fks_proc(i).eq.2.and. found_ini2) then
               write (*,*)'Initial state 2 g->gg already'/
     $              /' found in driver_mintMC'
               write (*,*) i_fks_pdg_proc
               write (*,*) j_fks_pdg_proc
               write (*,*) j_fks_proc
               stop
            elseif (abs(i_fks_pdg_proc(i)).eq.21 .and.
     $              j_fks_pdg_proc(i).eq.21 .and.
     $              j_fks_proc(i).gt.nincoming .and. .not.found_fnl)
     $              then
               found_fnl=.true.
            elseif (abs(i_fks_pdg_proc(i)).eq.21 .and.
     $              j_fks_pdg_proc(i).eq.21 .and.
     $              j_fks_proc(i).gt.nincoming .and. found_fnl) then
               write (*,*)
     &              'Final state g->gg already found in driver_mintMC'
               write (*,*) i_fks_pdg_proc
               write (*,*) j_fks_pdg_proc
               write (*,*) j_fks_proc
               stop
            endif
         enddo
c Loop again, and identify the nFKSprocesses that do not have a soft
c singularity and put them together with the corresponding gluon to
c gluons splitting
         do nFKSprocess=1,fks_configs
            call fks_inc_chooser()
            if (ini_fin_fks.eq.1 .and. j_fks.le.nincoming) cycle
            if (ini_fin_fks.eq.2 .and. j_fks.gt.nincoming) cycle
            if (.not.(need_color_links.or.need_charge_links)) then
               if (j_fks.eq.1 .and. found_ini1) then
                  do i=1,proc_map(0,0)
                     if ((abs(i_fks_pdg_proc(i)).eq.21.or.i_fks_pdg_proc(i).eq.22)
     $                    .and. j_fks_proc(i).eq.1) then
                        proc_map(i,0)=proc_map(i,0)+1
                        proc_map(i,proc_map(i,0))=nFKSprocess
                        exit
                     endif
                  enddo
               elseif (j_fks.eq.2 .and. found_ini2) then
                  do i=1,proc_map(0,0)
                     if ((abs(i_fks_pdg_proc(i)).eq.21.or.i_fks_pdg_proc(i).eq.22)
     $                   .and. j_fks_proc(i).eq.2) then
                        proc_map(i,0)=proc_map(i,0)+1
                        proc_map(i,proc_map(i,0))=nFKSprocess
                        exit
                     endif
                  enddo
               elseif (j_fks.gt.nincoming .and. found_fnl) then
                  do i=1,proc_map(0,0)
                     if (abs(i_fks_pdg_proc(i)).eq.21 .and.
     $                    j_fks_pdg_proc(i).eq.21.and.
     $                    j_fks_proc(i).gt.nincoming) then
                        proc_map(i,0)=proc_map(i,0)+1
                        proc_map(i,proc_map(i,0))=nFKSprocess
                        exit
                     endif
                  enddo
               else
                  write (*,*) 'Driver_mintMC: inconsistent process'
                  write (*,*) 'This process has nFKSprocesses'/
     $                 /' without soft singularities, but not a'/
     $                 /' corresponding g->gg splitting that has a'/
     $                 /' soft singularity.',found_ini1,found_ini2
     $                 ,found_fnl
                  do i=1,proc_map(0,0)
                     write (*,*) i,'-->',proc_map(i,0),':',
     &                    (proc_map(i,j),j=1,proc_map(i,0))
                  enddo
                  stop
               endif
            endif
         enddo
      elseif (sum.eq.0 .and. ickkw.eq.4) then
c MC over FKS directories (1 FKS directory per nbody PS point)
         proc_map(0,0)=fks_configs
         do i=1,fks_configs
            proc_map(i,0)=1
            proc_map(i,1)=i
         enddo
      else
         write (*,*) 'sum not known in driver_mintMC.f',sum
         stop
      endif
      write (*,*) 'FKS process map (sum=',sum,') :'
      do i=1,proc_map(0,0)
         write (*,*) i,'-->',proc_map(i,0),':',
     &        (proc_map(i,j),j=1,proc_map(i,0))
      enddo
      return
      end
c


      subroutine setup_event_attributes
c For FxFx or UNLOPS matching with pythia8, set the correct attributes
c for the <event> tag in the LHEF file. "npNLO" are the number of Born
c partons in this multiplicity when running the code at NLO accuracy
c ("npLO" is -1 in that case). When running LO only, invert "npLO" and
c "npNLO".
      implicit none
      include 'nexternal.inc'
      include 'run.inc'
      include 'genps.inc'
      integer i
      integer                 nattr,npNLO,npLO
      common/event_attributes/nattr,npNLO,npLO
      integer              nFKSprocess
      common/c_nFKSprocess/nFKSprocess
      integer idup(nexternal,maxproc),mothup(2,nexternal,maxproc),
     &     icolup(2,nexternal,maxflow),niprocs
      common /c_leshouche_inc/idup,mothup,icolup,niprocs
      character*4      abrv
      common /to_abrv/ abrv
      if ((shower_mc.eq.'PYTHIA8' .or. shower_mc.eq.'HERWIGPP') .and.
     $     (ickkw.eq.3.or.ickkw.eq.4))then
         nattr=2
         nFKSprocess=1          ! just pick one
         call fks_inc_chooser()
         call leshouche_inc_chooser()
         npNLO=0
         npLO=-1
         do i=nincoming+1,nexternal
c     include all quarks (except top quark) and the gluon.
            if(abs(idup(i,1)).le.5 .or. abs(idup(i,1)).eq.21)
     &           npNLO=npNLO+1
         enddo
         npNLO=npNLO-1
         if (npNLO.gt.99) then
            write (*,*) 'Too many partons',npNLO
            stop
         endif
         if (abrv.eq.'born') then
            npLO=npNLO
            npNLO=-1
         endif
      else
         nattr=0
      endif
      return
      end


      subroutine update_fks_dir(nFKS)
      implicit none
      include 'run.inc'
      integer nFKS
      integer              nFKSprocess
      common/c_nFKSprocess/nFKSprocess
      nFKSprocess=nFKS
      call fks_inc_chooser()
      call leshouche_inc_chooser()
      call setcuts
      call setfksfactor(.true.)
      return
      end

      subroutine update_vegas_x(xx,x)
      use mint_module
      implicit none
      integer i
      double precision xx(ndimmax),x(99),ran2
      external ran2
      integer         nndim
      common/tosigint/nndim
      character*4      abrv
      common /to_abrv/ abrv
      do i=1,99
         if (abrv.eq.'born') then
            if(i.le.nndim-3)then
               x(i)=xx(i)
            elseif(i.le.nndim) then
               x(i)=ran2()      ! Choose them flat when not including real-emision
            else
               x(i)=0.d0
            endif
         else
            if(i.le.nndim)then
               x(i)=xx(i)
            else
               x(i)=0.d0
            endif
         endif
      enddo
      return
      end



      subroutine get_born_nFKSprocess(nFKS_in,nFKS_out)
      implicit none
      include 'nexternal.inc'
      include 'nFKSconfigs.inc'
      include 'fks_info.inc'
      integer nFKS_in,nFKS_out,iFKS,iiFKS,nFKSprocessBorn(fks_configs)
      logical firsttime
      data firsttime /.true./
      save nFKSprocessBorn
c
      if (firsttime) then
         firsttime=.false.
         do iFKS=1,fks_configs
            nFKSprocessBorn(iFKS)=0
            if ( need_color_links_D(iFKS) .or. 
     &           need_charge_links_D(iFKS) )then
               nFKSprocessBorn(iFKS)=iFKS
            endif
            if (nFKSprocessBorn(iFKS).eq.0) then
c     try to find the process that has the same j_fks but with i_fks a
c     gluon
               do iiFKS=1,fks_configs
                  if ( (need_color_links_D(iiFKS) .or.
     &                  need_charge_links_D(iiFKS)) .and.
     &                 fks_j_D(iFKS).eq.fks_j_D(iiFKS) ) then
                     nFKSprocessBorn(iFKS)=iiFKS
                     exit
                  endif
               enddo
            endif
c     try to find the process that has the j_fks initial state if
c     current j_fks is initial state (and similar for final state j_fks)
            if (nFKSprocessBorn(iFKS).eq.0) then
               do iiFKS=1,fks_configs
                  if ( need_color_links_D(iiFKS) .or.
     &                 need_charge_links_D(iiFKS) ) then
                     if ( fks_j_D(iiFKS).le.nincoming .and.
     &                    fks_j_D(iFKS).le.nincoming ) then
                        nFKSprocessBorn(iFKS)=iiFKS
                        exit
                     elseif ( fks_j_D(iiFKS).gt.nincoming .and.
     &                        fks_j_D(iFKS).gt.nincoming ) then
                        nFKSprocessBorn(iFKS)=iiFKS
                        exit
                     endif
                  endif
               enddo
            endif
c     If still not found, just pick any one that has a soft singularity
            if (nFKSprocessBorn(iFKS).eq.0) then
               do iiFKS=1,fks_configs
                  if ( need_color_links_D(iiFKS) .or.
     &                 need_charge_links_D(iiFKS) ) then
                     nFKSprocessBorn(iFKS)=iiFKS
                  endif
               enddo
            endif
c     if there are no soft singularities at all, just do something trivial
            if (nFKSprocessBorn(iFKS).eq.0) then
               nFKSprocessBorn(iFKS)=iFKS
            endif
         enddo
         write (*,*) 'Total number of FKS directories is', fks_configs
         write (*,*) 'For the Born we use nFKSprocesses:'
         write (*,*)  nFKSprocessBorn
      endif
      if (nFKSprocessBorn(nFKS_in).eq.0) then
         write(*,*) 'Could not find the correct map to Born '/
     &        /'FKS configuration for the NLO FKS '/
     &        /'configuration', nFKS_in
         stop 1
      else
         nFKS_out=nFKSprocessBorn(nFKS_in)
      endif
      return
      end


      subroutine special_check_SoftSing(isoft)
      use weight_lines
      implicit none
      include 'nexternal.inc'
      include 'fks_info.inc'
      integer i_soft,isoft,i
      logical found_S
      i_soft=0
      found_S=.false.
      do i=1,icontr
         if (H_event(i)) then
            cycle
         else
            found_S=.true.
         endif
         if (abs(pdg_type_d(nFKS(i),fks_i_d(nFKS(i)))).eq.21) then
            i_soft=i
            exit
         endif
      enddo
      if (found_S .and. i_soft.eq.0) then
         ! add an artificial contribution
         call update_fks_dir(isoft)
         call add_wgt(2,1d-199,0d0,0d0)
      endif
      return
      end

      subroutine get_user_params(ncall,nitmax,
     &     ixi_i,iphi_i,iy_ij,SHsep)
c**********************************************************************
c     Routine to get user specified parameters for run
c**********************************************************************
      use mint_module
      implicit none
c
c     Constants
c
      include 'nexternal.inc'
      include 'genps.inc'
      include 'nFKSconfigs.inc'
      include 'fks_info.inc'
      include 'run.inc'
c
c     Arguments
c
      integer ncall,nitmax
c
c     Local
c
      integer i, j
      double precision dconfig
c
c     Global
c
      integer             ini_fin_fks
      common/fks_channels/ini_fin_fks
      integer           isum_hel
      logical                   multi_channel
      common/to_matrix/isum_hel, multi_channel
      logical fillh
      integer mc_hel,ihel
      double precision volh
      common/mc_int2/volh,mc_hel,ihel,fillh
      integer           use_cut
      common /to_weight/use_cut

      integer        lbw(0:nexternal)  !Use of B.W.
      common /to_BW/ lbw

      character*5 abrvinput
      character*4 abrv
      common /to_abrv/ abrv

      logical nbody
      common/cnbody/nbody
c
c To convert diagram number to configuration
c
      double precision pmass(-nexternal:0,lmaxconfigs,0:fks_configs)
      double precision pwidth(-nexternal:0,lmaxconfigs,0:fks_configs)
      integer iforest(2,-max_branch:-1,lmaxconfigs,0:fks_configs)
      integer sprop(-max_branch:-1,lmaxconfigs,0:fks_configs)
      integer tprid(-max_branch:-1,lmaxconfigs,0:fks_configs)
      integer mapconfig(0:lmaxconfigs,0:fks_configs)
      common /c_configurations/pmass,pwidth,iforest,sprop,tprid
     $     ,mapconfig
c
c MC counterterm stuff
c
c alsf and besf are the parameters that control gfunsoft
      double precision alsf,besf
      common/cgfunsfp/alsf,besf
c alazi and beazi are the parameters that control gfunazi
      double precision alazi,beazi
      common/cgfunazi/alazi,beazi
      
      logical SHsep
      logical Hevents
      common/SHevents/Hevents
c
c MINT stuff
c
      integer ixi_i,iphi_i,iy_ij

c-----
c  Begin Code
c-----
      
      open (unit=83,file='input_app.txt',status='old')
      
      write(*,'(a)') 'Enter number of events and iterations: '
      read(83,*) ncall,nitmax
      write(*,*) 'Number of events and iterations ',ncall,nitmax

      write(*,'(a)') 'Enter desired fractional accuracy: '
      read(83,*) accuracy
      write(*,*) 'Desired fractional accuracy: ',accuracy

      write(*,*)'Enter alpha, beta for G_soft'
      write(*,*)'  Enter alpha<0 to set G_soft=1 (no ME soft)'
      read(83,*)alsf,besf
      write (*,*) 'for G_soft: alpha=',alsf,', beta=',besf 

      write(*,*)'Enter alpha, beta for G_azi'
      write(*,*)'  Enter alpha>0 to set G_azi=0 (no azi corr)'
      read(83,*)alazi,beazi
      write (*,*) 'for G_azi: alpha=',alazi,', beta=',beazi
      i=2
      if (i.eq.0) then
         Hevents=.true.
         write (*,*) 'Doing the H-events'
         SHsep=.true.
      elseif (i.eq.1) then
         Hevents=.false.
         write (*,*) 'Doing the S-events'
         SHsep=.true.
      elseif (i.eq.2) then
         Hevents=.true.
         write (*,*) 'Doing the S and H events together'
         SHsep=.false.
      endif

c These should be ignored (but kept for 'historical reasons')      
      use_cut=2


      write(*,*) 'Suppress amplitude (0 no, 1 yes)? '
      read(83,*) i
      if (i .eq. 1) then
         multi_channel = .true.
         write(*,*) 'Using suppressed amplitude.'
      else
         multi_channel = .false.
         write(*,*) 'Using full amplitude.'
      endif

      write(*,*) 'Exact helicity sum (0 yes, n = number/event)? '
      read(83,*) i
      if (nincoming.eq.1) then
         write (*,*) 'Sum over helicities in the virtuals'/
     $        /' for decay process'
         mc_hel=0
      elseif (i.eq.0) then
         mc_hel=0
         write (*,*) 'Explicitly summing over helicities'/
     $        /' for the virtuals'
      else
         mc_hel=1
         write(*,*) 'Do MC over helicities for the virtuals'
      endif
      isum_hel = 0

      write(*,'(a)') 'Enter Configuration Number: '
      read(83,*) dconfig
      iconfig = int(dconfig)
      if ( nint(dconfig*10) - iconfig*10 .eq.0 ) then
         ini_fin_fks=0
      elseif ( nint(dconfig*10) -iconfig*10 .eq.1 ) then
         ini_fin_fks=1
      elseif ( nint(dconfig*10) -iconfig*10 .eq.2 ) then
         ini_fin_fks=2
      else
         write (*,*) 'ERROR: invalid configuration number',dconfig
         stop 1
      endif
      do i=1,mapconfig(0,0)
         if (iconfig.eq.mapconfig(i,0)) then
            iconfig=i
            exit
         endif
      enddo
      write(*,*) 'Running Configuration Number: ',iconfig,ini_fin_fks
      nchans=1
      iconfigs(1)=iconfig
      wgt_mult=1d0

      write (*,'(a)') 'Enter running mode for MINT:'
      write (*,'(a)') '0 to set-up grids, 1 to integrate,'//
     &     ' 2 to generate events'
      read (83,*) imode
      write (*,*) 'MINT running mode:',imode
      if (imode.eq.2)then
         write (*,*) 'Generating events, doing only one iteration'
         nitmax=1
      endif

      write (*,'(a)') 'Set the three folding parameters for MINT'
      write (*,'(a)') 'xi_i, y_ij, phi_i'
      read (83,*) ixi_i,iy_ij,iphi_i
      write (*,*)ixi_i,iy_ij,iphi_i


      abrvinput='     '
      write (*,*) "'all ', 'born', 'real', 'virt', 'novi' or 'grid'?"
      write (*,*) "Enter 'born0' or 'virt0' to perform"
      write (*,*) " a pure n-body integration (no S functions)"
c$$$      read(83,*) abrvinput
      abrvinput='all  '
      if(abrvinput(5:5).eq.'0')then
         write (*,*) 'This option is no longer supported:',abrvinput
         stop
        nbody=.true.
      else
        nbody=.false.
      endif
      abrv=abrvinput(1:4)
      if (fks_configs.eq.1) then
         if (pdg_type_d(1,fks_i_d(1)).eq.-21) then
            write (*,*) 'Process generated with [LOonly=QCD]. '/
     $           /'Setting abrv to "born".'
            abrv='born'
c$$$            if (ickkw.eq.3) then
c$$$               write (*,*) 'FxFx merging not possible with'/
c$$$     $              /' [LOonly=QCD] processes'
c$$$               stop 1
c$$$            endif
         endif
      endif
      if(nbody.and.abrv.ne.'born'.and.abrv.ne.'virt'
     &     .and. abrv.ne.'grid')then
        write(*,*)'Error in driver: inconsistent input',abrvinput
        stop
      endif

      write (*,*) "doing the ",abrv," of this channel"
      if(nbody)then
        write (*,*) "integration Born/virtual with Sfunction=1"
      else
        write (*,*) "Normal integration (Sfunction != 1)"
      endif
c
      lbw(0)=0
      close(83)
      end
