*     -*-fortran-*-

      real tBefore, tAfter
      real tBorn,tIS,tReal,tCount,tFxFx,tf_nb,tf_all,t_as,tr_s,tr_pdf
     &     ,t_plot,t_cuts,t_MC_subt
      common/timings/tBorn,tIS,tReal,tCount,tFxFx,tf_nb,tf_all,t_as
     &     ,tr_s,tr_pdf,t_plot,t_cuts,t_MC_subt
c obsolete:
      real tOLP, tFastJet, tPDF, tGenPS, tDSigI, tDSigR
      common/timings_old/tOLP, tFastJet, tPDF, tGenPS, tDSigI, tDSigR
