// This file was automatically generated based on instruction_set.yaml
// Do not modify its content directly

#pragma once

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include "madspace/compgraphs.hpp"

namespace py = pybind11;
using madspace::FunctionBuilder;

namespace {

void add_instructions(py::classh<FunctionBuilder>& fb) {
    fb.def("stack", &FunctionBuilder::stack, py::arg("args"));
    fb.def("unstack", &FunctionBuilder::unstack, py::arg("in1"));
    fb.def("stack_sizes", &FunctionBuilder::stack_sizes, py::arg("args"));
    fb.def("unstack_sizes", &FunctionBuilder::unstack_sizes, py::arg("in1"));
    fb.def("pop", &FunctionBuilder::pop, py::arg("in1"));
    fb.def("batch_cat", &FunctionBuilder::batch_cat, py::arg("args"));
    fb.def("batch_split", &FunctionBuilder::batch_split, py::arg("in1"), py::arg("counts"));
    fb.def("cat", &FunctionBuilder::cat, py::arg("args"));
    fb.def("batch_size", &FunctionBuilder::batch_size, py::arg("args"));
    fb.def("offset_indices", &FunctionBuilder::offset_indices, py::arg("batch_sizes_offset"), py::arg("batch_sizes_out"));
    fb.def("full", &FunctionBuilder::full, py::arg("args"));
    fb.def("squeeze", &FunctionBuilder::squeeze, py::arg("input"));
    fb.def("unsqueeze", &FunctionBuilder::unsqueeze, py::arg("input"));
    fb.def("accept_norm", &FunctionBuilder::accept_norm, py::arg("accepted_batch"), py::arg("full_batch"));
    fb.def("add", &FunctionBuilder::add, py::arg("in1"), py::arg("in2"));
    fb.def("add_int", &FunctionBuilder::add_int, py::arg("in1"), py::arg("in2"));
    fb.def("sub", &FunctionBuilder::sub, py::arg("in1"), py::arg("in2"));
    fb.def("mul", &FunctionBuilder::mul, py::arg("in1"), py::arg("in2"));
    fb.def("div", &FunctionBuilder::div, py::arg("in1"), py::arg("in2"));
    fb.def("reduce_sum", &FunctionBuilder::reduce_sum, py::arg("in1"));
    fb.def("reduce_sum_vector", &FunctionBuilder::reduce_sum_vector, py::arg("in1"));
    fb.def("batch_reduce_mean", &FunctionBuilder::batch_reduce_mean, py::arg("in1"));
    fb.def("batch_reduce_mean_keepdim", &FunctionBuilder::batch_reduce_mean_keepdim, py::arg("in1"));
    fb.def("reduce_product", &FunctionBuilder::reduce_product, py::arg("in1"));
    fb.def("sqrt", &FunctionBuilder::sqrt, py::arg("in1"));
    fb.def("square", &FunctionBuilder::square, py::arg("in1"));
    fb.def("min", &FunctionBuilder::min, py::arg("in1"), py::arg("in2"));
    fb.def("max", &FunctionBuilder::max, py::arg("in1"), py::arg("in2"));
    fb.def("obs_sqrt_s", &FunctionBuilder::obs_sqrt_s, py::arg("p_ext"));
    fb.def("obs_e", &FunctionBuilder::obs_e, py::arg("p"));
    fb.def("obs_px", &FunctionBuilder::obs_px, py::arg("p"));
    fb.def("obs_py", &FunctionBuilder::obs_py, py::arg("p"));
    fb.def("obs_pz", &FunctionBuilder::obs_pz, py::arg("p"));
    fb.def("obs_mass", &FunctionBuilder::obs_mass, py::arg("p"));
    fb.def("obs_pt", &FunctionBuilder::obs_pt, py::arg("p"));
    fb.def("obs_p_mag", &FunctionBuilder::obs_p_mag, py::arg("p"));
    fb.def("obs_phi", &FunctionBuilder::obs_phi, py::arg("p"));
    fb.def("obs_theta", &FunctionBuilder::obs_theta, py::arg("p"));
    fb.def("obs_y", &FunctionBuilder::obs_y, py::arg("p"));
    fb.def("obs_y_abs", &FunctionBuilder::obs_y_abs, py::arg("p"));
    fb.def("obs_eta", &FunctionBuilder::obs_eta, py::arg("p"));
    fb.def("obs_eta_abs", &FunctionBuilder::obs_eta_abs, py::arg("p"));
    fb.def("obs_delta_eta", &FunctionBuilder::obs_delta_eta, py::arg("p1"), py::arg("p2"));
    fb.def("obs_delta_phi", &FunctionBuilder::obs_delta_phi, py::arg("p1"), py::arg("p2"));
    fb.def("obs_delta_r", &FunctionBuilder::obs_delta_r, py::arg("p1"), py::arg("p2"));
    fb.def("boost_beam", &FunctionBuilder::boost_beam, py::arg("p1"), py::arg("x1"), py::arg("x2"));
    fb.def("boost_beam_inverse", &FunctionBuilder::boost_beam_inverse, py::arg("p1"), py::arg("x1"), py::arg("x2"));
    fb.def("com_p_in", &FunctionBuilder::com_p_in, py::arg("e_cm"));
    fb.def("r_to_x1x2", &FunctionBuilder::r_to_x1x2, py::arg("r"), py::arg("s_hat"), py::arg("s_lab"));
    fb.def("x1x2_to_r", &FunctionBuilder::x1x2_to_r, py::arg("x1"), py::arg("x2"), py::arg("s_lab"));
    fb.def("diff_cross_section", &FunctionBuilder::diff_cross_section, py::arg("x1"), py::arg("x2"), py::arg("pdf1"), py::arg("pdf2"), py::arg("matrix_element"), py::arg("e_cm2"));
    fb.def("two_body_decay_com", &FunctionBuilder::two_body_decay_com, py::arg("r_phi"), py::arg("r_cos_theta"), py::arg("m0"), py::arg("m1"), py::arg("m2"));
    fb.def("two_body_decay_com_inverse", &FunctionBuilder::two_body_decay_com_inverse, py::arg("p1"), py::arg("p2"));
    fb.def("two_body_decay", &FunctionBuilder::two_body_decay, py::arg("r_phi"), py::arg("r_cos_theta"), py::arg("m0"), py::arg("m1"), py::arg("m2"), py::arg("p0"));
    fb.def("two_body_decay_inverse", &FunctionBuilder::two_body_decay_inverse, py::arg("p1"), py::arg("p2"));
    fb.def("two_to_two_particle_scattering_com", &FunctionBuilder::two_to_two_particle_scattering_com, py::arg("r_phi"), py::arg("pa"), py::arg("pb"), py::arg("t_abs"), py::arg("m1"), py::arg("m2"));
    fb.def("two_to_two_particle_scattering_com_inverse", &FunctionBuilder::two_to_two_particle_scattering_com_inverse, py::arg("p1"), py::arg("p2"), py::arg("pa"), py::arg("pb"));
    fb.def("two_to_two_particle_scattering", &FunctionBuilder::two_to_two_particle_scattering, py::arg("r_phi"), py::arg("pa"), py::arg("pb"), py::arg("t_abs"), py::arg("m1"), py::arg("m2"));
    fb.def("two_to_two_particle_scattering_inverse", &FunctionBuilder::two_to_two_particle_scattering_inverse, py::arg("p1"), py::arg("p2"), py::arg("pa"), py::arg("pb"));
    fb.def("two_to_three_particle_scattering", &FunctionBuilder::two_to_three_particle_scattering, py::arg("phi_choice"), py::arg("pa"), py::arg("pb"), py::arg("p3"), py::arg("s23"), py::arg("t1_abs"), py::arg("m1"), py::arg("m2"));
    fb.def("two_to_three_particle_scattering_inverse", &FunctionBuilder::two_to_three_particle_scattering_inverse, py::arg("p1"), py::arg("p2"), py::arg("p3"), py::arg("pa"), py::arg("pb"), py::arg("t1_abs"), py::arg("s23"));
    fb.def("double_t_scattering", &FunctionBuilder::double_t_scattering, py::arg("r_phi"), py::arg("pa"), py::arg("pb"), py::arg("t1_abs"), py::arg("t2_abs"), py::arg("m1"));
    fb.def("double_t_scattering_inverse", &FunctionBuilder::double_t_scattering_inverse, py::arg("p1"), py::arg("p2"), py::arg("pa"), py::arg("pb"));
    fb.def("three_body_decay_com", &FunctionBuilder::three_body_decay_com, py::arg("r_e1"), py::arg("r_e2"), py::arg("r_phi"), py::arg("r_cos_theta"), py::arg("r_beta"), py::arg("m0"), py::arg("m1"), py::arg("m2"), py::arg("m3"));
    fb.def("three_body_decay_com_inverse", &FunctionBuilder::three_body_decay_com_inverse, py::arg("p1"), py::arg("p2"), py::arg("p3"));
    fb.def("three_body_decay", &FunctionBuilder::three_body_decay, py::arg("r_e1"), py::arg("r_e2"), py::arg("r_phi"), py::arg("r_cos_theta"), py::arg("r_beta"), py::arg("m0"), py::arg("m1"), py::arg("m2"), py::arg("m3"), py::arg("p0"));
    fb.def("three_body_decay_inverse", &FunctionBuilder::three_body_decay_inverse, py::arg("p1"), py::arg("p2"), py::arg("p3"));
    fb.def("t_inv_min_max", &FunctionBuilder::t_inv_min_max, py::arg("pa"), py::arg("pb"), py::arg("m1"), py::arg("m2"));
    fb.def("t_inv_value_and_min_max", &FunctionBuilder::t_inv_value_and_min_max, py::arg("pa"), py::arg("pb"), py::arg("p1"), py::arg("p2"));
    fb.def("t1_inv_min_max_doublet", &FunctionBuilder::t1_inv_min_max_doublet, py::arg("pa"), py::arg("pb"), py::arg("m1"), py::arg("mir_min"));
    fb.def("t1_inv_value_and_min_max_doublet", &FunctionBuilder::t1_inv_value_and_min_max_doublet, py::arg("pa"), py::arg("pb"), py::arg("p1"), py::arg("m1"), py::arg("mir_min"));
    fb.def("t2_inv_min_max_doublet", &FunctionBuilder::t2_inv_min_max_doublet, py::arg("pa"), py::arg("pb"), py::arg("m1"), py::arg("mir_min"), py::arg("t1_abs"));
    fb.def("t2_inv_value_and_min_max_doublet", &FunctionBuilder::t2_inv_value_and_min_max_doublet, py::arg("pa"), py::arg("pb"), py::arg("p1"), py::arg("m1"), py::arg("mir_min"), py::arg("t1_abs"));
    fb.def("s23_min_max", &FunctionBuilder::s23_min_max, py::arg("pa"), py::arg("pb"), py::arg("p3"), py::arg("t1_abs"), py::arg("m1"), py::arg("m2"));
    fb.def("s23_value_and_min_max", &FunctionBuilder::s23_value_and_min_max, py::arg("pa"), py::arg("pb"), py::arg("p3"), py::arg("t1_abs"), py::arg("p1"), py::arg("p2"));
    fb.def("invariants_from_momenta", &FunctionBuilder::invariants_from_momenta, py::arg("p_ext"), py::arg("factors"));
    fb.def("sde2_channel_weights", &FunctionBuilder::sde2_channel_weights, py::arg("invariants"), py::arg("masses"), py::arg("widths"), py::arg("indices"));
    fb.def("subchannel_weights", &FunctionBuilder::subchannel_weights, py::arg("invariants"), py::arg("masses"), py::arg("widths"), py::arg("indices"), py::arg("on_shell"), py::arg("group_sizes"));
    fb.def("apply_subchannel_weights", &FunctionBuilder::apply_subchannel_weights, py::arg("channel_weights_in"), py::arg("subchannel_weights"), py::arg("channel_indices"), py::arg("subchannel_indices"));
    fb.def("pt_eta_phi_x", &FunctionBuilder::pt_eta_phi_x, py::arg("p_ext"), py::arg("x1"), py::arg("x2"));
    fb.def("mirror_momenta", &FunctionBuilder::mirror_momenta, py::arg("p_ext"), py::arg("mirror"));
    fb.def("momenta_to_x1x2", &FunctionBuilder::momenta_to_x1x2, py::arg("p_ext"), py::arg("e_cm"));
    fb.def("uniform_invariant", &FunctionBuilder::uniform_invariant, py::arg("r"), py::arg("s_min"), py::arg("s_max"));
    fb.def("uniform_invariant_inverse", &FunctionBuilder::uniform_invariant_inverse, py::arg("s"), py::arg("s_min"), py::arg("s_max"));
    fb.def("breit_wigner_invariant", &FunctionBuilder::breit_wigner_invariant, py::arg("r"), py::arg("mass"), py::arg("width"), py::arg("s_min"), py::arg("s_max"));
    fb.def("breit_wigner_invariant_inverse", &FunctionBuilder::breit_wigner_invariant_inverse, py::arg("s"), py::arg("mass"), py::arg("width"), py::arg("s_min"), py::arg("s_max"));
    fb.def("stable_invariant", &FunctionBuilder::stable_invariant, py::arg("r"), py::arg("mass"), py::arg("s_min"), py::arg("s_max"));
    fb.def("stable_invariant_inverse", &FunctionBuilder::stable_invariant_inverse, py::arg("s"), py::arg("mass"), py::arg("s_min"), py::arg("s_max"));
    fb.def("stable_invariant_nu", &FunctionBuilder::stable_invariant_nu, py::arg("r"), py::arg("mass"), py::arg("nu"), py::arg("s_min"), py::arg("s_max"));
    fb.def("stable_invariant_nu_inverse", &FunctionBuilder::stable_invariant_nu_inverse, py::arg("s"), py::arg("mass"), py::arg("nu"), py::arg("s_min"), py::arg("s_max"));
    fb.def("fast_rambo_massless", &FunctionBuilder::fast_rambo_massless, py::arg("r"), py::arg("e_cm"), py::arg("p0"));
    fb.def("fast_rambo_massless_inverse", &FunctionBuilder::fast_rambo_massless_inverse, py::arg("p_out"), py::arg("e_cm"));
    fb.def("fast_rambo_massless_com", &FunctionBuilder::fast_rambo_massless_com, py::arg("r"), py::arg("e_cm"));
    fb.def("fast_rambo_massive", &FunctionBuilder::fast_rambo_massive, py::arg("r"), py::arg("e_cm"), py::arg("masses"), py::arg("p0"));
    fb.def("fast_rambo_massive_inverse", &FunctionBuilder::fast_rambo_massive_inverse, py::arg("p_out"), py::arg("e_cm"), py::arg("masses"));
    fb.def("fast_rambo_massive_com", &FunctionBuilder::fast_rambo_massive_com, py::arg("r"), py::arg("e_cm"), py::arg("masses"));
    fb.def("cut_unphysical", &FunctionBuilder::cut_unphysical, py::arg("w_in"), py::arg("p"), py::arg("x1"), py::arg("x2"));
    fb.def("cut_one", &FunctionBuilder::cut_one, py::arg("obs"), py::arg("min"), py::arg("max"));
    fb.def("cut_all", &FunctionBuilder::cut_all, py::arg("obs"), py::arg("min"), py::arg("max"));
    fb.def("cut_any", &FunctionBuilder::cut_any, py::arg("obs"), py::arg("min"), py::arg("max"));
    fb.def("scale_transverse_energy", &FunctionBuilder::scale_transverse_energy, py::arg("momenta"));
    fb.def("scale_transverse_mass", &FunctionBuilder::scale_transverse_mass, py::arg("momenta"));
    fb.def("scale_half_transverse_mass", &FunctionBuilder::scale_half_transverse_mass, py::arg("momenta"));
    fb.def("scale_partonic_energy", &FunctionBuilder::scale_partonic_energy, py::arg("momenta"));
    fb.def("chili_forward", &FunctionBuilder::chili_forward, py::arg("r"), py::arg("e_cm"), py::arg("m_out"), py::arg("pt_min"), py::arg("y_max"));
    fb.def("chili_inverse", &FunctionBuilder::chili_inverse, py::arg("p_ext"), py::arg("e_cm"), py::arg("m_out"), py::arg("pt_min"), py::arg("y_max"));
    fb.def("matrix_element", &FunctionBuilder::matrix_element, py::arg("args"));
    fb.def("collect_channel_weights", &FunctionBuilder::collect_channel_weights, py::arg("amp2"), py::arg("channel_indices"), py::arg("channel_count"));
    fb.def("interpolate_pdf", &FunctionBuilder::interpolate_pdf, py::arg("x"), py::arg("q"), py::arg("pid_indices"), py::arg("grid_logx"), py::arg("grid_logq2"), py::arg("grid_coeffs"));
    fb.def("interpolate_alpha_s", &FunctionBuilder::interpolate_alpha_s, py::arg("q"), py::arg("grid_logq2"), py::arg("grid_coeffs"));
    fb.def("matmul", &FunctionBuilder::matmul, py::arg("x"), py::arg("weight"), py::arg("bias"));
    fb.def("relu", &FunctionBuilder::relu, py::arg("in1"));
    fb.def("leaky_relu", &FunctionBuilder::leaky_relu, py::arg("in1"));
    fb.def("elu", &FunctionBuilder::elu, py::arg("in1"));
    fb.def("gelu", &FunctionBuilder::gelu, py::arg("in1"));
    fb.def("sigmoid", &FunctionBuilder::sigmoid, py::arg("in1"));
    fb.def("softplus", &FunctionBuilder::softplus, py::arg("in1"));
    fb.def("rqs_reshape", &FunctionBuilder::rqs_reshape, py::arg("input"), py::arg("bin_count"));
    fb.def("rqs_find_bin", &FunctionBuilder::rqs_find_bin, py::arg("input"), py::arg("in_sizes"), py::arg("out_sizes"), py::arg("derivatives"));
    fb.def("rqs_forward", &FunctionBuilder::rqs_forward, py::arg("input"), py::arg("condition"));
    fb.def("rqs_inverse", &FunctionBuilder::rqs_inverse, py::arg("input"), py::arg("condition"));
    fb.def("softmax", &FunctionBuilder::softmax, py::arg("input"));
    fb.def("softmax_prior", &FunctionBuilder::softmax_prior, py::arg("input"), py::arg("prior"));
    fb.def("sample_discrete", &FunctionBuilder::sample_discrete, py::arg("r"), py::arg("option_count"));
    fb.def("sample_discrete_inverse", &FunctionBuilder::sample_discrete_inverse, py::arg("index"), py::arg("option_count"));
    fb.def("sample_discrete_probs", &FunctionBuilder::sample_discrete_probs, py::arg("r"), py::arg("probs"));
    fb.def("sample_discrete_probs_inverse", &FunctionBuilder::sample_discrete_probs_inverse, py::arg("index"), py::arg("probs"));
    fb.def("discrete_histogram", &FunctionBuilder::discrete_histogram, py::arg("input"), py::arg("weights"), py::arg("option_count"));
    fb.def("permute_momenta", &FunctionBuilder::permute_momenta, py::arg("momenta"), py::arg("permutations"), py::arg("index"));
    fb.def("gather", &FunctionBuilder::gather, py::arg("index"), py::arg("choices"));
    fb.def("gather_int", &FunctionBuilder::gather_int, py::arg("index"), py::arg("choices"));
    fb.def("select_int", &FunctionBuilder::select_int, py::arg("input"), py::arg("indices"));
    fb.def("select", &FunctionBuilder::select, py::arg("input"), py::arg("indices"));
    fb.def("select_vector", &FunctionBuilder::select_vector, py::arg("input"), py::arg("indices"));
    fb.def("argsort", &FunctionBuilder::argsort, py::arg("input"));
    fb.def("quantile", &FunctionBuilder::quantile, py::arg("input"), py::arg("q"));
    fb.def("one_hot", &FunctionBuilder::one_hot, py::arg("index"), py::arg("option_count"));
    fb.def("madnis_abs_weight", &FunctionBuilder::madnis_abs_weight, py::arg("f"), py::arg("q"));
    fb.def("madnis_softclip", &FunctionBuilder::madnis_softclip, py::arg("f"), py::arg("q"), py::arg("norm"), py::arg("threshold"));
    fb.def("madnis_variance", &FunctionBuilder::madnis_variance, py::arg("f"), py::arg("g"), py::arg("q"), py::arg("mean"));
    fb.def("madnis_single_channel_variance", &FunctionBuilder::madnis_single_channel_variance, py::arg("var"), py::arg("abs_mean"));
    fb.def("madnis_multi_channel_variance", &FunctionBuilder::madnis_multi_channel_variance, py::arg("vars"), py::arg("abs_means"));
    fb.def("nonzero", &FunctionBuilder::nonzero, py::arg("input"));
    fb.def("batch_gather", &FunctionBuilder::batch_gather, py::arg("indices"), py::arg("values"));
    fb.def("batch_scatter", &FunctionBuilder::batch_scatter, py::arg("indices"), py::arg("target"), py::arg("source"));
    fb.def("random", &FunctionBuilder::random, py::arg("batch_size"), py::arg("count"));
    fb.def("random_int", &FunctionBuilder::random_int, py::arg("batch_size"), py::arg("max"));
    fb.def("unweight", &FunctionBuilder::unweight, py::arg("weights"), py::arg("max_weight"));
    fb.def("vegas_forward", &FunctionBuilder::vegas_forward, py::arg("input"), py::arg("grid"));
    fb.def("vegas_inverse", &FunctionBuilder::vegas_inverse, py::arg("input"), py::arg("grid"));
    fb.def("vegas_histogram", &FunctionBuilder::vegas_histogram, py::arg("input"), py::arg("weights"), py::arg("bin_count"));
    fb.def("histogram", &FunctionBuilder::histogram, py::arg("input"), py::arg("weights"), py::arg("min"), py::arg("max"), py::arg("bin_count"));
}
}
