C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(3,2,-1)*ProjP(-1,1)
C     
      SUBROUTINE FFV6M_3(F1, F2, MCOUP, M3, W3,V3)
      USE ALOHA_OBJECT
      USE MODEL_OBJECT
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 CZERO
      PARAMETER (CZERO=(0D0,0D0))
      TYPE(FLV_COUPLING) MCOUP
      DOUBLE COMPLEX COUP
      INTEGER FLV_INDEX
      TYPE(ALOHA) F1
      INTEGER FLV_INDEX1
      TYPE(ALOHA) F2
      INTEGER FLV_INDEX2
      REAL*8 M3
      REAL*8 P3(0:3)
      TYPE(ALOHA) V3
      REAL*8 W3
      COMPLEX*16 DENOM
      INTEGER*4 I
      V3%P(:) = +F1%P(:)+F2%P(:)
      P3(:) = -V3 % P (:)
      V3 % W(:) = CZERO
      FLV_INDEX1 = F1 %FLV_INDEX
      FLV_INDEX2 = F2 %FLV_INDEX
      IF(FLV_INDEX1.EQ.0.OR.FLV_INDEX2.EQ.0)THEN
        V3%W(:) = (0D0,0D0)
        RETURN
      ENDIF
      IF(MCOUP % PARTNER(FLV_INDEX1).NE.FLV_INDEX2)THEN
        V3%W(:) = (0D0,0D0)
        RETURN
      ENDIF
      COUP = MCOUP % VAL(FLV_INDEX1) % P
      DENOM = COUP/(P3(0)**2-P3(1)**2-P3(2)**2-P3(3)**2 - M3 * (M3 -CI
     $ * W3))
      V3%W(1)= DENOM*(-CI)*(F1 % W(3)*F2 % W(1)+F1 % W(4)*F2 % W(2))
      V3%W(2)= DENOM*(-CI)*(F1 % W(3)*F2 % W(2)+F1 % W(4)*F2 % W(1))
      V3%W(3)= DENOM*(-CI)*(+CI*(F1 % W(3)*F2 % W(2))-CI*(F1 % W(4)*F2
     $  % W(1)))
      V3%W(4)= DENOM*(-CI)*(F1 % W(3)*F2 % W(1)-F1 % W(4)*F2 % W(2))
      CALL MULTIPLY_PROPAGATOR_FACTOR(V3,M3, V3)
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(3,2,-1)*ProjP(-1,1)
C     
      SUBROUTINE FFV6_2M_3(F1, F2, MCOUP1, MCOUP2, M3, W3,V3)
      USE ALOHA_OBJECT
      USE MODEL_OBJECT
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 CZERO
      PARAMETER (CZERO=(0D0,0D0))
      TYPE(FLV_COUPLING) MCOUP1
      DOUBLE COMPLEX COUP1
      INTEGER FLV_INDEX
      TYPE(FLV_COUPLING) MCOUP2
      DOUBLE COMPLEX COUP2
      TYPE(ALOHA) F1
      INTEGER FLV_INDEX1
      TYPE(ALOHA) F2
      INTEGER FLV_INDEX2
      REAL*8 M3
      REAL*8 P3(0:3)
      TYPE(ALOHA) V3
      TYPE(ALOHA) VTMP
      REAL*8 W3
      COMPLEX*16 DENOM
      INTEGER*4 I
      CALL FFV6M_3(F1,F2,MCOUP1,M3,W3,V3)
      CALL FFV2M_3(F1,F2,MCOUP2,M3,W3,VTMP)
      DO I = 1, 5
        V3 %W(I) = V3%W(I) + VTMP%W(I)
      ENDDO
      END


