C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(3,2,-1)*ProjP(-1,1)
C     
      SUBROUTINE FFV6M_0(F1, F2, V3, MCOUP,VERTEX)
      USE ALOHA_OBJECT
      USE MODEL_OBJECT
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 CZERO
      PARAMETER (CZERO=(0D0,0D0))
      TYPE(FLV_COUPLING) MCOUP
      DOUBLE COMPLEX COUP
      INTEGER FLV_INDEX
      TYPE(ALOHA) F1
      INTEGER FLV_INDEX1
      TYPE(ALOHA) F2
      INTEGER FLV_INDEX2
      COMPLEX*16 TMP0
      TYPE(ALOHA) V3
      INTEGER*4 I
      COMPLEX*16 VERTEX
      FLV_INDEX1 = F1 %FLV_INDEX
      FLV_INDEX2 = F2 %FLV_INDEX
      IF(FLV_INDEX1.EQ.0.OR.FLV_INDEX2.EQ.0)THEN
        VERTEX = (0D0,0D0)
        RETURN
      ENDIF
      IF(MCOUP % PARTNER(FLV_INDEX1).NE.FLV_INDEX2)THEN
        VERTEX = (0D0,0D0)
        RETURN
      ENDIF
      COUP = MCOUP % VAL(FLV_INDEX1) % P
      TMP0 = (F1 % W(3)*(F2 % W(1)*(V3 % W(1)-V3 % W(4))-F2 % W(2)*(V3
     $  % W(2)+CI*(V3 % W(3))))+F1 % W(4)*(F2 % W(1)*(-V3 % W(2)+CI
     $ *(V3 % W(3)))+F2 % W(2)*(V3 % W(1)+V3 % W(4))))
      VERTEX = COUP*(-CI * TMP0)
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(3,2,-1)*ProjP(-1,1)
C     
      SUBROUTINE FFV6_2M_0(F1, F2, V3, MCOUP1, MCOUP2,VERTEX)
      USE ALOHA_OBJECT
      USE MODEL_OBJECT
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 CZERO
      PARAMETER (CZERO=(0D0,0D0))
      TYPE(FLV_COUPLING) MCOUP1
      DOUBLE COMPLEX COUP1
      INTEGER FLV_INDEX
      TYPE(FLV_COUPLING) MCOUP2
      DOUBLE COMPLEX COUP2
      TYPE(ALOHA) F1
      INTEGER FLV_INDEX1
      TYPE(ALOHA) F2
      INTEGER FLV_INDEX2
      TYPE(ALOHA) V3
      INTEGER*4 I
      COMPLEX*16 TMP
      COMPLEX*16 VERTEX
      CALL FFV6M_0(F1,F2,V3,MCOUP1,VERTEX)
      CALL FFV2M_0(F1,F2,V3,MCOUP2,TMP)
      VERTEX = VERTEX + TMP
      END


