C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(2,1) - P(2,3)
C     
      SUBROUTINE SVS1_2(S1, S3, COUP, M2, W2,V2)
      USE ALOHA_OBJECT
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 CZERO
      PARAMETER (CZERO=(0D0,0D0))
      COMPLEX*16 COUP
      REAL*8 M2
      REAL*8 P1(0:3)
      REAL*8 P2(0:3)
      REAL*8 P3(0:3)
      TYPE(ALOHA) S1
      TYPE(ALOHA) S3
      TYPE(ALOHA) V2
      REAL*8 W2
      COMPLEX*16 DENOM
      INTEGER*4 I
      P1(:) = S1 % P (:)
      P3(:) = S3 % P (:)
      V2%P(:) = +S1%P(:)+S3%P(:)
      P2(:) = -V2 % P (:)
      V2 % W(:) = CZERO
      DENOM = COUP/(P2(0)**2-P2(1)**2-P2(2)**2-P2(3)**2 - M2 * (M2 -CI
     $ * W2))
      V2%W(1)= DENOM*S1 % W(1)*S3 % W(1)*(-CI*(P1(0))+CI*(P3(0)))
      V2%W(2)= DENOM*S1 % W(1)*S3 % W(1)*(-CI*(P1(1))+CI*(P3(1)))
      V2%W(3)= DENOM*S1 % W(1)*S3 % W(1)*(-CI*(P1(2))+CI*(P3(2)))
      V2%W(4)= DENOM*S1 % W(1)*S3 % W(1)*(-CI*(P1(3))+CI*(P3(3)))
      CALL MULTIPLY_PROPAGATOR_FACTOR(V2,M2, V2)
      END


