C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(1,2) - P(1,3)
C     
      SUBROUTINE VSS1_0(V1, S2, S3, COUP,VERTEX)
      USE ALOHA_OBJECT
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 CZERO
      PARAMETER (CZERO=(0D0,0D0))
      COMPLEX*16 COUP
      REAL*8 P2(0:3)
      REAL*8 P3(0:3)
      TYPE(ALOHA) S2
      TYPE(ALOHA) S3
      COMPLEX*16 TMP3
      COMPLEX*16 TMP4
      TYPE(ALOHA) V1
      INTEGER*4 I
      COMPLEX*16 VERTEX
      P2(:) = S2 % P (:)
      P3(:) = S3 % P (:)
      TMP3 = (P2(0)*V1 % W(1)-P2(1)*V1 % W(2)-P2(2)*V1 % W(3)-P2(3)*V1
     $  % W(4))
      TMP4 = (V1 % W(1)*P3(0)-V1 % W(2)*P3(1)-V1 % W(3)*P3(2)-V1 % W(4)
     $ *P3(3))
      VERTEX = COUP*S2 % W(1)*S3 % W(1)*(-CI*(TMP3)+CI*(TMP4))
      END


