C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(1,2)
C     
      SUBROUTINE VVS1_1(V2, S3, COUP, M1, W1,V1)
      USE ALOHA_OBJECT
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 CZERO
      PARAMETER (CZERO=(0D0,0D0))
      COMPLEX*16 COUP
      REAL*8 M1
      REAL*8 P1(0:3)
      TYPE(ALOHA) S3
      TYPE(ALOHA) V1
      TYPE(ALOHA) V2
      REAL*8 W1
      COMPLEX*16 DENOM
      INTEGER*4 I
      V1%P(:) = +V2%P(:)+S3%P(:)
      P1(:) = -V1 % P (:)
      V1 % W(:) = CZERO
      DENOM = COUP/(P1(0)**2-P1(1)**2-P1(2)**2-P1(3)**2 - M1 * (M1 -CI
     $ * W1))
      V1%W(1)= DENOM*(-CI )* V2 % W(1)*S3 % W(1)
      V1%W(2)= DENOM*(-CI )* V2 % W(2)*S3 % W(1)
      V1%W(3)= DENOM*(-CI )* V2 % W(3)*S3 % W(1)
      V1%W(4)= DENOM*(-CI )* V2 % W(4)*S3 % W(1)
      CALL MULTIPLY_PROPAGATOR_FACTOR(V1,M1, V1)
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(1,2)
C     
      SUBROUTINE VVS1_SSS1_VSS1_SVS1_1(V2, S3, COUP1, COUP2, COUP3,
     $  COUP4, M1, W1,V1)
      USE ALOHA_OBJECT
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 CZERO
      PARAMETER (CZERO=(0D0,0D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 COUP3
      COMPLEX*16 COUP4
      REAL*8 M1
      REAL*8 P1(0:3)
      TYPE(ALOHA) S3
      TYPE(ALOHA) V1
      TYPE(ALOHA) V2
      TYPE(ALOHA) VTMP
      REAL*8 W1
      COMPLEX*16 DENOM
      INTEGER*4 I
      CALL VVS1_1(V2,S3,COUP1,M1,W1,V1)
      CALL SSS1_1(V2,S3,COUP2,M1,W1,VTMP)
      DO I = 1, 5
        V1 %W(I) = V1%W(I) + VTMP%W(I)
      ENDDO
      CALL VSS1_1(V2,S3,COUP3,M1,W1,VTMP)
      DO I = 1, 5
        V1 %W(I) = V1%W(I) + VTMP%W(I)
      ENDDO
      CALL SVS1_1(V2,S3,COUP4,M1,W1,VTMP)
      DO I = 1, 5
        V1 %W(I) = V1%W(I) + VTMP%W(I)
      ENDDO
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(1,2)
C     
      SUBROUTINE VVS1_VSS1_SVS1_SSS1_1(V2, S3, COUP1, COUP2, COUP3,
     $  COUP4, M1, W1,V1)
      USE ALOHA_OBJECT
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 CZERO
      PARAMETER (CZERO=(0D0,0D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 COUP3
      COMPLEX*16 COUP4
      REAL*8 M1
      REAL*8 P1(0:3)
      TYPE(ALOHA) S3
      TYPE(ALOHA) V1
      TYPE(ALOHA) V2
      TYPE(ALOHA) VTMP
      REAL*8 W1
      COMPLEX*16 DENOM
      INTEGER*4 I
      CALL VVS1_1(V2,S3,COUP1,M1,W1,V1)
      CALL VSS1_1(V2,S3,COUP2,M1,W1,VTMP)
      DO I = 1, 5
        V1 %W(I) = V1%W(I) + VTMP%W(I)
      ENDDO
      CALL SVS1_1(V2,S3,COUP3,M1,W1,VTMP)
      DO I = 1, 5
        V1 %W(I) = V1%W(I) + VTMP%W(I)
      ENDDO
      CALL SSS1_1(V2,S3,COUP4,M1,W1,VTMP)
      DO I = 1, 5
        V1 %W(I) = V1%W(I) + VTMP%W(I)
      ENDDO
      END


