name: Restore looptools cache
description: Restores looptools from cache and sets MG5 accordingly

inputs:
  setup_only:
    required: false
    default: "false"

runs:
  using: composite
  steps:

    - name: Set cache key
      run: echo "CACHE_KEY=looptools-$ImageOS" >> $GITHUB_ENV
      shell: bash

    - uses: actions/cache/restore@v5
      if: ${{ inputs.setup_only != 'true' }}
      with:
        path: ~/.cache/HEPtools
        key: ${{ env.CACHE_KEY }}

    # this ignore cuttools/iregi cache ... ok but we should try to fix that
    - run: |
        cd $GITHUB_WORKSPACE
        echo "ninja = /home/runner/.cache/HEPtools/ninja/lib" >>  input/mg5_configuration.txt
        echo "collier = /home/runner/.cache/HEPtools/collier" >>  input/mg5_configuration.txt
      shell: bash
