      SUBROUTINE SMATRIXHEL(P,HEL, FLAVOR, ANS)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=64)
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: HEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
CF2PY INTENT(IN) :: FLAVOR(NEXTERNAL)

C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER HEL
      INTEGER FLAVOR(NEXTERNAL)
C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/HELUSERCHOICE/USERHEL
C     ----------
C     BEGIN CODE
C     ----------
      USERHEL=HEL
      CALL SMATRIX(P,FLAVOR,ANS)
      USERHEL=-1

      END

      SUBROUTINE SMATRIX(P, FLAVOR, ANS)
C     
C     Generated by MadGraph5_aMC@NLO v. %(version)s, %(date)s
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     MadGraph5_aMC@NLO StandAlone Version
C     
C     Returns amplitude squared summed/avg over colors
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL)
C     
C     Process: u u~ > u u~ u u~
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
      INTEGER    NINITIAL
      PARAMETER (NINITIAL=2)
      INTEGER NPOLENTRIES
      PARAMETER (NPOLENTRIES=(NEXTERNAL+1)*6)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=64)
      INTEGER HELAVGFACTOR
      PARAMETER (HELAVGFACTOR=4)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
CF2PY INTENT(IN) :: FLAVOR(NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER NHEL(NEXTERNAL,NCOMB),NTRY
C     put in common block to expose this variable to python interface
      COMMON/PROCESS_NHEL/NHEL
      REAL*8 T
      REAL*8 MATRIX
      INTEGER IHEL,IDEN, I, J
C     For a 1>N process, them BEAMTWO_HELAVGFACTOR would be set to 1.
      INTEGER BEAMS_HELAVGFACTOR(2)
      DATA (BEAMS_HELAVGFACTOR(I),I=1,2)/2,2/
      INTEGER FLAVOR(NEXTERNAL)
      LOGICAL GOODHEL(NCOMB)
      DATA NTRY/0/
      DATA GOODHEL/NCOMB*.FALSE./

C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/HELUSERCHOICE/USERHEL
      DATA USERHEL/-1/
      LOGICAL HELRESET
      COMMON/HELRESET/HELRESET
      DATA HELRESET/.TRUE./

      DATA (NHEL(I,   1),I=1,6) / 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,   2),I=1,6) / 1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,   3),I=1,6) / 1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,   4),I=1,6) / 1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,   5),I=1,6) / 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,   6),I=1,6) / 1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,   7),I=1,6) / 1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,   8),I=1,6) / 1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,   9),I=1,6) / 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,  10),I=1,6) / 1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,  11),I=1,6) / 1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,  12),I=1,6) / 1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,  13),I=1,6) / 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,  14),I=1,6) / 1,-1, 1,-1,-1,-1/
      DATA (NHEL(I,  15),I=1,6) / 1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,  16),I=1,6) / 1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,  17),I=1,6) / 1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,  18),I=1,6) / 1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,  19),I=1,6) / 1, 1,-1, 1, 1, 1/
      DATA (NHEL(I,  20),I=1,6) / 1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,  21),I=1,6) / 1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,  22),I=1,6) / 1, 1,-1,-1,-1,-1/
      DATA (NHEL(I,  23),I=1,6) / 1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,  24),I=1,6) / 1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,  25),I=1,6) / 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,  26),I=1,6) / 1, 1, 1, 1,-1,-1/
      DATA (NHEL(I,  27),I=1,6) / 1, 1, 1, 1, 1, 1/
      DATA (NHEL(I,  28),I=1,6) / 1, 1, 1, 1, 1,-1/
      DATA (NHEL(I,  29),I=1,6) / 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,  30),I=1,6) / 1, 1, 1,-1,-1,-1/
      DATA (NHEL(I,  31),I=1,6) / 1, 1, 1,-1, 1, 1/
      DATA (NHEL(I,  32),I=1,6) / 1, 1, 1,-1, 1,-1/
      DATA (NHEL(I,  33),I=1,6) /-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,  34),I=1,6) /-1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,  35),I=1,6) /-1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,  36),I=1,6) /-1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,  37),I=1,6) /-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,  38),I=1,6) /-1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,  39),I=1,6) /-1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,  40),I=1,6) /-1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,  41),I=1,6) /-1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,  42),I=1,6) /-1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,  43),I=1,6) /-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,  44),I=1,6) /-1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,  45),I=1,6) /-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,  46),I=1,6) /-1,-1, 1,-1,-1,-1/
      DATA (NHEL(I,  47),I=1,6) /-1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,  48),I=1,6) /-1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,  49),I=1,6) /-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,  50),I=1,6) /-1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,  51),I=1,6) /-1, 1,-1, 1, 1, 1/
      DATA (NHEL(I,  52),I=1,6) /-1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,  53),I=1,6) /-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,  54),I=1,6) /-1, 1,-1,-1,-1,-1/
      DATA (NHEL(I,  55),I=1,6) /-1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,  56),I=1,6) /-1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,  57),I=1,6) /-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,  58),I=1,6) /-1, 1, 1, 1,-1,-1/
      DATA (NHEL(I,  59),I=1,6) /-1, 1, 1, 1, 1, 1/
      DATA (NHEL(I,  60),I=1,6) /-1, 1, 1, 1, 1,-1/
      DATA (NHEL(I,  61),I=1,6) /-1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,  62),I=1,6) /-1, 1, 1,-1,-1,-1/
      DATA (NHEL(I,  63),I=1,6) /-1, 1, 1,-1, 1, 1/
      DATA (NHEL(I,  64),I=1,6) /-1, 1, 1,-1, 1,-1/
      DATA IDEN/144/

      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      COMMON/BORN_BEAM_POL/POLARIZATIONS
      DATA ((POLARIZATIONS(I,J),I=0,NEXTERNAL),J=0,5)/NPOLENTRIES*-1/

C     
C     FUNCTIONS
C     
      LOGICAL IS_BORN_HEL_SELECTED
      INTEGER BROKEN_SYM
C     ----------
C     Check if helreset mode is on
C     ---------
      IF (HELRESET) THEN
        NTRY = 0
        DO I=1,NCOMB
          GOODHEL(I) = .FALSE.
        ENDDO
        HELRESET = .FALSE.
      ENDIF

C     ----------
C     BEGIN CODE
C     ----------
      IF(USERHEL.EQ.-1) NTRY=NTRY+1
C     When spin-2 particles are involved, the Helicity filtering is
C      dangerous for the 2->1 topology.
C     This is because depending on the MC setup the initial PS points
C      have back-to-back initial states
C     for which some of the spin-2 helicity configurations are zero.
C      But they are no longer zero
C     if the point is boosted on the z-axis. Remember that HELAS
C      helicity amplitudes are no longer
C     lorentz invariant with expternal spin-2 particles (only the
C      helicity sum is).
C     For this reason, we simply remove the filterin when there is
C      only three external particles.
      IF (NEXTERNAL.LE.3) THEN
        DO IHEL=1,NCOMB
          GOODHEL(IHEL)=.TRUE.
        ENDDO
      ENDIF
      ANS = 0D0
      DO IHEL=1,NCOMB
        IF (USERHEL.EQ.-1.OR.USERHEL.EQ.IHEL) THEN
          IF (GOODHEL(IHEL) .OR. NTRY .LT. 20.OR.USERHEL.NE.-1) THEN
            IF(NTRY.GE.2.AND.POLARIZATIONS(0,0).NE.
     $       -1.AND.(.NOT.IS_BORN_HEL_SELECTED(IHEL))) THEN
              CYCLE
            ENDIF
            T=MATRIX(P ,NHEL(1,IHEL),FLAVOR(1))
            IF(POLARIZATIONS(0,0).EQ.-1.OR.IS_BORN_HEL_SELECTED(IHEL))
     $        THEN
              ANS=ANS+T
            ENDIF
            IF (T .NE. 0D0 .AND. .NOT.    GOODHEL(IHEL)) THEN
              GOODHEL(IHEL)=.TRUE.
            ENDIF
          ENDIF
        ENDIF
      ENDDO
      ANS=ANS/DBLE(IDEN)*BROKEN_SYM(FLAVOR)
      IF(USERHEL.NE.-1) THEN
        ANS=ANS*HELAVGFACTOR
      ELSE
        DO J=1,NINITIAL
          IF (POLARIZATIONS(J,0).NE.-1) THEN
            ANS=ANS*BEAMS_HELAVGFACTOR(J)
            ANS=ANS/POLARIZATIONS(J,0)
          ENDIF
        ENDDO
      ENDIF
      END


      REAL*8 FUNCTION MATRIX(P,NHEL,FLAVOR)
      USE MODEL_OBJECT
C     
C     Generated by MadGraph5_aMC@NLO v. %(version)s, %(date)s
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared -- no average over initial
C      state/symmetry factor
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: u u~ > u u~ u u~
C     
      USE ALOHA_OBJECT
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=42)
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
      INTEGER    NWAVEFUNCS, NCOLOR
      PARAMETER (NWAVEFUNCS=16, NCOLOR=6)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL)
      INTEGER FLAVOR(NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J
      COMPLEX*16 ZTEMP
      INTEGER CF_INDEX
      INTEGER CF(NCOLOR*(NCOLOR+1)/2)
      INTEGER DENOM
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR), TMP_JAMP(55)
      TYPE(ALOHA) W(NWAVEFUNCS)
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
      DOUBLE PRECISION BWCUTOFF
C     
C     GLOBAL VARIABLES
C     
      INCLUDE 'coupl.inc'

C     
C     COLOR DATA
C     
      DATA DENOM/1/
      DATA (CF(I),I=  1,  6) /27,18,18,6,6,18/
C     1 T(2,1) T(3,4) T(5,6)
      DATA (CF(I),I=  7, 11) /27,6,18,18,6/
C     1 T(2,1) T(3,6) T(5,4)
      DATA (CF(I),I= 12, 15) /27,18,18,6/
C     1 T(2,4) T(3,1) T(5,6)
      DATA (CF(I),I= 16, 18) /27,6,18/
C     1 T(2,4) T(3,6) T(5,1)
      DATA (CF(I),I= 19, 20) /27,18/
C     1 T(2,6) T(3,1) T(5,4)
      DATA (CF(I),I= 21, 21) /27/
C     1 T(2,6) T(3,4) T(5,1)
C     ----------
C     BEGIN CODE
C     ----------
      BWCUTOFF=15  ! use if $ syntax is defined in the process
      CALL IXXXXX(P(0,1),ZERO,NHEL(1),+1, FLAVOR(1),W(1))
      CALL OXXXXX(P(0,2),ZERO,NHEL(2),-1, FLAVOR(2),W(2))
      CALL OXXXXX(P(0,3),ZERO,NHEL(3),+1, FLAVOR(3),W(3))
      CALL IXXXXX(P(0,4),ZERO,NHEL(4),-1, FLAVOR(4),W(4))
      CALL OXXXXX(P(0,5),ZERO,NHEL(5),+1, FLAVOR(5),W(5))
      CALL IXXXXX(P(0,6),ZERO,NHEL(6),-1, FLAVOR(6),W(6))
      CALL JIOXXX(W(1),W(2),GG,ZERO,ZERO,W(7))
      CALL JIOXXX(W(4),W(3),GG,ZERO,ZERO,W(8))
      CALL FVOXXX(W(5),W(7),GG,ZERO,ZERO,W(9))
C     Amplitude(s) for diagram number 1
      CALL IOVXXX(W(6),W(9),W(8),GG,AMP(1))
      CALL FVIXXX(W(6),W(7),GG,ZERO,ZERO,W(10))
C     Amplitude(s) for diagram number 2
      CALL IOVXXX(W(10),W(5),W(8),GG,AMP(2))
      CALL JIOXXX(W(6),W(5),GG,ZERO,ZERO,W(11))
C     Amplitude(s) for diagram number 3
      CALL VVVXXX(W(7),W(8),W(11),GG,AMP(3))
      CALL JIOXXX(W(6),W(3),GG,ZERO,ZERO,W(12))
      CALL FVIXXX(W(4),W(7),GG,ZERO,ZERO,W(13))
C     Amplitude(s) for diagram number 4
      CALL IOVXXX(W(13),W(5),W(12),GG,AMP(4))
C     Amplitude(s) for diagram number 5
      CALL IOVXXX(W(4),W(9),W(12),GG,AMP(5))
      CALL JIOXXX(W(4),W(5),GG,ZERO,ZERO,W(9))
C     Amplitude(s) for diagram number 6
      CALL VVVXXX(W(7),W(12),W(9),GG,AMP(6))
      CALL FVOXXX(W(3),W(7),GG,ZERO,ZERO,W(14))
C     Amplitude(s) for diagram number 7
      CALL IOVXXX(W(6),W(14),W(9),GG,AMP(7))
C     Amplitude(s) for diagram number 8
      CALL IOVXXX(W(10),W(3),W(9),GG,AMP(8))
C     Amplitude(s) for diagram number 9
      CALL IOVXXX(W(4),W(14),W(11),GG,AMP(9))
C     Amplitude(s) for diagram number 10
      CALL IOVXXX(W(13),W(3),W(11),GG,AMP(10))
      CALL JIOXXX(W(1),W(3),GG,ZERO,ZERO,W(13))
      CALL JIOXXX(W(4),W(2),GG,ZERO,ZERO,W(14))
      CALL FVOXXX(W(5),W(13),GG,ZERO,ZERO,W(10))
C     Amplitude(s) for diagram number 11
      CALL IOVXXX(W(6),W(10),W(14),GG,AMP(11))
      CALL FVIXXX(W(6),W(13),GG,ZERO,ZERO,W(7))
C     Amplitude(s) for diagram number 12
      CALL IOVXXX(W(7),W(5),W(14),GG,AMP(12))
C     Amplitude(s) for diagram number 13
      CALL VVVXXX(W(13),W(14),W(11),GG,AMP(13))
      CALL JIOXXX(W(6),W(2),GG,ZERO,ZERO,W(15))
      CALL FVIXXX(W(4),W(13),GG,ZERO,ZERO,W(16))
C     Amplitude(s) for diagram number 14
      CALL IOVXXX(W(16),W(5),W(15),GG,AMP(14))
C     Amplitude(s) for diagram number 15
      CALL IOVXXX(W(4),W(10),W(15),GG,AMP(15))
C     Amplitude(s) for diagram number 16
      CALL VVVXXX(W(13),W(15),W(9),GG,AMP(16))
      CALL FVOXXX(W(2),W(13),GG,ZERO,ZERO,W(10))
C     Amplitude(s) for diagram number 17
      CALL IOVXXX(W(6),W(10),W(9),GG,AMP(17))
C     Amplitude(s) for diagram number 18
      CALL IOVXXX(W(7),W(2),W(9),GG,AMP(18))
C     Amplitude(s) for diagram number 19
      CALL IOVXXX(W(4),W(10),W(11),GG,AMP(19))
C     Amplitude(s) for diagram number 20
      CALL IOVXXX(W(16),W(2),W(11),GG,AMP(20))
      CALL JIOXXX(W(1),W(5),GG,ZERO,ZERO,W(16))
      CALL FVOXXX(W(3),W(16),GG,ZERO,ZERO,W(10))
C     Amplitude(s) for diagram number 21
      CALL IOVXXX(W(6),W(10),W(14),GG,AMP(21))
      CALL FVIXXX(W(6),W(16),GG,ZERO,ZERO,W(7))
C     Amplitude(s) for diagram number 22
      CALL IOVXXX(W(7),W(3),W(14),GG,AMP(22))
C     Amplitude(s) for diagram number 23
      CALL VVVXXX(W(16),W(14),W(12),GG,AMP(23))
C     Amplitude(s) for diagram number 24
      CALL IOVXXX(W(4),W(10),W(15),GG,AMP(24))
      CALL FVIXXX(W(4),W(16),GG,ZERO,ZERO,W(10))
C     Amplitude(s) for diagram number 25
      CALL IOVXXX(W(10),W(3),W(15),GG,AMP(25))
C     Amplitude(s) for diagram number 26
      CALL VVVXXX(W(16),W(15),W(8),GG,AMP(26))
      CALL FVOXXX(W(2),W(16),GG,ZERO,ZERO,W(13))
C     Amplitude(s) for diagram number 27
      CALL IOVXXX(W(6),W(13),W(8),GG,AMP(27))
C     Amplitude(s) for diagram number 28
      CALL IOVXXX(W(7),W(2),W(8),GG,AMP(28))
C     Amplitude(s) for diagram number 29
      CALL IOVXXX(W(4),W(13),W(12),GG,AMP(29))
C     Amplitude(s) for diagram number 30
      CALL IOVXXX(W(10),W(2),W(12),GG,AMP(30))
      CALL FVIXXX(W(1),W(14),GG,ZERO,ZERO,W(10))
C     Amplitude(s) for diagram number 31
      CALL IOVXXX(W(10),W(5),W(12),GG,AMP(31))
      CALL FVIXXX(W(1),W(12),GG,ZERO,ZERO,W(13))
C     Amplitude(s) for diagram number 32
      CALL IOVXXX(W(13),W(5),W(14),GG,AMP(32))
C     Amplitude(s) for diagram number 33
      CALL IOVXXX(W(10),W(3),W(11),GG,AMP(33))
      CALL FVIXXX(W(1),W(11),GG,ZERO,ZERO,W(10))
C     Amplitude(s) for diagram number 34
      CALL IOVXXX(W(10),W(3),W(14),GG,AMP(34))
      CALL FVIXXX(W(1),W(15),GG,ZERO,ZERO,W(14))
C     Amplitude(s) for diagram number 35
      CALL IOVXXX(W(14),W(5),W(8),GG,AMP(35))
      CALL FVIXXX(W(1),W(8),GG,ZERO,ZERO,W(4))
C     Amplitude(s) for diagram number 36
      CALL IOVXXX(W(4),W(5),W(15),GG,AMP(36))
C     Amplitude(s) for diagram number 37
      CALL IOVXXX(W(14),W(3),W(9),GG,AMP(37))
      CALL FVIXXX(W(1),W(9),GG,ZERO,ZERO,W(14))
C     Amplitude(s) for diagram number 38
      CALL IOVXXX(W(14),W(3),W(15),GG,AMP(38))
C     Amplitude(s) for diagram number 39
      CALL IOVXXX(W(4),W(2),W(11),GG,AMP(39))
C     Amplitude(s) for diagram number 40
      CALL IOVXXX(W(10),W(2),W(8),GG,AMP(40))
C     Amplitude(s) for diagram number 41
      CALL IOVXXX(W(13),W(2),W(9),GG,AMP(41))
C     Amplitude(s) for diagram number 42
      CALL IOVXXX(W(14),W(2),W(12),GG,AMP(42))
      TMP_JAMP(39) = AMP(39) +  AMP(40)  ! used 3 times
      TMP_JAMP(38) = AMP(37) +  AMP(38)  ! used 3 times
      TMP_JAMP(37) = AMP(35) +  AMP(36)  ! used 3 times
      TMP_JAMP(36) = AMP(29) +  AMP(37)  ! used 3 times
      TMP_JAMP(35) = AMP(29) +  AMP(30)  ! used 3 times
      TMP_JAMP(34) = AMP(28) +  AMP(36)  ! used 3 times
      TMP_JAMP(33) = AMP(27) +  AMP(35)  ! used 3 times
      TMP_JAMP(32) = AMP(27) +  AMP(28)  ! used 3 times
      TMP_JAMP(31) = AMP(25) +  AMP(35)  ! used 3 times
      TMP_JAMP(30) = AMP(25) +  AMP(27)  ! used 3 times
      TMP_JAMP(29) = AMP(24) +  AMP(25)  ! used 3 times
      TMP_JAMP(28) = AMP(21) +  AMP(22)  ! used 3 times
      TMP_JAMP(27) = AMP(20) +  AMP(34)  ! used 3 times
      TMP_JAMP(26) = AMP(14) +  AMP(22)  ! used 3 times
      TMP_JAMP(25) = AMP(14) +  AMP(15)  ! used 3 times
      TMP_JAMP(24) = AMP(11) +  AMP(34)  ! used 3 times
      TMP_JAMP(23) = AMP(11) +  AMP(20)  ! used 3 times
      TMP_JAMP(22) = AMP(5) +  AMP(8)  ! used 3 times
      TMP_JAMP(21) = AMP(1) +  AMP(2)  ! used 3 times
      TMP_JAMP(20) = AMP(41) +  AMP(42)  ! used 3 times
      TMP_JAMP(19) = AMP(30) +  AMP(32)  ! used 3 times
      TMP_JAMP(18) = AMP(24) +  AMP(41)  ! used 3 times
      TMP_JAMP(17) = AMP(21) +  AMP(32)  ! used 3 times
      TMP_JAMP(16) = AMP(19) +  AMP(20)  ! used 3 times
      TMP_JAMP(15) = AMP(18) +  AMP(38)  ! used 3 times
      TMP_JAMP(14) = AMP(15) +  AMP(18)  ! used 3 times
      TMP_JAMP(13) = AMP(14) +  AMP(17)  ! used 3 times
      TMP_JAMP(12) = AMP(12) +  AMP(25)  ! used 3 times
      TMP_JAMP(11) = AMP(11) +  AMP(12)  ! used 3 times
      TMP_JAMP(10) = AMP(7) +  AMP(8)  ! used 3 times
      TMP_JAMP(9) = AMP(2) +  AMP(9)  ! used 3 times
      TMP_JAMP(8) = AMP(22) +  AMP(31)  ! used 3 times
      TMP_JAMP(7) = AMP(12) +  AMP(33)  ! used 3 times
      TMP_JAMP(6) = AMP(4) +  AMP(5)  ! used 3 times
      TMP_JAMP(5) = AMP(1) +  AMP(10)  ! used 3 times
      TMP_JAMP(4) = AMP(19) +  AMP(33)  ! used 3 times
      TMP_JAMP(3) = AMP(17) +  AMP(31)  ! used 3 times
      TMP_JAMP(2) = AMP(9) +  AMP(10)  ! used 3 times
      TMP_JAMP(1) = AMP(4) +  AMP(7)  ! used 3 times
      TMP_JAMP(52) = TMP_JAMP(38) + (3.000000000000000D+00) * AMP(42)  ! used 2 times
      TMP_JAMP(51) = TMP_JAMP(37) +  TMP_JAMP(32)  ! used 2 times
      TMP_JAMP(50) = TMP_JAMP(36) + (3.333333333333333D-01) *
     $  TMP_JAMP(22)  ! used 2 times
      TMP_JAMP(49) = TMP_JAMP(35) + (3.000000000000000D+00) * AMP(42)  ! used 2 times
      TMP_JAMP(48) = TMP_JAMP(27) + (3.000000000000000D+00) *
     $  TMP_JAMP(26)  ! used 2 times
      TMP_JAMP(47) = TMP_JAMP(22) + (3.333333333333333D-01) *
     $  TMP_JAMP(21)  ! used 2 times
      TMP_JAMP(46) = TMP_JAMP(18) + (3.333333333333333D-01) *
     $  TMP_JAMP(14)  ! used 2 times
      TMP_JAMP(45) = TMP_JAMP(18) + (3.333333333333333D-01) *
     $  TMP_JAMP(17)  ! used 2 times
      TMP_JAMP(44) = TMP_JAMP(17) + (3.333333333333333D-01) *
     $  TMP_JAMP(11)  ! used 2 times
      TMP_JAMP(43) = TMP_JAMP(4) + (3.000000000000000D+00) *
     $  TMP_JAMP(3)  ! used 2 times
      TMP_JAMP(42) = TMP_JAMP(4) + (3.333333333333333D-01) *
     $  TMP_JAMP(2)  ! used 2 times
      TMP_JAMP(41) = TMP_JAMP(3) + (3.333333333333333D-01) *
     $  TMP_JAMP(1)  ! used 2 times
      TMP_JAMP(40) = TMP_JAMP(2) + (3.000000000000000D+00) *
     $  TMP_JAMP(1)  ! used 2 times
      TMP_JAMP(55) = TMP_JAMP(48) +  TMP_JAMP(43)  ! used 2 times
      TMP_JAMP(54) = TMP_JAMP(47) + (3.333333333333333D-01) *
     $  TMP_JAMP(39)  ! used 2 times
      TMP_JAMP(53) = TMP_JAMP(40) +  TMP_JAMP(39)  ! used 2 times
      JAMP(1) = (-2.500000000000000D-01)*AMP(16)+(-2.500000000000000D
     $ -01)*AMP(23)+(2.500000000000000D-01)*TMP_JAMP(36)
     $ +(8.333333333333333D-02)*TMP_JAMP(47)+(8.333333333333333D-02)
     $ *TMP_JAMP(51)+(2.777777777777778D-02)*TMP_JAMP(53)
     $ +(8.333333333333333D-02)*TMP_JAMP(55)
      JAMP(2) = (2.500000000000000D-01)*AMP(13)+(2.500000000000000D-01)
     $ *AMP(26)+(-2.500000000000000D-01)*TMP_JAMP(12)+(
     $ -8.333333333333333D-02)*TMP_JAMP(15)+(-8.333333333333333D-02)
     $ *TMP_JAMP(19)+(-2.777777777777778D-02)*TMP_JAMP(20)+(
     $ -8.333333333333333D-02)*TMP_JAMP(21)+(-2.500000000000000D-01)
     $ *TMP_JAMP(33)+(-8.333333333333333D-02)*TMP_JAMP(41)+(
     $ -2.500000000000000D-01)*TMP_JAMP(42)+(-8.333333333333333D-02)
     $ *TMP_JAMP(50)
      JAMP(3) = (2.500000000000000D-01)*AMP(6)+(-2.500000000000000D-01)
     $ *AMP(26)+(-2.500000000000000D-01)*TMP_JAMP(34)+(
     $ -8.333333333333333D-02)*TMP_JAMP(44)+(-2.500000000000000D-01)
     $ *TMP_JAMP(46)+(-8.333333333333333D-02)*TMP_JAMP(53)+(
     $ -2.777777777777778D-02)*TMP_JAMP(55)
      JAMP(4) = (2.500000000000000D-01)*AMP(3)+(2.500000000000000D-01)
     $ *AMP(16)+(8.333333333333333D-02)*AMP(28)+(2.500000000000000D-01)
     $ *AMP(38)+(2.500000000000000D-01)*AMP(40)+(2.500000000000000D-01)
     $ *TMP_JAMP(5)+(8.333333333333333D-02)*TMP_JAMP(6)
     $ +(8.333333333333333D-02)*TMP_JAMP(7)+(2.777777777777778D-02)
     $ *TMP_JAMP(8)+(2.500000000000000D-01)*TMP_JAMP(14)
     $ +(8.333333333333333D-02)*TMP_JAMP(24)+(8.333333333333333D-02)
     $ *TMP_JAMP(30)+(8.333333333333333D-02)*TMP_JAMP(45)
     $ +(2.777777777777778D-02)*TMP_JAMP(49)
      JAMP(5) = (-2.500000000000000D-01)*AMP(3)+(2.500000000000000D-01)
     $ *AMP(23)+(2.500000000000000D-01)*AMP(30)+(8.333333333333333D-02)
     $ *AMP(36)+(2.500000000000000D-01)*AMP(39)+(2.500000000000000D-01)
     $ *TMP_JAMP(9)+(8.333333333333333D-02)*TMP_JAMP(10)
     $ +(2.777777777777778D-02)*TMP_JAMP(13)+(8.333333333333333D-02)
     $ *TMP_JAMP(16)+(8.333333333333333D-02)*TMP_JAMP(31)
     $ +(2.500000000000000D-01)*TMP_JAMP(44)+(8.333333333333333D-02)
     $ *TMP_JAMP(46)+(2.777777777777778D-02)*TMP_JAMP(52)
      JAMP(6) = (-2.500000000000000D-01)*AMP(6)+(-2.500000000000000D
     $ -01)*AMP(13)+(-2.500000000000000D-01)*AMP(34)+(
     $ -2.500000000000000D-01)*TMP_JAMP(23)+(-8.333333333333333D-02)
     $ *TMP_JAMP(25)+(-8.333333333333333D-02)*TMP_JAMP(28)+(
     $ -2.777777777777778D-02)*TMP_JAMP(29)+(-8.333333333333333D-02)
     $ *TMP_JAMP(38)+(-8.333333333333333D-02)*TMP_JAMP(49)+(
     $ -2.777777777777778D-02)*TMP_JAMP(51)+(-2.500000000000000D-01)
     $ *TMP_JAMP(54)

      MATRIX = 0.D0
      CF_INDEX = 0
      DO I = 1, NCOLOR
        ZTEMP = (0D0,0D0)
        DO J = I, NCOLOR
          CF_INDEX = CF_INDEX +1
          ZTEMP = ZTEMP + CF(CF_INDEX)*JAMP(J)
        ENDDO
        MATRIX = MATRIX+REAL(ZTEMP*DCONJG(JAMP(I)))
      ENDDO
      MATRIX = MATRIX / DENOM

      END

      SUBROUTINE GET_VALUE(P, ALPHAS, NHEL, FLAVOR ,ANS)
C     This routine is the f2py interface for GET_value_internal which
C      can not be in the interface
C     due to f2py not knowing how to handle the couplings common block
      USE MODEL_OBJECT
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER NHEL
      DOUBLE PRECISION ALPHAS
      REAL*8 PI
      INTEGER FLAVOR(NEXTERNAL)
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: NHEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
CF2PY INTENT(IN) :: ALPHAS
CF2PY INTENT(IN) :: FLAVOR(NEXTERNAL)
C     ROUTINE FOR F2PY to read the benchmark point.    

      CALL  GET_VALUE_INTERNAL(P, ALPHAS, NHEL, FLAVOR ,ANS)
      RETURN
      END


      SUBROUTINE GET_VALUE_INTERNAL(P, ALPHAS, NHEL, FLAVOR ,ANS)
      USE MODEL_OBJECT
C     This routine is the real value but can not be in the interface
C     due to f2py not knowing how to handle the couplings common block
      USE MODEL_OBJECT
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER NHEL
      DOUBLE PRECISION ALPHAS
      REAL*8 PI
      INTEGER FLAVOR(NEXTERNAL)
C     ROUTINE FOR F2PY to read the benchmark point.    
C     the include file with the values of the parameters and masses 
      INCLUDE 'coupl.inc'

      PI = 3.141592653589793D0
      G = 2* DSQRT(ALPHAS*PI)
      CALL UPDATE_AS_PARAM()
      IF (NHEL.NE.0) THEN
        CALL SMATRIXHEL(P, NHEL, FLAVOR, ANS)
      ELSE
        CALL SMATRIX(P, FLAVOR, ANS)
      ENDIF
      RETURN
      END

      SUBROUTINE INITIALISEMODEL(PATH)
C     ROUTINE FOR F2PY to read the benchmark point.    
      IMPLICIT NONE
      CHARACTER*512 PATH
CF2PY INTENT(IN) :: PATH
      CALL SETPARA(PATH)  !first call to setup the paramaters    
      RETURN
      END

      LOGICAL FUNCTION IS_BORN_HEL_SELECTED(HELID)
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
      INTEGER    NCOMB
      PARAMETER (NCOMB=64)
C     
C     ARGUMENTS
C     
      INTEGER HELID
C     
C     LOCALS
C     
      INTEGER I,J
      LOGICAL FOUNDIT
C     
C     GLOBALS
C     
      INTEGER HELC(NEXTERNAL,NCOMB)
      COMMON/PROCESS_NHEL/HELC

      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      COMMON/BORN_BEAM_POL/POLARIZATIONS
C     ----------
C     BEGIN CODE
C     ----------

      IS_BORN_HEL_SELECTED = .TRUE.
      IF (POLARIZATIONS(0,0).EQ.-1) THEN
        RETURN
      ENDIF

      DO I=1,NEXTERNAL
        IF (POLARIZATIONS(I,0).EQ.-1) THEN
          CYCLE
        ENDIF
        FOUNDIT = .FALSE.
        DO J=1,POLARIZATIONS(I,0)
          IF (HELC(I,HELID).EQ.POLARIZATIONS(I,J)) THEN
            FOUNDIT = .TRUE.
            EXIT
          ENDIF
        ENDDO
        IF(.NOT.FOUNDIT) THEN
          IS_BORN_HEL_SELECTED = .FALSE.
          RETURN
        ENDIF
      ENDDO

      RETURN
      END


      INTEGER FUNCTION BROKEN_SYM(FLAV)
      INCLUDE 'nexternal.inc'
      INTEGER FLAV(NEXTERNAL)
      INTEGER I,J,K,ICOMP
      INTEGER N_TOT, OLD_FACTOR, TOTAL_FACTOR
      INTEGER NCOMP, NENTRIES
      PARAMETER (NCOMP=1)
      PARAMETER (NENTRIES=4)
      INTEGER COMP_BEG(NCOMP), COMP_END(NCOMP), COMP_OLD(NCOMP)
      INTEGER PID_LIST(NENTRIES), PID_WORK(NENTRIES)
      INTEGER BLOCK_START(NENTRIES), BLOCK_LEN(NENTRIES)
      LOGICAL SAME_BLOCK
      DATA COMP_BEG /1/
      DATA COMP_END /4/
      DATA COMP_OLD /4/
      DATA PID_LIST /2,-2,2,-2/
      DATA BLOCK_START /3,4,5,6/
      DATA BLOCK_LEN /1,1,1,1/

      PID_WORK = PID_LIST
      TOTAL_FACTOR = 1
      DO ICOMP=1,NCOMP
        OLD_FACTOR = COMP_OLD(ICOMP)
        IF (COMP_OLD(ICOMP).GT.1) THEN
          DO I=COMP_BEG(ICOMP),COMP_END(ICOMP)
            IF (PID_WORK(I).EQ.0) CYCLE
            N_TOT = 1
            DO J=I+1,COMP_END(ICOMP)
              IF (PID_WORK(I).EQ.PID_WORK(J)) THEN
                SAME_BLOCK = .TRUE.
                IF (BLOCK_LEN(I).NE.BLOCK_LEN(J)) SAME_BLOCK = .FALSE.
                DO K=1,BLOCK_LEN(I)
                  IF (FLAV(BLOCK_START(I)+K-1).NE.FLAV(BLOCK_START(J)
     $             +K-1)) THEN
                    SAME_BLOCK = .FALSE.
                  ENDIF
                ENDDO
                IF (SAME_BLOCK) THEN
                  PID_WORK(J) = 0
                  N_TOT = N_TOT + 1
                  OLD_FACTOR = OLD_FACTOR/N_TOT
                ENDIF
              ENDIF
            ENDDO
          ENDDO
        ENDIF
        TOTAL_FACTOR = TOTAL_FACTOR*OLD_FACTOR
      ENDDO
      BROKEN_SYM = TOTAL_FACTOR
      RETURN
      END


