c
c     Calculated intermediate values that are printed out
c
      double precision  decw, w_w_nl, w_w_tau, w_w_ud, w_w_cs
      double precision  decz, w_z_nn, w_z_ll, w_z_tau
      double precision  w_z_uu, w_z_dd, w_z_cc, w_z_bb
      double precision  mt_h,mb_h,mc_h
      double precision  w_h_tt,w_h_bb,w_h_tau,w_h_cc
      double precision  w_h_ww,w_h_zz,w_h_WLWL,w_h_ZLZL
      common/calc_values/
     &                   decw, w_w_nl, w_w_tau, w_w_ud, w_w_cs,
     &                   decz, w_z_nn, w_z_ll, w_z_tau,
     &                   w_z_uu, w_z_dd, w_z_cc, w_z_bb,
     &                   mt_h, mb_h, mc_h,
     &                   w_h_tt,w_h_bb,w_h_tau,w_h_cc,
     &                   w_h_ww,w_h_zz,w_h_WLWL,w_h_ZLZL

