      SUBROUTINE ML5_0_SMATRIXHEL(P,HEL, FLAV_IDX, ANS)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=4)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=16)
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: HEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
CF2PY INTENT(IN) :: FLAV_IDX

C     
C     ARGUMENTS
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER HEL
      INTEGER FLAV_IDX
C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/ML5_0_HELUSERCHOICE/USERHEL
C     ----------
C     BEGIN CODE
C     ----------
      USERHEL=HEL
      CALL ML5_0_SMATRIX(P,FLAV_IDX,ANS)
      USERHEL=-1

      END

      SUBROUTINE ML5_0_SMATRIX(P, FLAV_IDX, ANS)
C     
C     Generated by MadGraph5_aMC@NLO v. %(version)s, %(date)s
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     MadGraph5_aMC@NLO StandAlone Version
C     
C     Returns amplitude squared summed/avg over colors
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL)
C     
C     Process: d d~ > t t~ QCD<=2 QED=0 [ virt = QCD ]
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=4)
      INTEGER    NINITIAL
      PARAMETER (NINITIAL=2)
      INTEGER NPOLENTRIES
      PARAMETER (NPOLENTRIES=(NEXTERNAL+1)*6)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=16)
      INTEGER HELAVGFACTOR
      PARAMETER (HELAVGFACTOR=4)
C     
C     ARGUMENTS
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
CF2PY INTENT(IN) :: FLAV_IDX
C     
C     LOCAL VARIABLES
C     
      INTEGER NHEL(NEXTERNAL,NCOMB)
C     put in common block to expose this variable to python interface
      COMMON/ML5_0_PROCESS_NHEL/NHEL
      REAL*8 T
      REAL*8 ML5_0_MATRIX
      INTEGER IHEL,IDEN, I, J
C     For a 1>N process, them BEAMTWO_HELAVGFACTOR would be set to 1.
      INTEGER BEAMS_HELAVGFACTOR(2)
      DATA (BEAMS_HELAVGFACTOR(I),I=1,2)/2,2/
      INTEGER FLAVOR(NEXTERNAL)
      INTEGER JC(NEXTERNAL)
      INTEGER NFLAV
      PARAMETER (NFLAV=1)
      INTEGER NNTRY_FLAV, NGOODHEL_FLAV
      PARAMETER (NNTRY_FLAV=NFLAV)
      PARAMETER (NGOODHEL_FLAV=NCOMB*NFLAV)
      INTEGER FLAV_IDX
      INTEGER ML5_0_GET_FLAVOR_INDEX
      INTEGER NTRY(NFLAV)
      LOGICAL GOODHEL(NCOMB,NFLAV)
      DATA NTRY/NNTRY_FLAV*0/
      DATA GOODHEL/NGOODHEL_FLAV*.FALSE./

C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/ML5_0_HELUSERCHOICE/USERHEL
      DATA USERHEL/-1/
      LOGICAL HELRESET
      COMMON/ML5_0_HELRESET/HELRESET
      DATA HELRESET/.TRUE./

      DATA (NHEL(I,   1),I=1,4) / 1,-1,-1, 1/
      DATA (NHEL(I,   2),I=1,4) / 1,-1,-1,-1/
      DATA (NHEL(I,   3),I=1,4) / 1,-1, 1, 1/
      DATA (NHEL(I,   4),I=1,4) / 1,-1, 1,-1/
      DATA (NHEL(I,   5),I=1,4) / 1, 1,-1, 1/
      DATA (NHEL(I,   6),I=1,4) / 1, 1,-1,-1/
      DATA (NHEL(I,   7),I=1,4) / 1, 1, 1, 1/
      DATA (NHEL(I,   8),I=1,4) / 1, 1, 1,-1/
      DATA (NHEL(I,   9),I=1,4) /-1,-1,-1, 1/
      DATA (NHEL(I,  10),I=1,4) /-1,-1,-1,-1/
      DATA (NHEL(I,  11),I=1,4) /-1,-1, 1, 1/
      DATA (NHEL(I,  12),I=1,4) /-1,-1, 1,-1/
      DATA (NHEL(I,  13),I=1,4) /-1, 1,-1, 1/
      DATA (NHEL(I,  14),I=1,4) /-1, 1,-1,-1/
      DATA (NHEL(I,  15),I=1,4) /-1, 1, 1, 1/
      DATA (NHEL(I,  16),I=1,4) /-1, 1, 1,-1/
      DATA IDEN/36/

      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      COMMON/ML5_0_BORN_BEAM_POL/POLARIZATIONS
      DATA ((POLARIZATIONS(I,J),I=0,NEXTERNAL),J=0,5)/NPOLENTRIES*-1/

C     
C     FUNCTIONS
C     
      LOGICAL ML5_0_IS_BORN_HEL_SELECTED
      INTEGER ML5_0_BROKEN_SYM
C     ----------
C     Check if helreset mode is on
C     ---------
      IF (HELRESET) THEN
        DO I=1,NFLAV
          NTRY(I) = 0
        ENDDO
        DO I=1,NCOMB
          DO J=1,NFLAV
            GOODHEL(I,J) = .FALSE.
          ENDDO
        ENDDO
        HELRESET = .FALSE.
      ENDIF

C     ----------
C     BEGIN CODE
C     ----------
C     FLAV_IDX=0 (or out of range) means GET_FLAVOR_INDEX could not
C      resolve
C     the requested flavor: it is not an allowed combination, so its
C      matrix
C     element is identically zero. Short-circuit before touching the
C     1..NFLAV GOODHEL/NTRY arrays.
      IF (FLAV_IDX.LT.1 .OR. FLAV_IDX.GT.NFLAV) THEN
        ANS = 0D0
        RETURN
      ENDIF
      CALL ML5_0_GET_FLAVOR(FLAV_IDX, FLAVOR)
      IF(USERHEL.EQ.-1) NTRY(FLAV_IDX)=NTRY(FLAV_IDX)+1
      DO IHEL=1,NEXTERNAL
        JC(IHEL) = +1
      ENDDO
C     When spin-2 particles are involved, the Helicity filtering is
C      dangerous for the 2->1 topology.
C     This is because depending on the MC setup the initial PS points
C      have back-to-back initial states
C     for which some of the spin-2 helicity configurations are zero.
C      But they are no longer zero
C     if the point is boosted on the z-axis. Remember that HELAS
C      helicity amplitudes are no longer
C     lorentz invariant with expternal spin-2 particles (only the
C      helicity sum is).
C     For this reason, we simply remove the filterin when there is
C      only three external particles.
      IF (NEXTERNAL.LE.3) THEN
        DO IHEL=1,NCOMB
          DO J=1,NFLAV
            GOODHEL(IHEL,J)=.TRUE.
          ENDDO
        ENDDO
      ENDIF
      ANS = 0D0
      DO IHEL=1,NCOMB
        IF (USERHEL.EQ.-1.OR.USERHEL.EQ.IHEL) THEN
          IF (GOODHEL(IHEL,FLAV_IDX) .OR. NTRY(FLAV_IDX) .LT.
     $      20.OR.USERHEL.NE.-1) THEN
            IF(NTRY(FLAV_IDX).GE.2.AND.POLARIZATIONS(0,0).NE.
     $       -1.AND.(.NOT.ML5_0_IS_BORN_HEL_SELECTED(IHEL))) THEN
              CYCLE
            ENDIF
            T=ML5_0_MATRIX(P ,NHEL(1,IHEL),JC(1),FLAV_IDX)
            IF(POLARIZATIONS(0,0).EQ.
     $       -1.OR.ML5_0_IS_BORN_HEL_SELECTED(IHEL)) THEN
              ANS=ANS+T
            ENDIF
            IF (T .NE. 0D0 .AND. .NOT.    GOODHEL(IHEL,FLAV_IDX)) THEN
              GOODHEL(IHEL,FLAV_IDX)=.TRUE.
            ENDIF
          ENDIF
        ENDIF
      ENDDO
      ANS=ANS/DBLE(IDEN)*ML5_0_BROKEN_SYM(FLAVOR)
      IF(USERHEL.NE.-1) THEN
        ANS=ANS*HELAVGFACTOR
      ELSE
        DO J=1,NINITIAL
          IF (POLARIZATIONS(J,0).NE.-1) THEN
            ANS=ANS*BEAMS_HELAVGFACTOR(J)
            ANS=ANS/POLARIZATIONS(J,0)
          ENDIF
        ENDDO
      ENDIF
      END


      REAL*8 FUNCTION ML5_0_MATRIX(P,NHEL,IC,FLAV_IDX)
      USE MODEL_OBJECT
C     
C     Generated by MadGraph5_aMC@NLO v. %(version)s, %(date)s
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared -- no average over initial
C      state/symmetry factor
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: d d~ > t t~ QCD<=2 QED=0 [ virt = QCD ]
C     
      USE ALOHA_OBJECT
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=1)
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=4)
      INTEGER    NWAVEFUNCS, NCOLOR
      PARAMETER (NWAVEFUNCS=5, NCOLOR=2)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
C     
C     ARGUMENTS
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
      INTEGER FLAV_IDX
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J
      COMPLEX*16 ZTEMP
      INTEGER CF_INDEX
      INTEGER ML5_0_CF(3)
      INTEGER ML5_0_DENOM
      COMMON /ML5_0_COLOR_MATRIX/ ML5_0_CF,ML5_0_DENOM
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR), TMP_JAMP(0)
      TYPE(ALOHA) W(NWAVEFUNCS)
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
C     
C     GLOBAL VARIABLES
C     
      INCLUDE 'coupl.inc'

C     COLOR DATA
      DATA ML5_0_DENOM/1/
      DATA (ML5_0_CF(I),I=  1,  2) /9,6/
C     1 T(2,1) T(3,4)
      DATA (ML5_0_CF(I),I=  3,  3) /9/
C     1 T(2,4) T(3,1)
C     
C     
C     ----------
C     BEGIN CODE
C     ----------
      CALL ML5_0_GET_AMP(P,NHEL,IC,FLAV_IDX,AMP)
C     WRITE (*,*) '  -> AMP = ', AMP
      CALL ML5_0_GET_JAMP(AMP,JAMP)
C     WRITE (*,*) '  -> JAMP = ', JAMP
      CALL ML5_0_GET_MATRIX(JAMP,ML5_0_MATRIX)
C     write (*,*) "  -> col.ave. |M|^2 for HEL=[", NHEL ,"] = ",
C      ML5_0_MATRIX



      END

      SUBROUTINE ML5_0_GET_NHEL(IDEN_STAR,NHEL_STAR)
C     CONSTANTS
C     
CF2PY INTENT(OUT) :: NHEL_STAR
CF2PY INTENT(OUT) :: IDEN_STAR
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=4)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=16)

      INTEGER NHEL(NEXTERNAL,NCOMB),NHEL_STAR(NEXTERNAL,NCOMB)
      INTEGER IDEN,IDEN_STAR

      DATA (NHEL(I,   1),I=1,4) / 1,-1,-1, 1/
      DATA (NHEL(I,   2),I=1,4) / 1,-1,-1,-1/
      DATA (NHEL(I,   3),I=1,4) / 1,-1, 1, 1/
      DATA (NHEL(I,   4),I=1,4) / 1,-1, 1,-1/
      DATA (NHEL(I,   5),I=1,4) / 1, 1,-1, 1/
      DATA (NHEL(I,   6),I=1,4) / 1, 1,-1,-1/
      DATA (NHEL(I,   7),I=1,4) / 1, 1, 1, 1/
      DATA (NHEL(I,   8),I=1,4) / 1, 1, 1,-1/
      DATA (NHEL(I,   9),I=1,4) /-1,-1,-1, 1/
      DATA (NHEL(I,  10),I=1,4) /-1,-1,-1,-1/
      DATA (NHEL(I,  11),I=1,4) /-1,-1, 1, 1/
      DATA (NHEL(I,  12),I=1,4) /-1,-1, 1,-1/
      DATA (NHEL(I,  13),I=1,4) /-1, 1,-1, 1/
      DATA (NHEL(I,  14),I=1,4) /-1, 1,-1,-1/
      DATA (NHEL(I,  15),I=1,4) /-1, 1, 1, 1/
      DATA (NHEL(I,  16),I=1,4) /-1, 1, 1,-1/
      DATA IDEN/36/
      IDEN_STAR = IDEN
      NHEL_STAR = NHEL
      END

      SUBROUTINE ML5_0_GET_AMP(P,NHEL,IC,FLAV_IDX,AMP)
      USE MODEL_OBJECT
C     
C     Process: d d~ > t t~ QCD<=2 QED=0 [ virt = QCD ]
C     
CF2PY INTENT(OUT) :: AMP
CF2PY INTENT(IN) :: NHEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
CF2PY INTENT(IN) :: IC
CF2PY INTENT(IN) :: FLAV_IDX

      USE ALOHA_OBJECT
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=1)
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=4)
      INTEGER    NWAVEFUNCS, NCOLOR
      PARAMETER (NWAVEFUNCS=5, NCOLOR=2)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
C     
C     ARGUMENTS
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
      INTEGER FLAV_IDX
      INTEGER FLAVOR(NEXTERNAL)
C     
C     LOCAL VARIABLES
C     
      COMPLEX*16 AMP(NGRAPHS)
      TYPE(ALOHA) W(NWAVEFUNCS)
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
      DOUBLE PRECISION BWCUTOFF
C     Flavor table for the FLAV_IDX -> FLAVOR rebuild.
      INTEGER NMASK_FLAV
      PARAMETER (NMASK_FLAV=1)
      INTEGER MASK_J
      INTEGER FLAV_TABLE(NEXTERNAL, NMASK_FLAV)
      DATA FLAV_TABLE / 1, 1, 1, 1 /
C     
C     GLOBAL VARIABLES
C     
      INCLUDE 'coupl.inc'

C     
C     
      BWCUTOFF=15  ! use if $ syntax is defined in the process
C     Rebuild FLAVOR(NEXTERNAL) from the resolved flavor index.
      IF (FLAV_IDX .GE. 1 .AND. FLAV_IDX .LE. NMASK_FLAV) THEN
        DO MASK_J = 1, NEXTERNAL
          FLAVOR(MASK_J) = FLAV_TABLE(MASK_J, FLAV_IDX)
        ENDDO
      ELSE
        DO MASK_J = 1, NEXTERNAL
          FLAVOR(MASK_J) = FLAV_TABLE(MASK_J, 1)
        ENDDO
      ENDIF
      CALL IXXXXX(P(0,1),ZERO,NHEL(1),+1, FLAVOR(1),W(1))
      CALL OXXXXX(P(0,2),ZERO,NHEL(2),-1, FLAVOR(2),W(2))
      CALL OXXXXX(P(0,3),MDL_MT,NHEL(3),+1, FLAVOR(3),W(3))
      CALL IXXXXX(P(0,4),MDL_MT,NHEL(4),-1, FLAVOR(4),W(4))
      CALL FFV1P0_3(W(1),W(2),GC_5,ZERO,ZERO,W(5))
C     Amplitude(s) for diagram number 1
      CALL FFV1_0(W(4),W(3),W(5),GC_5,AMP(1))

      END

      SUBROUTINE ML5_0_GET_JAMP(AMP,JAMP)
C     
C     Process: d d~ > t t~ QCD<=2 QED=0 [ virt = QCD ]
C     
CF2PY INTENT(OUT) :: JAMP
CF2PY INTENT(IN) :: AMP

      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=1)
      INTEGER    NCOLOR
      PARAMETER ( NCOLOR=2)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR), TMP_JAMP(0)

      JAMP(1) = (1.666666666666667D-01)*AMP(1)
      JAMP(2) = (-5.000000000000000D-01)*AMP(1)
      END

      SUBROUTINE ML5_0_GET_MATRIX(JAMP,MATRIX)
C     
C     Process: d d~ > t t~ QCD<=2 QED=0 [ virt = QCD ]
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
CF2PY INTENT(OUT) :: MATRIX
CF2PY INTENT(IN) :: JAMP


      INTEGER    NCOLOR
      PARAMETER (NCOLOR=2)
      REAL*8     ZERO,MATRIX
      PARAMETER (ZERO=0D0)
C     

C     LOCAL VARIABLES
C     
      INTEGER I,J
      COMPLEX*16 ZTEMP

      INTEGER CF_INDEX
      INTEGER ML5_0_CF(NCOLOR*(NCOLOR+1)/2)
      INTEGER ML5_0_DENOM
      COMMON /ML5_0_COLOR_MATRIX/ ML5_0_CF,ML5_0_DENOM
      COMPLEX*16 JAMP(NCOLOR), TMP_JAMP(0)
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
C     

C     COLOR DATA
C     

      MATRIX = 0.D0
      CF_INDEX = 0
      DO I = 1, NCOLOR
        ZTEMP = (0.D0,0.D0)
        DO J = I, NCOLOR
          CF_INDEX = CF_INDEX + 1
          ZTEMP = ZTEMP + ML5_0_CF(CF_INDEX)*JAMP(J)
        ENDDO
        MATRIX = MATRIX+ZTEMP*DCONJG(JAMP(I))/ML5_0_DENOM
      ENDDO
      END



      SUBROUTINE ML5_0_GET_INTER(JAMP_1,JAMP_2, INTER)

CF2PY INTENT(OUT) :: INTER
CF2PY INTENT(IN) :: JAMP_1
CF2PY INTENT(IN) :: JAMP_2

      INTEGER I,J
      INTEGER NCOLOR
      PARAMETER (NCOLOR=2)
      INTEGER CF_INDEX
      INTEGER ML5_0_CF(NCOLOR*(NCOLOR+1)/2)
      INTEGER ML5_0_DENOM
      COMMON /ML5_0_COLOR_MATRIX/ ML5_0_CF,ML5_0_DENOM
      COMPLEX*16 JAMP_1(NCOLOR),JAMP_2(NCOLOR),INTER

C     COLOR DATA
C     

      INTER = (0.D0,0.D0)
      CF_INDEX = 0
      DO I = 1, NCOLOR
C       ZTEMP = DCONJG(JAMP_2(I))
        DO J=I, NCOLOR
          CF_INDEX = CF_INDEX +1
          INTER = INTER + ML5_0_CF(CF_INDEX) * (JAMP_1(J) *
     $      DCONJG(JAMP_2(I)) +JAMP_1(I) * DCONJG(JAMP_2(J)))
        ENDDO
      ENDDO
      INTER = INTER/ (2D0*ML5_0_DENOM)

      END



      SUBROUTINE  ML5_0_GET_DENSITY(P, POS, N_CHANGING, ALLOW_HEL,
     $  N_COMB, FLAVOR, ALPHAS, INTER)
C     P momenta
C     NHEL base of helicity that are not changing
C     POS(N_CHNGING): position of the changing helicity
C     n_changing: number of changing helicity
C     ALLOW_HEL(NCOMB, N_CHANGING): combination of helicity to
C      consider (all jamp computed)
C     INTER((NCOMB*NCOMB+1)/2: all interference term (not the
C      symmetric one)
      USE MODEL_OBJECT
      IMPLICIT NONE
CF2PY INTENT(IN) :: P(0:3,4)
CF2PY INTENT(IN) :: POS(N_CHANGING)
CF2PY INTENT(IN) :: N_CHANGING
CF2PY INTENT(IN) :: ALLOW_HEL(N_CHANGING*N_COMB)
CF2PY INTENT(IN) :: N_COMB
CF2PY INTENT(IN) :: FLAVOR(4)
CF2PY INTENT(IN) :: ALPHAS
CF2PY INTENT(OUT) :: INTER(N_COMB*(N_COMB+1)/2)
C     
C     
C     ARGUMENTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=4)
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER THISNHEL(NEXTERNAL)
      INTEGER N_CHANGING, N_COMB
      INTEGER POS(*)
      INTEGER ALLOW_HEL(*)
      INTEGER FLAVOR(NEXTERNAL)
      DOUBLE PRECISION ALPHAS
      DOUBLE COMPLEX INTER(*)
      INTEGER NINTER
      INTEGER NB_NHEL
      DOUBLE COMPLEX, ALLOCATABLE :: TMP_INTER(:)
      PARAMETER (NB_NHEL=16)
C     LOCAL
      INTEGER I,IHEL,IPART
      DOUBLE PRECISION PI
C     
      INTEGER NHEL(NEXTERNAL,NB_NHEL),NTRY
C     put in common block to expose this variable to python interface
      COMMON/ML5_0_PROCESS_NHEL/NHEL
C     
C     include coupling definition to update the value of alphas
C     
      INCLUDE 'coupl.inc'

      NINTER = N_COMB*(N_COMB+1)/2
      ALLOCATE(TMP_INTER(NINTER))
      TMP_INTER(:) = (0D0, 0D0)

      DO I=1, N_COMB*(N_COMB+1)/2
        INTER(I) = 0
      ENDDO

      IF (ALPHAS.NE.0D0) THEN
        PI = 3.141592653589793D0
        G = 2* DSQRT(ALPHAS*PI)
        CALL UPDATE_AS_PARAM()
      ENDIF
      DO IHEL =1, NB_NHEL
        THISNHEL(:) = NHEL(:, IHEL)
        DO IPART=1,N_CHANGING
          IF(THISNHEL(POS(IPART)).NE.ALLOW_HEL(IPART)) GOTO 10  !BYPASS COMPUTATION FOR HELICITY
        ENDDO
        TMP_INTER(:) = 0
        CALL  ML5_0_GET_ALL_INTER(P, THISNHEL, POS, N_CHANGING,
     $    ALLOW_HEL, N_COMB, FLAVOR, TMP_INTER)
        DO I = 1, N_COMB*(N_COMB+1)/2
          INTER(I) = INTER(I) + TMP_INTER(I)
        ENDDO
 10   ENDDO
      RETURN
      DEALLOCATE(TMP_INTER)
      END

      SUBROUTINE  ML5_0_GET_ALL_INTER(P, NHEL, POS, N_CHANGING,
     $  ALLOW_HEL, N_COMB, FLAVOR, INTER)
C     P momenta
C     NHEL base of helicity that are not changing
C     POS(N_CHNGING): position of the changing helicity
C     n_changing: number of changing helicity
C     ALLOW_HEL(NCOMB, N_CHANGING): combination of helicity to
C      consider (all jamp computed)
C     INTER((NCOMB*NCOMB+1)/2: all interference term (not the
C      symmetric one)
      IMPLICIT NONE
CF2PY INTENT(IN) :: P(0:3,4)
CF2PY INTENT(IN) :: NHEL(4)
CF2PY INTENT(IN) :: POS(N_CHANGING)
CF2PY INTENT(IN) :: N_CHANGING
CF2PY INTENT(IN) :: ALLOW_HEL(N_CHANGING*N_COMB)
CF2PY INTENT(IN) :: N_COMB
CF2PY INTENT(IN) :: FLAVOR(4)
CF2PY INTENT(OUT) :: INTER(NCOMB*(NCOMB+1)/2)
C     
C     
C     ARGUMENTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=4)
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL)
      INTEGER N_CHANGING, N_COMB
      INTEGER POS(*)
      INTEGER ALLOW_HEL(*)
      INTEGER FLAVOR(NEXTERNAL)
      DOUBLE COMPLEX INTER(*)
C     
C     Intermediate array
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=1)
      INTEGER    NCOLOR
      PARAMETER (NCOLOR=2)
      INTEGER IC(NEXTERNAL)

      DOUBLE COMPLEX AMP(NGRAPHS)
      DOUBLE COMPLEX, ALLOCATABLE, SAVE :: JAMP(:,:)
      INTEGER, SAVE :: S_NCOMB = 0

C     
C     LOCAL
C     
      INTEGER I,J,SOL,N
      INTEGER FLAV_IDX
      INTEGER ML5_0_GET_FLAVOR_INDEX

      IF (ALLOCATED(JAMP) .AND. S_NCOMB.NE.N_COMB) THEN
        DEALLOCATE(JAMP)
      ENDIF

      IF (.NOT.ALLOCATED(JAMP)) THEN
        S_NCOMB=N_COMB
        ALLOCATE(JAMP(NCOLOR, N_COMB))
      ENDIF
C     ----------
C     BEGIN CODE
C     ----------
      IC(:)=1
      FLAV_IDX = ML5_0_GET_FLAVOR_INDEX(FLAVOR)
C     Unresolved flavor (not an allowed combination): the matrix
C      element and
C     therefore all interference terms are zero.
      IF (FLAV_IDX.EQ.0) THEN
        DO I = 1, N_COMB*(N_COMB+1)/2
          INTER(I) = (0D0, 0D0)
        ENDDO
        RETURN
      ENDIF
      DO I = 1, N_COMB
        DO N = 1, N_CHANGING
          NHEL(POS(N)) = ALLOW_HEL((I-1)*N_CHANGING+N)
        ENDDO
        CALL ML5_0_GET_AMP(P,NHEL,IC,FLAV_IDX,AMP)
        CALL ML5_0_GET_JAMP(AMP,JAMP(1,I))
      ENDDO

      SOL = 0
      DO I = 1, N_COMB
        DO J= I, N_COMB
          SOL = SOL +1
          CALL ML5_0_GET_INTER(JAMP(1,I), JAMP(1,J), INTER(SOL))
        ENDDO
      ENDDO


      RETURN
      END




      SUBROUTINE ML5_0_GET_VALUE(P, ALPHAS, NHEL, FLAVOR ,ANS)
C     f2py interface accepting the full FLAVOR(NEXTERNAL) array
C      (back-compat):
C     resolve it to FLAV_IDX and forward to GET_value_internal. Use
C     GET_value_idx below to pass the flavor index directly.
      USE MODEL_OBJECT
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=4)
C     
C     ARGUMENTS
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER NHEL
      DOUBLE PRECISION ALPHAS
      INTEGER FLAVOR(NEXTERNAL)
      INTEGER FLAV_IDX
      INTEGER ML5_0_GET_FLAVOR_INDEX
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: NHEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
CF2PY INTENT(IN) :: ALPHAS
CF2PY INTENT(IN) :: FLAVOR(NEXTERNAL)
C     ROUTINE FOR F2PY to read the benchmark point.

      FLAV_IDX = ML5_0_GET_FLAVOR_INDEX(FLAVOR)
      CALL  ML5_0_GET_VALUE_INTERNAL(P, ALPHAS, NHEL, FLAV_IDX ,ANS)
      RETURN
      END


      SUBROUTINE ML5_0_GET_VALUE_IDX(P, ALPHAS, NHEL, FLAV_IDX ,ANS)
C     f2py interface accepting the flavor index directly.
      USE MODEL_OBJECT
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=4)
C     
C     ARGUMENTS
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER NHEL
      DOUBLE PRECISION ALPHAS
      INTEGER FLAV_IDX
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: NHEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
CF2PY INTENT(IN) :: ALPHAS
CF2PY INTENT(IN) :: FLAV_IDX

      CALL  ML5_0_GET_VALUE_INTERNAL(P, ALPHAS, NHEL, FLAV_IDX ,ANS)
      RETURN
      END


      SUBROUTINE ML5_0_GET_VALUE_INTERNAL(P, ALPHAS, NHEL, FLAV_IDX 
     $ ,ANS)
      USE MODEL_OBJECT
C     This routine is the real value but can not be in the interface
C     due to f2py not knowing how to handle the couplings common block
      USE MODEL_OBJECT
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=4)
C     
C     ARGUMENTS
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER NHEL
      DOUBLE PRECISION ALPHAS
      REAL*8 PI
      INTEGER FLAV_IDX
C     ROUTINE FOR F2PY to read the benchmark point.
C     the include file with the values of the parameters and masses
      INCLUDE 'coupl.inc'

      PI = 3.141592653589793D0
      G = 2* DSQRT(ALPHAS*PI)
      CALL UPDATE_AS_PARAM()
      IF (NHEL.NE.0) THEN
        CALL ML5_0_SMATRIXHEL(P, NHEL, FLAV_IDX, ANS)
      ELSE
        CALL ML5_0_SMATRIX(P, FLAV_IDX, ANS)
      ENDIF
      RETURN
      END

      SUBROUTINE ML5_0_INITIALISEMODEL(PATH)
C     ROUTINE FOR F2PY to read the benchmark point.
      IMPLICIT NONE
      CHARACTER*512 PATH
CF2PY INTENT(IN) :: PATH
      CALL SETPARA(PATH)  !first call to setup the paramaters
      RETURN
      END

      LOGICAL FUNCTION ML5_0_IS_BORN_HEL_SELECTED(HELID)
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=4)
      INTEGER    NCOMB
      PARAMETER (NCOMB=16)
C     
C     ARGUMENTS
C     
      INTEGER HELID
C     
C     LOCALS
C     
      INTEGER I,J
      LOGICAL FOUNDIT
C     
C     GLOBALS
C     
      INTEGER HELC(NEXTERNAL,NCOMB)
      COMMON/ML5_0_PROCESS_NHEL/HELC

      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      COMMON/ML5_0_BORN_BEAM_POL/POLARIZATIONS
C     ----------
C     BEGIN CODE
C     ----------

      ML5_0_IS_BORN_HEL_SELECTED = .TRUE.
      IF (POLARIZATIONS(0,0).EQ.-1) THEN
        RETURN
      ENDIF

      DO I=1,NEXTERNAL
        IF (POLARIZATIONS(I,0).EQ.-1) THEN
          CYCLE
        ENDIF
        FOUNDIT = .FALSE.
        DO J=1,POLARIZATIONS(I,0)
          IF (HELC(I,HELID).EQ.POLARIZATIONS(I,J)) THEN
            FOUNDIT = .TRUE.
            EXIT
          ENDIF
        ENDDO
        IF(.NOT.FOUNDIT) THEN
          ML5_0_IS_BORN_HEL_SELECTED = .FALSE.
          RETURN
        ENDIF
      ENDDO

      RETURN
      END


      INTEGER FUNCTION ML5_0_BROKEN_SYM(FLAV)
      INCLUDE 'nexternal.inc'
      INTEGER FLAV(NEXTERNAL)
      INTEGER I,J,K,ICOMP
      INTEGER N_TOT, OLD_FACTOR, TOTAL_FACTOR
      INTEGER NCOMP, NENTRIES
      PARAMETER (NCOMP=1)
      PARAMETER (NENTRIES=2)
      INTEGER COMP_BEG(NCOMP), COMP_END(NCOMP), COMP_OLD(NCOMP)
      INTEGER PID_LIST(NENTRIES), PID_WORK(NENTRIES)
      INTEGER BLOCK_START(NENTRIES), BLOCK_LEN(NENTRIES)
      LOGICAL SAME_BLOCK
      DATA COMP_BEG /1/
      DATA COMP_END /2/
      DATA COMP_OLD /1/
      DATA PID_LIST /6,-6/
      DATA BLOCK_START /3,4/
      DATA BLOCK_LEN /1,1/

      PID_WORK = PID_LIST
      TOTAL_FACTOR = 1
      DO ICOMP=1,NCOMP
        OLD_FACTOR = COMP_OLD(ICOMP)
        IF (COMP_OLD(ICOMP).GT.1) THEN
          DO I=COMP_BEG(ICOMP),COMP_END(ICOMP)
            IF (PID_WORK(I).EQ.0) CYCLE
            N_TOT = 1
            DO J=I+1,COMP_END(ICOMP)
              IF (PID_WORK(I).EQ.PID_WORK(J)) THEN
                SAME_BLOCK = .TRUE.
                IF (BLOCK_LEN(I).NE.BLOCK_LEN(J)) SAME_BLOCK = .FALSE.
                DO K=1,BLOCK_LEN(I)
                  IF (FLAV(BLOCK_START(I)+K-1).NE.FLAV(BLOCK_START(J)
     $             +K-1)) THEN
                    SAME_BLOCK = .FALSE.
                  ENDIF
                ENDDO
                IF (SAME_BLOCK) THEN
                  PID_WORK(J) = 0
                  N_TOT = N_TOT + 1
                  OLD_FACTOR = OLD_FACTOR/N_TOT
                ENDIF
              ENDIF
            ENDDO
          ENDDO
        ENDIF
        TOTAL_FACTOR = TOTAL_FACTOR*OLD_FACTOR
      ENDDO
      ML5_0_BROKEN_SYM = TOTAL_FACTOR
      RETURN
      END



      INTEGER FUNCTION ML5_0_GET_FLAVOR_INDEX(FLAVOR)
C     Resolve an external FLAVOR(NEXTERNAL) group-position vector to
C      its
C     1-based index in the allowed-flavor table (the same ordering
C      used by
C     compute_flavor_masks / the FLAV_TABLE mask columns). A resolved
C      flavor
C     returns an index in [1,NFLAV]; a flavor that is NOT in the table
C      (i.e.
C     not a physical/allowed combination, so its matrix element is
C      zero)
C     returns 0. Callers MUST treat the 0 sentinel as "not a valid
C      flavor"
C     and short-circuit to a zero result before indexing the 1..NFLAV
C     GOODHEL/NTRY arrays or FLAV_TABLE (there is no reserved 0 slot).
C     Computed once per phase-space point and then threaded down to
C     MATRIX/GET_AMP and the good-helicity filter.
      INCLUDE 'nexternal.inc'
      INTEGER NFLAV
      PARAMETER (NFLAV=1)
      INTEGER FLAVOR(NEXTERNAL)
CF2PY INTENT(IN) :: FLAVOR(NEXTERNAL)
CF2PY INTENT(OUT) :: ML5_0_GET_FLAVOR_INDEX
      INTEGER FI_I, FI_J
      LOGICAL FI_MATCH
      INTEGER FI_TABLE(NEXTERNAL, NFLAV)
      DATA FI_TABLE /1, 1, 1, 1/
C     0 sentinel for an unresolved (not-in-table) flavor (see above).
      ML5_0_GET_FLAVOR_INDEX = 0
      DO FI_I = 1, NFLAV
        FI_MATCH = .TRUE.
        DO FI_J = 1, NEXTERNAL
          IF (FLAVOR(FI_J) .NE. FI_TABLE(FI_J, FI_I)) THEN
            FI_MATCH = .FALSE.
            EXIT
          ENDIF
        ENDDO
        IF (FI_MATCH) THEN
          ML5_0_GET_FLAVOR_INDEX = FI_I
          RETURN
        ENDIF
      ENDDO
      RETURN
      END



      SUBROUTINE ML5_0_GET_FLAVOR(FLAV_IDX, FLAVOR)
C     Reverse of GET_FLAVOR_INDEX: fill FLAVOR(NEXTERNAL) with the
C      per-leg
C     group-position vector of the FLAV_IDX-th allowed flavor (same
C      table /
C     ordering). FLAV_IDX is expected in [1,NFLAV] (GET_FLAVOR_INDEX
C      never
C     returns 0); the bounds guard below is purely defensive and maps
C      any
C     out-of-range value to the first flavor. Used by the outer entry
C      points
C     (SMATRIX, ...) which receive FLAV_IDX but still need the FLAVOR
C      array
C     (e.g. for BROKEN_SYM).
      INCLUDE 'nexternal.inc'
      INTEGER NFLAV
      PARAMETER (NFLAV=1)
      INTEGER FLAV_IDX
      INTEGER FLAVOR(NEXTERNAL)
CF2PY INTENT(IN) :: FLAV_IDX
CF2PY INTENT(OUT) :: FLAVOR(NEXTERNAL)
      INTEGER FA_I, FA_USE
      INTEGER FA_TABLE(NEXTERNAL, NFLAV)
      DATA FA_TABLE /1, 1, 1, 1/
      FA_USE = FLAV_IDX
      IF (FA_USE .LT. 1 .OR. FA_USE .GT. NFLAV) FA_USE = 1
      DO FA_I = 1, NEXTERNAL
        FLAVOR(FA_I) = FA_TABLE(FA_I, FA_USE)
      ENDDO
      RETURN
      END


