      SUBROUTINE SMATRIX(P, FLAV_IDX, ANS_SUMMED)
C     
C     Simple routine wrapper to provide the same interface for
C     backward compatibility for usage without split orders.
C     
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=4)
      INTEGER NSQAMPSO
      PARAMETER (NSQAMPSO=1)
C     
C     ARGUMENTS
C     
      REAL*8 P(0:3,NEXTERNAL), ANS_SUMMED
      INTEGER FLAV_IDX
C     
C     VARIABLES
C     
      INTEGER I
      REAL*8 ANS(0:NSQAMPSO)
C     
C     BEGIN CODE
C     
      CALL SMATRIX_SPLITORDERS(P, FLAV_IDX, ANS)
      ANS_SUMMED=ANS(0)

      END

      SUBROUTINE SMATRIXHEL(P,HEL, FLAV_IDX, ANS)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=4)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=16)
C     
C     ARGUMENTS
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER HEL
      INTEGER FLAV_IDX
C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/HELUSERCHOICE/USERHEL
C     ----------
C     BEGIN CODE
C     ----------
      USERHEL=HEL
      CALL SMATRIX(P, FLAV_IDX, ANS)
      USERHEL=-1

      END

      SUBROUTINE SMATRIXHEL_SPLITORDERS(P,HEL, FLAV_IDX, ANS)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=4)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=16)
      INTEGER NSQAMPSO
      PARAMETER (NSQAMPSO=1)
C     
C     ARGUMENTS
C     
      REAL*8 P(0:3,NEXTERNAL),ANS(0:NSQAMPSO)
      INTEGER HEL
      INTEGER FLAV_IDX
C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/HELUSERCHOICE/USERHEL
C     ----------
C     BEGIN CODE
C     ----------
      USERHEL=HEL
      CALL SMATRIX_SPLITORDERS(P, FLAV_IDX, ANS)
      USERHEL=-1

      END

      SUBROUTINE SMATRIX_SPLITORDERS(P, FLAV_IDX, ANS)
C     
C     Generated by MadGraph5_aMC@NLO v. %(version)s, %(date)s
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     MadGraph StandAlone Version
C     
C     Returns amplitude squared summed/avg over colors
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL)
C     
C     Process: d~ u > ve e+ [ all = QCD QED ] QCD^2<=0 QED^2<=6
C     Process: s~ c > ve e+ [ all = QCD QED ] QCD^2<=0 QED^2<=6
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=4)
      INTEGER    NINITIAL
      PARAMETER (NINITIAL=2)
      INTEGER NPOLENTRIES
      PARAMETER (NPOLENTRIES=(NEXTERNAL+1)*6)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=16)
      INTEGER NSQAMPSO
      PARAMETER (NSQAMPSO=1)
      INTEGER HELAVGFACTOR
      PARAMETER (HELAVGFACTOR=4)
      LOGICAL CHOSEN_SO_CONFIGS(NSQAMPSO)
      DATA CHOSEN_SO_CONFIGS/.TRUE./
      COMMON/CHOSEN_BORN_SQSO/CHOSEN_SO_CONFIGS
C     
C     ARGUMENTS
C     
      REAL*8 P(0:3,NEXTERNAL),ANS(0:NSQAMPSO)
C     FLAV_IDX (the dummy argument) is declared with NFLAV below.
C     
C     LOCAL VARIABLES
C     
      INTEGER FLAVOR(NEXTERNAL)
      REAL*8 T(NSQAMPSO), BUFF
      INTEGER IHEL,IDEN, I, J
C     For a 1>N process, them BEAMTWO_HELAVGFACTOR would be set to 1.
      INTEGER BEAMS_HELAVGFACTOR(2)
      DATA (BEAMS_HELAVGFACTOR(I),I=1,2)/2,2/
      INTEGER JC(NEXTERNAL)
      INTEGER NFLAV
      PARAMETER (NFLAV=1)
      INTEGER NNTRY_FLAV, NGOODHEL_FLAV
      PARAMETER (NNTRY_FLAV=NFLAV)
      PARAMETER (NGOODHEL_FLAV=NCOMB*NFLAV)
      INTEGER FLAV_IDX
      INTEGER GET_FLAVOR_INDEX
      INTEGER NTRY(NFLAV)
      LOGICAL GOODHEL(NCOMB,NFLAV)
      DATA NTRY/NNTRY_FLAV*0/
      DATA GOODHEL/NGOODHEL_FLAV*.FALSE./
      DATA IDEN/36/
C     
C     GLOBAL VARIABLES
C     
      INTEGER NHEL(NEXTERNAL,NCOMB)
      DATA (NHEL(I,   1),I=1,4) /-1, 1,-1, 1/
      DATA (NHEL(I,   2),I=1,4) /-1, 1,-1,-1/
      DATA (NHEL(I,   3),I=1,4) /-1, 1, 1, 1/
      DATA (NHEL(I,   4),I=1,4) /-1, 1, 1,-1/
      DATA (NHEL(I,   5),I=1,4) /-1,-1,-1, 1/
      DATA (NHEL(I,   6),I=1,4) /-1,-1,-1,-1/
      DATA (NHEL(I,   7),I=1,4) /-1,-1, 1, 1/
      DATA (NHEL(I,   8),I=1,4) /-1,-1, 1,-1/
      DATA (NHEL(I,   9),I=1,4) / 1, 1,-1, 1/
      DATA (NHEL(I,  10),I=1,4) / 1, 1,-1,-1/
      DATA (NHEL(I,  11),I=1,4) / 1, 1, 1, 1/
      DATA (NHEL(I,  12),I=1,4) / 1, 1, 1,-1/
      DATA (NHEL(I,  13),I=1,4) / 1,-1,-1, 1/
      DATA (NHEL(I,  14),I=1,4) / 1,-1,-1,-1/
      DATA (NHEL(I,  15),I=1,4) / 1,-1, 1, 1/
      DATA (NHEL(I,  16),I=1,4) / 1,-1, 1,-1/
      COMMON/PROCESS_NHEL/NHEL

      INTEGER USERHEL
      DATA USERHEL/-1/
      COMMON/HELUSERCHOICE/USERHEL
      LOGICAL HELRESET
      COMMON/HELRESET/HELRESET
      DATA HELRESET/.TRUE./

      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      COMMON/BORN_BEAM_POL/POLARIZATIONS
      DATA ((POLARIZATIONS(I,J),I=0,NEXTERNAL),J=0,5)/NPOLENTRIES*-1/

C     
C     FUNCTIONS
C     
      LOGICAL IS_BORN_HEL_SELECTED
      INTEGER BROKEN_SYM

C     ----------
C     Check if helreset mode is on
C     ---------
      IF (HELRESET) THEN
        DO I=1,NFLAV
          NTRY(I) = 0
        ENDDO
        DO I=1,NCOMB
          DO J=1,NFLAV
            GOODHEL(I,J) = .FALSE.
          ENDDO
        ENDDO
        HELRESET = .FALSE.
      ENDIF


C     ----------
C     BEGIN CODE
C     ----------
C     FLAV_IDX=0 (or out of range): GET_FLAVOR_INDEX could not resolve
C      the
C     requested flavor -- it is not an allowed combination, so its
C      matrix
C     element is identically zero. Short-circuit before touching the
C     1..NFLAV GOODHEL/NTRY arrays.
      IF (FLAV_IDX.LT.1 .OR. FLAV_IDX.GT.NFLAV) THEN
        ANS(:) = 0D0
        RETURN
      ENDIF
      CALL GET_FLAVOR(FLAV_IDX, FLAVOR)
      IF(USERHEL.EQ.-1) NTRY(FLAV_IDX)=NTRY(FLAV_IDX)+1
      DO IHEL=1,NEXTERNAL
        JC(IHEL) = +1
      ENDDO
      ANS(:) = 0D0
C     When spin-2 particles are involved, the Helicity filtering is
C      dangerous for the 2->1 topology.
C     This is because depending on the MC setup the initial PS points
C      have back-to-back initial states
C     for which some of the spin-2 helicity configurations are zero.
C      But they are no longer zero
C     if the point is boosted on the z-axis. Remember that HELAS
C      helicity amplitudes are no longer
C     lorentz invariant with expternal spin-2 particles (only the
C      helicity sum is).
C     For this reason, we simply remove the filterin when there is
C      only three external particles.
      IF (NEXTERNAL.LE.3) THEN
        GOODHEL(:,:) = .TRUE.
      ENDIF
      DO IHEL=1,NCOMB
        IF (USERHEL.EQ.-1.OR.USERHEL.EQ.IHEL) THEN
          IF (GOODHEL(IHEL,FLAV_IDX) .OR. NTRY(FLAV_IDX) .LT. 20
     $      .OR.USERHEL.NE.-1) THEN
            IF(NTRY(FLAV_IDX).GE.2.AND.POLARIZATIONS(0,0).NE.
     $       -1.AND.(.NOT.IS_BORN_HEL_SELECTED(IHEL))) THEN
              CYCLE
            ENDIF
            CALL MATRIX(P ,NHEL(1,IHEL),JC(1),FLAV_IDX, T)
            BUFF=0D0
            DO I=1,NSQAMPSO
              IF(POLARIZATIONS(0,0).EQ.-1.OR.IS_BORN_HEL_SELECTED(IHEL)
     $         ) THEN
                ANS(I)=ANS(I)+T(I)
              ENDIF
              BUFF=BUFF+T(I)
            ENDDO
            IF (BUFF .NE. 0D0 .AND. .NOT.    GOODHEL(IHEL,FLAV_IDX))
     $        THEN
              GOODHEL(IHEL,FLAV_IDX)=.TRUE.
            ENDIF
          ENDIF
        ENDIF
      ENDDO
      ANS(0)=0.0D0
      DO I=1,NSQAMPSO
        ANS(I)=ANS(I)/DBLE(IDEN)*BROKEN_SYM(FLAVOR)
        IF (CHOSEN_SO_CONFIGS(I)) THEN
          ANS(0)=ANS(0)+ANS(I)
        ENDIF
      ENDDO
      IF(USERHEL.NE.-1) THEN
        DO I=0,NSQAMPSO
          ANS(I)=ANS(I)*HELAVGFACTOR
        ENDDO
      ELSE
        DO J=1,NINITIAL
          IF (POLARIZATIONS(J,0).NE.-1) THEN
            DO I=0,NSQAMPSO
              ANS(I)=ANS(I)*BEAMS_HELAVGFACTOR(J)
              ANS(I)=ANS(I)/POLARIZATIONS(J,0)
            ENDDO
          ENDIF
        ENDDO
      ENDIF
      END


      SUBROUTINE MATRIX(P,NHEL,IC,FLAV_IDX,RES)
      USE MODEL_OBJECT
C     
C     Generated by MadGraph5_aMC@NLO v. %(version)s, %(date)s
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared summed/avg over colors
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: d~ u > ve e+ [ all = QCD QED ] QCD^2<=0 QED^2<=6
C     Process: s~ c > ve e+ [ all = QCD QED ] QCD^2<=0 QED^2<=6
C     
      USE ALOHA_OBJECT
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=1)
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=4)
      INTEGER    NWAVEFUNCS, NCOLOR
      PARAMETER (NWAVEFUNCS=5, NCOLOR=1)
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=1, NSQAMPSO=1)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
      INTEGER DENOM
      INTEGER CF(1)
      COMMON /COLOR_MATRIX/ CF,DENOM
C     
C     ARGUMENTS
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
      INTEGER FLAV_IDX
      REAL*8 RES(NSQAMPSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J,M,N
      COMPLEX*16 ZTEMP
      COMPLEX*16 AMP(NGRAPHS)
      INTEGER CF_INDEX
      COMPLEX*16 JAMP(NCOLOR,NAMPSO)
      COMPLEX*16 TMP_JAMP(0)
      TYPE(ALOHA) W(NWAVEFUNCS)
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
C     
C     FUNCTION
C     
      INTEGER SQSOINDEX
C     
C     GLOBAL VARIABLES
C     
      INCLUDE 'coupl.inc'

C     
C     COLOR DATA
C     
      DATA DENOM/1/
      DATA (CF(I),I=  1,  1) /3/
C     1 T(1,2)
C     ----------
C     BEGIN CODE
C     ----------
      CALL GET_AMP(P,NHEL,IC,FLAV_IDX,AMP)
C     WRITE (*,*) '  -> AMP = ', AMP
      CALL GET_JAMP(AMP,JAMP)
C     WRITE (*,*) '  -> JAMP = ', JAMP
      CALL GET_MATRIX(JAMP, RES)
C     write (*,*) "  -> col.ave. |M|^2 for HEL=[", NHEL ,"] = ", MATRIX



      END


      SUBROUTINE GET_NHEL(IDEN_STAR,NHEL_STAR)
C     CONSTANTS
C     
CF2PY INTENT(OUT) :: NHEL_STAR
CF2PY INTENT(OUT) :: IDEN_STAR
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=4)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=16)

      INTEGER NHEL(NEXTERNAL,NCOMB),NHEL_STAR(NEXTERNAL,NCOMB)
      INTEGER IDEN,IDEN_STAR

      DATA (NHEL(I,   1),I=1,4) /-1, 1,-1, 1/
      DATA (NHEL(I,   2),I=1,4) /-1, 1,-1,-1/
      DATA (NHEL(I,   3),I=1,4) /-1, 1, 1, 1/
      DATA (NHEL(I,   4),I=1,4) /-1, 1, 1,-1/
      DATA (NHEL(I,   5),I=1,4) /-1,-1,-1, 1/
      DATA (NHEL(I,   6),I=1,4) /-1,-1,-1,-1/
      DATA (NHEL(I,   7),I=1,4) /-1,-1, 1, 1/
      DATA (NHEL(I,   8),I=1,4) /-1,-1, 1,-1/
      DATA (NHEL(I,   9),I=1,4) / 1, 1,-1, 1/
      DATA (NHEL(I,  10),I=1,4) / 1, 1,-1,-1/
      DATA (NHEL(I,  11),I=1,4) / 1, 1, 1, 1/
      DATA (NHEL(I,  12),I=1,4) / 1, 1, 1,-1/
      DATA (NHEL(I,  13),I=1,4) / 1,-1,-1, 1/
      DATA (NHEL(I,  14),I=1,4) / 1,-1,-1,-1/
      DATA (NHEL(I,  15),I=1,4) / 1,-1, 1, 1/
      DATA (NHEL(I,  16),I=1,4) / 1,-1, 1,-1/
      DATA IDEN/36/
      IDEN_STAR = IDEN
      NHEL_STAR = NHEL
      END


      SUBROUTINE GET_AMP(P,NHEL,IC,FLAV_IDX,AMP)
      USE MODEL_OBJECT
C     
C     Process: d~ u > ve e+ [ all = QCD QED ] QCD^2<=0 QED^2<=6
C     Process: s~ c > ve e+ [ all = QCD QED ] QCD^2<=0 QED^2<=6
C     
CF2PY INTENT(OUT) :: AMP
CF2PY INTENT(IN) :: NHEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
CF2PY INTENT(IN) :: IC
CF2PY INTENT(IN) :: FLAV_IDX

      USE ALOHA_OBJECT
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=1)
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=4)
      INTEGER    NWAVEFUNCS, NCOLOR
      PARAMETER (NWAVEFUNCS=5, NCOLOR=1)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
C     
C     ARGUMENTS
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
      INTEGER FLAV_IDX
      INTEGER FLAVOR(NEXTERNAL)
C     
C     LOCAL VARIABLES
C     
      COMPLEX*16 AMP(NGRAPHS)
      TYPE(ALOHA) W(NWAVEFUNCS)
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
      DOUBLE PRECISION BWCUTOFF
C     Flavor table for the FLAV_IDX -> FLAVOR rebuild.
      INTEGER NMASK_FLAV
      PARAMETER (NMASK_FLAV=1)
      INTEGER MASK_J
      INTEGER FLAV_TABLE(NEXTERNAL, NMASK_FLAV)
      DATA FLAV_TABLE / 1, 1, 1, 1 /
C     
C     GLOBAL VARIABLES
C     
      INCLUDE 'coupl.inc'

C     
C     
      BWCUTOFF=15  ! use if $ syntax is defined in the process
C     Rebuild FLAVOR(NEXTERNAL) from the resolved flavor index.
      IF (FLAV_IDX .GE. 1 .AND. FLAV_IDX .LE. NMASK_FLAV) THEN
        DO MASK_J = 1, NEXTERNAL
          FLAVOR(MASK_J) = FLAV_TABLE(MASK_J, FLAV_IDX)
        ENDDO
      ELSE
        DO MASK_J = 1, NEXTERNAL
          FLAVOR(MASK_J) = FLAV_TABLE(MASK_J, 1)
        ENDDO
      ENDIF
      CALL OXXXXX(P(0,1),ZERO,NHEL(1),-1, FLAVOR(1),W(1))
      CALL IXXXXX(P(0,2),ZERO,NHEL(2),+1, FLAVOR(2),W(2))
      CALL OXXXXX(P(0,3),ZERO,NHEL(3),+1, FLAVOR(3),W(3))
      CALL IXXXXX(P(0,4),ZERO,NHEL(4),-1, FLAVOR(4),W(4))
      CALL FFV2P0_3(W(2),W(1),GC_124,DCMPLX(CMASS_MDL_MW),W(5))
C     Amplitude(s) for diagram number 1
      CALL FFV2_0(W(4),W(3),W(5),GC_124,AMP(1))

      END


      SUBROUTINE GET_JAMP(AMP,JAMP)
C     
C     Process: d~ u > ve e+ [ all = QCD QED ] QCD^2<=0 QED^2<=6
C     Process: s~ c > ve e+ [ all = QCD QED ] QCD^2<=0 QED^2<=6
C     
CF2PY INTENT(OUT) :: JAMP
CF2PY INTENT(IN) :: AMP

      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=1)
      INTEGER    NCOLOR
      PARAMETER ( NCOLOR=1)
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=1, NSQAMPSO=1)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
      COMPLEX*16 AMP(NGRAPHS), TMP_JAMP(0)
      COMPLEX*16 JAMP(NCOLOR,NAMPSO)

      JAMP(:,:) = 0D0
C     JAMPs contributing to orders QCD=0 QED=2
      JAMP(1,1) = AMP(1)
      END

      SUBROUTINE GET_MATRIX(JAMP, RES)
C     
C     Process: d~ u > ve e+ [ all = QCD QED ] QCD^2<=0 QED^2<=6
C     Process: s~ c > ve e+ [ all = QCD QED ] QCD^2<=0 QED^2<=6
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
CF2PY INTENT(OUT) :: MATRIX
CF2PY INTENT(IN) :: JAMP(NCOLOR,NAMPSO)


      INTEGER    NCOLOR
      PARAMETER (NCOLOR=1)
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=1, NSQAMPSO=1)
      REAL*8     ZERO,RES(NSQAMPSO)
      PARAMETER (ZERO=0D0)
      INTEGER SQSOINDEX
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J,M,N
      COMPLEX*16 ZTEMP

      INTEGER CF_INDEX
      INTEGER CF(NCOLOR*(NCOLOR+1)/2)
      INTEGER DENOM
      COMMON /COLOR_MATRIX/ CF,DENOM
      COMPLEX*16 JAMP(NCOLOR,NAMPSO), TMP_JAMP(0)
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
C     
C     COLOR DATA
C     

      RES(:) = 0.D0
      DO M = 1, NAMPSO
        CF_INDEX= 0
        DO I = 1, NCOLOR
          ZTEMP = (0.D0,0.D0)
          DO J = I, NCOLOR
            CF_INDEX = CF_INDEX +1
            ZTEMP = ZTEMP + CF(CF_INDEX)*JAMP(J,M)
          ENDDO
          DO N = 1, NAMPSO
            RES(SQSOINDEX(M,N)) = RES(SQSOINDEX(M,N)) + REAL(ZTEMP
     $       *DCONJG(JAMP(I,N)))
          ENDDO
        ENDDO
      ENDDO
      RES(:) = RES(:)/DENOM
      END

      SUBROUTINE GET_INTER(JAMP_1,JAMP_2, INTER)
      IMPLICIT NONE
CF2PY INTENT(OUT) :: INTER(NSQAMPSO)
CF2PY INTENT(IN) :: JAMP_1(NCOLOR,NAMPSO)
CF2PY INTENT(IN) :: JAMP_2(NCOLOR,NAMPSO)

      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=1, NSQAMPSO=1)
      INTEGER SQSOINDEX

      INTEGER I,J,M,N
      INTEGER NCOLOR
      PARAMETER (NCOLOR=1)
      INTEGER CF_INDEX
      INTEGER CF(NCOLOR*(NCOLOR+1)/2)
      INTEGER DENOM
      COMMON /COLOR_MATRIX/ CF,DENOM
      COMPLEX*16 JAMP_1(NCOLOR,NAMPSO),JAMP_2(NCOLOR,NAMPSO),ZTEMP
     $ ,INTER(NSQAMPSO)
C     
C     COLOR DATA
C     

      INTER(:) = 0.D0
      DO M = 1, NAMPSO
        CF_INDEX= 0
        DO I = 1, NCOLOR
          DO J = I, NCOLOR
            CF_INDEX = CF_INDEX +1
            DO N = 1, NAMPSO
              INTER(SQSOINDEX(M,N)) =
     $            INTER(SQSOINDEX(M,N)) +
     $            CF(CF_INDEX)*(DCONJG(JAMP_2(I,N))*
     $            JAMP_1(J,M)+DCONJG(JAMP_2(J,N))*JAMP_1(I,M))
            ENDDO
          ENDDO
        ENDDO
      ENDDO
      INTER(:) = INTER(:)/(2D0*DENOM)
      RETURN
      END

      SUBROUTINE  GET_DENSITY(P, POS, N_CHANGING, ALLOW_HEL, N_COMB,
     $  FLAVOR, ALPHAS, INTER_SUM)
C     P momenta
C     NHEL base of helicity that are not changing
C     POS(N_CHNGING): position of the changing helicity
C     n_changing: number of changing helicity
C     ALLOW_HEL(NCOMB, N_CHANGING): combination of helicity to
C      consider (all jamp computed)
C     INTER((NCOMB*NCOMB+1)/2i,NSQAMPSO) : all interference term (not
C      the symmetric one)
      USE MODEL_OBJECT
      IMPLICIT NONE
CF2PY INTENT(IN) :: P(0:3,4)
CF2PY INTENT(IN) :: POS(N_CHANGING)
CF2PY INTENT(IN) :: N_CHANGING
CF2PY INTENT(IN) :: ALLOW_HEL(N_CHANGING*N_COMB)
CF2PY INTENT(IN) :: N_COMB
CF2PY INTENT(IN) :: FLAVOR(4)
CF2PY INTENT(IN) :: ALPHAS
CF2PY INTENT(OUT) :: INTER_SUM(N_COMB*(N_COMB+1)/2)
C     

      INTEGER NB_NHEL
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NB_NHEL=16)
      PARAMETER (NAMPSO=1, NSQAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=4)
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER THISNHEL(NEXTERNAL)
      INTEGER N_CHANGING, N_COMB
      INTEGER NINTER
      INTEGER POS(*)
      INTEGER ALLOW_HEL(*)
      INTEGER FLAVOR(NEXTERNAL)
      DOUBLE COMPLEX, ALLOCATABLE :: TMP_INTER(:,:)
      DOUBLE PRECISION ALPHAS
      DOUBLE COMPLEX INTER_SUM(*)
C     LOCAL
      INTEGER I,IHEL,IPART
      INTEGER J
      DOUBLE PRECISION PI
C     
C     GLOBAL
C     
      LOGICAL CHOSEN_SO_CONFIGS(NSQAMPSO)
      COMMON/CHOSEN_BORN_SQSO/CHOSEN_SO_CONFIGS

      INTEGER NHEL(NEXTERNAL,NB_NHEL),NTRY
C     put in common block to expose this variable to python interface
      COMMON/PROCESS_NHEL/NHEL
C     
C     include coupling definition to update the value of alphas
C     
      INCLUDE 'coupl.inc'

      NINTER = N_COMB*(N_COMB+1)/2
      ALLOCATE(TMP_INTER(NSQAMPSO, NINTER))
      TMP_INTER(:,:) = (0D0, 0D0)

      DO I = 1,  N_COMB*(N_COMB+1)/2
        INTER_SUM(I) = 0D0
      ENDDO

      IF (ALPHAS.NE.0D0) THEN
        PI = 3.141592653589793D0
        G = 2* DSQRT(ALPHAS*PI)
        CALL UPDATE_AS_PARAM()
      ENDIF

      DO IHEL =1, NB_NHEL
        THISNHEL(:) = NHEL(:, IHEL)
        DO IPART=1,N_CHANGING
          IF(THISNHEL(POS(IPART)).NE.ALLOW_HEL(IPART)) GOTO 10  !BYPASS COMPUTATION FOR HELICITY
        ENDDO
        TMP_INTER(:,:) = 0
        CALL  GET_ALL_INTER(P, THISNHEL, POS, N_CHANGING, ALLOW_HEL,
     $    N_COMB, FLAVOR, TMP_INTER)
        DO J =1, NSQAMPSO
          IF (CHOSEN_SO_CONFIGS(J)) THEN
            DO I = 1, N_COMB*(N_COMB+1)/2
              INTER_SUM(I) = INTER_SUM(I) + TMP_INTER(J,I)
            ENDDO
          ENDIF
        ENDDO
 10   ENDDO
      RETURN
      DEALLOCATE(TMP_INTER)
      END



      SUBROUTINE  GET_ALL_INTER(P, NHEL, POS, N_CHANGING, ALLOW_HEL,
     $  N_COMB, FLAVOR, INTER)
C     P momenta
C     NHEL base of helicity that are not changing
C     POS(N_CHNGING): position of the changing helicity
C     n_changing: number of changing helicity
C     ALLOW_HEL(NCOMB, N_CHANGING): combination of helicity to
C      consider (all jamp computed)
C     INTER(NSO, (NCOMB*NCOMB+1)/2): all interference term (not the
C      symmetric one)
      IMPLICIT NONE
CF2PY INTENT(IN) :: P(0:3,4)
CF2PY INTENT(IN) :: NHEL(4)
CF2PY INTENT(IN) :: POS(N_CHANGING)
CF2PY INTENT(IN) :: N_CHANGING
CF2PY INTENT(IN) :: ALLOW_HEL(N_CHANGING*N_COMB)
CF2PY INTENT(IN) :: N_COMB
CF2PY INTENT(IN) :: FLAVOR(4)
CF2PY INTENT(OUT) :: INTER(NSQAMPSO,NCOMB*(NCOMB+1)/2)
C     
C     
C     ARGUMENTS
C     
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=1, NSQAMPSO=1)
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=4)
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL)
      INTEGER N_CHANGING, N_COMB
      INTEGER POS(*)
      INTEGER ALLOW_HEL(*)
      INTEGER FLAVOR(NEXTERNAL)
      DOUBLE COMPLEX INTER(NSQAMPSO,*)
C     
C     Intermediate array
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=1)
      INTEGER    NCOLOR
      PARAMETER (NCOLOR=1)
      INTEGER IC(NEXTERNAL)

      DOUBLE COMPLEX AMP(NGRAPHS)
      DOUBLE COMPLEX, ALLOCATABLE:: JAMP(:,:,:)
      INTEGER, SAVE :: S_NCOMB = -1
C     
C     LOCAL
C     
      INTEGER I,J,SOL,N
      INTEGER FLAV_IDX
      INTEGER GET_FLAVOR_INDEX

C     ----------
C     BEGIN CODE
C     ----------
      IF (ALLOCATED(JAMP).AND. N_COMB.NE.S_NCOMB)THEN
        DEALLOCATE(JAMP)
      ENDIF
      IF (.NOT.ALLOCATED(JAMP))THEN
        ALLOCATE(JAMP(NCOLOR, NAMPSO, N_COMB))
        S_NCOMB=N_COMB
      ENDIF
      IC(:)=1
      FLAV_IDX = GET_FLAVOR_INDEX(FLAVOR)
      DO I = 1, N_COMB
        DO N = 1, N_CHANGING
          NHEL(POS(N)) = ALLOW_HEL((I-1)*N_CHANGING+N)
        ENDDO
        CALL GET_AMP(P,NHEL,IC,FLAV_IDX,AMP)
        CALL GET_JAMP(AMP,JAMP(1,1,I))
      ENDDO

      SOL = 0
      DO I = 1, N_COMB
        DO J= I, N_COMB
          SOL = SOL +1
          CALL GET_INTER(JAMP(1,1,I), JAMP(1,1,J), INTER(1,SOL))
        ENDDO
      ENDDO


      RETURN
      END




      SUBROUTINE GET_VALUE(P, ALPHAS, NHEL, FLAVOR ,ANS)
C     f2py interface accepting the full FLAVOR(NEXTERNAL) array
C      (back-compat):
C     resolve it to FLAV_IDX and forward to GET_value_idx.
      USE MODEL_OBJECT
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=4)
C     
C     ARGUMENTS
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER NHEL
      DOUBLE PRECISION ALPHAS
      INTEGER FLAVOR(NEXTERNAL)
      INTEGER FLAV_IDX
      INTEGER GET_FLAVOR_INDEX
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: NHEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
CF2PY INTENT(IN) :: ALPHAS
CF2PY INTENT(IN) :: FLAVOR(NEXTERNAL)

      FLAV_IDX = GET_FLAVOR_INDEX(FLAVOR)
      CALL GET_VALUE_IDX(P, ALPHAS, NHEL, FLAV_IDX, ANS)
      RETURN
      END

      SUBROUTINE GET_VALUE_IDX(P, ALPHAS, NHEL, FLAV_IDX ,ANS)
C     f2py interface accepting the flavor index directly.
      USE MODEL_OBJECT
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=4)
C     
C     ARGUMENTS
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER NHEL
      DOUBLE PRECISION ALPHAS
      REAL*8 PI
      INTEGER FLAV_IDX
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: NHEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
CF2PY INTENT(IN) :: ALPHAS
CF2PY INTENT(IN) :: FLAV_IDX
C     the include file with the values of the parameters and masses
      INCLUDE 'coupl.inc'

      PI = 3.141592653589793D0
      G = 2* DSQRT(ALPHAS*PI)
      CALL UPDATE_AS_PARAM()
      IF (NHEL.NE.0) THEN
        CALL SMATRIXHEL(P, NHEL, FLAV_IDX, ANS)
      ELSE
        CALL SMATRIX(P, FLAV_IDX, ANS)
      ENDIF
      RETURN
      END

      SUBROUTINE INITIALISEMODEL(PATH)
C     ROUTINE FOR F2PY to read the benchmark point.
      IMPLICIT NONE
      CHARACTER*512 PATH
CF2PY INTENT(IN) :: PATH
      CALL SETPARA(PATH)  !first call to setup the paramaters
      RETURN
      END

      LOGICAL FUNCTION IS_BORN_HEL_SELECTED(HELID)
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=4)
      INTEGER    NCOMB
      PARAMETER (NCOMB=16)
C     
C     ARGUMENTS
C     
      INTEGER HELID
C     
C     LOCALS
C     
      INTEGER I,J
      LOGICAL FOUNDIT
C     
C     GLOBALS
C     
      INTEGER HELC(NEXTERNAL,NCOMB)
      COMMON/PROCESS_NHEL/HELC

      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      COMMON/BORN_BEAM_POL/POLARIZATIONS
C     ----------
C     BEGIN CODE
C     ----------

      IS_BORN_HEL_SELECTED = .TRUE.
      IF (POLARIZATIONS(0,0).EQ.-1) THEN
        RETURN
      ENDIF

      DO I=1,NEXTERNAL
        IF (POLARIZATIONS(I,0).EQ.-1) THEN
          CYCLE
        ENDIF
        FOUNDIT = .FALSE.
        DO J=1,POLARIZATIONS(I,0)
          IF (HELC(I,HELID).EQ.POLARIZATIONS(I,J)) THEN
            FOUNDIT = .TRUE.
            EXIT
          ENDIF
        ENDDO
        IF(.NOT.FOUNDIT) THEN
          IS_BORN_HEL_SELECTED = .FALSE.
          RETURN
        ENDIF
      ENDDO

      RETURN
      END

      INTEGER FUNCTION BROKEN_SYM(FLAV)
      INCLUDE 'nexternal.inc'
      INTEGER FLAV(NEXTERNAL)
      INTEGER I,J,K,ICOMP
      INTEGER N_TOT, OLD_FACTOR, TOTAL_FACTOR
      INTEGER NCOMP, NENTRIES
      PARAMETER (NCOMP=1)
      PARAMETER (NENTRIES=2)
      INTEGER COMP_BEG(NCOMP), COMP_END(NCOMP), COMP_OLD(NCOMP)
      INTEGER PID_LIST(NENTRIES), PID_WORK(NENTRIES)
      INTEGER BLOCK_START(NENTRIES), BLOCK_LEN(NENTRIES)
      LOGICAL SAME_BLOCK
      DATA COMP_BEG /1/
      DATA COMP_END /2/
      DATA COMP_OLD /1/
      DATA PID_LIST /12,-11/
      DATA BLOCK_START /3,4/
      DATA BLOCK_LEN /1,1/

      PID_WORK = PID_LIST
      TOTAL_FACTOR = 1
      DO ICOMP=1,NCOMP
        OLD_FACTOR = COMP_OLD(ICOMP)
        IF (COMP_OLD(ICOMP).GT.1) THEN
          DO I=COMP_BEG(ICOMP),COMP_END(ICOMP)
            IF (PID_WORK(I).EQ.0) CYCLE
            N_TOT = 1
            DO J=I+1,COMP_END(ICOMP)
              IF (PID_WORK(I).EQ.PID_WORK(J)) THEN
                SAME_BLOCK = .TRUE.
                IF (BLOCK_LEN(I).NE.BLOCK_LEN(J)) SAME_BLOCK = .FALSE.
                DO K=1,BLOCK_LEN(I)
                  IF (FLAV(BLOCK_START(I)+K-1).NE.FLAV(BLOCK_START(J)
     $             +K-1)) THEN
                    SAME_BLOCK = .FALSE.
                  ENDIF
                ENDDO
                IF (SAME_BLOCK) THEN
                  PID_WORK(J) = 0
                  N_TOT = N_TOT + 1
                  OLD_FACTOR = OLD_FACTOR/N_TOT
                ENDIF
              ENDIF
            ENDDO
          ENDDO
        ENDIF
        TOTAL_FACTOR = TOTAL_FACTOR*OLD_FACTOR
      ENDDO
      BROKEN_SYM = TOTAL_FACTOR
      RETURN
      END



      INTEGER FUNCTION GET_FLAVOR_INDEX(FLAVOR)
C     Resolve an external FLAVOR(NEXTERNAL) group-position vector to
C      its
C     1-based index in the allowed-flavor table (the same ordering
C      used by
C     compute_flavor_masks / the FLAV_TABLE mask columns). A resolved
C      flavor
C     returns an index in [1,NFLAV]; a flavor that is NOT in the table
C      (i.e.
C     not a physical/allowed combination, so its matrix element is
C      zero)
C     returns 0. Callers MUST treat the 0 sentinel as "not a valid
C      flavor"
C     and short-circuit to a zero result before indexing the 1..NFLAV
C     GOODHEL/NTRY arrays or FLAV_TABLE (there is no reserved 0 slot).
C     Computed once per phase-space point and then threaded down to
C     MATRIX/GET_AMP and the good-helicity filter.
      INCLUDE 'nexternal.inc'
      INTEGER NFLAV
      PARAMETER (NFLAV=1)
      INTEGER FLAVOR(NEXTERNAL)
CF2PY INTENT(IN) :: FLAVOR(NEXTERNAL)
CF2PY INTENT(OUT) :: GET_FLAVOR_INDEX
      INTEGER FI_I, FI_J
      LOGICAL FI_MATCH
      INTEGER FI_TABLE(NEXTERNAL, NFLAV)
      DATA FI_TABLE /1, 1, 1, 1/
C     0 sentinel for an unresolved (not-in-table) flavor (see above).
      GET_FLAVOR_INDEX = 0
      DO FI_I = 1, NFLAV
        FI_MATCH = .TRUE.
        DO FI_J = 1, NEXTERNAL
          IF (FLAVOR(FI_J) .NE. FI_TABLE(FI_J, FI_I)) THEN
            FI_MATCH = .FALSE.
            EXIT
          ENDIF
        ENDDO
        IF (FI_MATCH) THEN
          GET_FLAVOR_INDEX = FI_I
          RETURN
        ENDIF
      ENDDO
      RETURN
      END



      SUBROUTINE GET_FLAVOR(FLAV_IDX, FLAVOR)
C     Reverse of GET_FLAVOR_INDEX: fill FLAVOR(NEXTERNAL) with the
C      per-leg
C     group-position vector of the FLAV_IDX-th allowed flavor (same
C      table /
C     ordering). FLAV_IDX is expected in [1,NFLAV] (GET_FLAVOR_INDEX
C      never
C     returns 0); the bounds guard below is purely defensive and maps
C      any
C     out-of-range value to the first flavor. Used by the outer entry
C      points
C     (SMATRIX, ...) which receive FLAV_IDX but still need the FLAVOR
C      array
C     (e.g. for BROKEN_SYM).
      INCLUDE 'nexternal.inc'
      INTEGER NFLAV
      PARAMETER (NFLAV=1)
      INTEGER FLAV_IDX
      INTEGER FLAVOR(NEXTERNAL)
CF2PY INTENT(IN) :: FLAV_IDX
CF2PY INTENT(OUT) :: FLAVOR(NEXTERNAL)
      INTEGER FA_I, FA_USE
      INTEGER FA_TABLE(NEXTERNAL, NFLAV)
      DATA FA_TABLE /1, 1, 1, 1/
      FA_USE = FLAV_IDX
      IF (FA_USE .LT. 1 .OR. FA_USE .GT. NFLAV) FA_USE = 1
      DO FA_I = 1, NEXTERNAL
        FLAVOR(FA_I) = FA_TABLE(FA_I, FA_USE)
      ENDDO
      RETURN
      END



C     Set of functions to handle the array indices of the split orders


      INTEGER FUNCTION SQSOINDEX(ORDERINDEXA, ORDERINDEXB)
C     
C     This functions plays the role of the interference matrix. It can
C      be hardcoded or 
C     made more elegant using hashtables if its execution speed ever
C      becomes a relevant
C     factor. From two split order indices, it return the
C      corresponding index in the squared 
C     order canonical ordering.
C     
C     CONSTANTS
C     

      INTEGER    NSO, NSQUAREDSO, NAMPSO
      PARAMETER (NSO=2, NSQUAREDSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERINDEXA, ORDERINDEXB
C     
C     LOCAL VARIABLES
C     
      INTEGER I, SQORDERS(NSO)
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      DATA (AMPSPLITORDERS(  1,I),I=  1,  2) /    0,    2/
      COMMON/AMPSPLITORDERS/AMPSPLITORDERS
C     
C     FUNCTION
C     
      INTEGER SOINDEX_FOR_SQUARED_ORDERS
C     
C     BEGIN CODE
C     
      DO I=1,NSO
        SQORDERS(I)=AMPSPLITORDERS(ORDERINDEXA,I)
     $   +AMPSPLITORDERS(ORDERINDEXB,I)
      ENDDO
      SQSOINDEX=SOINDEX_FOR_SQUARED_ORDERS(SQORDERS)
      END

      INTEGER FUNCTION SOINDEX_FOR_SQUARED_ORDERS(ORDERS)
C     
C     This functions returns the integer index identifying the squared
C      split orders list passed in argument which corresponds to the
C      values of the following list of couplings (and in this order).
C     ['QCD', 'QED']
C     
C     CONSTANTS
C     
      INTEGER    NSO, NSQSO, NAMPSO
      PARAMETER (NSO=2, NSQSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J
      INTEGER SQSPLITORDERS(NSQSO,NSO)
      DATA (SQSPLITORDERS(  1,I),I=  1,  2) /    0,    4/
      COMMON/SQPLITORDERS/SQPLITORDERS
C     
C     BEGIN CODE
C     
      DO I=1,NSQSO
        DO J=1,NSO
          IF (ORDERS(J).NE.SQSPLITORDERS(I,J)) GOTO 1009
        ENDDO
        SOINDEX_FOR_SQUARED_ORDERS = I
        RETURN
 1009   CONTINUE
      ENDDO

      WRITE(*,*) 'ERROR:: Stopping in function'
      WRITE(*,*) 'SOINDEX_FOR_SQUARED_ORDERS'
      WRITE(*,*) 'Could not find squared orders ',(ORDERS(I),I=1,NSO)
      STOP

      END

      SUBROUTINE GET_NSQSO_BORN(NSQSO)
C     
C     Simple subroutine returning the number of squared split order
C     contributions returned when calling smatrix_split_orders 
C     

      INTEGER    NSQUAREDSO
      PARAMETER  (NSQUAREDSO=1)

      INTEGER NSQSO

      NSQSO=NSQUAREDSO

      END

C     This is the inverse subroutine of SOINDEX_FOR_SQUARED_ORDERS.
C      Not directly useful, but provided nonetheless.
      SUBROUTINE GET_SQUARED_ORDERS_FOR_SOINDEX(SOINDEX,ORDERS)
C     
C     This functions returns the orders identified by the squared
C      split order index in argument. Order values correspond to
C      following list of couplings (and in this order):
C     ['QCD', 'QED']
C     
C     CONSTANTS
C     
      INTEGER    NSO, NSQSO
      PARAMETER (NSO=2, NSQSO=1)
C     
C     ARGUMENTS
C     
      INTEGER SOINDEX, ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I
      INTEGER SQPLITORDERS(NSQSO,NSO)
      COMMON/SQPLITORDERS/SQPLITORDERS
C     
C     BEGIN CODE
C     
      IF (SOINDEX.GT.0.AND.SOINDEX.LE.NSQSO) THEN
        DO I=1,NSO
          ORDERS(I) =  SQPLITORDERS(SOINDEX,I)
        ENDDO
        RETURN
      ENDIF

      WRITE(*,*) 'ERROR:: Stopping function'
     $ //' GET_SQUARED_ORDERS_FOR_SOINDEX'
      WRITE(*,*) 'Could not find squared orders index ',SOINDEX
      STOP

      END SUBROUTINE

C     This is the inverse subroutine of getting amplitude SO orders.
C      Not directly useful, but provided nonetheless.
      SUBROUTINE GET_ORDERS_FOR_AMPSOINDEX(SOINDEX,ORDERS)
C     
C     This functions returns the orders identified by the split order
C      index in argument. Order values correspond to following list of
C      couplings (and in this order):
C     ['QCD', 'QED']
C     
C     CONSTANTS
C     
      INTEGER    NSO, NAMPSO
      PARAMETER (NSO=2, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER SOINDEX, ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      COMMON/AMPSPLITORDERS/AMPSPLITORDERS
C     
C     BEGIN CODE
C     
      IF (SOINDEX.GT.0.AND.SOINDEX.LE.NAMPSO) THEN
        DO I=1,NSO
          ORDERS(I) =  AMPSPLITORDERS(SOINDEX,I)
        ENDDO
        RETURN
      ENDIF

      WRITE(*,*) 'ERROR:: Stopping function GET_ORDERS_FOR_AMPSOINDEX'
      WRITE(*,*) 'Could not find amplitude split orders index ',SOINDEX
      STOP

      END SUBROUTINE

C     This function is not directly useful, but included for
C      completeness
      INTEGER FUNCTION SOINDEX_FOR_AMPORDERS(ORDERS)
C     
C     This functions returns the integer index identifying the
C      amplitude split orders passed in argument which correspond to
C      the values of the following list of couplings (and in this
C      order):
C     ['QCD', 'QED']
C     
C     CONSTANTS
C     
      INTEGER    NSO, NAMPSO
      PARAMETER (NSO=2, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      COMMON/AMPSPLITORDERS/AMPSPLITORDERS
C     
C     BEGIN CODE
C     
      DO I=1,NAMPSO
        DO J=1,NSO
          IF (ORDERS(J).NE.AMPSPLITORDERS(I,J)) GOTO 1009
        ENDDO
        SOINDEX_FOR_AMPORDERS = I
        RETURN
 1009   CONTINUE
      ENDDO

      WRITE(*,*) 'ERROR:: Stopping function SOINDEX_FOR_AMPORDERS'
      WRITE(*,*) 'Could not find squared orders ',(ORDERS(I),I=1,NSO)
      STOP

      END

