      SUBROUTINE MC_NATIVE_PROPS(PMASS,PWIDTH,POW)
      USE MC_NATIVE_CONTEXT, ONLY: ACTIVE_CONTEXT,ENSURE_NATIVE_CONTEXT
      IMPLICIT NONE
      INCLUDE 'nexternal.inc'
      INCLUDE 'maxconfigs.inc'
      INCLUDE 'coupl.inc'
      DOUBLE PRECISION ZERO
      PARAMETER(ZERO=0D0)
      DOUBLE PRECISION PMASS(-NEXTERNAL:0,LMAXCONFIGS),PWIDTH(
     $ -NEXTERNAL:0,LMAXCONFIGS)
      INTEGER POW(-NEXTERNAL:0,LMAXCONFIGS)
      CALL ENSURE_NATIVE_CONTEXT()
      PMASS=0D0
      PWIDTH=0D0
      POW=0
      SELECT CASE(ACTIVE_CONTEXT)
      CASE(2)
      PMASS( -1,   1)  = ABS(MDL_MW)
      PWIDTH( -1,   1) = ABS(MDL_WW)
      POW( -1,   1) = 2
      END SELECT
      END
