      SUBROUTINE SMATRIX_REAL(P,WGT)
      IMPLICIT NONE
      INCLUDE 'nexternal.inc'
      DOUBLE PRECISION P(0:3,NEXTERNAL),Q(0:3,NEXTERNAL),WGT
      INTEGER NFKSPROCESS
      COMMON/C_NFKSPROCESS/NFKSPROCESS
      SELECT CASE(NFKSPROCESS)
      CASE(1)
      CALL SMATRIX1(P,WGT)
      CASE(2)
      CALL SMATRIX1(P,WGT)
      CASE(3)
      CALL SMATRIX1(P,WGT)
      CASE(4)
      CALL SMATRIX2(P,WGT)
      CASE(5)
      CALL SMATRIX3(P,WGT)
      CASE DEFAULT
      STOP 'Invalid native real sector'
      END SELECT
      END
