name: Restore lhapdf cache
description: Restores lhapdf from cache and sets MG5 accordingly

runs:
  using: composite
  steps:
    - name: Set cache key
      run: echo "CACHE_KEY=lhapdf-$ImageOS" >> $GITHUB_ENV
      shell: bash

    - uses: actions/cache/restore@v5
      with:
        path: ~/.cache/HEPtools-lhapdf
        key: ${{ env.CACHE_KEY }}

    - run: |
        cp -r ~/.cache/HEPtools-lhapdf/* ~/.cache/HEPtools 
        cd $GITHUB_WORKSPACE
        echo "heptools_install_dir=/home/runner/.cache/HEPtools" >> input/mg5_configuration.txt
        echo "lhapdf = /home/runner/.cache/HEPtools/bin/lhapdf-config" >>       input/mg5_configuration.txt
        echo "lhapdf_py3 = /home/runner/.cache/HEPtools/bin/lhapdf-config" >>       input/mg5_configuration.txt
        echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/runner/.cache/HEPTools/lhapdf6_py3//lib" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/runner/.cache/HEPTools/lib" >> $GITHUB_ENV
      shell: bash
