name: Restore full heptools cache
description: Restores lhapdf from cache and sets MG5 accordingly

runs:
  using: composite
  steps:
    # setup other environment 
    - run: |
        cd $GITHUB_WORKSPACE
        cp input/.mg5_configuration_default.txt input/mg5_configuration.txt
        cp Template/LO/Source/.make_opts Template/LO/Source/make_opts
      shell: bash
