name: Restore rivet/contur cache
description: Restores lhapdf from cache and sets MG5 accordingly

runs:
  using: composite
  steps:
    - uses: ./.github/actions/restore_heptools_pythia8
    - name: Set cache key
      run: echo "CACHE_KEY=contur-$ImageOS" >> $GITHUB_ENV
      shell: bash

    - uses: actions/cache/restore@v5
      with:
        path: ~/.cache/HEPtools
        key: ${{ env.CACHE_KEY }}

    - run: |
        cd $GITHUB_WORKSPACE
        echo "hepmc3_path = /home/runner/.cache/HEPtools/hepmc3" >>  input/mg5_configuration.txt
        echo "rivet_path = /home/runner/.cache/HEPtools/rivet" >>  input/mg5_configuration.txt
        echo "yoda_path = /home/runner/.cache/HEPtools/yoda" >>  input/mg5_configuration.txt
        echo "contur_path = /home/runner/.cache/HEPtools/contur" >>  input/mg5_configuration.txt
        echo "fastjet = /home/runner/.cache/HEPtools/fastjet/bin/fastjet-config" >>  input/mg5_configuration.txt
        echo "PYTHONPATH=$PYTHONPATH:/home/runner/.cache/HEPTools/contur/python3.10/:/home/runner/.cache/HEPTools/contur/python3.12/:/home/runner/.cache/HEPTools/rivet/python3.10/:/home/runner/.cache/HEPTools/rivet/python3.12/:/home/runner/.cache/HEPTools/rivet/local/python3.10/:/home/runner/.cache/HEPTools/rivet/local/python3.12/:/home/runner/.cache/HEPTools/lhapdf_py3/python3.10/:/home/runner/.cache/HEPTools/lhapdf_py3/python3.12/" >> $GITHUB_ENV 
      shell: bash
