ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of loop_sm'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_5 = ', GC_5
      WRITE(*,2) 'UVWfct_b_0_1eps = ', UVWFCT_B_0_1EPS
      WRITE(*,2) 'R2_UUA = ', R2_UUA
      WRITE(*,2) 'R2_DDZ_V3 = ', R2_DDZ_V3
      WRITE(*,2) 'R2_UUZ_V2 = ', R2_UUZ_V2
      WRITE(*,2) 'UVWfct_t_0 = ', UVWFCT_T_0
      WRITE(*,2) 'GC_2 = ', GC_2
      WRITE(*,2) 'GC_3 = ', GC_3
      WRITE(*,2) 'GC_21 = ', GC_21
      WRITE(*,2) 'GC_22 = ', GC_22
      WRITE(*,2) 'GC_23 = ', GC_23
      WRITE(*,2) 'GC_24 = ', GC_24
