C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(3,2,1)
C     
      SUBROUTINE FFV1_1(F2, V3, COUP, M1, W1,F1)
      USE ALOHA_OBJECT
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      TYPE(ALOHA) F1
      INTEGER FLV_INDEX1
      TYPE(ALOHA) F2
      INTEGER FLV_INDEX2
      REAL*8 M1
      REAL*8 P1(0:3)
      TYPE(ALOHA) V3
      REAL*8 W1
      COMPLEX*16 DENOM
      F1%P(:) = +F2%P(:)+V3%P(:)
      P1(:) = -F1 % P (:)
      F1 % FLV_INDEX = F2 % FLV_INDEX
      DENOM = COUP/(P1(0)**2-P1(1)**2-P1(2)**2-P1(3)**2 - M1 * (M1 -CI
     $ * W1))
      F1%W(1)= DENOM*CI*(F2 % W(1)*(P1(0)*(-V3 % W(1)+V3 % W(4))+(P1(1)
     $ *(V3 % W(2)-CI*(V3 % W(3)))+(P1(2)*(+CI*(V3 % W(2))+V3 % W(3))
     $ +P1(3)*(-V3 % W(1)+V3 % W(4)))))+(F2 % W(2)*(P1(0)*(V3 % W(2)
     $ +CI*(V3 % W(3)))+(P1(1)*(-1D0)*(V3 % W(1)+V3 % W(4))+(P1(2)*(
     $ -1D0)*(+CI*(V3 % W(1)+V3 % W(4)))+P1(3)*(V3 % W(2)+CI*(V3 % W(3)
     $ )))))+M1*(F2 % W(3)*(V3 % W(1)+V3 % W(4))+F2 % W(4)*(V3 % W(2)
     $ +CI*(V3 % W(3))))))
      F1%W(2)= DENOM*(-CI)*(F2 % W(1)*(P1(0)*(-V3 % W(2)+CI*(V3 % W(3))
     $ )+(P1(1)*(V3 % W(1)-V3 % W(4))+(P1(2)*(-CI*(V3 % W(1))+CI*(V3 %
     $  W(4)))+P1(3)*(V3 % W(2)-CI*(V3 % W(3))))))+(F2 % W(2)*(P1(0)
     $ *(V3 % W(1)+V3 % W(4))+(P1(1)*(-1D0)*(V3 % W(2)+CI*(V3 % W(3)))
     $ +(P1(2)*(+CI*(V3 % W(2))-V3 % W(3))-P1(3)*(V3 % W(1)+V3 % W(4)))
     $ ))+M1*(F2 % W(3)*(-V3 % W(2)+CI*(V3 % W(3)))+F2 % W(4)*(-V3 %
     $  W(1)+V3 % W(4)))))
      F1%W(3)= DENOM*(-CI)*(F2 % W(3)*(P1(0)*(V3 % W(1)+V3 % W(4))
     $ +(P1(1)*(-V3 % W(2)+CI*(V3 % W(3)))+(P1(2)*(-1D0)*(+CI*(V3 %
     $  W(2))+V3 % W(3))-P1(3)*(V3 % W(1)+V3 % W(4)))))+(F2 % W(4)
     $ *(P1(0)*(V3 % W(2)+CI*(V3 % W(3)))+(P1(1)*(-V3 % W(1)+V3 % W(4))
     $ +(P1(2)*(-CI*(V3 % W(1))+CI*(V3 % W(4)))-P1(3)*(V3 % W(2)+CI
     $ *(V3 % W(3))))))+M1*(F2 % W(1)*(-V3 % W(1)+V3 % W(4))+F2 % W(2)
     $ *(V3 % W(2)+CI*(V3 % W(3))))))
      F1%W(4)= DENOM*CI*(F2 % W(3)*(P1(0)*(-V3 % W(2)+CI*(V3 % W(3)))
     $ +(P1(1)*(V3 % W(1)+V3 % W(4))+(P1(2)*(-1D0)*(+CI*(V3 % W(1)+V3
     $  % W(4)))+P1(3)*(-V3 % W(2)+CI*(V3 % W(3))))))+(F2 % W(4)*(P1(0)
     $ *(-V3 % W(1)+V3 % W(4))+(P1(1)*(V3 % W(2)+CI*(V3 % W(3)))+(P1(2)
     $ *(-CI*(V3 % W(2))+V3 % W(3))+P1(3)*(-V3 % W(1)+V3 % W(4)))))+M1
     $ *(F2 % W(1)*(-V3 % W(2)+CI*(V3 % W(3)))+F2 % W(2)*(V3 % W(1)+V3
     $  % W(4)))))
      END


