C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(3,2,1)
C     
      SUBROUTINE FFV1L3_1(P3, F2, COUP, M1, W1, P1, COEFF)
      USE ALOHA_OBJECT
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 P1(0:3)
      INCLUDE 'coef_specs.inc'
      COMPLEX*16 COEFF(MAXLWFSIZE,0:VERTEXMAXCOEFS-1,MAXLWFSIZE)
      REAL*8 W1
      REAL*8 M1
      COMPLEX*16 P3(0:3)
      TYPE(ALOHA) F2
      COMPLEX*16 COUP
      P1(0) = +F2%P(0)+P3(0)
      P1(1) = +F2%P(1)+P3(1)
      P1(2) = +F2%P(2)+P3(2)
      P1(3) = +F2%P(3)+P3(3)
      COEFF(1,0,1)= COUP*(F2 % W(1)*(+CI*(P1(0)+P1(3)))+(F2 % W(2)*(
     $ +CI*(P1(1))-P1(2))+CI*(F2 % W(3)*M1)))
      COEFF(2,0,1)= COUP*(F2 % W(1)*(+CI*(P1(1))+P1(2))+(F2 % W(2)*(
     $ +CI*(P1(0))-CI*(P1(3)))+CI*(F2 % W(4)*M1)))
      COEFF(3,0,1)= COUP*(F2 % W(3)*(+CI*(P1(0))-CI*(P1(3)))+(F2 % W(4)
     $ *(-CI*(P1(1))+P1(2))+CI*(F2 % W(1)*M1)))
      COEFF(4,0,1)= COUP*(F2 % W(3)*(-1D0)*(+CI*(P1(1))+P1(2))+(F2 %
     $  W(4)*(+CI*(P1(0)+P1(3)))+CI*(F2 % W(2)*M1)))
      COEFF(1,1,1)= COUP*CI * F2 % W(1)
      COEFF(2,1,1)= COUP*CI * F2 % W(2)
      COEFF(3,1,1)= COUP*CI * F2 % W(3)
      COEFF(4,1,1)= COUP*CI * F2 % W(4)
      COEFF(1,2,1)= COUP*CI * F2 % W(2)
      COEFF(2,2,1)= COUP*CI * F2 % W(1)
      COEFF(3,2,1)= COUP*-CI * F2 % W(4)
      COEFF(4,2,1)= COUP*-CI * F2 % W(3)
      COEFF(1,3,1)= COUP*-F2 % W(2)
      COEFF(2,3,1)= COUP*F2 % W(1)
      COEFF(3,3,1)= COUP*F2 % W(4)
      COEFF(4,3,1)= COUP*-F2 % W(3)
      COEFF(1,4,1)= COUP*CI * F2 % W(1)
      COEFF(2,4,1)= COUP*-CI * F2 % W(2)
      COEFF(3,4,1)= COUP*-CI * F2 % W(3)
      COEFF(4,4,1)= COUP*CI * F2 % W(4)
      COEFF(1,0,2)= COUP*(-1D0)*(F2 % W(1)*(+CI*(P1(1))-P1(2))+(F2 %
     $  W(2)*(+CI*(P1(0)+P1(3)))-CI*(F2 % W(4)*M1)))
      COEFF(2,0,2)= COUP*(F2 % W(1)*(-CI*(P1(0))+CI*(P1(3)))+(F2 % W(2)
     $ *(-1D0)*(+CI*(P1(1))+P1(2))+CI*(F2 % W(3)*M1)))
      COEFF(3,0,2)= COUP*(-1D0)*(F2 % W(3)*(+CI*(P1(1))-P1(2))+(F2 %
     $  W(4)*(-CI*(P1(0))+CI*(P1(3)))+CI*(F2 % W(2)*M1)))
      COEFF(4,0,2)= COUP*(F2 % W(3)*(+CI*(P1(0)+P1(3)))+(F2 % W(4)*(
     $ -1D0)*(+CI*(P1(1))+P1(2))-CI*(F2 % W(1)*M1)))
      COEFF(1,1,2)= COUP*-CI * F2 % W(2)
      COEFF(2,1,2)= COUP*-CI * F2 % W(1)
      COEFF(3,1,2)= COUP*CI * F2 % W(4)
      COEFF(4,1,2)= COUP*CI * F2 % W(3)
      COEFF(1,2,2)= COUP*-CI * F2 % W(1)
      COEFF(2,2,2)= COUP*-CI * F2 % W(2)
      COEFF(3,2,2)= COUP*-CI * F2 % W(3)
      COEFF(4,2,2)= COUP*-CI * F2 % W(4)
      COEFF(1,3,2)= COUP*F2 % W(1)
      COEFF(2,3,2)= COUP*-F2 % W(2)
      COEFF(3,3,2)= COUP*F2 % W(3)
      COEFF(4,3,2)= COUP*-F2 % W(4)
      COEFF(1,4,2)= COUP*-CI * F2 % W(2)
      COEFF(2,4,2)= COUP*CI * F2 % W(1)
      COEFF(3,4,2)= COUP*-CI * F2 % W(4)
      COEFF(4,4,2)= COUP*CI * F2 % W(3)
      COEFF(1,0,3)= COUP*(-1D0)*(F2 % W(1)*(P1(1)+CI*(P1(2)))+(F2 %
     $  W(2)*(-1D0)*(P1(0)+P1(3))+F2 % W(4)*M1))
      COEFF(2,0,3)= COUP*(-1D0)*(F2 % W(1)*(P1(0)-P1(3))+(F2 % W(2)*(
     $ -P1(1)+CI*(P1(2)))-F2 % W(3)*M1))
      COEFF(3,0,3)= COUP*(-1D0)*(F2 % W(3)*(P1(1)+CI*(P1(2)))+(F2 %
     $  W(4)*(P1(0)-P1(3))-F2 % W(2)*M1))
      COEFF(4,0,3)= COUP*(-1D0)*(F2 % W(3)*(-1D0)*(P1(0)+P1(3))+(F2 %
     $  W(4)*(-P1(1)+CI*(P1(2)))+F2 % W(1)*M1))
      COEFF(1,1,3)= COUP*F2 % W(2)
      COEFF(2,1,3)= COUP*-F2 % W(1)
      COEFF(3,1,3)= COUP*-F2 % W(4)
      COEFF(4,1,3)= COUP*F2 % W(3)
      COEFF(1,2,3)= COUP*-F2 % W(1)
      COEFF(2,2,3)= COUP*F2 % W(2)
      COEFF(3,2,3)= COUP*-F2 % W(3)
      COEFF(4,2,3)= COUP*F2 % W(4)
      COEFF(1,3,3)= COUP*-CI * F2 % W(1)
      COEFF(2,3,3)= COUP*-CI * F2 % W(2)
      COEFF(3,3,3)= COUP*-CI * F2 % W(3)
      COEFF(4,3,3)= COUP*-CI * F2 % W(4)
      COEFF(1,4,3)= COUP*F2 % W(2)
      COEFF(2,4,3)= COUP*F2 % W(1)
      COEFF(3,4,3)= COUP*F2 % W(4)
      COEFF(4,4,3)= COUP*F2 % W(3)
      COEFF(1,0,4)= COUP*(F2 % W(1)*(-1D0)*(+CI*(P1(0)+P1(3)))+(F2 %
     $  W(2)*(+CI*(P1(1))-P1(2))+CI*(F2 % W(3)*M1)))
      COEFF(2,0,4)= COUP*(-1D0)*(F2 % W(1)*(+CI*(P1(1))+P1(2))+(F2 %
     $  W(2)*(-CI*(P1(0))+CI*(P1(3)))+CI*(F2 % W(4)*M1)))
      COEFF(3,0,4)= COUP*(F2 % W(3)*(+CI*(P1(0))-CI*(P1(3)))+(F2 % W(4)
     $ *(+CI*(P1(1))-P1(2))-CI*(F2 % W(1)*M1)))
      COEFF(4,0,4)= COUP*(-1D0)*(F2 % W(3)*(+CI*(P1(1))+P1(2))+(F2 %
     $  W(4)*(+CI*(P1(0)+P1(3)))-CI*(F2 % W(2)*M1)))
      COEFF(1,1,4)= COUP*-CI * F2 % W(1)
      COEFF(2,1,4)= COUP*CI * F2 % W(2)
      COEFF(3,1,4)= COUP*CI * F2 % W(3)
      COEFF(4,1,4)= COUP*-CI * F2 % W(4)
      COEFF(1,2,4)= COUP*CI * F2 % W(2)
      COEFF(2,2,4)= COUP*-CI * F2 % W(1)
      COEFF(3,2,4)= COUP*CI * F2 % W(4)
      COEFF(4,2,4)= COUP*-CI * F2 % W(3)
      COEFF(1,3,4)= COUP*-F2 % W(2)
      COEFF(2,3,4)= COUP*-F2 % W(1)
      COEFF(3,3,4)= COUP*-F2 % W(4)
      COEFF(4,3,4)= COUP*-F2 % W(3)
      COEFF(1,4,4)= COUP*-CI * F2 % W(1)
      COEFF(2,4,4)= COUP*-CI * F2 % W(2)
      COEFF(3,4,4)= COUP*-CI * F2 % W(3)
      COEFF(4,4,4)= COUP*-CI * F2 % W(4)
      END


