C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(3,2,1)
C     
      SUBROUTINE FFV1_2(F1, V3, COUP, M2, W2,F2)
      USE ALOHA_OBJECT
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      TYPE(ALOHA) F1
      INTEGER FLV_INDEX1
      TYPE(ALOHA) F2
      INTEGER FLV_INDEX2
      REAL*8 M2
      REAL*8 P2(0:3)
      TYPE(ALOHA) V3
      REAL*8 W2
      COMPLEX*16 DENOM
      F2%P(:) = +F1%P(:)+V3%P(:)
      P2(:) = -F2 % P (:)
      F2 % FLV_INDEX = F1 % FLV_INDEX
      DENOM = COUP/(P2(0)**2-P2(1)**2-P2(2)**2-P2(3)**2 - M2 * (M2 -CI
     $ * W2))
      F2%W(1)= DENOM*CI*(F1 % W(1)*(P2(0)*(V3 % W(1)+V3 % W(4))+(P2(1)
     $ *(-1D0)*(V3 % W(2)+CI*(V3 % W(3)))+(P2(2)*(+CI*(V3 % W(2))-V3 %
     $  W(3))-P2(3)*(V3 % W(1)+V3 % W(4)))))+(F1 % W(2)*(P2(0)*(V3 %
     $  W(2)-CI*(V3 % W(3)))+(P2(1)*(-V3 % W(1)+V3 % W(4))+(P2(2)*(+CI
     $ *(V3 % W(1))-CI*(V3 % W(4)))+P2(3)*(-V3 % W(2)+CI*(V3 % W(3)))))
     $ )+M2*(F1 % W(3)*(V3 % W(1)-V3 % W(4))+F1 % W(4)*(-V3 % W(2)+CI
     $ *(V3 % W(3))))))
      F2%W(2)= DENOM*(-CI)*(F1 % W(1)*(P2(0)*(-1D0)*(V3 % W(2)+CI*(V3
     $  % W(3)))+(P2(1)*(V3 % W(1)+V3 % W(4))+(P2(2)*(+CI*(V3 % W(1)
     $ +V3 % W(4)))-P2(3)*(V3 % W(2)+CI*(V3 % W(3))))))+(F1 % W(2)
     $ *(P2(0)*(-V3 % W(1)+V3 % W(4))+(P2(1)*(V3 % W(2)-CI*(V3 % W(3)))
     $ +(P2(2)*(+CI*(V3 % W(2))+V3 % W(3))+P2(3)*(-V3 % W(1)+V3 % W(4))
     $ )))+M2*(F1 % W(3)*(V3 % W(2)+CI*(V3 % W(3)))-F1 % W(4)*(V3 %
     $  W(1)+V3 % W(4)))))
      F2%W(3)= DENOM*(-CI)*(F1 % W(3)*(P2(0)*(-V3 % W(1)+V3 % W(4))
     $ +(P2(1)*(V3 % W(2)+CI*(V3 % W(3)))+(P2(2)*(-CI*(V3 % W(2))+V3 %
     $  W(3))+P2(3)*(-V3 % W(1)+V3 % W(4)))))+(F1 % W(4)*(P2(0)*(V3 %
     $  W(2)-CI*(V3 % W(3)))+(P2(1)*(-1D0)*(V3 % W(1)+V3 % W(4))+(P2(2)
     $ *(+CI*(V3 % W(1)+V3 % W(4)))+P2(3)*(V3 % W(2)-CI*(V3 % W(3))))))
     $ +M2*(F1 % W(1)*(-1D0)*(V3 % W(1)+V3 % W(4))+F1 % W(2)*(-V3 %
     $  W(2)+CI*(V3 % W(3))))))
      F2%W(4)= DENOM*CI*(F1 % W(3)*(P2(0)*(-1D0)*(V3 % W(2)+CI*(V3 %
     $  W(3)))+(P2(1)*(V3 % W(1)-V3 % W(4))+(P2(2)*(+CI*(V3 % W(1))-CI
     $ *(V3 % W(4)))+P2(3)*(V3 % W(2)+CI*(V3 % W(3))))))+(F1 % W(4)
     $ *(P2(0)*(V3 % W(1)+V3 % W(4))+(P2(1)*(-V3 % W(2)+CI*(V3 % W(3)))
     $ +(P2(2)*(-1D0)*(+CI*(V3 % W(2))+V3 % W(3))-P2(3)*(V3 % W(1)+V3
     $  % W(4)))))+M2*(F1 % W(1)*(V3 % W(2)+CI*(V3 % W(3)))+F1 % W(2)
     $ *(V3 % W(1)-V3 % W(4)))))
      END


