C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(3,2,-1)*ProjM(-1,1) + 2*Gamma(3,2,-1)*ProjP(-1,1)
C     
      SUBROUTINE MP_FFV4P0_3(F1, F2, COUP, M3, W3,V3)
      USE ALOHA_OBJECT
      IMPLICIT NONE
      COMPLEX*32 CI
      PARAMETER (CI=(0Q0,1Q0))
      COMPLEX*32 COUP
      TYPE(MP_ALOHA) F1
      INTEGER FLV_INDEX1
      TYPE(MP_ALOHA) F2
      INTEGER FLV_INDEX2
      REAL*16 M3
      REAL*16 P3(0:3)
      TYPE(MP_ALOHA) V3
      REAL*16 W3
      COMPLEX*32 DENOM
      V3%P(:) = +F1%P(:)+F2%P(:)
      P3(:) = -V3 % P (:)
      FLV_INDEX1 = F1 %FLV_INDEX
      FLV_INDEX2 = F2 %FLV_INDEX
      IF(FLV_INDEX1.NE.FLV_INDEX2.OR.FLV_INDEX1.EQ.0D0)THEN
        V3%W(:) = (0D0,0D0)
        RETURN
      ENDIF
      DENOM = COUP/(P3(0)**2-P3(1)**2-P3(2)**2-P3(3)**2 - M3 * (M3 -CI
     $ * W3))
      V3%W(1)= DENOM*(-2Q0 * CI)*(+1Q0/2Q0*(F1 % W(1)*F2 % W(3)+F1 %
     $  W(2)*F2 % W(4))+F1 % W(3)*F2 % W(1)+F1 % W(4)*F2 % W(2))
      V3%W(2)= DENOM*(-2Q0 * CI)*(-1Q0/2Q0*(F1 % W(1)*F2 % W(4)+F1 %
     $  W(2)*F2 % W(3))+F1 % W(3)*F2 % W(2)+F1 % W(4)*F2 % W(1))
      V3%W(3)= DENOM*(-CI)*(-CI*(F1 % W(1)*F2 % W(4))+CI*(F1 % W(2)*F2
     $  % W(3))+2Q0 * CI*(F1 % W(3)*F2 % W(2))-2Q0 * CI*(F1 % W(4)*F2
     $  % W(1)))
      V3%W(4)= DENOM*(-2Q0 * CI)*(-1Q0/2Q0*(F1 % W(1)*F2 % W(3))+1Q0
     $ /2Q0*(F1 % W(2)*F2 % W(4))+F1 % W(3)*F2 % W(1)-F1 % W(4)*F2 %
     $  W(2))
      END


