C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(3,2,1)
C     
      SUBROUTINE MP_FFV1L1P0_3(P1, F2, COUP, M3, W3, P3, COEFF)
      USE ALOHA_OBJECT
      IMPLICIT NONE
      COMPLEX*32 CI
      PARAMETER (CI=(0Q0,1Q0))
      REAL*16 M3
      REAL*16 W3
      COMPLEX*32 P1(0:3)
      INCLUDE 'coef_specs.inc'
      COMPLEX*32 COEFF(MAXLWFSIZE,0:VERTEXMAXCOEFS-1,MAXLWFSIZE)
      COMPLEX*32 P3(0:3)
      TYPE(MP_ALOHA) F2
      COMPLEX*32 COUP
      P3(0) = +P1(0)+F2%P(0)
      P3(1) = +P1(1)+F2%P(1)
      P3(2) = +P1(2)+F2%P(2)
      P3(3) = +P1(3)+F2%P(3)
      COEFF(1,0,1)= COUP*-CI * F2 % W(3)
      COEFF(2,0,1)= COUP*CI * F2 % W(4)
      COEFF(3,0,1)= COUP*-F2 % W(4)
      COEFF(4,0,1)= COUP*CI * F2 % W(3)
      COEFF(1,0,2)= COUP*-CI * F2 % W(4)
      COEFF(2,0,2)= COUP*CI * F2 % W(3)
      COEFF(3,0,2)= COUP*F2 % W(3)
      COEFF(4,0,2)= COUP*-CI * F2 % W(4)
      COEFF(1,0,3)= COUP*-CI * F2 % W(1)
      COEFF(2,0,3)= COUP*-CI * F2 % W(2)
      COEFF(3,0,3)= COUP*F2 % W(2)
      COEFF(4,0,3)= COUP*-CI * F2 % W(1)
      COEFF(1,0,4)= COUP*-CI * F2 % W(2)
      COEFF(2,0,4)= COUP*-CI * F2 % W(1)
      COEFF(3,0,4)= COUP*-F2 % W(1)
      COEFF(4,0,4)= COUP*CI * F2 % W(2)
      END


