C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(1,4)*Metric(2,3) - Metric(1,2)*Metric(3,4)
C     
      SUBROUTINE MP_VVVV3L2P0_1(P2, V3, V4, COUP, M1, W1, P1, COEFF)
      USE ALOHA_OBJECT
      IMPLICIT NONE
      COMPLEX*32 CI
      PARAMETER (CI=(0Q0,1Q0))
      COMPLEX*32 P2(0:3)
      COMPLEX*32 TMP2
      COMPLEX*32 P1(0:3)
      TYPE(MP_ALOHA) V4
      REAL*16 W1
      INCLUDE 'coef_specs.inc'
      COMPLEX*32 COEFF(MAXLWFSIZE,0:VERTEXMAXCOEFS-1,MAXLWFSIZE)
      REAL*16 M1
      COMPLEX*32 COUP
      TYPE(MP_ALOHA) V3
      P1(0) = +P2(0)+V3%P(0)+V4%P(0)
      P1(1) = +P2(1)+V3%P(1)+V4%P(1)
      P1(2) = +P2(2)+V3%P(2)+V4%P(2)
      P1(3) = +P2(3)+V3%P(3)+V4%P(3)
      TMP2 = (V3 % W(1)*V4 % W(1)-V3 % W(2)*V4 % W(2)-V3 % W(3)*V4 %
     $  W(3)-V3 % W(4)*V4 % W(4))
      COEFF(1,0,1)= COUP*(-CI*(V3 % W(1)*V4 % W(1))+CI*(TMP2))
      COEFF(2,0,1)= COUP*-CI * V3 % W(1)*V4 % W(2)
      COEFF(3,0,1)= COUP*-CI * V3 % W(1)*V4 % W(3)
      COEFF(4,0,1)= COUP*-CI * V3 % W(1)*V4 % W(4)
      COEFF(1,0,2)= COUP*CI * V3 % W(2)*V4 % W(1)
      COEFF(2,0,2)= COUP*(+CI*(V3 % W(2)*V4 % W(2)+TMP2))
      COEFF(3,0,2)= COUP*CI * V3 % W(2)*V4 % W(3)
      COEFF(4,0,2)= COUP*CI * V3 % W(2)*V4 % W(4)
      COEFF(1,0,3)= COUP*CI * V3 % W(3)*V4 % W(1)
      COEFF(2,0,3)= COUP*CI * V3 % W(3)*V4 % W(2)
      COEFF(3,0,3)= COUP*(+CI*(V3 % W(3)*V4 % W(3)+TMP2))
      COEFF(4,0,3)= COUP*CI * V3 % W(3)*V4 % W(4)
      COEFF(1,0,4)= COUP*CI * V3 % W(4)*V4 % W(1)
      COEFF(2,0,4)= COUP*CI * V3 % W(4)*V4 % W(2)
      COEFF(3,0,4)= COUP*CI * V3 % W(4)*V4 % W(3)
      COEFF(4,0,4)= COUP*(+CI*(V3 % W(4)*V4 % W(4)+TMP2))
      END


