      DOUBLE PRECISION FUNCTION DSIG(PP,WGT,IMODE)
C     ****************************************************
C     
C     Generated by MadGraph5_aMC@NLO v. %(version)s, %(date)s
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Process: u u~ > g g
C     
C     RETURNS DIFFERENTIAL CROSS SECTION
C     Input:
C     pp    4 momentum of external particles
C     wgt   weight from Monte Carlo
C     imode 0 run, 1 init, 2 reweight, 
C     3 finalize, 4 only PDFs,
C     5 squared amplitude only (never
C     generate events)
C     Output:
C     Amplitude squared and summed
C     ****************************************************
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INCLUDE 'genps.inc'
      INCLUDE 'nexternal.inc'
      INCLUDE 'maxconfigs.inc'
      INCLUDE 'maxamps.inc'
      DOUBLE PRECISION       CONV
      PARAMETER (CONV=389379.66*1000)  !CONV TO PICOBARNS
      REAL*8     PI
      PARAMETER (PI=3.1415926D0)
C     
C     ARGUMENTS 
C     
      DOUBLE PRECISION PP(0:3,NEXTERNAL), WGT
      INTEGER IMODE
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,ITYPE,LP,IPROC
      DOUBLE PRECISION U1
      DOUBLE PRECISION UX2
      DOUBLE PRECISION XPQ(-7:7),PD(0:MAXPROC)
      DOUBLE PRECISION DSIGUU,R,RCONF

      INTEGER LUN,ICONF,IFACT,NFACT
      DATA NFACT/1/
      SAVE NFACT
C     
C     STUFF FOR DRESSED EE COLLISIONS
C     
      INCLUDE '../../Source/PDF/eepdf.inc'
      DOUBLE PRECISION EE_COMP_PROD

      INTEGER I_EE
C     
C     STUFF FOR UPC
C     
      DOUBLE PRECISION PHOTONPDFSQUARE
C     
C     EXTERNAL FUNCTIONS
C     
      LOGICAL PASSCUTS
      DOUBLE PRECISION ALPHAS2,REWGT,PDG2PDF,CUSTOM_BIAS
      INTEGER NEXTUNOPEN
C     
C     GLOBAL VARIABLES
C     
      INTEGER          IPSEL
      COMMON /SUBPROC/ IPSEL
C     MINCFIG has this config number
      INTEGER           MINCFIG, MAXCFIG
      COMMON/TO_CONFIGS/MINCFIG, MAXCFIG
      INTEGER MAPCONFIG(0:LMAXCONFIGS), ICONFIG
      COMMON/TO_MCONFIGS/MAPCONFIG, ICONFIG
C     Keep track of whether cuts already calculated for this event
      LOGICAL CUTSDONE,CUTSPASSED
      COMMON/TO_CUTSDONE/CUTSDONE,CUTSPASSED

      INCLUDE 'coupl.inc'
      INCLUDE 'run.inc'
C     Common blocks
      CHARACTER*7         PDLABEL,EPA_LABEL
      INTEGER       LHAID
      COMMON/TO_PDF/LHAID,PDLABEL,EPA_LABEL
      INCLUDE 'vector.inc'
C     jamp2 information
      DOUBLE PRECISION JAMP2(0:MAXFLOW, NB_PAGE)
      COMMON/TO_JAMPS/       JAMP2

C     
C     local
C     
      DOUBLE PRECISION P1(0:3, NEXTERNAL)
      INTEGER CHANNEL
C     
C     DATA
C     
      DATA U1/1*1D0/
      DATA UX2/1*1D0/
C     ----------
C     BEGIN CODE
C     ----------
      DSIG=0D0
      CUTSDONE=.FALSE.
      CUTSPASSED=.FALSE.
      IF(IMODE.EQ.1)THEN
C       Set up process information from file symfact
        LUN=NEXTUNOPEN()
        NFACT=1
        OPEN(UNIT=LUN,FILE='../symfact.dat',STATUS='OLD',ERR=20)
        DO WHILE(.TRUE.)
          READ(LUN,*,ERR=10,END=10) RCONF, IFACT
          ICONF=INT(RCONF)
          IF(ICONF.EQ.MAPCONFIG(MINCFIG))THEN
            NFACT=IFACT
          ENDIF
        ENDDO
        DSIG = NFACT
 10     CLOSE(LUN)
        RETURN
 20     WRITE(*,*)'Error opening symfact.dat. No symmetry factor used.'
        RETURN
      ENDIF
C     Continue only if IMODE is 0, 4 or 5
      IF(IMODE.NE.0.AND.IMODE.NE.4.AND.IMODE.NE.5) RETURN

      IF (PASSCUTS(PP)) THEN
        IF (ABS(LPP(1)) .GE. 1) THEN
            !LP=SIGN(1,LPP(1))
          U1=PDG2PDF(LPP(1),2, 1,XBK(1),DSQRT(Q2FACT(1)))
        ENDIF
        IF (ABS(LPP(2)) .GE. 1) THEN
            !LP=SIGN(1,LPP(2))
          UX2=PDG2PDF(LPP(2),-2, 2,XBK(2),DSQRT(Q2FACT(2)))
        ENDIF
        PD(0) = 0D0
        IPROC = 0
        IPROC=IPROC+1  ! u u~ > g g
        PD(IPROC)=U1*UX2
        PD(0)=PD(0)+DABS(PD(IPROC))
        IF (IMODE.EQ.4)THEN
          DSIG = PD(0)
          RETURN
        ENDIF
        IF(FRAME_ID.NE.6)THEN
          CALL BOOST_TO_FRAME(PP, FRAME_ID, P1)
        ELSE
          P1 = PP
        ENDIF

        CHANNEL = MAPCONFIG(ICONFIG)
        CALL SMATRIX(P1,0,CHANNEL,DSIGUU,JAMP2(0,1),1)

        IF (IMODE.EQ.5) THEN
          IF (DSIGUU.LT.1D199) THEN
            DSIG = DSIGUU*CONV
          ELSE
            DSIG = 0.0D0
          ENDIF
          RETURN
        ENDIF
C       Select a flavor combination (need to do here for right sign)
        CALL RANMAR(R)
        IPSEL=0
        DO WHILE (R.GE.0D0 .AND. IPSEL.LT.IPROC)
          IPSEL=IPSEL+1
          R=R-DABS(PD(IPSEL))/PD(0)
        ENDDO

        DSIGUU=DSIGUU*REWGT(PP)

C       Apply the bias weight specified in the run card (default is
C        1.0)
        DSIGUU=DSIGUU*CUSTOM_BIAS(PP,DSIGUU,1,1)

        DSIGUU=DSIGUU*NFACT

        IF (DSIGUU.LT.1D199) THEN
C         Set sign of dsig based on sign of PDF and matrix element
          DSIG=DSIGN(CONV*PD(0)*DSIGUU,DSIGUU*PD(IPSEL))
        ELSE
          WRITE(*,*) 'Error in matrix element'
          DSIGUU=0D0
          DSIG=0D0
        ENDIF
C       Generate events only if IMODE is 0.
        IF(IMODE.EQ.0.AND.DABS(DSIG).GT.0D0)THEN
C         Call UNWGT to unweight and store events
          CALL UNWGT(PP,DSIG*WGT,1,1)
        ENDIF
      ENDIF
      END
C     
C     Functionality to handling grid
C     

      SUBROUTINE WRITE_GOOD_HEL(STREAM_ID)
      IMPLICIT NONE
      INTEGER STREAM_ID
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=16)
      LOGICAL GOODHEL(NCOMB)
      INTEGER NTRY
      COMMON/BLOCK_GOODHEL/NTRY,GOODHEL
      WRITE(STREAM_ID,*) GOODHEL
      RETURN
      END


      SUBROUTINE READ_GOOD_HEL(STREAM_ID)
      IMPLICIT NONE
      INCLUDE 'genps.inc'
      INTEGER STREAM_ID
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=16)
      LOGICAL GOODHEL(NCOMB)
      INTEGER NTRY
      COMMON/BLOCK_GOODHEL/NTRY,GOODHEL
      READ(STREAM_ID,*) GOODHEL
      NTRY = MAXTRIES + 1
      RETURN
      END

      SUBROUTINE INIT_GOOD_HEL()
      IMPLICIT NONE
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=16)
      LOGICAL GOODHEL(NCOMB)
      INTEGER NTRY
      INTEGER I

      DO I=1,NCOMB
        GOODHEL(I) = .FALSE.
      ENDDO
      NTRY = 0
      END

      INTEGER FUNCTION GET_MAXSPROC()
      IMPLICIT NONE
      GET_MAXSPROC = 1
      RETURN
      END




      DOUBLE PRECISION FUNCTION DSIG_VEC(ALL_PP, ALL_XBK, ALL_Q2FACT,
     $  ALL_CM_RAP, ALL_WGT,IMODE, ALL_OUT)
C     ****************************************************
C     
C     Generated by MadGraph5_aMC@NLO v. %(version)s, %(date)s
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Process: u u~ > g g
C     
C     RETURNS DIFFERENTIAL CROSS SECTION
C     Input:
C     pp    4 momentum of external particles
C     wgt   weight from Monte Carlo
C     imode 0 run, 1 init, 2 reweight, 
C     3 finalize, 4 only PDFs,
C     5 squared amplitude only (never
C     generate events)
C     Output:
C     Amplitude squared and summed
C     ****************************************************
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INCLUDE '../../Source/vector.inc'
      INCLUDE 'genps.inc'
      INCLUDE 'nexternal.inc'
      INCLUDE 'maxconfigs.inc'
      INCLUDE 'maxamps.inc'
      DOUBLE PRECISION       CONV
      PARAMETER (CONV=389379.66*1000)  !CONV TO PICOBARNS
      REAL*8     PI
      PARAMETER (PI=3.1415926D0)
C     
C     ARGUMENTS 
C     
      DOUBLE PRECISION ALL_PP(0:3,NEXTERNAL,NB_PAGE)
      DOUBLE PRECISION ALL_WGT(NB_PAGE)
      DOUBLE PRECISION ALL_XBK(2,NB_PAGE)
      DOUBLE PRECISION ALL_Q2FACT(2,NB_PAGE)
      DOUBLE PRECISION ALL_CM_RAP(NB_PAGE)
      INTEGER IMODE
      DOUBLE PRECISION ALL_OUT(NB_PAGE)
C     ----------
C     BEGIN CODE
C     ----------
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,ITYPE,LP,IPROC
      DOUBLE PRECISION U1
      DOUBLE PRECISION UX2
      DOUBLE PRECISION XPQ(-7:7),PD(0:MAXPROC)
      DOUBLE PRECISION ALL_PD(0:MAXPROC, NB_PAGE)
      DOUBLE PRECISION DSIGUU,R,RCONF
      INTEGER LUN,ICONF,IFACT,NFACT
      DATA NFACT/1/
      SAVE NFACT
      DOUBLE PRECISION RHEL  ! random number
      INTEGER CHANNEL
C     
C     STUFF FOR DRESSED EE COLLISIONS --even if not supported for now--
C     
      INCLUDE '../../Source/PDF/eepdf.inc'
      DOUBLE PRECISION EE_COMP_PROD

      INTEGER I_EE
C     
C     EXTERNAL FUNCTIONS
C     
      LOGICAL PASSCUTS
      DOUBLE PRECISION ALPHAS2,REWGT,PDG2PDF,CUSTOM_BIAS
      INTEGER NEXTUNOPEN
      DOUBLE PRECISION DSIG
C     
C     GLOBAL VARIABLES
C     
      INTEGER          IPSEL
      COMMON /SUBPROC/ IPSEL
C     MINCFIG has this config number
      INTEGER           MINCFIG, MAXCFIG
      COMMON/TO_CONFIGS/MINCFIG, MAXCFIG
      INTEGER MAPCONFIG(0:LMAXCONFIGS), ICONFIG
      COMMON/TO_MCONFIGS/MAPCONFIG, ICONFIG
C     Keep track of whether cuts already calculated for this event
      LOGICAL CUTSDONE,CUTSPASSED
      COMMON/TO_CUTSDONE/CUTSDONE,CUTSPASSED
C     jamp2 information      
      DOUBLE PRECISION JAMP2(0:MAXFLOW, NB_PAGE)
      COMMON/TO_JAMPS/       JAMP2

      INCLUDE 'coupl.inc'
      INCLUDE 'run.inc'

      DOUBLE PRECISION P_MULTI(0:3, NEXTERNAL, NB_PAGE)
      DOUBLE PRECISION HEL_RAND(NB_PAGE)
      INTEGER SELECTED_HEL(NB_PAGE)

C     Common blocks
      CHARACTER*7         PDLABEL,EPA_LABEL
      INTEGER       LHAID
      COMMON/TO_PDF/LHAID,PDLABEL,EPA_LABEL

C     
C     local
C     
      DOUBLE PRECISION P1(0:3, NEXTERNAL)
      INTEGER IVEC

C     
C     DATA
C     
      DATA U1/1*1D0/
      DATA UX2/1*1D0/
C     ----------
C     BEGIN CODE
C     ----------
      CUTSDONE=.FALSE.
      CUTSPASSED=.FALSE.
      IF(IMODE.EQ.1)THEN
        NFACT = DSIG(ALL_PP(0,1,1), ALL_WGT(1), IMODE)
        RETURN
      ENDIF

C     Continue only if IMODE is 0, 4 or 5
      IF(IMODE.NE.0.AND.IMODE.NE.4.AND.IMODE.NE.5) RETURN

      IF (PASSCUTS(PP)) THEN
        IF (ABS(LPP(1)) .GE. 1) THEN
            !LP=SIGN(1,LPP(1))
          U1=PDG2PDF(LPP(1),2, 1,XBK(1),DSQRT(Q2FACT(1)))
        ENDIF
        IF (ABS(LPP(2)) .GE. 1) THEN
            !LP=SIGN(1,LPP(2))
          UX2=PDG2PDF(LPP(2),-2, 2,XBK(2),DSQRT(Q2FACT(2)))
        ENDIF
        PD(0) = 0D0
        IPROC = 0
        IPROC=IPROC+1  ! u u~ > g g
        PD(IPROC)=U1*UX2
        PD(0)=PD(0)+DABS(PD(IPROC))


        IF (IMODE.EQ.4)THEN
          ALL_OUT(:) = ALL_PD(0,:)
          RETURN
        ENDIF

        DO IVEC=1,NB_PAGE
C         Do not need those three here do I?	 
          XBK(:) = ALL_XBK(:,IVEC)
C         CM_RAP = ALL_CM_RAP(IVEC)
          Q2FACT(:) = ALL_Q2FACT(:, IVEC)

          IF(FRAME_ID.NE.6)THEN
            CALL BOOST_TO_FRAME(ALL_PP(0,1,IVEC), FRAME_ID, P_MULTI(0
     $       ,1,IVEC))
          ELSE
            P_MULTI(:,:,IVEC) = ALL_PP(:,:,IVEC)
          ENDIF
          CALL RANMAR(HEL_RAND(IVEC))
C         CALL SMATRIX(P1, RHEL, channel, ALL_OUT(IVEC), JAMP2(0,
C          IVEC), IVEC)
        ENDDO
        CHANNEL = MAPCONFIG(ICONFIG)

C       do IVEC=1, NB_PAGE
C       CALL SMATRIX(p_multi(0,1,IVEC), hel_rand(ivec), channel,
C        ALL_OUT(IVEC), JAMP2(0, IVEC), IVEC)
C       enddo 
        CALL SMATRIX_MULTI(P_MULTI, HEL_RAND,  CHANNEL, ALL_OUT ,
     $    SELECTED_HEL, JAMP2)


        DO IVEC=1,NB_PAGE
          DSIGUU = ALL_OUT(IVEC)
          IF (IMODE.EQ.5) THEN
            IF (DSIGUU.LT.1D199) THEN
              ALL_OUT(IVEC) = DSIGUU*CONV
            ELSE
              ALL_OUT(IVEC) = 0.0D0
            ENDIF
            RETURN
          ENDIF
C         Select a flavor combination (need to do here for right sign)
          CALL RANMAR(R)
          IPSEL=0
          DO WHILE (R.GE.0D0 .AND. IPSEL.LT.IPROC)
            IPSEL=IPSEL+1
            R=R-DABS(ALL_PD(IPSEL,IVEC))/ALL_PD(0,IVEC)
          ENDDO

          XBK(:) = ALL_XBK(:,IVEC)
C         CM_RAP = ALL_CM_RAP(IVEC)
          Q2FACT(:) = ALL_Q2FACT(:, IVEC)

          IF(FRAME_ID.NE.6)THEN
            CALL BOOST_TO_FRAME(ALL_PP(0,1,IVEC), FRAME_ID, P1)
          ELSE
            P1 = ALL_PP(:,:,IVEC)
          ENDIF
          CALL RESTORE_CL_VAL_TO(IVEC)
          DSIGUU=DSIGUU*REWGT(P1)

C         Apply the bias weight specified in the run card (default is
C          1.0)
          DSIGUU=DSIGUU*CUSTOM_BIAS(P1,DSIGUU,1, IVEC)

          DSIGUU=DSIGUU*NFACT

          IF (DSIGUU.LT.1D199) THEN
C           Set sign of dsig based on sign of PDF and matrix element
            ALL_OUT(IVEC)=DSIGN(CONV*ALL_PD(0,IVEC)*DSIGUU,DSIGUU
     $       *ALL_PD(IPSEL,IVEC))
          ELSE
            WRITE(*,*) 'Error in matrix element'
            DSIGUU=0D0
            ALL_OUT(IVEC)=0D0
          ENDIF
C         Generate events only if IMODE is 0.
          IF(IMODE.EQ.0.AND.DABS(ALL_OUT(IVEC)).GT.0D0)THEN
C           Call UNWGT to unweight and store events
            CALL UNWGT(ALL_PP(0,1,IVEC), ALL_OUT(IVEC)*ALL_WGT(IVEC),1
     $       , IVEC)
          ENDIF
        ENDDO
      ENDIF
      END
C     
C     Functionality to handling grid
C     

      SUBROUTINE WRITE_GOOD_HEL(STREAM_ID)
      IMPLICIT NONE
      INTEGER STREAM_ID
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=16)
      LOGICAL GOODHEL(NCOMB)
      INTEGER NTRY
      COMMON/BLOCK_GOODHEL/NTRY,GOODHEL
      WRITE(STREAM_ID,*) GOODHEL
      RETURN
      END


      SUBROUTINE READ_GOOD_HEL(STREAM_ID)
      IMPLICIT NONE
      INCLUDE 'genps.inc'
      INTEGER STREAM_ID
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=16)
      LOGICAL GOODHEL(NCOMB)
      INTEGER NTRY
      COMMON/BLOCK_GOODHEL/NTRY,GOODHEL
      READ(STREAM_ID,*) GOODHEL
      NTRY = MAXTRIES + 1
      RETURN
      END

      SUBROUTINE INIT_GOOD_HEL()
      IMPLICIT NONE
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=16)
      LOGICAL GOODHEL(NCOMB)
      INTEGER NTRY
      INTEGER I

      DO I=1,NCOMB
        GOODHEL(I) = .FALSE.
      ENDDO
      NTRY = 0
      END

      INTEGER FUNCTION GET_MAXSPROC()
      IMPLICIT NONE
      GET_MAXSPROC = 1
      RETURN
      END







      SUBROUTINE PRINT_ZERO_AMP()

      RETURN
      END


      SUBROUTINE SMATRIX_MULTI(P_MULTI, HEL_RAND,  CHANNEL, OUT ,
     $  SELECTED_HEL, JAMP2_MULTI)

      USE OMP_LIB

      INCLUDE 'nexternal.inc'
      INCLUDE '../../Source/vector.inc'
      INCLUDE 'maxamps.inc'
      DOUBLE PRECISION P_MULTI(0:3, NEXTERNAL, NB_PAGE)
      DOUBLE PRECISION HEL_RAND(NB_PAGE)
      INTEGER CHANNEL
      DOUBLE PRECISION OUT(NB_PAGE)
      INTEGER SELECTED_HEL(NB_PAGE)
      DOUBLE PRECISION JAMP2_MULTI(0:MAXFLOW, NB_PAGE)

      INTEGER IVEC


!$OMP PARALLEL
!$OMP DO
      DO IVEC=1, NB_PAGE
        CALL SMATRIX(P_MULTI(0,1,IVEC),
     &	                         hel_rand(IVEC),
     &				 channel,
     &				 out(IVEC),
C       &				 selected_hel(IVEC),
     &				 jamp2_multi(0,IVEC),
     &				 IVEC
     &				 )
      ENDDO
!$OMP END DO
!$OMP END PARALLEL
      RETURN
      END

      INTEGER FUNCTION GET_NHEL(HEL, IPART)
C     if hel>0 return the helicity of particule ipart for the selected
C      helicity configuration
C     if hel=0 return the number of helicity state possible for that
C      particle 
      IMPLICIT NONE
      INTEGER HEL,I, IPART
      INCLUDE 'nexternal.inc'
      INTEGER ONE_NHEL(NEXTERNAL)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=16)
      INTEGER NHEL(NEXTERNAL,0:NCOMB)
      DATA (NHEL(I,0),I=1,4) / 2, 2, 2, 2/
      DATA (NHEL(I,   1),I=1,4) / 1,-1,-1,-1/
      DATA (NHEL(I,   2),I=1,4) / 1,-1,-1, 1/
      DATA (NHEL(I,   3),I=1,4) / 1,-1, 1,-1/
      DATA (NHEL(I,   4),I=1,4) / 1,-1, 1, 1/
      DATA (NHEL(I,   5),I=1,4) / 1, 1,-1,-1/
      DATA (NHEL(I,   6),I=1,4) / 1, 1,-1, 1/
      DATA (NHEL(I,   7),I=1,4) / 1, 1, 1,-1/
      DATA (NHEL(I,   8),I=1,4) / 1, 1, 1, 1/
      DATA (NHEL(I,   9),I=1,4) /-1,-1,-1,-1/
      DATA (NHEL(I,  10),I=1,4) /-1,-1,-1, 1/
      DATA (NHEL(I,  11),I=1,4) /-1,-1, 1,-1/
      DATA (NHEL(I,  12),I=1,4) /-1,-1, 1, 1/
      DATA (NHEL(I,  13),I=1,4) /-1, 1,-1,-1/
      DATA (NHEL(I,  14),I=1,4) /-1, 1,-1, 1/
      DATA (NHEL(I,  15),I=1,4) /-1, 1, 1,-1/
      DATA (NHEL(I,  16),I=1,4) /-1, 1, 1, 1/

      GET_NHEL = NHEL(IPART, IABS(HEL))
      RETURN
      END


