#!/bin/bash
# $1 should be the executable
# $2 should be the input file
# $3 should be the event file (excluding the run number), preferably gzip'ed
# $4 should be the run number

CONDOR_INITIAL_DIR=`pwd`
if [ -n "$_CONDOR_SCRATCH_DIR" ]; then
    cd $_CONDOR_SCRATCH_DIR
fi
cp -af  $CONDOR_INITIAL_DIR/$1 .
cp -af  $CONDOR_INITIAL_DIR/$2 .
if [ -e $CONDOR_INITIAL_DIR/$3.$4.gz ] ; then
    cp -af  $CONDOR_INITIAL_DIR/$3.$4.gz $3.gz
    gunzip $3.gz
elif [ -e $CONDOR_INITIAL_DIR/$3.$4 ] ; then
    cp -af  $CONDOR_INITIAL_DIR/$3.$4 $3
else
    exit
fi

./$1 <$2 >file.log

for file in *.top *.TOP ; do
    cp -f $file $CONDOR_INITIAL_DIR/$4\_$file
done

cp -f file.log $CONDOR_INITIAL_DIR/$4\_file.log
