# .github/workflows/warm-caches.yml
name: Warm all caches

permissions:
  actions: write
  contents: read
on:
  push:
  schedule:
    - cron: '0 3 * * 0'    # every Sunday 3am
  workflow_dispatch:         
    inputs:
      reset_heptools:
        type: boolean
        default: false
      reset_ufo:
        type: boolean
        default: false
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:

  delete-cache:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
#
    steps:
      - uses: actions/checkout@v5
#
      - name: Set cache key
        run: echo "CACHE_KEY=$ImageOS" >> $GITHUB_ENV
#
      - name: Delete heptools related cache
        if: github.event_name == 'schedule' || inputs.reset_heptools == 'true'
        run: | 
          gh cache delete heptools-${{ env.CACHE_KEY }} --repo $GITHUB_REPOSITORY || true
          gh cache delete lhapdf-${{ env.CACHE_KEY }} --repo $GITHUB_REPOSITORY || true
          gh cache delete pythia8-${{ env.CACHE_KEY }} --repo $GITHUB_REPOSITORY || true
          gh cache delete emela-${{ env.CACHE_KEY }} --repo $GITHUB_REPOSITORY || true
          gh cache delete contur-${{ env.CACHE_KEY }} --repo $GITHUB_REPOSITORY || true
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Delete ufo cache
        if: github.event_name == 'schedule' || inputs.reset_ufo == 'true'
        run: | 
          gh cache delete pip-numpy-${{ env.CACHE_KEY }} --repo $GITHUB_REPOSITORY || true
        env:
          GH_TOKEN: ${{ github.token }}

  rebuild-numpy-cache:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
    needs: delete-cache
    steps:
      - name: Set cache key
        run: echo "CACHE_KEY=$ImageOS" >> $GITHUB_ENV

      - name: Cache pip packages
        id: cache-pip
        uses: actions/cache@v5
        with:
          path: ~/.cache/pip-packages
          key: pip-numpy-${{ env.CACHE_KEY }}

      - name: Install numpy into cache dir (if not cached)
        if: steps.cache-pip.outputs.cache-hit != 'true'
        run: pip install --target ~/.cache/pip-packages numpy

  heptools_cache:
    runs-on: ${{ matrix.os }}
    needs: delete-cache
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/checkout_mg5
      - uses: ./.github/actions/ensure_heptools
        with:
          wait_minutes: "3"
